"""Shared runtime contracts for Aegis.

This package is intentionally dependency-light and side-effect-free. It defines
the stable data shapes that the kernel, modules, and surfaces can share while
developing in parallel.
"""

from .inventory import CONTRACT_SURFACES
from .runtime import (
    ActivityGraph,
    AgentRunState,
    AgentRunStep,
    ArtifactRecord,
    CloneIdentityRecord,
    ContextBundle,
    EmbeddingIndexInvalidation,
    EmbeddingIndexPolicy,
    EmbeddingIndexRebuildPlan,
    EvidenceCandidate,
    EvidenceGraph,
    EvidenceRetrievalRequest,
    EvidenceRetrievalResult,
    EventEnvelope,
    ExperienceRecord,
    ExecutionResult,
    GoalNode,
    IntentCandidate,
    IntentCandidateScore,
    IntentDecision,
    IntentReason,
    IntentResolutionRequest,
    MemoryRecord,
    MixtureModelSelection,
    PatternCluster,
    PlanDraft,
    PlanStep,
    PromptEnvelope,
    ProcedureCandidate,
    ProcedureLibrary,
    ProcedureRecord,
    ProcedureStep,
    ProfileGraph,
    ProfileGrowthState,
    ProfileState,
    RecallReason,
    RecallReasons,
    RelationshipMemoryRecord,
    ResumePacket,
    SessionContinuityState,
    SessionState,
    StrongModelProfile,
    StructuredTurnRecord,
    StructuredTurnSlot,
    UserCardRecord,
    VerificationBundle,
    WeakModelProfile,
)

__all__ = [
    "ArtifactRecord",
    "AgentRunState",
    "AgentRunStep",
    "CloneIdentityRecord",
    "CONTRACT_SURFACES",
    "ContextBundle",
    "EmbeddingIndexInvalidation",
    "EmbeddingIndexPolicy",
    "EmbeddingIndexRebuildPlan",
    "EvidenceCandidate",
    "EvidenceGraph",
    "EvidenceRetrievalRequest",
    "EvidenceRetrievalResult",
    "EventEnvelope",
    "ExperienceRecord",
    "ExecutionResult",
    "GoalNode",
    "IntentCandidate",
    "IntentCandidateScore",
    "IntentDecision",
    "IntentReason",
    "IntentResolutionRequest",
    "MemoryRecord",
    "MixtureModelSelection",
    "StrongModelProfile",
    "StructuredTurnRecord",
    "StructuredTurnSlot",
    "PlanDraft",
    "PlanStep",
    "PromptEnvelope",
    "ProcedureCandidate",
    "ProcedureLibrary",
    "ProcedureRecord",
    "ProcedureStep",
    "VerificationBundle",
    "ProfileGraph",
    "ProfileGrowthState",
    "ProfileState",
    "RecallReason",
    "RecallReasons",
    "RelationshipMemoryRecord",
    "ResumePacket",
    "SessionContinuityState",
    "SessionState",
    "UserCardRecord",
    "VerificationBundle",
    "WeakModelProfile",
    "ActivityGraph",
]
