"""Public inventory of the shared runtime contract surface.

Keep this list stable so module teams can agree on the names they are building
against without reaching into implementation details.
"""

CONTRACT_SURFACES = (
    "StrongModelProfile",
    "WeakModelProfile",
    "MixtureModelSelection",
    "ProfileState",
    "CloneIdentityRecord",
    "UserCardRecord",
    "RelationshipMemoryRecord",
    "ProfileGraph",
    "SessionState",
    "GoalNode",
    "ActivityGraph",
    "IntentReason",
    "IntentCandidate",
    "IntentCandidateScore",
    "IntentDecision",
    "IntentResolutionRequest",
    "MemoryRecord",
    "StructuredTurnSlot",
    "StructuredTurnRecord",
    "PatternCluster",
    "ProcedureCandidate",
    "VerificationBundle",
    "ArtifactRecord",
    "EvidenceGraph",
    "RecallReason",
    "RecallReasons",
    "EvidenceRetrievalRequest",
    "EvidenceCandidate",
    "EmbeddingIndexInvalidation",
    "EmbeddingIndexRebuildPlan",
    "EmbeddingIndexPolicy",
    "EvidenceRetrievalResult",
    "ResumePacket",
    "ProcedureStep",
    "ProcedureRecord",
    "ProcedureLibrary",
    "PromptEnvelope",
    "ContextBundle",
    "PlanStep",
    "PlanDraft",
    "ExecutionResult",
    "EventEnvelope",
)
