name: MS Teams Chat Extraction
description: Sentiment Analysis for MS Teams Chats
steps:
  - MSTeamsMessages:
      credentials:
        tenant_id: "MS_TEAMS_TENANT_ID"
        client_id: "MS_TEAMS_CLIENT_ID"
        client_secret: "MS_TEAMS_CLIENT_SECRET"
      comments: "Extracting MS Teams Chat Messages"
      team_id: MS_TEAMS_DEFAULT_TEAMS_ID
      chat_name: "National CE Field Team Chat"
      program_name: "Hisense"
      weeks: 8
      as_dataframe: True
  - SentimentAnalysis:
      text_column: text
      sentiment_model: "MarieAngeA13/Sentiment-Analysis-BERT"
      sentiment_levels: 3
      emotions_model: "AdamCodd/distilbert-base-uncased-finetuned-emotion-balanced"
  - TransformRows:
      fields:
        created_date:
          value:
            - to_date
  - CopyToMongoDB:
      schema: hisense
      tablename: msteams_chats
      dbtype: documentdb
