name: Hisense Customer Satisfaction
description: Customer Satisfaction from Reviews.
steps:
  - OpenWithPandas:
      mime: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      trim: true
      file:
        pattern: reviews_test.xlsx
      directory: /home/ubuntu/symbits/hisense/files/reviews/
  - tFilter:
      operator: "&"
      filter:
        - column: review
          expression: "not_null"
  - CustomerSatisfaction:
      llm:
        name: VertexLLM
        model_name: gemini-1.5-pro
        temperature: 0.4
      review_column: review
      product_column: product_name
      columns:  # optional columns to be preserved:
        - product_name
        - product_model
        - sku
        - product_type
        - account_name
        - picture_url
        - url
      output_column: customer_satisfaction
  - PandasToFile:
      filename: /home/ubuntu/symbits/hisense/customer-satisfaction-hisense-{today}.xlsx
      mime: application/vnd.ms-excel
      masks:
        today:
          - today
          - mask: "%m%d%Y"
  # - CopyToBigQuery:
  #     tablename: customer_satisfaction
  #     schema: hisense
  # - CopyToMongoDB:
  #     schema: hisense
  #     tablename: customer_satisfaction
  #     dbtype: documentdb
