name: Hisense Employee Evaluation
description: Employee Evaluation based on Chats.
steps:
  - OpenWithPandas:
      mime: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      process: true
      trim: true
      file:
        pattern: chats-hisense-ce-03042025.xlsx
        yesterday:
            - yesterday
            - mask: "%Y%m%d"
      directory: /home/ubuntu/symbits/hisense/
  - tFilter:
      operator: "&"
      filter:
        - column: text
          expression: "not_null"
  - EmployeeEvaluation:
      llm:
        name: VertexLLM
        model_name: gemini-1.5-pro
        temperature: 0.4
      output_column: employee_evaluation
  - PandasToFile:
      filename: /home/ubuntu/symbits/hisense/employee-evaluation-hisense-{today}.xlsx
      mime: application/vnd.ms-excel
      masks:
        today:
          - today
          - mask: "%m%d%Y"
