[project]
name = "ovld"
version = "0.5.18"
description = "Overloading Python functions"
authors = [
    { name = "Olivier Breuleux", email = "breuleux@gmail.com" }
]
dependencies = []
readme = "README.md"
license = "MIT"
requires-python = ">= 3.9"

[project.urls]
Homepage = "https://ovld.readthedocs.io/en/latest/"
Documentation = "https://ovld.readthedocs.io/en/latest/"
Repository = "https://github.com/breuleux/ovld"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "codefind~=0.1.6",
    "pytest>=8.3.2",
    "pytest-benchmark>=4.0.0",
    "pytest-cov>=5.0.0",
    "pytest-regressions>=2.5.0",
    "mkdocs>=1.6.1",
]
benchmark = [
    "multimethod>=1.12",
    "multipledispatch>=1.0.0",
    "plum-dispatch>=2.5.2",
    "runtype>=0.5.3",
]

[tool.hatch.build.targets.wheel]
packages = ["src/ovld"]

[tool.ruff]
line-length = 95
exclude = ["docs/"]

[tool.ruff.lint]
extend-select = ["I"]
ignore = [
    "B015",     # because of lazy tests
    "B018",     # because of lazy tests
    "DTZ001",   # require tzinfo arg to datetime, not appropriate for our tests
    "FA102",    # tests are 3.9 incompatible but that's fine
    "FA100",    # tests are 3.9 incompatible but that's fine
    "F811",     # repeated defs, ovld basically requires disabling this
    "F821",     # because of strings in advanced annotations that are not references
    "PLW0120",  # else:return -> return; I don't like this rule
    "RET501",   # return None -> return; I don't like this rule
    "RUF023",   # who cares if slots are sorted?
    "S102",     # use of exec is fine
    "SIM102",   # combine if statements; I don't like this rule
    "SIM114",   # combine if statements; I don't like this rule
    "TC004",    # irrelevant
    "UP007",    # Union[] vs |
    "UP045",    # Optional[] vs |None

    "PYI041",   # int | float = float; need to fix this
]

# Ignore these for now, ruff reports SyntaxError because they use Python 3.10+ features
exclude = ["benchmarks/test_calc.py", "benchmarks/test_tweaknum.py", "docs/", "gen*"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--benchmark-columns=median,min,max"
testpaths = [
    "tests",
]
