project:
  type: website
  render:
    - 8ChannelDemultiplexer.qmd
    - 90BendPolarizationSplitterRotator.qmd
    - 90OpticalHybrid.qmd
    - AbsorbingBoundaryReflection.qmd
    - AdiabaticCouplerLN.qmd
    - AdvancedGaussianSources.qmd
    - AllDielectricStructuralColor.qmd
    - AndersonLocalization.qmd
    - AnimationTutorial.qmd
    - AnisotropicBendsEME.qmd
    - AnisotropicMetamaterialBroadbandPBS.qmd
    - AntiResonantHollowCoreFiber.qmd
    - AutoGrid.qmd
    - Autograd0Overview.qmd
    - Autograd0Quickstart.qmd
    - Autograd0QuickstartII.qmd
    - Autograd10YBranchLevelSet.qmd
    - Autograd12LightExtractor.qmd
    - Autograd13Metasurface.qmd
    - Autograd15Antenna.qmd
    - Autograd16BilayerCoupler.qmd
    - Autograd17BandPassFilter.qmd
    - Autograd18TopologyBend.qmd
    - Autograd19ApodizedCoupler.qmd
    - Autograd1Intro.qmd
    - Autograd20MetalensWaveguideTaper.qmd
    - Autograd21GaPLightExtractor.qmd
    - Autograd22PhotonicCrystal.qmd
    - Autograd23FabricationAwareInvdes.qmd
    - Autograd24DigitalSplitter.qmd
    - Autograd25WaveguideCrossing.qmd
    - Autograd26DiffractiveBeamSplitter.qmd
    - Autograd27Smatrix.qmd
    - Autograd28FiberLens.qmd
    - Autograd29SourceGradients.qmd
    - Autograd2GradientChecking.qmd
    - Autograd30ParallelAdjoint.qmd
    - Autograd33FPCavity.qmd
    - Autograd32WDMTopologyToContourFinetuning.qmd
    - Autograd3InverseDesign.qmd
    - Autograd4MultiObjective.qmd
    - Autograd5BoundaryGradients.qmd
    - Autograd6GratingCoupler.qmd
    - Autograd7Metalens.qmd
    - Autograd8WaveguideBend.qmd
    - Autograd9WDM.qmd
    - AvalanchePhotodiode.qmd
    - Bandstructure.qmd
    - BatchModeSolver.qmd
    - BayesianOptimizationYJunction.qmd
    - BeerLambert.qmd
    - BilayerSiNEdgeCoupler.qmd
    - BilayerSiNSiGC.qmd
    - BilevelPSR.qmd
    - BiosensorGrating.qmd
    - BistablePCCavity.qmd
    - BlueMicroLED.qmd
    - BoundaryConditions.qmd
    - BraggGratings.qmd
    - BroadbandDirectionalCoupler.qmd
    - BroadbandPlaneWaveWithConstantObliqueIncidentAngle.qmd
    - BullseyeCavityPSO.qmd
    - CMOSRGBSensor.qmd
    - CPOHeat.qmd
    - CavityFOM.qmd
    - ChargeSolver.qmd
    - CreatingGeometryUsingTrimesh.qmd
    - CustomFieldSource.qmd
    - CustomMediumTutorial.qmd
    - Design.qmd
    - DielectricMetasurfaceAbsorber.qmd
    - DirectionalCoupler.qmd
    - DirectionalCouplerSurrogate.qmd
    - DirectionalScatteringNanodisks.qmd
    - DisorderedPlasmonicColor.qmd
    - Dispersion.qmd
    - DistributedBraggReflectorCavity.qmd
    - DivergedFDTDSimulation.qmd
    - EMEBends.qmd
    - EMESolver.qmd
    - EdgeCoupler.qmd
    - EffectiveIndexApproximation.qmd
    - EulerWaveguideBend.qmd
    - FarFieldProjectionNonDecayingField.qmd
    - FieldProjections.qmd
    - Fitting.qmd
    - FocusedApodGC.qmd
    - FreeFormCoupler.qmd
    - FresnelLens.qmd
    - FullyAnisotropic.qmd
    - GDSCreation.qmd
    - GDSExport.qmd
    - GDSImport.qmd
    - GUIDataTutorial.qmd
    - GeneticAlgorithmReflector.qmd
    - GeometryTransformations.qmd
    - GradientMetasurfaceReflector.qmd
    - GrapheneMetamaterial.qmd
    - GratingCoupler.qmd
    - GratingEfficiency.qmd
    - GroupDelayCalculation.qmd
    - Gyrotropic.qmd
    - HeatDissipationSOI.qmd
    - HeatSolver.qmd
    - HexagonalLatticeBands.qmd
    - HighQGe.qmd
    - HighQSi.qmd
    - IntegratedVivaldiAntenna.qmd
    - InverseDesign.qmd
    - KLayoutPlugin_DRCQuickstart.qmd
    - KerrSidebands.qmd
    - LNOIPolarizationSplitterRotator.qmd
    - LayerRefinement.qmd
    - LedLEECalculation.qmd
    - LocalSubpixel.qmd
    - LowContrastWaveguide.qmd
    - MetasurfaceHologram.qmd
    - MIMResonator.qmd
    - MMI1x4.qmd
    - MMIMeepBenchmark.qmd
    - MMIPowerSplitter2x2.qmd
    - MachZehnderModulator.qmd
    - MaxwellStressTensor.qmd
    - MetalHeaterPhaseShifter.qmd
    - MetalOxideSunscreen.qmd
    - Metalens.qmd
    - MetasurfaceBIC.qmd
    - MicrowaveFrequencySelectiveSurface.qmd
    - MidIRMetalens.qmd
    - MoS2Waveguide.qmd
    - ModalSourcesMonitors.qmd
    - ModeOverlap.qmd
    - ModeSimulation.qmd
    - ModeSolver.qmd
    - ModesBentAngled.qmd
    - MultiplexingMMI.qmd
    - MultipoleExpansion.qmd
    - NanobeamCavity.qmd
    - NanostructuredBoronNitride.qmd
    - Near2FarSphereRCS.qmd
    - NonHermitianMetagratings.qmd
    - OpticalLuneburgLens.qmd
    - OpticalSwitchDBS.qmd
    - OptimizedL3.qmd
    - PCMBraggGratingFilter.qmd
    - PECSphereRCS.qmd
    - PICComponents.qmd
    - PINMachZehnder.qmd
    - ParameterScan.qmd
    - ParameterScanWebRun.qmd
    - ParticleSwarmOptimizedPBS.qmd
    - PhaseChangeAntennas.qmd
    - PhotoThermalWaveguides.qmd
    - PhotonicCrystalWaveguidePolarizationFilter.qmd
    - PhotonicCrystalsComponents.qmd
    - PhotonicSpinSelector.qmd
    - PlasmonicNanoparticle.qmd
    - PlasmonicNanorodArray.qmd
    - PlasmonicPhotothermalHeating.qmd
    - PlasmonicWaveguideCO2Sensor.qmd
    - PlasmonicYagiUdaNanoantenna.qmd
    - PolarizationSplitterRotator.qmd
    - Primer.qmd
    - QMRSMetasurface.qmd
    - RFAutograd1RectangularPatchAntenna.qmd
    - RadiativeCoolingGlass.qmd
    - RadiativeLossesModeSolver.qmd
    - ResonanceFinder.qmd
    - RingResonator.qmd
    - SMatrix.qmd
    - STLImport.qmd
    - SWGBroadbandPolarizer.qmd
    - SWGWaveguideCrossing.qmd
    - SbendCMAES.qmd
    - ScaleInvariantWaveguide.qmd
    - SelfIntersectingPolyslab.qmd
    - SiNToAlOxVerticalCoupler.qmd
    - SiWaveguideTPA.qmd
    - SiliconOrganicHybrid.qmd
    - SiliconToPlasmonicCoupler.qmd
    - SimpleModeSolverGUI.qmd
    - Simulation.qmd
    - SourceNormalization.qmd
    - StartHere.qmd
    - StripToSlotConverters.qmd
    - Symmetry.qmd
    - TFLNTidy3d.qmd
    - TFSF.qmd
    - THzDemultiplexerFilter.qmd
    - TaperedWgDispersion.qmd
    - ThermallyTunedRingResonator.qmd
    - ThermoOpticDopedModulator.qmd
    - TidyFab0GC.qmd
    - TimeModulationTutorial.qmd
    - TopoQuantumPhC.qmd
    - TransientThermoOpticShifter.qmd
    - TunableChiralMetasurface.qmd
    - UnstructuredData.qmd
    - VerticalGratingCoupler.qmd
    - VerticalPINSSAC.qmd
    - VizData.qmd
    - VizSimulation.qmd
    - VortexMetasurface.qmd
    - WaveguideBendSimulator.qmd
    - WaveguideCrossing.qmd
    - WaveguideGratingAntenna.qmd
    - WaveguidePluginDemonstration.qmd
    - WaveguideSizeConverter.qmd
    - WaveguideToRingCoupling.qmd
    - WebAPI.qmd
    - XarrayTutorial.qmd
    - YJunction.qmd
    - ZeroCrossTalkTE.qmd
    - ZonePlateFieldProjection.qmd

execute:
  freeze: true
  warning: false
