name: Zoom Interface
description: Zoom Interface
steps:
  # - Zoom:
  #     from_date: "2025-10-13"
  #     to_date: "2025-10-14"
  #     save_path: "/home/ubuntu/symbits/zoom/recordings"
  #     download: true
  #     download_transcripts: false
  # - TableOutput:
  #     depends:
  #       - Zoom_1
  #     tablename: calls
  #     schema: assurant
  #     flavor: postgres
  #     pk:
  #       - id
  - QueryToPandas:
      query: select local_path from assurant.calls where id IN ('ce2585c5-dffb-4323-a29e-12a05076f90e')
  - ExtractTranscript:
      audio_column: local_path
      language: en
      model_size: small
      diarization: true
      summarization: true
      device: cuda
      cuda_number: 0
      skip_errors: true
  - CallAnalysis:
      prompt_file: prompt-audio-sentiment.txt
      llm:
        llm: google
        model: gemini-2.5-pro
        temperature: 0.4
        max_tokens: 8192
      use_dataframe: true
      file_path_column: srt_path
      directory: /home/ubuntu/symbits/zoom/recordings/
      pattern: "*.srt"
      description_column: filename
      content_column: transcript_content
      output_column: call_analysis
      as_text: true
  - PandasToFile:
      filename: /home/ubuntu/symbits/zoom/calls.csv
      mime: text/csv
      quoting: string
      pd_args:
        sep: "|"
