name: Splitting a PDF File into Multiple PDFs
description: Split a PDF file into multiple PDFs based on specified page ranges.
steps:
  - SplitPDF:
      files:
        - /home/ubuntu/symbits/smartsheet/row_attachments/106_HVAC_Thoro-Air_HVAC FULL Packet.pdf
      split_pattern:
        HVAC:
          sow: [0, 9]
          w9: [10, 15]
          ach: [16, 16]
          eq_services: [17, 31]
        Garage:
          sow: [21, 30]
          w9: [15, 20]
          ach: [0, 0]
          eq_services: [1, 14]
        Pool:
          sow: [21, 30]
          w9: [15, 20]
          ach: [0, 0]
          eq_services: [1, 14]
        Electrical:
          sow: [21, 30]
          w9: [15, 20]
          ach: [0, 0]
          eq_services: [1, 14]
      directory: /home/ubuntu/symbits/assurant/packets/
