[build-system]
# Minimum requirements for the build system to execute.
requires = [
    'setuptools >= 77.0.0',
    'passagemath-conf ~= 10.8.10.0 ; sys_platform != "win32"',
    'passagemath-setup ~= 10.8.10.0',
    'passagemath-environment ~= 10.8.10.0',
    'passagemath-categories ~= 10.8.10.0',
    'passagemath-modules ~= 10.8.10.0',
    'cython >=3.1.0,<3.3.0',
    'gmpy2 ~=2.1.b999', 'gmpy2 ~=2.3.b1; sys_platform == "win32"',
    'cysignals !=1.12.4; sys_platform == "win32"', 'cysignals >= 1.12.6; python_version >= "3.14"', 'cysignals >=1.11.2, != 1.12.0',
    'memory_allocator <0.2',
    'pkgconfig',
]
build-backend = "setuptools.build_meta"

[project]
name = "passagemath-gap"
description = "passagemath: Computational Group Theory with GAP"
dependencies = [
    'cysignals !=1.12.4; sys_platform == "win32"', 'cysignals >= 1.12.6; python_version >= "3.14"', 'cysignals >=1.11.2, != 1.12.0',
    'dot2tex >=2.12.0',
    'memory_allocator <0.2',
    'pexpect >=4.8.0',
    'passagemath-conf ~= 10.8.10.0 ; sys_platform != "win32"',
    'passagemath-environment ~= 10.8.10.0',
    'passagemath-categories ~= 10.8.10.0',
    'passagemath-gap-pkg-factint-data ~= 10.8.10.0',
    'passagemath-gap-pkg-primgrp-data ~= 10.8.10.0',
    'passagemath-gap-pkg-smallgrp-data ~= 10.8.10.0',
    'passagemath-repl ~= 10.8.10.0',                         ]
dynamic = ["version"]
license = "GPL-2.0-or-later"
authors = [{name = "The Sage Developers", email = "sage-support@googlegroups.com"}]
maintainers = [
    {name = "Matthias Köppe"},
    {name = "passagemath contributors"},
]
classifiers = [
    "Development Status :: 6 - Mature",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering :: Mathematics",
]
requires-python = ">=3.11, <3.15"

[project.urls]
"release notes" = "https://github.com/passagemath/passagemath/releases"
"repo (upstream)" = "https://github.com/sagemath/sage"
"repo" = "https://github.com/passagemath/passagemath"
documentation = "https://passagemath.org/docs/latest"
"homepage (upstream)" = "https://www.sagemath.org"
"discourse" = "https://passagemath.discourse.group"
"tracker (upstream)" = "https://github.com/sagemath/sage/issues"
"tracker" = "https://github.com/passagemath/passagemath/issues"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.optional-dependencies]
test            = []

# GAP packages
# - external dependencies per 'ExternalConditions' in PackageInfo.g
# - dependencies on packages with external dependencies per 'NeededOtherPackages' in PackageInfo.g
4ti2interface   = ['passagemath-latte-4ti2 ~= 10.8.10.0',]
aclib           = ["passagemath-gap[polycyclic]"]
agt             = ['passagemath-gap-pkg-agt-data ~= 10.8.10.0',]
alnuth          = ['passagemath-pari ~= 10.8.10.0',]
automata        = ['passagemath-graphviz ~= 10.8.10.0',]
caratinterface  = ['passagemath-gap-pkg-caratinterface ~= 10.8.10.0',]
cddinterface    = ['passagemath-gap-pkg-cddinterface ~= 10.8.10.0',]
corefreesub     = ["passagemath-gap[polycyclic]",
                   'passagemath-graphviz ~= 10.8.10.0',]
cryst           = ["passagemath-gap[polycyclic]"]
crystcat        = ["passagemath-gap[cryst]"]
ctbllib         = ['passagemath-gap-pkg-ctbllib-data ~= 10.8.10.0',]
cubefree        = ["passagemath-gap[grpconst,polycyclic]"]
curlinterface   = ['passagemath-gap-pkg-curlinterface ~= 10.8.10.0',]
deepthought     = ["passagemath-gap[polycyclic]"]
difsets         = ['passagemath-gap-pkg-difsets-data ~= 10.8.10.0',]
digraphs        = ['passagemath-graphviz ~= 10.8.10.0',]
fining          = ['passagemath-graphviz ~= 10.8.10.0',]
float           = ['passagemath-gap-pkg-float ~= 10.8.10.0',]
fr              = ["passagemath-gap[polycyclic]"]
fwtree          = ["passagemath-gap[polycyclic]"]
grpconst        = ["passagemath-gap[irredsol]"]
guarana         = ["passagemath-gap[polenta]"]
hap             = ["passagemath-gap[polycyclic,crystcat,aclib,nq]",
                   'passagemath-graphviz ~= 10.8.10.0',]
hapcryst        = ["passagemath-gap[polycyclic,aclib,cryst,hap,polymaking]"]
help            = ["passagemath-gap[ctbllib]"]
irredsol        = ['passagemath-gap-pkg-irredsol-data ~= 10.8.10.0',]
lpres           = ["passagemath-gap[polycyclic]"]
modisom         = ["passagemath-gap[polycyclic]"]
nilmat          = ["passagemath-gap[polenta]"]
nq              = ["passagemath-gap[polycyclic]"]
normalizinterface = ['passagemath-gap-pkg-normalizinterface ~= 10.8.10.0',]
numericalsgps   = ['passagemath-gap-pkg-numericalsgps-data ~= 10.8.10.0',
                   'passagemath-graphviz ~= 10.8.10.0',]
polenta         = ["passagemath-gap[polycyclic,alnuth,radiroot]"]
polycyclic      = ["passagemath-gap[alnuth]"]
polymaking      = ['passagemath-polymake ~= 10.8.10.0',]
radiroot        = ["passagemath-gap[alnuth]"]
rcwa            = ['passagemath-gap-pkg-rcwa-data ~= 10.8.10.0', "passagemath-gap[resclasses]"]
resclasses      = ["passagemath-gap[polycyclic]"]
semigroups      = ['passagemath-gap-pkg-semigroups ~= 10.8.10.0',]
sglppow         = ['passagemath-gap-pkg-sglppow-data ~= 10.8.10.0',]
sgpviz          = ['passagemath-graphviz ~= 10.8.10.0',]
simpcomp        = ['passagemath-gap-pkg-simpcomp-data ~= 10.8.10.0',]
singular        = ['passagemath-singular ~= 10.8.10.0',]
smallsemi       = ['passagemath-gap-pkg-smallsemi-data ~= 10.8.10.0',]
sonata          = ['passagemath-gap-pkg-sonata-data ~= 10.8.10.0',]
symbcompcc      = ["passagemath-gap[polycyclic]"]
tomlib          = ['passagemath-gap-pkg-tomlib-data ~= 10.8.10.0',]
transgrp        = ['passagemath-gap-pkg-transgrp-data ~= 10.8.10.0',]
xmod            = ["passagemath-gap[hap]"]
unitlib         = ['passagemath-gap-pkg-unitlib-data ~= 10.8.10.0',]
yangbaxter      = ['passagemath-gap-pkg-yangbaxter-data ~= 10.8.10.0', "passagemath-gap[cryst]"]

# Jupyter
jupyterkernel   = ['passagemath-gap-pkg-jupyterkernel',]
jupyterlab      = [
    "passagemath-gap[jupyterkernel]",
    'jupyterlab',
]
notebook        = [
    "passagemath-gap[jupyterkernel]",
    'notebook >=6.1.1',
]

# Everything as in standard Sage
standard        = [
    "passagemath-gap[transgrp,ctbllib,tomlib,irredsol]",
    'passagemath-pari ~= 10.8.10.0',
    'passagemath-singular ~= 10.8.10.0',
]

# The full set of GAP packages shipped by the GAP distribution;
# omitted: polymaking
# omitted: jupyterkernel -- the indirect self-reference passagemath-gap-package-jupyterkernel -> passagemath-gap is problematic for tox, which tries to "install_package_deps" before installing the package.
full            = [
    "passagemath-gap[standard,4ti2interface,agt,caratinterface,cddinterface,curlinterface,difsets,normalizinterface,numericalsgps,rcwa,semigroups,sglppow,simpcomp,smallsemi,sonata,unitlib,yangbaxter]"
]

[tool.cibuildwheel.linux]
repair-wheel-command = [
    'python3 -m pip install passagemath-conf auditwheel',
    'python3 {package}/repair_wheel.py {wheel}',
    'auditwheel repair -w {dest_dir} {wheel}',
]
[tool.cibuildwheel.macos]
repair-wheel-command = [
    'python3 -m pip install passagemath-conf auditwheel',
    'python3 {package}/repair_wheel.py {wheel}',
    'delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}',
]

[tool.setuptools]
include-package-data = false

[tool.setuptools.dynamic]
version = {file = ["VERSION.txt"]}

[external]
# External dependencies in the format proposed by https://peps.python.org/pep-0725
build-requires = [
  "virtual:compiler/c",
  "virtual:compiler/cpp",
  "pkg:generic/pkg-config",
]

host-requires = [
  "pkg:generic/gap",
  "pkg:generic/gmp",
  "pkg:generic/mpc",
  "pkg:generic/mpfr",
]

dependencies = [
]
