[tox]
envlist=
  py312-default
  py312-batching
  py312-pex_tests
  py313-default
  py313-batching
  py313-pex_tests
  py314-default
  py314-batching
  py314-pex_tests

skipsdist = True

[testenv]
download = True
setenv =
  DD_DOGSTATSD_DISABLE = true
passenv =
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
    CI_*
    BUILDKITE*
    DAGSTER_GIT_REPO_DIR
    DAGSTER_INTERNAL_GIT_REPO_DIR
    SNOWFLAKE*
    AWS_*
    DOCKER_CONFIG
install_command = /bin/bash {env:DAGSTER_INTERNAL_GIT_REPO_DIR}/scripts/uv-install-tests.sh {packages}
deps =
  IGNORED
allowlist_externals =
  /bin/bash
  echo
  uv
commands =
  /bin/bash -c '! pip list --exclude-editable | grep -e dagster'
  default: pytest -vv \
    --ignore ./dagster_cloud_tests/agent_tests/pex_tests \
    --ignore ./dagster_cloud_tests/cli_tests/pex_tests \
    --durations 10 {posargs}
  batching: pytest -vv ./dagster_cloud_tests/agent_tests/test_dagster_cloud_agent.py --agent-batching-enabled --durations 10 {posargs}
  pex_tests: pytest -vv ./dagster_cloud_tests/agent_tests/pex_tests ./dagster_cloud_tests/cli_tests/pex_tests --durations 10 {posargs} --timeout 300