[project]
name = 'nvidia-cuda-runtime-cu13'
authors = [
    {name = 'NVIDIA Kitmaker Team', email = 'kitmaker@nvidia.com' },
]
description = 'DEPRECATED: Use nvidia-cuda-runtime instead'
license = 'Apache-2.0'
dependencies = []
version = '0.0.1'
readme = 'README.md'

[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'
