# Entry conditions:
# - `setup/checkout` has already happened
# - working dir is the root directory of your project (e.g. `reflex/`).
# - You have a `uv.lock` file in the root directory of your project
# - You have a `pyproject.toml` file in the root directory of your project
#
# Exit conditions:
# - Python of version `python-version` is ready to be invoked as `python`.
# - Uv of version `uv-version` is ready to be invoked as `uv`.
# - If `run-uv-sync` is true, deps as defined in `pyproject.toml` will have been installed into a `.venv`.

name: "Setup Reflex build environment"
description: "Sets up Python, installs uv, installs project deps"
inputs:
  python-version:
    description: "Python version setup"
    required: true
  uv-version:
    description: "Uv version to install"
    required: false
    default: latest
  run-uv-sync:
    description: "Whether to run uv sync on current dir"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Install UV
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        version: ${{ inputs.uv-version }}
        python-version: ${{ inputs.python-version }}
        enable-cache: false

    - if: ${{ inputs.run-uv-sync == 'true' }}
      name: Run uv sync
      shell: bash
      run: uv sync --all-extras --dev --prerelease=allow
