[project]
name = "renault-api"
version = "0.5.14"
description = "Renault API"
license = "MIT"
license-files = ["LICENSE.rst"]
requires-python = ">=3.10"
readme = "README.rst"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "aiohttp>=3.9.5",
    "PyJWT>=2.8.0",
    "marshmallow-dataclass>=8.2.0",
]

[[project.authors]]
name = "epenet"

[project.optional-dependencies]
cli = [
    "click>=8.0.1",
    "dateparser>=1.0.0",
    "tabulate>=0.8.7",
]

[project.scripts]
renault-api = "renault_api.cli.__main__:main"

[project.urls]
Homepage = "https://github.com/hacf-fr/renault-api"
Repository = "https://github.com/hacf-fr/renault-api"
Documentation = "https://renault-api.readthedocs.io"
Changelog = "https://github.com/hacf-fr/renault-api/releases"

[dependency-groups]
dev = [
    "aiointercept==0.1.12",
    "codespell==2.4.3",
    "covdefaults==2.3.0",
    "coverage[toml]==7.16.2",
    "pre-commit-hooks==6.0.0",
    "prek==0.5.4",
    "pytest==9.1.1",
    "pytest-asyncio==1.4.0",
    "pytest-cov==7.1.0",
    "ruff==0.16.9",
    "syrupy==6.1.1",
    "ty==0.0.84",
    "yamllint==1.38.0",
    "zizmor==1.30.1",
]
docs = [
    "furo==2025.12.19; python_version >= '3.14'",
    "myst-parser==5.1.0; python_version >= '3.14'",
    "sphinx==9.1.0; python_version >= '3.14'",
    "sphinx-autobuild==2025.8.25; python_version >= '3.14'",
    "sphinx-click==6.2.0; python_version >= '3.14'",
]

[tool.uv]
default-groups = [
    "dev",
    "docs",
]

[tool.codespell]
skip = "node_modules,package-lock.json,uv.lock"
ignore-words-list = "advices,equipments,espace,garantie,groupe,notse,rcall,serie"

[tool.coverage.paths]
source = [
    "src",
    "*/site-packages",
]

[tool.coverage.run]
plugins = ["covdefaults"]
source = ["renault_api"]

[tool.coverage.covdefaults]
subtract_omit = "*/__main__.py"

[tool.coverage.report]
fail_under = 89

[tool.ty.environment]
python-version = "3.10"

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
ignore = [
    "A001",
    "A002",
    "N815",
    "PLR0911",
    "PLR0913",
    "PLR0917",
]
select = [
    "A",
    "B",
    "C4",
    "C90",
    "E",
    "ERA",
    "F",
    "I",
    "N",
    "PL",
    "PT",
    "UP",
]

[tool.ruff.lint.isort]
force-single-line = true
known-local-folder = ["renault_api"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pydocstyle]
convention = "google"

[build-system]
requires = ["uv_build>=0.12.21,<0.13"]
build-backend = "uv_build"
