[tox]
verbosity = 2
color = true
envlist = unit-310, unit-311, unit-312, integration-310, integration-312, docs

[testenv]
deps = pytest
       pytest-cov
       pytest-mock
       coverage

[testenv:unit]
commands = pytest -v --disable-warnings --cov=streamsets/sdk tests/unit

[testenv:integration]
commands = python -m pytest -v --cov=streamsets/sdk --disable-warnings --sch-credential-id={env:SCH_CREDENTIAL_ID} --sch-token={env:SCH_TOKEN} --sdc-version={env:SDC_VERSION} --transformer-version={env:TRANSFORMER_VERSION} --aster-url={env:ASTER_URL} tests/integration

[testenv:unit-310]
basepython = python3.10
commands = pytest -v --cov=streamsets/sdk --cov-report xml:coverage_unit_310.xml --junitxml results_unit_310.xml --disable-warnings tests/unit

[testenv:unit-311]
basepython = python3.11
commands = pytest -v --cov=streamsets/sdk --cov-report xml:coverage_unit_311.xml --junitxml results_unit_311.xml --disable-warnings tests/unit

[testenv:unit-312]
basepython = python3.12
commands = pytest -v --cov=streamsets/sdk --cov-report xml:coverage_unit_312.xml --junitxml results_unit_312.xml --disable-warnings tests/unit

[testenv:integration-310]
basepython = python3.10
commands = python -m pytest -v --cov=streamsets/sdk --cov-report xml:coverage_integration_310.xml --junitxml results_integration_310.xml --disable-warnings --sys-admin-email={env:SYS_ADMIN_EMAIL} --sys-admin-password={env:SYS_ADMIN_PASSWORD} --org-admin-email={env:ORG_ADMIN_EMAIL} --org-admin-password={env:ORG_ADMIN_PASSWORD} --firebase-api-key={env:FIREBASE_API_KEY} --sdc-version={env:SDC_VERSION} --transformer-version={env:TRANSFORMER_VERSION} --aster-url={env:ASTER_URL} --aws-key-id={env:AWS_ACCESS_KEY_ID} --aws-access-key={env:AWS_SECRET_ACCESS_KEY} --environment-region={env:REGION} --vpc-id={env:VPC_ID} --aws-subnet-ids={env:SUBNET_IDS} --aws-security-group-id={env:SECURITY_GROUP_ID}  --instance-profile={env:INSTANCE_PROFILE} --snowflake-username {env:SNOWFLAKE_USERNAME} --snowflake-password {env:SNOWFLAKE_PASSWORD} tests/integration

[testenv:integration-312]
basepython = python3.12
commands = python -m pytest -vvv --cov=streamsets/sdk --cov-report xml:coverage_integration_312.xml --junitxml results_integration_312.xml --disable-warnings --sys-admin-email={env:SYS_ADMIN_EMAIL} --sys-admin-password={env:SYS_ADMIN_PASSWORD} --org-admin-email={env:ORG_ADMIN_EMAIL} --org-admin-password={env:ORG_ADMIN_PASSWORD} --firebase-api-key={env:FIREBASE_API_KEY} --sdc-version={env:SDC_VERSION} --transformer-version={env:TRANSFORMER_VERSION} --aster-url={env:ASTER_URL} --aws-key-id={env:AWS_ACCESS_KEY_ID} --aws-access-key={env:AWS_SECRET_ACCESS_KEY} --environment-region={env:REGION} --vpc-id={env:VPC_ID} --aws-subnet-ids={env:SUBNET_IDS} --aws-security-group-id={env:SECURITY_GROUP_ID}  --instance-profile={env:INSTANCE_PROFILE} --snowflake-username {env:SNOWFLAKE_USERNAME} --snowflake-password {env:SNOWFLAKE_PASSWORD} tests/integration

[testenv:format]
deps = black
       isort
       flake8
commands = black --config=evergreen/pyproject.toml streamsets/sdk
           isort --settings-path=evergreen/pyproject.toml streamsets/sdk
           flake8 --config=evergreen/.flake8 streamsets/sdk

[testenv:docs]
deps = -rdocs/requirements.txt
commands = sphinx-build -b html -d .sphinx-build docs html
