# coding: utf-8

"""
    SwiftyRX API

    API for the SwiftyRX Backend 

    The version of the OpenAPI document: 0.1.DEV-0
    Contact: paul.tindall@rxfoundry.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rxfoundry.clients.swifty_api.models.patient_message import PatientMessage

class TestPatientMessage(unittest.TestCase):
    """PatientMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatientMessage:
        """Test PatientMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatientMessage`
        """
        model = PatientMessage()
        if include_optional:
            return PatientMessage(
                message_id = '',
                message_type = 'created',
                is_completed = True,
                activity_tasks = [
                    rxfoundry.clients.swifty_api.models.patient_message_task.PatientMessageTask(
                        parent_task_type = 'patient_message', 
                        uuid = '', 
                        message_id = '', 
                        patient_external_id = '', 
                        patient_external_slug = '', 
                        created_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        task_type = '', 
                        manual_review_required = True, 
                        is_completed = True, 
                        statuses = [
                            rxfoundry.clients.swifty_api.models.patient_message_task_status.PatientMessageTaskStatus(
                                uuid = '', 
                                status_type = rxfoundry.clients.swifty_api.models.status_type.StatusType(
                                    uuid = '', 
                                    status_type_description = '', ), 
                                status_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                status_info = { }, 
                                patient = rxfoundry.clients.swifty_api.models.patient.Patient(
                                    uuid = '', 
                                    last_name = '', 
                                    first_name = '', 
                                    middle_name = '', 
                                    suffix = '', 
                                    prefix = '', 
                                    gender = rxfoundry.clients.swifty_api.models.code.Code(
                                        uuid = '', 
                                        code = '', 
                                        description = '', ), 
                                    date_of_birth = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    home_address = rxfoundry.clients.swifty_api.models.address.Address(
                                        uuid = '', 
                                        address_line_one = '', 
                                        address_line_two = '', 
                                        city = '', 
                                        state_province = '', 
                                        postal_code = '', 
                                        country_code = '', 
                                        longitude = 1.337, 
                                        latitude = 1.337, 
                                        distance = 1.337, ), 
                                    primary_phone = '', 
                                    alternate_phone = '', 
                                    email = '', 
                                    external_references = [
                                        rxfoundry.clients.swifty_api.models.patient_external_identifier.PatientExternalIdentifier(
                                            external_id = '', 
                                            external_system_slug = '', 
                                            external_email = '', 
                                            external_mobile_phone = '', )
                                        ], 
                                    allergies = [
                                        rxfoundry.clients.swifty_api.models.patient_allergy.PatientAllergy(
                                            allergy = rxfoundry.clients.swifty_api.models.code.Code(
                                                uuid = '', 
                                                code = '', 
                                                description = '', ), 
                                            description = '', )
                                        ], 
                                    conditions = [
                                        rxfoundry.clients.swifty_api.models.patient_condition.PatientCondition(
                                            condition = , 
                                            description = '', )
                                        ], 
                                    medications = [
                                        rxfoundry.clients.swifty_api.models.patient_medication.PatientMedication(
                                            medication = null, 
                                            description = '', )
                                        ], 
                                    insurances = [
                                        rxfoundry.clients.swifty_api.models.insurance.Insurance(
                                            uuid = '', 
                                            member_id = '', 
                                            rx_bin = '', 
                                            rx_pcn = '', 
                                            rx_group = '', 
                                            is_savings_card = True, 
                                            is_coupon_card = True, 
                                            patient_relationship = , 
                                            payer_responsibility = , )
                                        ], 
                                    preferred_language = , 
                                    former_names = [
                                        rxfoundry.clients.swifty_api.models.patient_name.PatientName(
                                            first_name = '', 
                                            last_name = '', 
                                            middle_name = '', 
                                            suffix = '', 
                                            prefix = '', 
                                            credentials = '', )
                                        ], 
                                    former_phone_numbers = [
                                        rxfoundry.clients.swifty_api.models.patient_phone_number.PatientPhoneNumber(
                                            phone_number = '', )
                                        ], 
                                    former_addresses = [
                                        rxfoundry.clients.swifty_api.models.address.Address(
                                            uuid = '', 
                                            address_line_one = '', 
                                            address_line_two = '', 
                                            city = '', 
                                            state_province = '', 
                                            postal_code = '', 
                                            country_code = '', 
                                            longitude = 1.337, 
                                            latitude = 1.337, 
                                            distance = 1.337, )
                                        ], 
                                    former_insurances = [
                                        rxfoundry.clients.swifty_api.models.insurance.Insurance(
                                            uuid = '', 
                                            member_id = '', 
                                            rx_bin = '', 
                                            rx_pcn = '', 
                                            rx_group = '', 
                                            is_savings_card = True, 
                                            is_coupon_card = True, )
                                        ], 
                                    is_registered = True, 
                                    score = 56, ), )
                            ], )
                    ]
            )
        else:
            return PatientMessage(
        )
        """

    def testPatientMessage(self):
        """Test PatientMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
