# coding: utf-8

"""
    SwiftyRX API

    API for the SwiftyRX Backend 

    The version of the OpenAPI document: 0.1.DEV-0
    Contact: paul.tindall@rxfoundry.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rxfoundry.clients.swifty_api.models.prescription_change_request_and_response import PrescriptionChangeRequestAndResponse

class TestPrescriptionChangeRequestAndResponse(unittest.TestCase):
    """PrescriptionChangeRequestAndResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrescriptionChangeRequestAndResponse:
        """Test PrescriptionChangeRequestAndResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrescriptionChangeRequestAndResponse`
        """
        model = PrescriptionChangeRequestAndResponse()
        if include_optional:
            return PrescriptionChangeRequestAndResponse(
                change_request = rxfoundry.clients.swifty_api.models.prescription_change_request.PrescriptionChangeRequest(
                    message_id = '', 
                    prescription_number = '', 
                    change_request_code = rxfoundry.clients.swifty_api.models.code.Code(
                        uuid = '', 
                        code = '', 
                        description = '', ), 
                    change_request_sub_code = rxfoundry.clients.swifty_api.models.code.Code(
                        uuid = '', 
                        code = '', 
                        description = '', ), 
                    change_request_text = '', 
                    urgency = , 
                    requested_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                change_request_tasks = [
                    rxfoundry.clients.swifty_api.models.prescription_message_task.PrescriptionMessageTask(
                        parent_task_type = 'prescription_message', 
                        uuid = '', 
                        created_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        task_type = '', 
                        is_completed = True, 
                        manual_review_required = True, )
                    ],
                requested_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                requested_by = rxfoundry.clients.swifty_api.models.user.User(
                    username = '', 
                    first_name = '', 
                    last_name = '', 
                    email = '', 
                    is_staff = True, 
                    is_superuser = True, ),
                response = rxfoundry.clients.swifty_api.models.prescription_change_request_response.PrescriptionChangeRequestResponse(
                    message_id = '', 
                    request_message_id = '', 
                    approval_type = 'approved', 
                    changed_prescription_data = rxfoundry.clients.swifty_api.models.prescription_data.PrescriptionData(
                        source = 'Surescripts_RxTransferInitiationRequest', 
                        retract_message_id = '', 
                        external_rx_number = '', 
                        external_system_slug = '', 
                        patient_ref = '', 
                        prescriber_ref = '', 
                        supervisor_ref = '', 
                        from_pharmacy_npi = '', 
                        medication_ref = '', 
                        number_of_refills = 0, 
                        fill_quantity = 0.00010, 
                        quantity_uom_code = rxfoundry.clients.swifty_api.models.code.Code(
                            uuid = '', 
                            code = '', 
                            description = '', ), 
                        days_supply = 0, 
                        written_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        substitutions_code = '', 
                        sig_text = '', ), 
                    denial_codes = [
                        rxfoundry.clients.swifty_api.models.code.Code(
                            uuid = '', 
                            code = '', 
                            description = '', )
                        ], 
                    approval_text = '', 
                    denial_text = '', 
                    pending_text = '', 
                    tasks = [
                        rxfoundry.clients.swifty_api.models.prescription_message_task.PrescriptionMessageTask(
                            parent_task_type = 'prescription_message', 
                            uuid = '', 
                            created_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            task_type = '', 
                            is_completed = True, 
                            manual_review_required = True, )
                        ], ),
                response_tasks = [
                    rxfoundry.clients.swifty_api.models.prescription_message_task.PrescriptionMessageTask(
                        parent_task_type = 'prescription_message', 
                        uuid = '', 
                        created_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        task_type = '', 
                        is_completed = True, 
                        manual_review_required = True, )
                    ],
                responded_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                responded_by = rxfoundry.clients.swifty_api.models.user.User(
                    username = '', 
                    first_name = '', 
                    last_name = '', 
                    email = '', 
                    is_staff = True, 
                    is_superuser = True, ),
                response_status = 'APPROVED'
            )
        else:
            return PrescriptionChangeRequestAndResponse(
        )
        """

    def testPrescriptionChangeRequestAndResponse(self):
        """Test PrescriptionChangeRequestAndResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
