# coding: utf-8

"""
    SwiftyRX API

    API for the SwiftyRX Backend 

    The version of the OpenAPI document: 1.0.0.BUILD
    Contact: paul.tindall@rxfoundry.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rxfoundry.clients.swifty_api.models.patient_assignment_data import PatientAssignmentData

class TestPatientAssignmentData(unittest.TestCase):
    """PatientAssignmentData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatientAssignmentData:
        """Test PatientAssignmentData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatientAssignmentData`
        """
        model = PatientAssignmentData()
        if include_optional:
            return PatientAssignmentData(
                object_type = 'assignment',
                sub_tenant_slug = '',
                external_references = [
                    rxfoundry.clients.swifty_api.models.patient_external_identifier.PatientExternalIdentifier(
                        external_id = '', 
                        external_system_slug = '', 
                        external_email = '', 
                        external_mobile_phone = '', )
                    ]
            )
        else:
            return PatientAssignmentData(
                object_type = 'assignment',
                sub_tenant_slug = '',
        )
        """

    def testPatientAssignmentData(self):
        """Test PatientAssignmentData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
