name: Sync DocumentDB With NN
description: Sync DocumentDB With Network Ninja
steps:
  - DocumentDBQuery:
      schema: networkninja
      tablename: batches
      query:
        data.payload.event_id: 28046
        # data.metadata.transaction_type: "DELETE"
        # data.metadata.type: "store_photo"
        # data.metadata.timestamp: {
        #     "$gte": 1742774400.0,
        #     "$lte": 1743379200.999999
        # }
  # - NetworkNinja:
  #     comment: Network Ninja Router for processing the payload.
  #     action: process_payload
