# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from chalk._gen.chalk.streaming.v1 import debug_service_pb2 as chalk_dot_streaming_dot_v1_dot_debug__service__pb2


class StreamingDebugServiceStub(object):
    """Streaming Debug Service
    Provides APIs for managing and querying streaming resolver debug configuration
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetStreamingDebugConfig = channel.unary_unary(
            "/chalk.streaming.v1.StreamingDebugService/SetStreamingDebugConfig",
            request_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.SetStreamingDebugConfigRequest.SerializeToString,
            response_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.SetStreamingDebugConfigResponse.FromString,
        )
        self.GetStreamingDebugConfig = channel.unary_unary(
            "/chalk.streaming.v1.StreamingDebugService/GetStreamingDebugConfig",
            request_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetStreamingDebugConfigRequest.SerializeToString,
            response_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetStreamingDebugConfigResponse.FromString,
        )
        self.EnableDebugMode = channel.unary_unary(
            "/chalk.streaming.v1.StreamingDebugService/EnableDebugMode",
            request_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.EnableDebugModeRequest.SerializeToString,
            response_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.EnableDebugModeResponse.FromString,
        )
        self.DisableDebugMode = channel.unary_unary(
            "/chalk.streaming.v1.StreamingDebugService/DisableDebugMode",
            request_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.DisableDebugModeRequest.SerializeToString,
            response_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.DisableDebugModeResponse.FromString,
        )
        self.GetDebugModeStatus = channel.unary_unary(
            "/chalk.streaming.v1.StreamingDebugService/GetDebugModeStatus",
            request_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugModeStatusRequest.SerializeToString,
            response_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugModeStatusResponse.FromString,
        )
        self.GetDebugMessages = channel.unary_unary(
            "/chalk.streaming.v1.StreamingDebugService/GetDebugMessages",
            request_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugMessagesRequest.SerializeToString,
            response_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugMessagesResponse.FromString,
        )
        self.GetDebugMessagesV2 = channel.unary_unary(
            "/chalk.streaming.v1.StreamingDebugService/GetDebugMessagesV2",
            request_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugMessagesV2Request.SerializeToString,
            response_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugMessagesV2Response.FromString,
        )
        self.WatchDebugStream = channel.unary_stream(
            "/chalk.streaming.v1.StreamingDebugService/WatchDebugStream",
            request_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.WatchDebugStreamRequest.SerializeToString,
            response_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.WatchDebugStreamResponse.FromString,
        )
        self.PushTopic = channel.unary_unary(
            "/chalk.streaming.v1.StreamingDebugService/PushTopic",
            request_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.PushTopicRequest.SerializeToString,
            response_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.PushTopicResponse.FromString,
        )


class StreamingDebugServiceServicer(object):
    """Streaming Debug Service
    Provides APIs for managing and querying streaming resolver debug configuration
    """

    def SetStreamingDebugConfig(self, request, context):
        """Set streaming debug configuration (sample rates) for a resolver"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStreamingDebugConfig(self, request, context):
        """Get current streaming debug configuration for a resolver"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EnableDebugMode(self, request, context):
        """Deprecated: use SetStreamingDebugConfig instead"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DisableDebugMode(self, request, context):
        """Deprecated: use SetStreamingDebugConfig with logger_config=null instead"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDebugModeStatus(self, request, context):
        """Deprecated: use GetStreamingDebugConfig instead"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDebugMessages(self, request, context):
        """Get recent debug messages as parquet"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDebugMessagesV2(self, request, context):
        """Get recent debug messages as a structured response with per-feature
        values, error details, aggregate counts, and the expression each output
        feature is bound to in the resolver.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def WatchDebugStream(self, request, context):
        """Watch for new debug files in cloud storage and stream them back"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PushTopic(self, request, context):
        """Push a message to a streaming topic"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_StreamingDebugServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SetStreamingDebugConfig": grpc.unary_unary_rpc_method_handler(
            servicer.SetStreamingDebugConfig,
            request_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.SetStreamingDebugConfigRequest.FromString,
            response_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.SetStreamingDebugConfigResponse.SerializeToString,
        ),
        "GetStreamingDebugConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetStreamingDebugConfig,
            request_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetStreamingDebugConfigRequest.FromString,
            response_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetStreamingDebugConfigResponse.SerializeToString,
        ),
        "EnableDebugMode": grpc.unary_unary_rpc_method_handler(
            servicer.EnableDebugMode,
            request_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.EnableDebugModeRequest.FromString,
            response_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.EnableDebugModeResponse.SerializeToString,
        ),
        "DisableDebugMode": grpc.unary_unary_rpc_method_handler(
            servicer.DisableDebugMode,
            request_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.DisableDebugModeRequest.FromString,
            response_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.DisableDebugModeResponse.SerializeToString,
        ),
        "GetDebugModeStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetDebugModeStatus,
            request_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugModeStatusRequest.FromString,
            response_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugModeStatusResponse.SerializeToString,
        ),
        "GetDebugMessages": grpc.unary_unary_rpc_method_handler(
            servicer.GetDebugMessages,
            request_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugMessagesRequest.FromString,
            response_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugMessagesResponse.SerializeToString,
        ),
        "GetDebugMessagesV2": grpc.unary_unary_rpc_method_handler(
            servicer.GetDebugMessagesV2,
            request_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugMessagesV2Request.FromString,
            response_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugMessagesV2Response.SerializeToString,
        ),
        "WatchDebugStream": grpc.unary_stream_rpc_method_handler(
            servicer.WatchDebugStream,
            request_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.WatchDebugStreamRequest.FromString,
            response_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.WatchDebugStreamResponse.SerializeToString,
        ),
        "PushTopic": grpc.unary_unary_rpc_method_handler(
            servicer.PushTopic,
            request_deserializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.PushTopicRequest.FromString,
            response_serializer=chalk_dot_streaming_dot_v1_dot_debug__service__pb2.PushTopicResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "chalk.streaming.v1.StreamingDebugService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class StreamingDebugService(object):
    """Streaming Debug Service
    Provides APIs for managing and querying streaming resolver debug configuration
    """

    @staticmethod
    def SetStreamingDebugConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chalk.streaming.v1.StreamingDebugService/SetStreamingDebugConfig",
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.SetStreamingDebugConfigRequest.SerializeToString,
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.SetStreamingDebugConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetStreamingDebugConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chalk.streaming.v1.StreamingDebugService/GetStreamingDebugConfig",
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetStreamingDebugConfigRequest.SerializeToString,
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetStreamingDebugConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def EnableDebugMode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chalk.streaming.v1.StreamingDebugService/EnableDebugMode",
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.EnableDebugModeRequest.SerializeToString,
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.EnableDebugModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DisableDebugMode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chalk.streaming.v1.StreamingDebugService/DisableDebugMode",
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.DisableDebugModeRequest.SerializeToString,
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.DisableDebugModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetDebugModeStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chalk.streaming.v1.StreamingDebugService/GetDebugModeStatus",
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugModeStatusRequest.SerializeToString,
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugModeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetDebugMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chalk.streaming.v1.StreamingDebugService/GetDebugMessages",
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugMessagesRequest.SerializeToString,
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetDebugMessagesV2(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chalk.streaming.v1.StreamingDebugService/GetDebugMessagesV2",
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugMessagesV2Request.SerializeToString,
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.GetDebugMessagesV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def WatchDebugStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/chalk.streaming.v1.StreamingDebugService/WatchDebugStream",
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.WatchDebugStreamRequest.SerializeToString,
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.WatchDebugStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PushTopic(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chalk.streaming.v1.StreamingDebugService/PushTopic",
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.PushTopicRequest.SerializeToString,
            chalk_dot_streaming_dot_v1_dot_debug__service__pb2.PushTopicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
