"""The compiled extension's Python surface, declared in full (tfs-077).

THIS FILE IS THE SEAM'S ONLY COMPILER. `tensorfs` ships `py.typed`, which tells every
consumer's type checker that what it reads here is true. Until tfs-077 it was not: this
stub ended in `def __getattr__(name: str) -> Any` and `Store` carried one too, so every
attribute on the extension typed as `Any`. `Store.prepare_model_source` was then called
with six arguments against a five-parameter binding and shipped through cozy-runtime's
strict-mode CI, refusing every model-source preparation on a rented pod (cozy-runtime#296);
a second signature change on the same method went the same way and was caught only by a
hand-written frozen-signature table. Both were compile errors that nothing compiled.

There is NO `__getattr__` here and there must never be one. A name absent from this file is
an attribute error, not an `Any`. `scripts/stub_conform.py` runs against the BUILT
extension in CI and refuses on a missing name, an extra name, a changed parameter list, a
changed default, a method declared as a property — and on the reappearance of a
`__getattr__`, because that one line would make every other check in this file vacuous.

WHAT IS MACHINE-CHECKED: names, arity, parameter names and order, positional-/keyword-only
kinds, defaults, and callable-vs-property. WHAT IS NOT: the annotations themselves. pyo3
erases Rust types into `PyObject` and `__text_signature__` carries no annotation to compare
against, so `hex: str` is a human's assertion. Change a Rust parameter's TYPE without
changing its name and this file will still say `str` and CI will still be green — which is
why cozy-runtime keeps a contract test for argument MEANING beside its call sites.

`dict[str, Any]` on a return is deliberate where the row shape is the caller's business and
documented in `tensorfs/__init__.py`'s TypedDicts; the model-source path, which is the seam
that broke, is typed to its rows here.
"""

from collections.abc import Callable, Mapping, Sequence
from os import PathLike
from types import ModuleType
from typing import Any, Literal, NotRequired, Self, TypedDict

__version__: str

#: `tensorfs._ext.plane`, typed in full by `plane.pyi` (the `tensorfs.plane` facade).
plane: ModuleType

StrPath = str | PathLike[str]

#: `ReadLease.bytes` is a property, so inside that class body the name `bytes` is the
#: property and not the builtin. mypy said so the first time this file was checked.
_Bytes = bytes

# --------------------------------------------------------------------------------- typed
# rows. Only where a caller indexes the result: a TypedDict that drifts from the Rust
# `set_item` calls is a wrong answer with a type on it, so these are kept to the surfaces
# a consumer actually reads.

class TreeRoot(TypedDict):
    owner: str
    producer: str
    receipt_digest: NotRequired[str]
    receipt: NotRequired[bytes]
    manifest_digest: str
    manifest_length: int
    complete: bool
    released: bool

class CheckpointRoot(TypedDict):
    owner: str
    repository: str
    manifest_digest: str
    manifest_length: int
    released: bool

class KeyedRoot(TypedDict):
    space: str
    key: str
    manifest_digest: str
    manifest_length: int
    bytes: int
    created_unix_ms: int

class SelectedSource(TypedDict):
    canonical: str
    selection_sha256: str
    content_manifest_digest: str
    content_manifest_length: int
    members: list[tuple[str, str, int, str]]
    allowed_hosts: list[str]
    credential_hosts: list[str]

class MaterializedSource(TypedDict):
    artifact: TreeRoot
    transferred_bytes: int

class PreparedSource(TypedDict):
    """One prepared foreign source, as `Store.prepare_model_source` returns it."""

    slot: str
    profile: str
    manifest_digest: str
    manifest_length: int
class SourceCheckpoint(TypedDict):
    slot: str
    plan_digest: str
    head: str
    head_length: int
    index: int
    bytes: int

class CheckpointObject(TypedDict):
    kind: str
    object_id: str
    length: int

class SourceCheckpointPage(TypedDict):
    operation: str
    plan_digest: str
    index: int
    bytes: int
    previous: tuple[str, int] | None
    progress: tuple[str, int] | None
    next_offset: int | None
    objects: list[CheckpointObject]

class PreparedModelSource(TypedDict):
    replayed: bool
    complete: bool
    sources: list[PreparedSource]
    checkpoints: list[SourceCheckpoint]
    spent: list[str]
    converted_roles: int
    resumed_roles: int
    deferred_ops: int
    converted_bytes: int
    largest_op_bytes: int
    required_write_bytes: int
    write_interval_bytes: int

class DerivedWriteEstimate(TypedDict):
    payload_bytes: int
    largest_part_bytes: int
    parts: int

class ManifestRow(TypedDict):
    manifest_id: str
    manifest: bytes
    header: bytes | None

class ReleaseRow(TypedDict):
    org: str
    name: str
    version: str
    revision: int
    lane: str
    manifest_digest: str
    manifest_length: int

class LocalRow(TypedDict):
    name: str
    source_selection: str
    manifest_digest: str
    manifest_length: int

# ------------------------------------------------------------------------- typed refusals
# `Refusal` is the base of every code in `err::Code`; the subclasses are BUILT IN RUST from
# that list, and the names below are the frozen Python spelling of it. `code` is a class
# attribute on each subclass and `detail` is set on the instance.

class Refusal(Exception):
    code: str
    detail: str

class AmbiguousClassification(Refusal): ...
class ArchiveRefused(Refusal): ...
class ArithOverflow(Refusal): ...
class ArtifactIncomplete(Refusal): ...
class AttachmentCardinality(Refusal): ...
class BadBase64(Refusal): ...
class BlobNotRetained(Refusal): ...
class BufferSize(Refusal): ...
class ByteLengthMismatch(Refusal): ...
class CapabilityUnqualified(Refusal): ...
class CapacityExhausted(Refusal): ...
class CarrierGeometry(Refusal): ...
class CarrierHeaderCap(Refusal): ...
class CarrierOverlap(Refusal): ...
class CarrierTruncated(Refusal): ...
class CensusIncomplete(Refusal): ...
class CheckpointAbsent(Refusal): ...
class CheckpointConflict(Refusal): ...
class CheckpointReferenced(Refusal): ...
class ConstructionOrderRequired(Refusal): ...
class ConvertSizeCap(Refusal): ...
class ConvertsNothing(Refusal): ...
class CountCap(Refusal): ...
class CredentialRequired(Refusal): ...
class CrossSubjectReplay(Refusal): ...
class DeadlineExceeded(Refusal): ...
class DepthCap(Refusal): ...
class DialectMismatch(Refusal): ...
class DispositionConflict(Refusal): ...
class DivisionRemainder(Refusal): ...
class DoubleEncode(Refusal): ...
class DtypeMismatch(Refusal): ...
class DtypeUnknown(Refusal): ...
class DuplicateKey(Refusal): ...
class DurabilityUnproven(Refusal): ...
class EmptyComponents(Refusal): ...
class EncodingMismatch(Refusal): ...
class EvidenceArmAmbiguous(Refusal): ...
class EvidenceNotResident(Refusal): ...
class ExtraComponent(Refusal): ...
class ExtraTensor(Refusal): ...
class FdHeadroom(Refusal): ...
class GgufArchMixed(Refusal): ...
class GgufArchUndeclared(Refusal): ...
class GgufCarrierTruncated(Refusal): ...
class GgufEncodingNotReviewed(Refusal): ...
class GgufGeometry(Refusal): ...
class GgufMagicAbsent(Refusal): ...
class GgufMetadataTruncated(Refusal): ...
class GgufRefused(Refusal): ...
class GgufShapeUnrecoverable(Refusal): ...
class GgufTypeUnknown(Refusal): ...
class GgufVersionUnsupported(Refusal): ...
class GoldenMismatch(Refusal): ...
class HubRefused(Refusal): ...
class HubUnreachable(Refusal): ...
class InlineExclusive(Refusal): ...
class InlineThreshold(Refusal): ...
class IoFailed(Refusal): ...
class JournalStale(Refusal): ...
class KeyGrammar(Refusal): ...
class LeaseNotCovered(Refusal): ...
class LeaseRevoked(Refusal): ...
class LengthMismatch(Refusal): ...
class LockContended(Refusal): ...
class MalformedCbor(Refusal): ...
class MalformedDigest(Refusal): ...
class MalformedJson(Refusal): ...
class MissingCompanionRole(Refusal): ...
class MissingComponent(Refusal): ...
class MissingField(Refusal): ...
class MissingTensor(Refusal): ...
class NonAsciiField(Refusal): ...
class NonIntegerNumber(Refusal): ...
class NoncanonicalEncoding(Refusal): ...
class NotContained(Refusal): ...
class NotRegularFile(Refusal): ...
class NumberRange(Refusal): ...
class ObjectAbsent(Refusal): ...
class ObjectCorrupt(Refusal): ...
class ObjectIdMismatch(Refusal): ...
class OptionalRoleForbidden(Refusal): ...
class PathCaseCollision(Refusal): ...
class PathDigestMismatch(Refusal): ...
class PathIllegal(Refusal): ...
class PathOrder(Refusal): ...
class PathParentMissing(Refusal): ...
class PathReserved(Refusal): ...
class PermuteNotBlockGranular(Refusal): ...
class PermissionDenied(Refusal): ...
class PickleRefused(Refusal): ...
class PlacementUnfit(Refusal): ...
class PlatformUnsupported(Refusal): ...
class ProfileRequired(Refusal): ...
class ProjectionWeightPath(Refusal): ...
class QuotaExhausted(Refusal): ...
class RangeBounds(Refusal): ...
class RankCap(Refusal): ...
class ReclaimInsufficient(Refusal): ...
class ReclaimNotPermitted(Refusal): ...
class RedirectRefused(Refusal): ...
class RefNotFound(Refusal): ...
class ReleaseAbsent(Refusal): ...
class ReleaseConflict(Refusal): ...
class RemedyFromTarget(Refusal): ...
class RepositoryAbsent(Refusal): ...
class RepositoryConflict(Refusal): ...
class RepositoryFull(Refusal): ...
class RoleSetMismatch(Refusal): ...
class RootAbsent(Refusal): ...
class RootExpired(Refusal): ...
class RootGeneration(Refusal): ...
class SeamUnbanked(Refusal): ...
class ShapeMismatch(Refusal): ...
class ShortRead(Refusal): ...
class SizeCap(Refusal): ...
class SlotStarved(Refusal): ...
class SnapshotPinned(Refusal): ...
class SortOrder(Refusal): ...
class SourceNotAllowed(Refusal): ...
class Stalled(Refusal): ...
class StampMismatch(Refusal): ...
class StoreBusy(Refusal): ...
class StoreEra(Refusal): ...
class StoreRootAbsent(Refusal): ...
class SweepSetIncomplete(Refusal): ...
class TensorSchemaMismatch(Refusal): ...
class TlsUntrusted(Refusal): ...
class TotalBytesCap(Refusal): ...
class TotalRefsCap(Refusal): ...
class TrailingBytes(Refusal): ...
class TransactionClosed(Refusal): ...
class TransactionConflict(Refusal): ...
class TransferFailed(Refusal): ...
class TraversalIncomplete(Refusal): ...
class TraversalOrderMismatch(Refusal): ...
class UncitedEncoding(Refusal): ...
class UnclassifiedExtras(Refusal): ...
class UnknownEncoding(Refusal): ...
class UnknownField(Refusal): ...
class UnknownFormat(Refusal): ...
class UnknownRelation(Refusal): ...
class UnknownToLocalCapability(Refusal): ...
class UnregisteredEncoding(Refusal): ...
class UnregisteredFingerprint(Refusal): ...
class VectorMismatch(Refusal): ...
class VectorsRequired(Refusal): ...
class VerifierOutputIncomplete(Refusal): ...
class WholeDigestMismatch(Refusal): ...
class WriterFenced(Refusal): ...
class WrongType(Refusal): ...
class ZeroElement(Refusal): ...

#: The frozen wire name to its class, for a caller dispatching on the code rather than the
#: type. Built in Rust from the same list.
CODES: dict[str, type[Refusal]]

# --------------------------------------------------------------------------------- reads

class Batch:
    """One filled slot in the reader ring. `release()` is a positive act: the slot is not
    recycled until the caller says the DMA out of it has completed."""

    @property
    def index(self) -> int: ...
    @property
    def slot(self) -> int: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def io_bytes(self) -> int: ...
    @property
    def read_ms(self) -> float: ...
    @property
    def released(self) -> bool: ...
    def items(self) -> list[Any]: ...
    def release(self) -> bool: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *_args: object) -> bool: ...

class ReadPlan:
    def select(self, whats: Sequence[str]) -> ReadPlan: ...
    @property
    def bytes(self) -> int: ...
    @property
    def io_bytes(self) -> int: ...
    @property
    def inline_parts(self) -> int: ...
    @property
    def order(self) -> str: ...
    def items(self) -> list[Any]: ...
    def batches(self, slot_bytes: int) -> int: ...
    def __len__(self) -> int: ...

class ReadLease:
    """A verified hold on a closure. Live for as long as the lock the kernel drops on
    process death, never a wall clock."""

    @property
    def hold_id(self) -> str: ...
    @property
    def manifest(self) -> str: ...
    @property
    def bytes(self) -> int: ...
    @property
    def objects(self) -> list[tuple[str, int]]: ...
    @property
    def receipts(self) -> list[Any]: ...
    @property
    def live(self) -> bool: ...
    def recheck(self) -> None: ...
    def release(self) -> None: ...
    def read_into(
        self, object: str, object_length: int, off: int, length: int, into: object
    ) -> None: ...
    def read_asset(self, header: _Bytes, name: str, max_bytes: int = 67108864) -> _Bytes: ...
    def read_part_into(
        self, header: _Bytes, component: str, key: str, role: str, off: int, into: object
    ) -> None: ...
    def stream(
        self,
        plan: ReadPlan,
        slots: Sequence[object],
        on_batch: Callable[[Batch], object],
        readers: int = 4,
    ) -> dict[str, Any]: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *_args: object) -> bool: ...

class Closure:
    def insert(self, data: bytes) -> str: ...
    def digests(self) -> list[str]: ...
    def __len__(self) -> int: ...

# --------------------------------------------------------------------------------- writes

class Operation:
    """One repository operation's exact CAS holds, released when it commits or is dropped."""

    def hold_blob(self, identity: str, length: int) -> None: ...
    def hold_manifest(self, identity: str, length: int) -> None: ...
    def commit_release(
        self,
        current: bytes | None,
        version: str,
        lane: str,
        manifest_id: str,
        manifest_length: int,
    ) -> bytes: ...

class DerivedWriter:
    def part_write_bound(self, component: str, key: str, role: str) -> int: ...
    def config_write_bound(self, name: str) -> int: ...
    def sources(self) -> list[Any]: ...
    def completed_parts(self) -> list[tuple[str, str, str]]: ...
    def completed_configs(self) -> list[str]: ...
    def checkpoint(self, operation_id: str, slot: str, *, previous: tuple[str, int] | None = None) -> dict[str, str | int | None]: ...
    def source_read_into(
        self, source: str, component: str, key: str, role: str, off: int, into: object
    ) -> None: ...
    def add_part(self, component: str, key: str, role: str, reader: object) -> dict[str, Any]: ...
    def add_config(self, name: str, reader: object) -> None: ...
    def commit(self) -> Any: ...
    def fence(self) -> bool: ...

class RepoObjectCache:
    def __init__(self, root: str) -> None: ...
    @property
    def root(self) -> str: ...
    def admit(
        self, store: Store, object_id: str, length: int, *, manifest: bool = False
    ) -> Literal["hit", "missing", "corrupt", "unavailable"]: ...
    def backfill(
        self, store: Store, object_id: str, length: int, *, manifest: bool = False
    ) -> Literal["stored", "present", "unavailable"]: ...

# ---------------------------------------------------------------------------------- store

class Store:
    """A content-addressed store rooted at one directory. Never created implicitly: `open`
    refuses an absent root, `ensure` creates one, `init` demands a fresh one (tfs-053)."""

    @staticmethod
    def ensure(root: StrPath | None = None) -> Store: ...
    @staticmethod
    def open(root: StrPath | None = None) -> Store: ...
    @staticmethod
    def init(root: StrPath | None = None) -> Store: ...
    @property
    def root(self) -> str: ...
    def bind_fingerprint_registry(self, data: bytes | None) -> None: ...
    @property
    def implementation_sha256(self) -> str: ...
    def verify_checkpoint_source(
        self, repository: str, manifest_id: str, manifest_length: int,
    ) -> None: ...
    def retain_checkpoint_root(
        self, owner: str, repository: str, manifest_id: str, manifest_length: int,
    ) -> CheckpointRoot: ...
    def checkpoint_root(self, owner: str) -> CheckpointRoot | None: ...
    def release_checkpoint_root(
        self, owner: str, repository: str, manifest_id: str, manifest_length: int,
    ) -> CheckpointRoot: ...
    def create_tree_root(self, owner: str, manifest_id: str, manifest_length: int) -> TreeRoot: ...
    def import_tree(
        self, owner: str, manifest_bytes: bytes, files: Sequence[tuple[str, StrPath]],
    ) -> TreeRoot: ...
    def retain_tree_root(self, source_owner: str, owner: str) -> TreeRoot: ...
    def tree_root(self, owner: str) -> TreeRoot | None: ...
    def deliver_tree_root(self, owner: str) -> None: ...
    def release_tree_root(self, owner: str) -> None: ...
    def release_tree_retention(self, source_owner: str, receipt_digest: str, owner: str) -> None: ...
    def adopt_source_progress(self, source_owner: str, owner: str) -> TreeRoot: ...
    def put_keyed_root(
        self, space: str, key: str, manifest_bytes: bytes, files: Sequence[tuple[str, StrPath]],
    ) -> KeyedRoot: ...
    def keyed_root(self, space: str, key: str) -> KeyedRoot | None: ...
    def keyed_roots(self, space: str) -> list[KeyedRoot]: ...
    def drop_keyed_root(self, space: str, key: str) -> bool: ...
    def resolve_source(
        self, source_uri: str, carriers: Sequence[str] = ..., *, profiles: Sequence[str] = ..., files: Sequence[str] = ..., credential: str = ...,
        huggingface: str | None = None, civitai: str | None = None, allow_local: bool = False,
        registry: bytes | None = None,
    ) -> SelectedSource: ...
    # progress(present, total): durable bytes of the selection's distinct objects, called
    # from download threads; an exception it raises stops the download and is re-raised.
    def materialize_source(
        self, owner: str, members: Sequence[tuple[str, str, int, str]], *,
        allowed_hosts: Sequence[str], credential_hosts: Sequence[str] = ...,
        credential: str = ..., allow_local: bool = False,
        progress: Callable[[int, int], object] | None = None,
    ) -> MaterializedSource: ...
    # An empty checkpoints list with adopt_from_operation_id snapshots the stopped
    # predecessor's verified local journal before normal independent adoption.
    def prepare_source_artifact(
        self, source_owner: str, operation_id: str, profiles: Sequence[tuple[str, str]], *,
        checkpoints: Sequence[tuple[str, str, int]] = ...,
        adopt_from_operation_id: str | None = None,
        registry: bytes | None = None,
    ) -> PreparedModelSource: ...
    #: Read-only: the mount is recorded on the Store by `tfs store ensure --repo-cache`,
    #: and no caller of this facade passes one.
    @property
    def repo_cache(self) -> str | None: ...
    def prepare_readers(self) -> None: ...
    def complete_cozytensors_manifests(self) -> list[str]: ...
    def contains(self, hex: str) -> bool: ...
    def update_model_assets(
        self,
        manifest_id: str,
        manifest_length: int,
        copies: Sequence[tuple[str, str, str]] = ...,
        inherits: Sequence[tuple[str, str]] = ...,
        drops: Sequence[str] = ...,
    ) -> dict[str, str | int]: ...
    def inherit_model_assets(
        self,
        target_manifest_id: str,
        target_manifest_length: int,
        source_manifest_id: str,
        source_manifest_length: int,
        names: Sequence[str] = ...,
    ) -> dict[str, str | int]: ...
    def objects(self) -> list[str]: ...
    def reap_holds(self) -> list[str]: ...

    # -- content
    def put_file(
        self, path: StrPath, expect: str | None = None, expect_length: int | None = None
    ) -> dict[str, Any]: ...
    def put_reader(self, reader: object, expect: str, expect_length: int) -> dict[str, Any]: ...
    def put_manifest(
        self, data: bytes, expect: str | None = None, expect_length: int | None = None
    ) -> dict[str, Any]: ...
    def verify(self, hex: str) -> dict[str, Any]: ...
    def document(self, hex: str, max_bytes: int = ...) -> bytes: ...
    def manifest(self, hex: str) -> ManifestRow: ...
    def walk(self, hex: str) -> list[dict[str, Any]]: ...
    def walk_cozytensors(self, hex: str) -> list[dict[str, Any]]: ...
    def checkout(self, hex: str, dest: StrPath, symlink: bool = True) -> dict[str, Any]: ...
    def materialize(self, hex: str, path: str, dest: StrPath) -> int: ...

    # -- leases
    def acquire(self, manifest: str, objects: Sequence[tuple[str, int]]) -> ReadLease: ...
    def acquire_manifest(self, hex: str) -> ReadLease: ...
    def acquire_cozytensors(self, hex: str) -> ReadLease: ...

    # -- repository
    def begin_operation(self, operation_id: str, org: str, name: str) -> Operation: ...
    def repo_get(self, org: str, name: str) -> bytes: ...
    def resolve_release(self, org: str, name: str, version: str, lane: str) -> ReleaseRow: ...
    def resolve_local(self, name: str) -> LocalRow: ...
    def replace_local(
        self,
        current: bytes | None,
        name: str,
        source_selection: str,
        manifest_id: str,
        manifest_length: int,
    ) -> bytes: ...
    def remove_local(self, current: bytes, name: str) -> dict[str, Any]: ...
    def update_release(
        self,
        current: bytes,
        org: str,
        name: str,
        version: str,
        expected_revision: int,
        set: Sequence[tuple[str, str, int]],
        remove: Sequence[str],
    ) -> bytes: ...
    def yank_release(
        self, current: bytes, org: str, name: str, version: str, expected_revision: int
    ) -> bytes: ...

    # Headers fix the plan before bodies arrive. Only landed physical carriers are read.
    def prepare_model_source(
        self,
        operation_id: str,
        source_selection_digest: str,
        profiles: Sequence[tuple[str, str]],
        roster: Sequence[tuple[str, str, int, StrPath, bytes]],
        landed: Sequence[str],
        *,
        checkpoints: Sequence[tuple[str, str, int]] = ...,
        adopt_from_operation_id: str | None = ...,
        registry: bytes | None = None,
        write_budget_bytes: int | None = None,
    ) -> PreparedModelSource: ...
    def checkpoint_page(
        self, head_id: str, head_length: int, *, operation_id: str, slot: str,
        plan_digest: str, offset: int = 0, limit: int = 128,
    ) -> SourceCheckpointPage: ...
    def checkpoint_push(
        self, object_id: str, length: int, manifest: bool, grant: str, *, allow_local: bool = False,
    ) -> dict[str, int | bool]: ...
    def checkpoint_fetch(
        self, object_id: str, length: int, manifest: bool, url: str, *, allow_local: bool = False,
        derived_restore: tuple[str, int] | None = None,
    ) -> dict[str, int | bool]: ...
    def source_checkpoints(self, operation_id: str) -> list[SourceCheckpoint]: ...
    def model_source_operations(self) -> list[str]: ...
    def release_model_source(self, operation_id: str) -> None: ...

    # -- derived
    def inspect_derived_source(
        self,
        manifest: str,
        manifest_length: int,
        components: Sequence[str],
        configs: Sequence[str],
    ) -> dict[str, Any]: ...
    def derived_declaration(
        self, sources: dict[str, Any], targets: dict[str, Any], configs: dict[str, Any],
        order: Sequence[tuple[str, str]], max_new_bytes: int,
        files: Mapping[str, str | tuple[str, int]] | None = None, *, work_fingerprint: str,
    ) -> bytes: ...
    def validate_derived_checkpoint(
        self, transaction_id: str, declaration: bytes, head_id: str, head_length: int, *,
        operation_id: str, slot: str, plan_digest: str,
    ) -> None: ...
    def begin_derived(
        self,
        transaction_id: str,
        writer_session_id: int,
        sources: dict[str, Any],
        targets: dict[str, Any],
        configs: dict[str, Any],
        order: Sequence[tuple[str, str]],
        max_new_bytes: int,
        files: Mapping[str, str | tuple[str, int]] | None = None,
        *,
        work_fingerprint: str,
        checkpoint: tuple[str, int] | None = None,
    ) -> DerivedWriter: ...
    def derived_write_estimate(
        self,
        transaction_id: str,
        writer_session_id: int,
        sources: dict[str, Any],
        targets: dict[str, Any],
        configs: dict[str, Any],
        order: Sequence[tuple[str, str]],
        max_new_bytes: int,
        files: Mapping[str, str | tuple[str, int]] | None = None,
        *,
        work_fingerprint: str,
        checkpoint: tuple[str, int] | None = None,
    ) -> DerivedWriteEstimate: ...
    def adopt_derived_checkpoint(
        self, transaction_id: str, source_transaction_id: str, declaration: bytes,
        head_id: str, head_length: int, *, operation_id: str, slot: str,
    ) -> dict[str, Any]: ...
    def derived_lookup(self, transaction_id: str) -> dict[str, Any]: ...
    def derived_fence(self, transaction_id: str, writer_session_id: int) -> bool: ...
    def derived_abandon(self, transaction_id: str) -> dict[str, Any]: ...
    def derived_adopt(self, transaction_id: str, scratch_root_id: str) -> Any: ...
    def derived_dispose(self, transaction_id: str) -> Any: ...
    def retain_derived_result(self, transaction_id: str, expected_receipt_digest: str, retention_id: str) -> Any: ...
    def release_derived_retention(self, transaction_id: str, expected_receipt_digest: str, retention_id: str) -> Any: ...

# ------------------------------------------------------------------------ module functions

def home(root: StrPath | None = None) -> str: ...
def platform_gate(platform: str) -> None: ...

class Stats(TypedDict):
    catalog_opens: int
    presence_passes: int
    repo_cache_verified_reads: int
    admission_batches: int
    admitted_objects: int
    admission_nanos: int
    syncs: int
    sync_nanos: int
    recovery_rehashed: int
    recovery_removed: int
    recovery_nanos: int

def stats() -> Stats: ...
def object_id(data: bytes) -> str: ...
def parse_header(data: bytes, closure: Closure | None = None) -> Any: ...
def parse_manifest(data: bytes) -> Any: ...
def run_doc(
    doc: str,
    data: bytes,
    closure: Closure | None = None,
    platform: Sequence[str] | None = None,
) -> dict[str, Any]: ...
def receipt_binds(
    receipt: bytes, subject: bytes, manifest: bytes, header: bytes, stamp: bytes
) -> None: ...
def recanonicalize(doc: str, data: bytes) -> bytes: ...
def render(data: bytes, max_bytes: int) -> str: ...
def doc_kinds() -> list[str]: ...
def platform_digests() -> list[str]: ...
def seed_digests() -> list[tuple[str, str]]: ...
def dtypes() -> dict[str, int]: ...
def manifest_max_bytes() -> int: ...
def capability(encoding: str, device: str, observations: bytes | None = None) -> dict[str, Any]: ...

#: The raw census comparison. `tensorfs.fit` is the typed wrapper and is what callers use.
def _fit(
    tensors: Sequence[tuple[str, str, Sequence[int], str | None]],
    header: bytes,
    *,
    custody: str,
    encoded_leaves: bool,
    device: str | None = None,
    observations: bytes | None = None,
) -> dict[str, Any]: ...
def plan(
    header: bytes,
    traversal: Sequence[tuple[str, str]],
    components: Sequence[str] | None = None,
    window: int = ...,
) -> ReadPlan: ...
def gc(root: StrPath, dry_run: bool = False, *, evict_cached: bool = False, keep_manifests: list[str] = ...) -> dict[str, Any]: ...
def read_source_heads(
    source_uri: str,
    members: Sequence[tuple[str, str, int, str]],
    *,
    credential: str = ...,
    huggingface: str | None = None,
    civitai: str | None = None,
    allow_local: bool = False,
) -> list[tuple[str, bytes]]: ...
def select_source_profile(
    store: Store,
    heads: Sequence[tuple[str, int, bytes]],
    *,
    registry: bytes | None = None,
) -> str: ...
def source_profile_converters(
    store: Store,
    profiles: Sequence[str],
    *,
    registry: bytes | None = None,
) -> list[tuple[str, str | None]]: ...
def prepare_selected_source(
    store: Store,
    operation_id: str,
    source_selection_digest: str,
    profiles: Sequence[tuple[str, str]],
    members: Sequence[tuple[str, str, int, bytes]],
    *,
    registry: bytes | None = None,
    write_budget_bytes: int | None = None,
) -> dict[str, Any]: ...
def record_model_source_custody(
    store: Store, operation_id: str, objects: Sequence[tuple[str, int]], evidence: str
) -> None: ...
def model_source_objects(store: Store, operation_id: str) -> list[dict[str, Any]]: ...
def transfer_object(
    source: Store, destination: Store, object_id: str, expected_length: int
) -> dict[str, Any]: ...
def transfer_manifest(
    source: Store, destination: Store, manifest_id: str, expected_length: int
) -> dict[str, Any]: ...
def fetch_plan(
    store: Store,
    session: str,
    manifest: str,
    manifest_length: int,
    declared: Sequence[tuple[str, int]],
) -> dict[str, Any]: ...
def fetch_admit(store: Store, plan: bytes, object_id: str, reader: object) -> dict[str, Any]: ...
def fetch_complete(store: Store, plan: bytes) -> int: ...
def fetch_complete_cozytensors(store: Store, plan: bytes) -> int: ...
class PullCancellation:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...

#: The most memory one transfer stream holds, whatever its object's size.
STREAM_MEMORY: int
#: The profile a source no reviewed profile recognizes is selected under: stored as-is.
AS_IS_PROFILE: str

# Concurrent transfer streams whose buffers fit the memory available now: at most `wanted`,
# at least 1 (cgroup limit less unreclaimable usage, or MemAvailable).
def transfer_streams(wanted: int) -> int: ...

def pull(
    store: Store,
    hub: str,
    refspec: str,
    *,
    lane: str = ...,
    credential: str = ...,
    timeout: float | None = None,
    session: str = ...,
    streams: int = ...,
    streams_start: int = ...,
    allowed_hosts: Sequence[str] = ...,
    allow_local: bool = False,
    sample_seconds: float | None = None,
    cancellation: PullCancellation | None = None,
    progress: Callable[[int, int], object] | None = None,
) -> dict[str, Any]: ...

#: Feature names a caller may detect instead of versions ("ensure/1", ...).
CAPABILITIES: list[str]

def ensure(
    store: Store,
    ref: str,
    *,
    hub: str,
    lane: str = ...,
    step: str = ...,
    credential: str = ...,
    ca_file: StrPath | None = None,
    allowed_hosts: Sequence[str] = ...,
    allow_local: bool = False,
    keep: Sequence[str] = ...,
    streams: int = ...,
    streams_start: int = ...,
    sample_seconds: float | None = None,
    cancellation: PullCancellation | None = None,
    progress: Callable[[dict[str, Any]], object] | None = None,
) -> dict[str, Any]: ...
def relieve(store: Store, *, keep: Sequence[str] = ...) -> dict[str, Any]: ...
