"""
Type annotations for resiliencehubv2 service literal definitions.

[Documentation](https://youtype.github.io/boto3_stubs_docs/mypy_boto3_resiliencehubv2/literals/)

Copyright 2026 Vlad Emelianov

Usage::

    ```python
    from mypy_boto3_resiliencehubv2.literals import AchievabilityStatusType

    data: AchievabilityStatusType = "ACHIEVABLE"
    ```
"""

import sys

if sys.version_info >= (3, 12):
    from typing import Literal
else:
    from typing_extensions import Literal


__all__ = (
    "AchievabilityStatusType",
    "ActorTypeType",
    "AssertionSourceType",
    "AssessmentErrorCodeType",
    "AssessmentSortFieldType",
    "AssessmentStatusType",
    "AssessmentStepType",
    "CostCurrencyType",
    "DependencyCriticalityType",
    "DependencyDiscoveryInputType",
    "DependencyDiscoveryStatusType",
    "FailureCategoryType",
    "FailureModeAssessmentSuccessWaiterName",
    "FindingSeverityType",
    "FindingStatusType",
    "InputSourceTypeType",
    "ListAssertionsPaginatorName",
    "ListDependenciesPaginatorName",
    "ListFailureModeAssessmentsPaginatorName",
    "ListFailureModeFindingsPaginatorName",
    "ListInputSourcesPaginatorName",
    "ListPoliciesPaginatorName",
    "ListReportsPaginatorName",
    "ListResourcesPaginatorName",
    "ListServiceEventsPaginatorName",
    "ListServiceFunctionsPaginatorName",
    "ListServiceTopologyEdgesPaginatorName",
    "ListServicesPaginatorName",
    "ListSystemEventsPaginatorName",
    "ListSystemsPaginatorName",
    "ListUserJourneysPaginatorName",
    "MultiAzDisasterRecoveryApproachType",
    "MultiRegionDisasterRecoveryApproachType",
    "PaginatorName",
    "PolicyComponentType",
    "PolicyValueSourceType",
    "QueryGranularityType",
    "RegionName",
    "ReportGenerationErrorCodeType",
    "ReportGenerationStatusType",
    "ReportSucceededWaiterName",
    "ReportTypeType",
    "ResilienceHubV2ServiceName",
    "ResourceDiscoveryErrorCodeType",
    "ResourceDiscoveryRunStatusType",
    "ResourceServiceName",
    "ServiceAssessmentCompletedWaiterName",
    "ServiceEventTypeType",
    "ServiceFunctionCriticalityType",
    "ServiceFunctionSourceType",
    "ServiceName",
    "ServiceResourceDiscoveryCompletedWaiterName",
    "SortOrderType",
    "SystemEventTypeType",
    "TopologyTypeType",
    "WaiterName",
)


AchievabilityStatusType = Literal["ACHIEVABLE", "NOT_ACHIEVABLE"]
ActorTypeType = Literal["SYSTEM", "USER"]
AssertionSourceType = Literal["AI_GENERATED", "USER"]
AssessmentErrorCodeType = Literal[
    "AGENT_ERROR",
    "CMK_ACCESS_DENIED",
    "DESIGN_FILE_ACCESS_DENIED",
    "INTERNAL_ERROR",
    "INVALID_PERMISSIONS",
]
AssessmentSortFieldType = Literal["STARTED_AT"]
AssessmentStatusType = Literal["FAILED", "IN_PROGRESS", "NOT_STARTED", "PENDING", "SUCCESS"]
AssessmentStepType = Literal[
    "DESIGN_ANALYSIS",
    "FAILURE_MODE_FINDINGS_CONSOLIDATION",
    "FAILURE_MODE_FINDINGS_ENRICHMENT",
    "INPUT_VALIDATION",
    "POLICY_VALIDATION",
    "RESILIENCE_ASSESSMENT",
    "SERVICE_FUNCTION_GENERATION",
    "TOPOLOGY_ENHANCEMENT",
    "TOPOLOGY_GENERATION",
]
CostCurrencyType = Literal["USD"]
DependencyCriticalityType = Literal["HARD", "SOFT", "UNKNOWN"]
DependencyDiscoveryInputType = Literal["DISABLED", "ENABLED"]
DependencyDiscoveryStatusType = Literal["DISABLED", "ENABLED", "INITIALIZING"]
FailureCategoryType = Literal[
    "EXCESSIVE_LATENCY",
    "EXCESSIVE_LOAD",
    "MISCONFIGURATION_AND_BUGS",
    "SHARED_FATE",
    "SINGLE_POINT_OF_FAILURE",
]
FailureModeAssessmentSuccessWaiterName = Literal["failure_mode_assessment_success"]
FindingSeverityType = Literal["HIGH", "LOW", "MEDIUM"]
FindingStatusType = Literal["IRRELEVANT", "OPEN", "RESOLVED"]
InputSourceTypeType = Literal["CFN_STACK", "DESIGN_FILE", "EKS", "MONITORING", "TAGS", "TERRAFORM"]
ListAssertionsPaginatorName = Literal["list_assertions"]
ListDependenciesPaginatorName = Literal["list_dependencies"]
ListFailureModeAssessmentsPaginatorName = Literal["list_failure_mode_assessments"]
ListFailureModeFindingsPaginatorName = Literal["list_failure_mode_findings"]
ListInputSourcesPaginatorName = Literal["list_input_sources"]
ListPoliciesPaginatorName = Literal["list_policies"]
ListReportsPaginatorName = Literal["list_reports"]
ListResourcesPaginatorName = Literal["list_resources"]
ListServiceEventsPaginatorName = Literal["list_service_events"]
ListServiceFunctionsPaginatorName = Literal["list_service_functions"]
ListServiceTopologyEdgesPaginatorName = Literal["list_service_topology_edges"]
ListServicesPaginatorName = Literal["list_services"]
ListSystemEventsPaginatorName = Literal["list_system_events"]
ListSystemsPaginatorName = Literal["list_systems"]
ListUserJourneysPaginatorName = Literal["list_user_journeys"]
MultiAzDisasterRecoveryApproachType = Literal[
    "ACTIVE_ACTIVE", "BACKUP_AND_RESTORE", "HOT_STANDBY", "PILOT_LIGHT", "WARM_STANDBY"
]
MultiRegionDisasterRecoveryApproachType = Literal[
    "ACTIVE_ACTIVE", "BACKUP_AND_RESTORE", "HOT_STANDBY", "PILOT_LIGHT", "WARM_STANDBY"
]
PolicyComponentType = Literal[
    "AVAILABILITY_SLO",
    "DATA_RECOVERY",
    "MULTI_AZ_DISASTER_RECOVERY",
    "MULTI_REGION_DISASTER_RECOVERY",
]
PolicyValueSourceType = Literal["CROSS_ACCOUNT", "SELF"]
QueryGranularityType = Literal["DAILY", "HOURLY"]
ReportGenerationErrorCodeType = Literal[
    "CONFIGURATION_ERROR", "INSUFFICIENT_PERMISSIONS", "INTERNAL_ERROR"
]
ReportGenerationStatusType = Literal["FAILED", "PENDING", "SUCCEEDED"]
ReportSucceededWaiterName = Literal["report_succeeded"]
ReportTypeType = Literal["FAILURE_MODE"]
ResourceDiscoveryErrorCodeType = Literal[
    "ACCESS_DENIED",
    "CLUSTER_NOT_FOUND",
    "INTERNAL_ERROR",
    "INVALID_PERMISSIONS",
    "STACK_NOT_FOUND",
    "STATE_FILE_NOT_FOUND",
    "UNSUPPORTED_CLUSTER",
]
ResourceDiscoveryRunStatusType = Literal[
    "COMPLETED_WITH_FAILURES", "FAILED", "NOT_STARTED", "RUNNING", "SUCCEEDED"
]
ServiceAssessmentCompletedWaiterName = Literal["service_assessment_completed"]
ServiceEventTypeType = Literal[
    "ASSERTION_CREATED",
    "ASSERTION_DELETED",
    "ASSERTION_UPDATED",
    "SERVICE_ACHIEVABILITY_UPDATED",
    "SERVICE_CREATED",
    "SERVICE_DELETED",
    "SERVICE_FUNCTION_CREATED",
    "SERVICE_FUNCTION_DELETED",
    "SERVICE_FUNCTION_RESOURCES_ADDED",
    "SERVICE_FUNCTION_RESOURCES_REMOVED",
    "SERVICE_FUNCTION_UPDATED",
    "SERVICE_INPUT_SOURCES_UPDATED",
    "SERVICE_POLICY_ASSOCIATED",
    "SERVICE_POLICY_DISASSOCIATED",
    "SERVICE_RESOURCES_ASSOCIATED",
    "SERVICE_RESOURCES_DISASSOCIATED",
    "SERVICE_SYSTEM_ASSOCIATED",
    "SERVICE_SYSTEM_DISASSOCIATED",
    "SERVICE_WORKFLOW_UPDATED",
]
ServiceFunctionCriticalityType = Literal["PRIMARY", "SUPPLEMENTAL"]
ServiceFunctionSourceType = Literal["AI_GENERATED", "USER"]
ServiceResourceDiscoveryCompletedWaiterName = Literal["service_resource_discovery_completed"]
SortOrderType = Literal["ASC", "DESC"]
SystemEventTypeType = Literal[
    "SYSTEM_CREATED",
    "SYSTEM_DELETED",
    "SYSTEM_POLICY_ASSOCIATED",
    "SYSTEM_POLICY_DISASSOCIATED",
    "SYSTEM_SERVICE_ASSOCIATED",
    "SYSTEM_SERVICE_DISASSOCIATED",
    "SYSTEM_USER_JOURNEY_CREATED",
    "SYSTEM_USER_JOURNEY_DELETED",
    "SYSTEM_USER_JOURNEY_UPDATED",
]
TopologyTypeType = Literal["CONTAINMENT", "DATA_FLOW", "OBSERVABILITY", "PERMISSIONS"]
ResilienceHubV2ServiceName = Literal["resiliencehubv2"]
ServiceName = Literal[
    "accessanalyzer",
    "account",
    "acm",
    "acm-pca",
    "aiops",
    "amp",
    "amplify",
    "amplifybackend",
    "amplifyuibuilder",
    "apigateway",
    "apigatewaymanagementapi",
    "apigatewayv2",
    "appconfig",
    "appconfigdata",
    "appfabric",
    "appflow",
    "appintegrations",
    "application-autoscaling",
    "application-insights",
    "application-signals",
    "applicationcostprofiler",
    "appmesh",
    "apprunner",
    "appstream",
    "appsync",
    "arc-region-switch",
    "arc-zonal-shift",
    "artifact",
    "athena",
    "auditmanager",
    "autoscaling",
    "autoscaling-plans",
    "b2bi",
    "backup",
    "backup-gateway",
    "backupsearch",
    "batch",
    "bcm-dashboards",
    "bcm-data-exports",
    "bcm-pricing-calculator",
    "bcm-recommended-actions",
    "bedrock",
    "bedrock-agent",
    "bedrock-agent-runtime",
    "bedrock-agentcore",
    "bedrock-agentcore-control",
    "bedrock-data-automation",
    "bedrock-data-automation-runtime",
    "bedrock-runtime",
    "billing",
    "billingconductor",
    "braket",
    "budgets",
    "ce",
    "chatbot",
    "chime",
    "chime-sdk-identity",
    "chime-sdk-media-pipelines",
    "chime-sdk-meetings",
    "chime-sdk-messaging",
    "chime-sdk-voice",
    "cleanrooms",
    "cleanroomsml",
    "cloud9",
    "cloudcontrol",
    "clouddirectory",
    "cloudformation",
    "cloudfront",
    "cloudfront-keyvaluestore",
    "cloudhsm",
    "cloudhsmv2",
    "cloudsearch",
    "cloudsearchdomain",
    "cloudtrail",
    "cloudtrail-data",
    "cloudwatch",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codeconnections",
    "codedeploy",
    "codeguru-reviewer",
    "codeguru-security",
    "codeguruprofiler",
    "codepipeline",
    "codestar-connections",
    "codestar-notifications",
    "cognito-identity",
    "cognito-idp",
    "cognito-sync",
    "comprehend",
    "comprehendmedical",
    "compute-optimizer",
    "compute-optimizer-automation",
    "config",
    "connect",
    "connect-contact-lens",
    "connectcampaigns",
    "connectcampaignsv2",
    "connectcases",
    "connecthealth",
    "connectparticipant",
    "controlcatalog",
    "controltower",
    "cost-optimization-hub",
    "cur",
    "customer-profiles",
    "databrew",
    "dataexchange",
    "datapipeline",
    "datasync",
    "datazone",
    "dax",
    "deadline",
    "detective",
    "devicefarm",
    "devops-agent",
    "devops-guru",
    "directconnect",
    "discovery",
    "dlm",
    "dms",
    "docdb",
    "docdb-elastic",
    "drs",
    "ds",
    "ds-data",
    "dsql",
    "dynamodb",
    "dynamodbstreams",
    "ebs",
    "ec2",
    "ec2-instance-connect",
    "ecr",
    "ecr-public",
    "ecs",
    "efs",
    "eks",
    "eks-auth",
    "elasticache",
    "elasticbeanstalk",
    "elb",
    "elbv2",
    "elementalinference",
    "emr",
    "emr-containers",
    "emr-serverless",
    "entityresolution",
    "es",
    "events",
    "evs",
    "finspace",
    "finspace-data",
    "firehose",
    "fis",
    "fms",
    "forecast",
    "forecastquery",
    "frauddetector",
    "freetier",
    "fsx",
    "gamelift",
    "gameliftstreams",
    "geo-maps",
    "geo-places",
    "geo-routes",
    "glacier",
    "globalaccelerator",
    "glue",
    "grafana",
    "greengrass",
    "greengrassv2",
    "groundstation",
    "guardduty",
    "health",
    "healthlake",
    "iam",
    "identitystore",
    "imagebuilder",
    "importexport",
    "inspector",
    "inspector-scan",
    "inspector2",
    "interconnect",
    "internetmonitor",
    "invoicing",
    "iot",
    "iot-data",
    "iot-jobs-data",
    "iot-managed-integrations",
    "iotdeviceadvisor",
    "iotfleetwise",
    "iotsecuretunneling",
    "iotsitewise",
    "iotthingsgraph",
    "iottwinmaker",
    "iotwireless",
    "ivs",
    "ivs-realtime",
    "ivschat",
    "kafka",
    "kafkaconnect",
    "kendra",
    "kendra-ranking",
    "keyspaces",
    "keyspacesstreams",
    "kinesis",
    "kinesis-video-archived-media",
    "kinesis-video-media",
    "kinesis-video-signaling",
    "kinesis-video-webrtc-storage",
    "kinesisanalytics",
    "kinesisanalyticsv2",
    "kinesisvideo",
    "kms",
    "lakeformation",
    "lambda",
    "lambda-core",
    "lambda-microvms",
    "launch-wizard",
    "lex-models",
    "lex-runtime",
    "lexv2-models",
    "lexv2-runtime",
    "license-manager",
    "license-manager-linux-subscriptions",
    "license-manager-user-subscriptions",
    "lightsail",
    "location",
    "logs",
    "lookoutequipment",
    "m2",
    "machinelearning",
    "macie2",
    "mailmanager",
    "managedblockchain",
    "managedblockchain-query",
    "marketplace-agreement",
    "marketplace-catalog",
    "marketplace-deployment",
    "marketplace-discovery",
    "marketplace-entitlement",
    "marketplace-reporting",
    "marketplacecommerceanalytics",
    "mediaconnect",
    "mediaconvert",
    "medialive",
    "mediapackage",
    "mediapackage-vod",
    "mediapackagev2",
    "mediastore",
    "mediastore-data",
    "mediatailor",
    "medical-imaging",
    "memorydb",
    "meteringmarketplace",
    "mgh",
    "mgn",
    "migration-hub-refactor-spaces",
    "migrationhub-config",
    "migrationhuborchestrator",
    "migrationhubstrategy",
    "mpa",
    "mq",
    "mturk",
    "mwaa",
    "mwaa-serverless",
    "neptune",
    "neptune-graph",
    "neptunedata",
    "network-firewall",
    "networkflowmonitor",
    "networkmanager",
    "networkmonitor",
    "notifications",
    "notificationscontacts",
    "nova-act",
    "oam",
    "observabilityadmin",
    "odb",
    "omics",
    "opensearch",
    "opensearchserverless",
    "organizations",
    "osis",
    "outposts",
    "partnercentral-account",
    "partnercentral-benefits",
    "partnercentral-channel",
    "partnercentral-revenue-measurement",
    "partnercentral-selling",
    "payment-cryptography",
    "payment-cryptography-data",
    "pca-connector-ad",
    "pca-connector-scep",
    "pcs",
    "personalize",
    "personalize-events",
    "personalize-runtime",
    "pi",
    "pinpoint",
    "pinpoint-email",
    "pinpoint-sms-voice",
    "pinpoint-sms-voice-v2",
    "pipes",
    "polly",
    "pricing",
    "proton",
    "qapps",
    "qbusiness",
    "qconnect",
    "quicksight",
    "ram",
    "rbin",
    "rds",
    "rds-data",
    "redshift",
    "redshift-data",
    "redshift-serverless",
    "rekognition",
    "repostspace",
    "resiliencehub",
    "resiliencehubv2",
    "resource-explorer-2",
    "resource-groups",
    "resourcegroupstaggingapi",
    "rolesanywhere",
    "route53",
    "route53-recovery-cluster",
    "route53-recovery-control-config",
    "route53-recovery-readiness",
    "route53domains",
    "route53globalresolver",
    "route53profiles",
    "route53resolver",
    "rtbfabric",
    "rum",
    "s3",
    "s3control",
    "s3files",
    "s3outposts",
    "s3tables",
    "s3vectors",
    "sagemaker",
    "sagemaker-a2i-runtime",
    "sagemaker-edge",
    "sagemaker-featurestore-runtime",
    "sagemaker-geospatial",
    "sagemaker-metrics",
    "sagemaker-runtime",
    "sagemakerjobruntime",
    "savingsplans",
    "scheduler",
    "schemas",
    "sdb",
    "secretsmanager",
    "security-ir",
    "securityagent",
    "securityhub",
    "securitylake",
    "serverlessrepo",
    "service-quotas",
    "servicecatalog",
    "servicecatalog-appregistry",
    "servicediscovery",
    "ses",
    "sesv2",
    "shield",
    "signer",
    "signer-data",
    "signin",
    "simpledbv2",
    "snow-device-management",
    "snowball",
    "sns",
    "socialmessaging",
    "sqs",
    "ssm",
    "ssm-contacts",
    "ssm-guiconnect",
    "ssm-incidents",
    "ssm-quicksetup",
    "ssm-sap",
    "sso",
    "sso-admin",
    "sso-oidc",
    "stepfunctions",
    "storagegateway",
    "sts",
    "supplychain",
    "support",
    "support-app",
    "supportauthz",
    "sustainability",
    "swf",
    "synthetics",
    "taxsettings",
    "textract",
    "timestream-influxdb",
    "timestream-query",
    "timestream-write",
    "tnb",
    "transcribe",
    "transfer",
    "translate",
    "trustedadvisor",
    "uxc",
    "verifiedpermissions",
    "voice-id",
    "vpc-lattice",
    "waf",
    "waf-regional",
    "wafv2",
    "wellarchitected",
    "wickr",
    "wisdom",
    "workdocs",
    "workmail",
    "workmailmessageflow",
    "workspaces",
    "workspaces-instances",
    "workspaces-thin-client",
    "workspaces-web",
    "xray",
]
ResourceServiceName = Literal[
    "cloudformation", "cloudwatch", "dynamodb", "ec2", "glacier", "iam", "s3", "sns", "sqs"
]
PaginatorName = Literal[
    "list_assertions",
    "list_dependencies",
    "list_failure_mode_assessments",
    "list_failure_mode_findings",
    "list_input_sources",
    "list_policies",
    "list_reports",
    "list_resources",
    "list_service_events",
    "list_service_functions",
    "list_service_topology_edges",
    "list_services",
    "list_system_events",
    "list_systems",
    "list_user_journeys",
]
WaiterName = Literal[
    "failure_mode_assessment_success",
    "report_succeeded",
    "service_assessment_completed",
    "service_resource_discovery_completed",
]
RegionName = Literal[
    "af-south-1",
    "ap-east-1",
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-south-1",
    "ap-southeast-1",
    "ap-southeast-2",
    "ca-central-1",
    "eu-central-1",
    "eu-north-1",
    "eu-south-1",
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "me-south-1",
    "sa-east-1",
    "us-east-1",
    "us-east-2",
    "us-west-1",
    "us-west-2",
]
