# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Qot_GetOptionMarketStatistic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2
import Qot_OptionCommon_pb2 as Qot__OptionCommon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"Qot_GetOptionMarketStatistic.proto\x12\x1cQot_GetOptionMarketStatistic\x1a\x0c\x43ommon.proto\x1a\x16Qot_OptionCommon.proto\"x\n\rStatisticItem\x12\x0c\n\x04time\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x11\n\tcallValue\x18\x03 \x02(\x03\x12\x10\n\x08putValue\x18\x04 \x02(\x03\x12\x12\n\ntotalValue\x18\x05 \x01(\x03\x12\r\n\x05ratio\x18\x06 \x01(\x01\"f\n\x03\x43\x32S\x12\x14\n\x0coptionMarket\x18\x01 \x02(\x05\x12\x10\n\x08\x64\x61taType\x18\x02 \x02(\x05\x12\x11\n\tbeginTime\x18\x03 \x02(\t\x12\x0f\n\x07\x65ndTime\x18\x04 \x02(\t\x12\x13\n\x0bnextPageKey\x18\x05 \x01(\x0c\"\x86\x01\n\x03S2C\x12\x14\n\x0coptionMarket\x18\x01 \x02(\x05\x12\x10\n\x08\x64\x61taType\x18\x02 \x02(\x05\x12\x42\n\rstatisticList\x18\x03 \x03(\x0b\x32+.Qot_GetOptionMarketStatistic.StatisticItem\x12\x13\n\x0bnextPageKey\x18\x04 \x01(\x0c\"9\n\x07Request\x12.\n\x03\x63\x32s\x18\x01 \x02(\x0b\x32!.Qot_GetOptionMarketStatistic.C2S\"r\n\x08Response\x12\x15\n\x07retType\x18\x01 \x02(\x05:\x04-400\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\x05\x12.\n\x03s2c\x18\x04 \x01(\x0b\x32!.Qot_GetOptionMarketStatistic.S2CB\x15\n\x13\x63om.futu.openapi.pb')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Qot_GetOptionMarketStatistic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023com.futu.openapi.pb'
  _STATISTICITEM._serialized_start=106
  _STATISTICITEM._serialized_end=226
  _C2S._serialized_start=228
  _C2S._serialized_end=330
  _S2C._serialized_start=333
  _S2C._serialized_end=467
  _REQUEST._serialized_start=469
  _REQUEST._serialized_end=526
  _RESPONSE._serialized_start=528
  _RESPONSE._serialized_end=642
# @@protoc_insertion_point(module_scope)
