# Temporal-specific encoding format constants
NEW_ENCODING_FORMAT = "json/wf_v1"
LEGACY_ENCODING_FORMAT = "json/abraxas_v1"
ACCEPTED_ENCODING_FORMATS = frozenset({NEW_ENCODING_FORMAT, LEGACY_ENCODING_FORMAT})
CUSTOM_ENCODING_FORMAT = NEW_ENCODING_FORMAT
