# SPDX-FileCopyrightText: All Contributors to the PyTango project
# SPDX-License-Identifier: LGPL-3.0-or-later

"""
This is the main PyTango package file.
Documentation for this package can be found online:

http://pytango.readthedocs.io
"""

__all__ = (
    "FMT_UNKNOWN",
    "IMAGE",
    "READ",
    "READ_WITH_WRITE",
    "READ_WRITE",
    "SCALAR",
    "SPECTRUM",
    "WRITE",
    "AccessControlType",
    "ApiUtil",
    "ArchiveEventInfo",
    "ArchiveEventProp",
    "ArgType",
    "AsynCall",
    "AsynReplyNotArrived",
    "AttReqType",
    "Attr",
    "AttrConfEventData",
    "AttrData",
    "AttrDataFormat",
    "AttrMemorizedType",
    "AttrProperty",
    "AttrQuality",
    "AttrReadEvent",
    "AttrSerialModel",
    "AttrWriteType",
    "AttrWrittenEvent",
    "Attribute",
    "AttributeAlarm",
    "AttributeAlarmInfo",
    "AttributeConfig",
    "AttributeConfig_2",
    "AttributeConfig_3",
    "AttributeConfig_5",
    "AttributeDimension",
    "AttributeEventInfo",
    "AttributeInfo",
    "AttributeInfoEx",
    "AttributeInfoList",
    "AttributeInfoListEx",
    "AttributeProxy",
    "AutoTangoAllowThreads",
    "AutoTangoMonitor",
    "ChangeEventInfo",
    "ChangeEventProp",
    "ClientAddr",
    "CmdArgType",
    "CmdDoneEvent",
    "CommandInfo",
    "CommandInfoList",
    "CommunicationFailed",
    "Connection",
    "ConnectionFailed",
    "ConstDevString",
    "DServer",
    "DataReadyEventData",
    "Database",
    "DbData",
    "DbDatum",
    "DbDevExportInfo",
    "DbDevExportInfos",
    "DbDevFullInfo",
    "DbDevImportInfo",
    "DbDevImportInfos",
    "DbDevInfo",
    "DbDevInfos",
    "DbHistory",
    "DbHistoryList",
    "DbServerData",
    "DbServerInfo",
    "DebugIt",
    "DevBoolean",
    "DevCommandInfo",
    "DevDouble",
    "DevEncoded",
    "DevEnum",
    "DevError",
    "DevFailed",
    "DevFloat",
    "DevIntrChangeEventData",
    "DevLong",
    "DevLong64",
    "DevShort",
    "DevSource",
    "DevState",
    "DevString",
    "DevUChar",
    "DevULong",
    "DevULong64",
    "DevUShort",
    "DevVarBooleanArray",
    "DevVarCharArray",
    "DevVarDoubleArray",
    "DevVarDoubleStringArray",
    "DevVarFloatArray",
    "DevVarLong64Array",
    "DevVarLongArray",
    "DevVarLongStringArray",
    "DevVarShortArray",
    "DevVarStringArray",
    "DevVarULong64Array",
    "DevVarULongArray",
    "DevVarUShortArray",
    "DevVoid",
    "DeviceAttribute",
    "DeviceAttributeConfig",
    "DeviceAttributeHistory",
    "DeviceClass",
    "DeviceData",
    "DeviceDataHistory",
    "DeviceDataHistoryList",
    "DeviceDataList",
    "DeviceImpl",
    "DeviceInfo",
    "DeviceProxy",
    "DeviceUnlocked",
    "Device_2Impl",
    "Device_3Impl",
    "Device_4Impl",
    "Device_5Impl",
    "Device_6Impl",
    "DispLevel",
    "EncodedAttribute",
    "EnsureOmniThread",
    "ErrSeverity",
    "ErrorIt",
    "EventData",
    "EventProperties",
    "EventReason",
    "EventSubMode",
    "EventSystemFailed",
    "EventType",
    "Except",
    "ExtractAs",
    "FatalIt",
    "GreenMode",
    "Group",
    "GroupAttrReply",
    "GroupAttrReplyList",
    "GroupCmdReply",
    "GroupCmdReplyList",
    "GroupReply",
    "GroupReplyList",
    "ImageAttr",
    "InfoIt",
    "Interceptors",
    "KeepAliveCmdCode",
    "LatestDeviceImpl",
    "Level",
    "LockCmdCode",
    "LockerInfo",
    "LockerLanguage",
    "LogIt",
    "LogLevel",
    "LogTarget",
    "Logger",
    "Logging",
    "MessBoxType",
    "MultiAttrProp",
    "MultiAttribute",
    "MultiClassAttribute",
    "NamedDevFailed",
    "NamedDevFailedList",
    "NonDbDevice",
    "NonSupportedFeature",
    "NotAllowed",
    "PeriodicEventInfo",
    "PeriodicEventProp",
    "PollCmdCode",
    "PollDevice",
    "PollObjType",
    "PyTangoUserWarning",
    "Release",
    "SerialModel",
    "SpectrumAttr",
    "StdDoubleVector",
    "StdLongVector",
    "StdNamedDevFailedVector",
    "StdStringVector",
    "SubDevDiag",
    "TangoStream",
    "TimeVal",
    "TimedAttrData",
    "TimedCmdData",
    "UserDefaultAttrProp",
    "Util",
    "WAttribute",
    "WarnIt",
    "WrongData",
    "WrongNameSyntax",
    "__version__",
    "__version_description__",
    "__version_info__",
    "__version_long__",
    "__version_number__",
    "alarm_flags",
    "asyn_req_type",
    "cb_sub_model",
    "class_factory",
    "class_list",
    "constants",
    "constructed_class",
    "cpp_class_list",
    "delete_class_list",
    "get_attribute_proxy",
    "get_class",
    "get_classes",
    "get_constructed_class",
    "get_constructed_classes",
    "get_cpp_class",
    "get_cpp_classes",
    "get_device_proxy",
    "get_green_mode",
    "is_array_type",
    "is_bool_type",
    "is_float_type",
    "is_int_type",
    "is_numerical_type",
    "is_omni_thread",
    "is_scalar_type",
    "is_str_type",
    "obj_2_str",
    "raise_asynch_exception",
    "requires_pytango",
    "requires_tango",
    "seqStr_2_obj",
    "set_green_mode",
    "str_2_obj",
    "telemetry",
)

__docformat__ = "restructuredtext"

from ._tango import (
    FMT_UNKNOWN,
    IMAGE,
    READ,
    READ_WITH_WRITE,
    READ_WRITE,
    SCALAR,
    SPECTRUM,
    WRITE,
    AccessControlType,
    ApiUtil,
    ArchiveEventInfo,
    ArchiveEventProp,
    AsynCall,
    AsynReplyNotArrived,
    Attr,
    AttrConfEventData,
    AttrDataFormat,
    AttReqType,
    Attribute,
    AttributeAlarm,
    AttributeAlarmInfo,
    AttributeConfig,
    AttributeConfig_2,
    AttributeConfig_3,
    AttributeConfig_5,
    AttributeDimension,
    AttributeEventInfo,
    AttributeInfo,
    AttributeInfoEx,
    AttributeInfoList,
    AttributeInfoListEx,
    AttrMemorizedType,
    AttrProperty,
    AttrQuality,
    AttrReadEvent,
    AttrSerialModel,
    AttrWriteType,
    AttrWrittenEvent,
    AutoTangoAllowThreads,
    AutoTangoMonitor,
    ChangeEventInfo,
    ChangeEventProp,
    ClientAddr,
    CmdArgType,
    CmdDoneEvent,
    CommandInfo,
    CommandInfoList,
    CommunicationFailed,
    Connection,
    ConnectionFailed,
    ConstDevString,
    Database,
    DataReadyEventData,
    DbData,
    DbDatum,
    DbDevExportInfo,
    DbDevExportInfos,
    DbDevFullInfo,
    DbDevImportInfo,
    DbDevImportInfos,
    DbDevInfo,
    DbDevInfos,
    DbHistory,
    DbHistoryList,
    DbServerData,
    DbServerInfo,
    DevBoolean,
    DevCommandInfo,
    DevDouble,
    DevEncoded,
    DevEnum,
    DevError,
    DevFailed,
    DevFloat,
    Device_2Impl,
    Device_3Impl,
    Device_4Impl,
    Device_5Impl,
    Device_6Impl,
    DeviceAttribute,
    DeviceAttributeConfig,
    DeviceAttributeHistory,
    DeviceData,
    DeviceDataHistory,
    DeviceDataHistoryList,
    DeviceDataList,
    DeviceImpl,
    DeviceInfo,
    DeviceProxy,
    DeviceUnlocked,
    DevIntrChangeEventData,
    DevLong,
    DevLong64,
    DevShort,
    DevSource,
    DevState,
    DevString,
    DevUChar,
    DevULong,
    DevULong64,
    DevUShort,
    DevVarBooleanArray,
    DevVarCharArray,
    DevVarDoubleArray,
    DevVarDoubleStringArray,
    DevVarFloatArray,
    DevVarLong64Array,
    DevVarLongArray,
    DevVarLongStringArray,
    DevVarShortArray,
    DevVarStringArray,
    DevVarULong64Array,
    DevVarULongArray,
    DevVarUShortArray,
    DevVoid,
    DispLevel,
    DServer,
    EncodedAttribute,
    EnsureOmniThread,
    ErrSeverity,
    EventData,
    EventProperties,
    EventReason,
    EventSubMode,
    EventSystemFailed,
    EventType,
    Except,
    ExtractAs,
    GreenMode,
    GroupAttrReply,
    GroupAttrReplyList,
    GroupCmdReply,
    GroupCmdReplyList,
    GroupReply,
    GroupReplyList,
    ImageAttr,
    Interceptors,
    KeepAliveCmdCode,
    Level,
    LockCmdCode,
    LockerInfo,
    LockerLanguage,
    Logger,
    Logging,
    LogLevel,
    LogTarget,
    MessBoxType,
    MultiAttribute,
    MultiClassAttribute,
    NamedDevFailed,
    NamedDevFailedList,
    NonDbDevice,
    NonSupportedFeature,
    NotAllowed,
    PeriodicEventInfo,
    PeriodicEventProp,
    PollCmdCode,
    PollDevice,
    PollObjType,
    SerialModel,
    SpectrumAttr,
    StdDoubleVector,
    StdLongVector,
    StdNamedDevFailedVector,
    StdStringVector,
    SubDevDiag,
    TimeVal,
    UserDefaultAttrProp,
    WAttribute,
    WrongData,
    WrongNameSyntax,
    alarm_flags,
    asyn_req_type,
    cb_sub_model,
    constants,
    is_omni_thread,
    raise_asynch_exception,
)

__auto_die_callbacks_holder = {}


# Aliases

ArgType = CmdArgType

# Release

from .release import Release

__author__ = Release.author_lines
__version_info__ = Release.version_info
__version_short__ = Release.version
__version__ = Release.version_long
__version_long__ = Release.version_long
__version_number__ = Release.version_number
__version_description__ = Release.version_description
__doc__ = Release.long_description

# Pytango imports

import tango.telemetry as telemetry

from ._warnings import PyTangoUserWarning
from .attr_data import AttrData
from .attribute_proxy import AttributeProxy, get_attribute_proxy
from .device_class import DeviceClass
from .device_proxy import get_device_proxy
from .device_server import (
    LatestDeviceImpl,
    MultiAttrProp,
)
from .globals import (
    class_factory,
    class_list,
    constructed_class,
    cpp_class_list,
    delete_class_list,
    get_class,
    get_classes,
    get_constructed_class,
    get_constructed_classes,
    get_cpp_class,
    get_cpp_classes,
)
from .green import get_green_mode, set_green_mode
from .group import Group
from .log4tango import DebugIt, ErrorIt, FatalIt, InfoIt, LogIt, TangoStream, WarnIt
from .pyutil import TimedAttrData, TimedCmdData, Util
from .utils import (
    _RemovedClass,
    is_array_type,
    is_bool_type,
    is_float_type,
    is_int_type,
    is_numerical_type,
    is_scalar_type,
    is_str_type,
    obj_2_str,
    requires_pytango,
    requires_tango,
    seqStr_2_obj,
    str_2_obj,
)

# PyTango initialization
from .pytango_init import init as __init  # isort: skip

PipeWriteType = _RemovedClass(
    "PipeWriteType Enum was removed from PyTango starting from version 10.1.0. Pipes are not supported anymore. "
    "Please update your code!"
)

__init()
requires_tango("10.3.0", software_name="PyTango")
