from .llm_storage_routes import llm_bp
from .chat_routes import chat_bp
from .search_routes import search_bp
from .upload_routes import upload_bp
from .worker_routes import worker_bp
from .v1_routes import v1_bp
from .messages_routes import messages_bp
from .prompt_routes import prompt_bp
from .ml_routes import ml_bp
from .phone_brick_routes import phone_brick_bp
from .discord_routes import discord_bp
from .auth_proxy_routes import auth_proxy_bp
from .welcome_routes import welcome_bp
from .comms_routes import comms_bp
from .video_routes import video_bp
from .fleet_routes import fleet_bp
from .agent_routes import agent_bp
from .review_routes import review_bp
from .pypi_routes import pypi_bp
from .eviction_routes import eviction_bp
from .group_routes import group_bp
from .model_group_routes import model_group_bp
from .oracle_routes import oracle_bp
from .keeper_help_routes import keeper_help_bp
from .script_first_routes import script_first_bp
from .fleet_doctrine_routes import fleet_doctrine_bp
from .interim_routes import interim_bp
