"""Public inventory of the layered context surface."""

CONTEXT_SURFACES = (
    "ContextLayerBudget",
    "ContextBudgetRequest",
    "ContextBudgetPlan",
    "ContextSummaryRequest",
    "ContextRetrievalRequest",
    "ContextLayerSnapshot",
    "StablePrefix",
    "SessionSnapshot",
    "ReplayPacket",
    "TurnPacket",
    "ProcedureOverlay",
    "WorkspaceAttachments",
    "SessionFrame",
    "ContextSourceTrace",
    "ContextAssemblyPlan",
    "ContextAssemblyResult",
    "SummaryHook",
    "RetrievalScheduler",
    "BudgetManager",
    "PromptRenderer",
    "ContextPlanner",
    "DeterministicBudgetManager",
    "DeterministicRetrievalScheduler",
    "DeterministicSummaryHook",
    "MarkdownPromptRenderer",
    "SessionFrameBuilder",
    "LayeredContextPlanner",
    "ContextRuntime",
)
