[project]
name = "pysen-plugins"
description = "Collection of pysen plugins"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
  { name = "Toru Ogawa", email = "ogawa@preferred.jp" },
  { name = "Ryo Miyajima", email = "ryo@preferred.jp" },
  { name = "Linsho Kaku", email = "linsho@preferred.jp" },
]
classifiers = [
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX",
  "Operating System :: MacOS",
  "Operating System :: Unix",
]
dependencies = ["pysen>=0.11.0,<0.12.0"]
dynamic = ["version"]

[build-system]
requires = ["hatchling>=1.27.0,<2.0.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "pysen_plugins/_version.py"

[tool.hatch.build.targets.sdist]
include = ["/pysen_plugins/"]

[tool.pysen]
version = "0.11"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
py_version = "py311"
isort_known_first_party = ["pysen", "pysen_plugins"]

[[tool.pysen.lint.mypy_targets]]
paths = ["pysen_plugins/"]

[tool.pysen.lint.source]
excludes = ["examples/"]
