[tox]
minversion = 3.18.0
envlist = py3,coverage,pep8

[testenv]
deps =
  -r{toxinidir}/test-requirements.txt
commands =
  pytest {posargs}

[testenv:coverage]
commands =
  coverage erase
  pytest --cov=wsme --cov=wsmeext {posargs}
  coverage xml
  coverage report --show-missing

[testenv:docs]
allowlist_externals =
  rm
deps =
  -r{toxinidir}/doc/requirements.txt
commands =
  rm -fr doc/build
  sphinx-build -W -b html doc/source doc/build/html

[testenv:pep8]
deps = flake8
commands =
  flake8 wsme wsmeext setup.py

[testenv:venv]
usedevelop = True
commands = {posargs}
