"""
Type annotations for cloudwatchomni service literal definitions.

[Documentation](https://youtype.github.io/types_boto3_docs/types_boto3_cloudwatchomni/literals/)

Copyright 2026 Vlad Emelianov

Usage::

    ```python
    from types_boto3_cloudwatchomni.literals import AccessGrantPermissionType

    data: AccessGrantPermissionType = "CUSTOM"
    ```
"""

import sys

if sys.version_info >= (3, 12):
    from typing import Literal
else:
    from typing_extensions import Literal


__all__ = (
    "AccessGrantPermissionType",
    "AccessGrantPrincipalTypeType",
    "AccessGrantTypeType",
    "AccessProfileTypeType",
    "AlertSortFieldType",
    "AlertSortOrderType",
    "AlertStateType",
    "AssumeStatusType",
    "AuthTypeType",
    "CloudWatchOmniServiceName",
    "ComparatorType",
    "DomainStatusType",
    "EdgeTypeType",
    "EncryptionStrategyType",
    "GetContextGraphPaginatorName",
    "GetTelemetryQueryResultsPaginatorName",
    "IdentityProviderType",
    "IntegrationStatusType",
    "IntegrationTypeType",
    "ListAccessGrantsPaginatorName",
    "ListAccessProfilesPaginatorName",
    "ListAlertsPaginatorName",
    "ListDomainAccessGrantsForOrganizationPaginatorName",
    "ListDomainsPaginatorName",
    "ListIntegrationsPaginatorName",
    "ListOmniDashboardsPaginatorName",
    "ListSpacesForOrganizationPaginatorName",
    "ListSpacesPaginatorName",
    "ListTelemetryFieldsPaginatorName",
    "ListTelemetryQuerySessionsPaginatorName",
    "ListViewsPaginatorName",
    "NodeCategoryType",
    "NodeTypeType",
    "NotificationStatusType",
    "NotificationTargetTypeType",
    "OrganizationCredentialTypeType",
    "OrganizationGrantPermissionType",
    "OrganizationGrantPrincipalTypeType",
    "PaginatorName",
    "PrincipalTypeType",
    "QueryLanguageType",
    "QueryStatusType",
    "ResourceServiceName",
    "RowScopeOperatorType",
    "ScopeType",
    "SearchPrincipalsPaginatorName",
    "ServiceName",
    "SignalType",
    "SignalTypeType",
    "SourceType",
    "SpaceStatusType",
    "TelemetryTypeType",
    "ThresholdModeType",
    "ViewTypeType",
)


AccessGrantPermissionType = Literal["CUSTOM", "READ", "READ_WRITE_DELETE", "SPACE_ADMIN"]
AccessGrantPrincipalTypeType = Literal[
    "ACCESS_PROFILE", "AGENT", "ALERT", "IAM_ROLE", "IAM_ROOT", "IAM_USER", "IDC_GROUP", "IDC_USER"
]
AccessGrantTypeType = Literal["CUSTOMER_MANAGED", "SERVICE_MANAGED"]
AccessProfileTypeType = Literal["CUSTOMER_MANAGED", "SERVICE_MANAGED"]
AlertSortFieldType = Literal["NAME", "STATE"]
AlertSortOrderType = Literal["ASC", "DESC"]
AlertStateType = Literal["CRITICAL", "NODATA", "OK", "WARNING"]
AssumeStatusType = Literal["ALLOWED", "DENIED"]
AuthTypeType = Literal["API_KEY", "NONE", "OAUTH2"]
ComparatorType = Literal["GT", "GTE", "LT", "LTE"]
DomainStatusType = Literal["ACTIVE"]
EdgeTypeType = Literal["ACCESSES", "CALLS", "RUNS_ON"]
EncryptionStrategyType = Literal["AWS_OWNED", "CUSTOMER_MANAGED"]
GetContextGraphPaginatorName = Literal["get_context_graph"]
GetTelemetryQueryResultsPaginatorName = Literal["get_telemetry_query_results"]
IdentityProviderType = Literal["IAM", "IDC"]
IntegrationStatusType = Literal["ACTIVE", "DELETED", "ERROR", "FAILED", "PENDING", "PENDING_OAUTH"]
IntegrationTypeType = Literal["AWS_CONFIG_SLREC", "AWS_INTEGRATION", "EXTERNAL_AGENT", "SLACK"]
ListAccessGrantsPaginatorName = Literal["list_access_grants"]
ListAccessProfilesPaginatorName = Literal["list_access_profiles"]
ListAlertsPaginatorName = Literal["list_alerts"]
ListDomainAccessGrantsForOrganizationPaginatorName = Literal[
    "list_domain_access_grants_for_organization"
]
ListDomainsPaginatorName = Literal["list_domains"]
ListIntegrationsPaginatorName = Literal["list_integrations"]
ListOmniDashboardsPaginatorName = Literal["list_omni_dashboards"]
ListSpacesForOrganizationPaginatorName = Literal["list_spaces_for_organization"]
ListSpacesPaginatorName = Literal["list_spaces"]
ListTelemetryFieldsPaginatorName = Literal["list_telemetry_fields"]
ListTelemetryQuerySessionsPaginatorName = Literal["list_telemetry_query_sessions"]
ListViewsPaginatorName = Literal["list_views"]
NodeCategoryType = Literal[
    "COMPUTE", "DATABASE", "GEN_AI_AGENT", "GEN_AI_MODEL", "MESSAGING_QUEUE", "NETWORK", "STORAGE"
]
NodeTypeType = Literal["REMOTE_SERVICE", "RESOURCE", "SERVICE"]
NotificationStatusType = Literal["DISABLED", "ENABLED"]
NotificationTargetTypeType = Literal["pagerduty", "slack", "sns"]
OrganizationCredentialTypeType = Literal["SPACE_OPERATION"]
OrganizationGrantPermissionType = Literal["ADMIN"]
OrganizationGrantPrincipalTypeType = Literal[
    "IAM_ROLE", "IAM_ROOT", "IAM_USER", "IDC_GROUP", "IDC_USER"
]
PrincipalTypeType = Literal["GROUP", "USER"]
QueryLanguageType = Literal["PROMQL", "SQL"]
QueryStatusType = Literal["Cancelled", "Complete", "Failed", "Running"]
RowScopeOperatorType = Literal["IN"]
ScopeType = Literal["ACCOUNT", "ORGANIZATION"]
SearchPrincipalsPaginatorName = Literal["search_principals"]
SignalType = Literal["CONFIG", "LOGS", "METRICS", "TRACES", "UNKNOWN"]
SignalTypeType = Literal["LOGS", "TRACES"]
SourceType = Literal[
    "AWS_INTEGRATION",
    "AZURE_VNET_FLOW_LOG",
    "CLOUDFRONT_ACCESS_LOG",
    "CLOUDTRAIL",
    "CODE_SEMANTICS",
    "CONFIG",
    "ELB_ACCESS_LOG",
    "IAM_POLICY",
    "S3_ACCESS_LOG",
    "TELEMETRY",
    "VPC_FLOW_LOG",
    "WAF_ACCESS_LOG",
]
SpaceStatusType = Literal["ACTIVE", "MOVING", "SUSPENDED"]
TelemetryTypeType = Literal["LOGS", "TRACES"]
ThresholdModeType = Literal["COUNT_OF_RESULTS", "FIELD_VALUE"]
ViewTypeType = Literal["MANAGED", "USER"]
CloudWatchOmniServiceName = Literal["cloudwatchomni"]
ServiceName = Literal[
    "accessanalyzer",
    "account",
    "account-access",
    "acm",
    "acm-pca",
    "agent-registry",
    "agent-registry-control",
    "aiops",
    "amp",
    "amplify",
    "amplifybackend",
    "amplifyuibuilder",
    "apigateway",
    "apigatewaymanagementapi",
    "apigatewayv2",
    "appconfig",
    "appconfigdata",
    "appfabric",
    "appflow",
    "appintegrations",
    "application-autoscaling",
    "application-insights",
    "application-signals",
    "applicationcostprofiler",
    "appmesh",
    "apprunner",
    "appstream",
    "appsync",
    "arc-region-switch",
    "arc-zonal-shift",
    "artifact",
    "athena",
    "auditmanager",
    "autoscaling",
    "autoscaling-plans",
    "b2bi",
    "backup",
    "backup-gateway",
    "backupsearch",
    "batch",
    "bcm-dashboards",
    "bcm-data-exports",
    "bcm-pricing-calculator",
    "bcm-recommended-actions",
    "bedrock",
    "bedrock-agent",
    "bedrock-agent-runtime",
    "bedrock-agentcore",
    "bedrock-agentcore-control",
    "bedrock-data-automation",
    "bedrock-data-automation-runtime",
    "bedrock-runtime",
    "billing",
    "billingconductor",
    "braket",
    "budgets",
    "ce",
    "chatbot",
    "chime",
    "chime-sdk-identity",
    "chime-sdk-media-pipelines",
    "chime-sdk-meetings",
    "chime-sdk-messaging",
    "chime-sdk-voice",
    "cleanrooms",
    "cleanroomsml",
    "cloud9",
    "cloudcontrol",
    "clouddirectory",
    "cloudformation",
    "cloudfront",
    "cloudfront-keyvaluestore",
    "cloudhsm",
    "cloudhsmv2",
    "cloudsearch",
    "cloudsearchdomain",
    "cloudtrail",
    "cloudtrail-data",
    "cloudwatch",
    "cloudwatchomni",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codeconnections",
    "codedeploy",
    "codeguru-reviewer",
    "codeguru-security",
    "codeguruprofiler",
    "codepipeline",
    "codestar-connections",
    "codestar-notifications",
    "cognito-identity",
    "cognito-idp",
    "cognito-sync",
    "comprehend",
    "comprehendmedical",
    "compute-optimizer",
    "compute-optimizer-automation",
    "config",
    "connect",
    "connect-contact-lens",
    "connectcampaigns",
    "connectcampaignsv2",
    "connectcases",
    "connecthealth",
    "connectparticipant",
    "controlcatalog",
    "controltower",
    "cost-optimization-hub",
    "cur",
    "customer-profiles",
    "databrew",
    "dataexchange",
    "datapipeline",
    "datasync",
    "datazone",
    "dax",
    "deadline",
    "detective",
    "devicefarm",
    "devops-agent",
    "devops-guru",
    "directconnect",
    "discovery",
    "dlm",
    "dms",
    "docdb",
    "docdb-elastic",
    "drs",
    "ds",
    "ds-data",
    "dsql",
    "dynamodb",
    "dynamodbstreams",
    "ebs",
    "ec2",
    "ec2-instance-connect",
    "ecr",
    "ecr-public",
    "ecs",
    "efs",
    "eks",
    "eks-auth",
    "elasticache",
    "elasticbeanstalk",
    "elb",
    "elbv2",
    "elementalinference",
    "emr",
    "emr-containers",
    "emr-serverless",
    "entityresolution",
    "es",
    "eventbridgev2",
    "events",
    "evs",
    "finspace",
    "finspace-data",
    "firehose",
    "fis",
    "fms",
    "forecast",
    "forecastquery",
    "frauddetector",
    "freetier",
    "fsx",
    "gamelift",
    "gameliftstreams",
    "geo-maps",
    "geo-places",
    "geo-routes",
    "glacier",
    "globalaccelerator",
    "glue",
    "grafana",
    "greengrass",
    "greengrassv2",
    "groundstation",
    "guardduty",
    "health",
    "healthlake",
    "iam",
    "iam-toolbox",
    "identitystore",
    "imagebuilder",
    "importexport",
    "inspector",
    "inspector-scan",
    "inspector2",
    "interconnect",
    "internetmonitor",
    "invoicing",
    "iot",
    "iot-data",
    "iot-jobs-data",
    "iot-managed-integrations",
    "iotdeviceadvisor",
    "iotfleetwise",
    "iotsecuretunneling",
    "iotsitewise",
    "iotthingsgraph",
    "iottwinmaker",
    "iotwireless",
    "ivs",
    "ivs-realtime",
    "ivschat",
    "kafka",
    "kafkaconnect",
    "kendra",
    "kendra-ranking",
    "keyspaces",
    "keyspacesstreams",
    "kinesis",
    "kinesis-video-archived-media",
    "kinesis-video-media",
    "kinesis-video-signaling",
    "kinesis-video-webrtc-storage",
    "kinesisanalytics",
    "kinesisanalyticsv2",
    "kinesisvideo",
    "kms",
    "lakeformation",
    "lambda",
    "lambda-core",
    "lambda-microvms",
    "launch-wizard",
    "lex-models",
    "lex-runtime",
    "lexv2-models",
    "lexv2-runtime",
    "license-manager",
    "license-manager-linux-subscriptions",
    "license-manager-user-subscriptions",
    "lightsail",
    "location",
    "logs",
    "lookoutequipment",
    "m2",
    "machinelearning",
    "macie2",
    "mailmanager",
    "managedblockchain",
    "managedblockchain-query",
    "marketplace-agreement",
    "marketplace-catalog",
    "marketplace-deployment",
    "marketplace-discovery",
    "marketplace-entitlement",
    "marketplace-reporting",
    "marketplacecommerceanalytics",
    "mediaconnect",
    "mediaconvert",
    "medialive",
    "mediapackage",
    "mediapackage-vod",
    "mediapackagev2",
    "mediastore",
    "mediastore-data",
    "mediatailor",
    "medical-imaging",
    "memorydb",
    "meteringmarketplace",
    "mgh",
    "mgn",
    "migration-hub-refactor-spaces",
    "migrationhub-config",
    "migrationhuborchestrator",
    "migrationhubstrategy",
    "mpa",
    "mq",
    "mturk",
    "mwaa",
    "mwaa-serverless",
    "neptune",
    "neptune-graph",
    "neptunedata",
    "network-firewall",
    "network-security-manager",
    "networkflowmonitor",
    "networkmanager",
    "networkmonitor",
    "notifications",
    "notificationscontacts",
    "nova-act",
    "oam",
    "observabilityadmin",
    "odb",
    "omics",
    "opensearch",
    "opensearchserverless",
    "organizations",
    "osis",
    "outposts",
    "partnercentral-account",
    "partnercentral-benefits",
    "partnercentral-channel",
    "partnercentral-revenue-measurement",
    "partnercentral-selling",
    "payment-cryptography",
    "payment-cryptography-data",
    "pca-connector-ad",
    "pca-connector-scep",
    "pcs",
    "personalize",
    "personalize-events",
    "personalize-runtime",
    "pi",
    "pinpoint",
    "pinpoint-email",
    "pinpoint-sms-voice",
    "pinpoint-sms-voice-v2",
    "pipes",
    "polly",
    "pricing",
    "pricing-plan-manager",
    "proton",
    "qapps",
    "qbusiness",
    "qconnect",
    "quicksight",
    "ram",
    "rbin",
    "rds",
    "rds-data",
    "redshift",
    "redshift-data",
    "redshift-serverless",
    "rekognition",
    "repostspace",
    "resiliencehub",
    "resiliencehubv2",
    "resource-explorer-2",
    "resource-groups",
    "resourcegroupstaggingapi",
    "rolesanywhere",
    "route53",
    "route53-recovery-cluster",
    "route53-recovery-control-config",
    "route53-recovery-readiness",
    "route53domains",
    "route53globalresolver",
    "route53profiles",
    "route53resolver",
    "rtbfabric",
    "rum",
    "s3",
    "s3control",
    "s3files",
    "s3outposts",
    "s3tables",
    "s3vectors",
    "sagemaker",
    "sagemaker-a2i-runtime",
    "sagemaker-edge",
    "sagemaker-featurestore-runtime",
    "sagemaker-geospatial",
    "sagemaker-metrics",
    "sagemaker-runtime",
    "sagemakerjobruntime",
    "savingsplans",
    "scheduler",
    "schemas",
    "sdb",
    "secretsmanager",
    "security-ir",
    "securityagent",
    "securityhub",
    "securitylake",
    "serverlessrepo",
    "service-quotas",
    "servicecatalog",
    "servicecatalog-appregistry",
    "servicediscovery",
    "ses",
    "sesv2",
    "shield",
    "signer",
    "signer-data",
    "signin",
    "simpledbv2",
    "snow-device-management",
    "snowball",
    "sns",
    "socialmessaging",
    "sqs",
    "ssm",
    "ssm-contacts",
    "ssm-guiconnect",
    "ssm-incidents",
    "ssm-quicksetup",
    "ssm-sap",
    "sso",
    "sso-admin",
    "sso-oidc",
    "stepfunctions",
    "storagegateway",
    "sts",
    "supplychain",
    "support",
    "support-app",
    "supportauthz",
    "sustainability",
    "swf",
    "synthetics",
    "taxsettings",
    "textract",
    "timestream-influxdb",
    "timestream-query",
    "timestream-write",
    "tnb",
    "transcribe",
    "transfer",
    "translate",
    "trustedadvisor",
    "uxc",
    "verifiedpermissions",
    "voice-id",
    "vpc-lattice",
    "waf",
    "waf-regional",
    "wafv2",
    "wellarchitected",
    "wickr",
    "wisdom",
    "workdocs",
    "workmail",
    "workmailmessageflow",
    "workspaces",
    "workspaces-instances",
    "workspaces-thin-client",
    "workspaces-web",
    "xray",
]
ResourceServiceName = Literal[
    "cloudformation", "cloudwatch", "dynamodb", "ec2", "glacier", "iam", "s3", "sns", "sqs"
]
PaginatorName = Literal[
    "get_context_graph",
    "get_telemetry_query_results",
    "list_access_grants",
    "list_access_profiles",
    "list_alerts",
    "list_domain_access_grants_for_organization",
    "list_domains",
    "list_integrations",
    "list_omni_dashboards",
    "list_spaces",
    "list_spaces_for_organization",
    "list_telemetry_fields",
    "list_telemetry_query_sessions",
    "list_views",
    "search_principals",
]
