# coding: utf-8

# Copyright (c) The OGX Contributors.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

"""
    OGX Specification - Stable & Experimental APIs

    This is the specification of the OGX that provides                     a set of endpoints and their corresponding interfaces that are     tailored to                     best leverage Llama Models.      **🔗 COMBINED**: This specification includes both stable production-ready APIs     and experimental pre-release APIs. Use stable APIs for production deployments     and experimental APIs for testing new features.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Any, ClassVar
from typing_extensions import Self

class SearchRankingOptions(BaseModel):
    """
    Options for ranking and filtering search results.  This class configures how search results are ranked and filtered. You can use algorithm-based rerankers (weighted, RRF) or neural rerankers. Defaults from VectorStoresConfig are used when parameters are not provided.  Examples:     # Weighted ranker with custom alpha     SearchRankingOptions(ranker=\"weighted\", alpha=0.7)      # RRF ranker with custom impact factor     SearchRankingOptions(ranker=\"rrf\", impact_factor=50.0)      # Use config defaults (just specify ranker type)     SearchRankingOptions(ranker=\"weighted\")  # Uses alpha from VectorStoresConfig      # Score threshold filtering     SearchRankingOptions(ranker=\"weighted\", score_threshold=0.5)
    """ # noqa: E501
    ranker: Optional[StrictStr] = None
    score_threshold: Optional[Union[StrictFloat, StrictInt]] = None
    alpha: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = None
    impact_factor: Optional[Union[Annotated[float, Field(strict=True, ge=0.0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    weights: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = None
    model: Optional[StrictStr] = None
    __properties: ClassVar[list[str]] = ["ranker", "score_threshold", "alpha", "impact_factor", "weights", "model"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )



    def __getattribute__(self, name):
        """Override to automatically unwrap OneOf/AnyOf instances."""
        value = super().__getattribute__(name)

        # Unwrap OneOf/AnyOf wrappers directly
        if hasattr(value, 'actual_instance') and value.actual_instance is not None:
            return value.actual_instance

        # If the value is a dict, unwrap any OneOf instances in its values
        # Only create a new dict if unwrapping is actually needed, to preserve
        # mutability of the original (e.g. additional_properties)
        if isinstance(value, dict):
            needs_unwrap = any(
                hasattr(v, 'actual_instance') and v.actual_instance is not None
                for v in value.values()
            )
            if needs_unwrap:
                return {
                    k: v.actual_instance if hasattr(v, 'actual_instance') and v.actual_instance is not None else v
                    for k, v in value.items()
                }

        return value



    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of SearchRankingOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if ranker (nullable) is None
        # and model_fields_set contains the field
        if self.ranker is None and "ranker" in self.model_fields_set:
            _dict['ranker'] = None

        # set to None if score_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.score_threshold is None and "score_threshold" in self.model_fields_set:
            _dict['score_threshold'] = None

        # set to None if alpha (nullable) is None
        # and model_fields_set contains the field
        if self.alpha is None and "alpha" in self.model_fields_set:
            _dict['alpha'] = None

        # set to None if impact_factor (nullable) is None
        # and model_fields_set contains the field
        if self.impact_factor is None and "impact_factor" in self.model_fields_set:
            _dict['impact_factor'] = None

        # set to None if weights (nullable) is None
        # and model_fields_set contains the field
        if self.weights is None and "weights" in self.model_fields_set:
            _dict['weights'] = None

        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of SearchRankingOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            k: v for k, v in {
            "ranker": obj.get("ranker"),
            "score_threshold": obj.get("score_threshold"),
            "alpha": obj.get("alpha"),
            "impact_factor": obj.get("impact_factor"),
            "weights": obj.get("weights"),
            "model": obj.get("model"),
            }.items() if k in obj
        })
        return _obj


