"""The author-facing surface — the ONLY cozy-runtime package/job code imports.

Structural fence (cozy-runtime.md §7, boundaries.md): this package may import schema and
typing libraries and the pure canonical-JSON facade only. It cannot import
cozy_runtime.internal, cozy_runtime.cli, the
worker protocol, TensorFS, Varena or any RecordOwner; it cannot read environment or config;
it names no device, allocator, compile or ingest surface. `checks/architecture.py` proves it.

A handler's SIGNATURE is its capability declaration: `Context` says where it runs, and
everything it DOES rides a typed service parameter it named. A `Model` has two lifecycle
methods — `load(loader)` and `unload(loader)` — and the runtime owns when each runs
(model-lifecycle.md). The surface below is the complete set of things a package author
touches, minus the codec plane (cr-017). Per-service fakes live in `cozy_runtime.author.fakes`.
"""

from cozy_runtime import canonical_json
from cozy_runtime.author._activity import ThreadPoolExecutor
from cozy_runtime.author._app import App, Registration, RegistrationError
from cozy_runtime.author._artifacts import ModelArtifact, ObjectRef, SourceArtifact
from cozy_runtime.author._assets import (
    Asset,
    AssetInfo,
    Assets,
    AudioAsset,
    FileAsset,
    Image,
    ImageAsset,
    Tree,
    VideoAsset,
)
from cozy_runtime.author._attention import AttentionContext
from cozy_runtime.author._attention_scope import (
    AttentionLayout,
    attention_scope,
    expect_attention,
)
from cozy_runtime.author._calls import ChildCallError, PendingCall, invocable, prefetch
from cozy_runtime.author._capture import (
    ActivationCapture,
    ActivationCaptureResult,
    ExecutionEnvironment,
    ExecutionObservation,
)
from cozy_runtime.author._concurrent import concurrently
from cozy_runtime.author._context import (
    AdapterRef,
    Context,
    Device,
    RequestView,
)
from cozy_runtime.author._data import data_values
from cozy_runtime.author._decode import (
    DEFAULT_DECODE_LIMITS,
    DecodedAudio,
    DecodedAudioChunk,
    DecodedAudioFormat,
    DecodedImage,
    DecodedMediaEvent,
    DecodedMediaHeader,
    DecodedMediaStream,
    DecodedVideo,
    DecodedVideoFormat,
    DecodedVideoFrame,
    DecodeLimits,
    DecoderUnavailable,
    MediaDecodeError,
    MediaDecoder,
    Mixed,
)
from cozy_runtime.author._defaults import Clamp, Overlay, Recipe, decode_request
from cozy_runtime.author._demand import RequestFeatures
from cozy_runtime.author._describe import assert_declaration_shape, describe
from cozy_runtime.author._errors import (
    NEUTRAL_ERROR_SET,
    AuthorError,
    Cancelled,
    CapabilityError,
    ConformanceError,
    DeadlineExceeded,
    DefaultResolutionError,
    InvalidRequest,
    Outcome,
    OutputError,
    PreflightViolation,
    UnsupportedInput,
    classify,
)
from cozy_runtime.author._invoke import (
    Invocation,
    InvocationResult,
    PreparedRequest,
    attempt,
    invoke,
    prepare,
)
from cozy_runtime.author._loader import (
    Artifact,
    Backend,
    CheckpointUnnormalized,
    Config,
    ConstructionRecord,
    DerivedCache,
    Fit,
    Loader,
    ModelAssets,
    ModelFitRefused,
    ModuleLike,
    Scheduler,
    TensorSpec,
    register_adapter,
    registered_adapters,
)
from cozy_runtime.author._markers import (
    AssetBound,
    AssetLimits,
    Bound,
    ImagePreparation,
    ModelDefault,
    Preflight,
    Shape,
)
from cozy_runtime.author._memo import MemoDistribution, MemoResource
from cozy_runtime.author._model import (
    AdapterCompatibility,
    ConstructionIdentity,
    Model,
    ModelRegistry,
    ModelTestHarness,
    ScopeCall,
    placeable,
    sequence_parallel,
    uses_components,
)
from cozy_runtime.author._model_reader import WeightsReader, WeightsView
from cozy_runtime.author._script import ScriptContext, script_app
from cozy_runtime.author._services import (
    JOB_ONLY,
    SERVING_ONLY,
    AdjustmentRow,
    Adjustments,
    Budget,
    BudgetExhausted,
    BudgetFacts,
    CheckpointConflict,
    CheckpointDeclaration,
    Checkpoints,
    CheckpointSave,
    CheckpointSinkUnbuilt,
    Egress,
    EgressResponse,
    ImageFrame,
    Outputs,
    SavedAudioFacts,
    SavedVideo,
    Scratch,
    Secrets,
    Settings,
    Telemetry,
    VideoJoin,
)
from cozy_runtime.author._signature import ModelBinding, Surface
from cozy_runtime.author._spread import spread
from cozy_runtime.author._weights import (
    MAX_WEIGHTS_NEW_BYTES,
    WeightsOutput,
    WeightsReceipt,
)
from cozy_runtime.author.publication import (
    AssessmentRef,
    CheckpointRef,
    ReleaseReceipt,
    attach_assessment,
    publish_release,
    upload_checkpoint,
)

__all__ = [
    "DEFAULT_DECODE_LIMITS",
    "JOB_ONLY",
    "MAX_WEIGHTS_NEW_BYTES",
    "NEUTRAL_ERROR_SET",
    "SERVING_ONLY",
    "ActivationCapture",
    "ActivationCaptureResult",
    "AdapterCompatibility",
    "AdapterRef",
    "AdjustmentRow",
    "Adjustments",
    "App",
    "Artifact",
    "AssessmentRef",
    "Asset",
    "AssetBound",
    "AssetInfo",
    "AssetLimits",
    "Assets",
    "AttentionContext",
    "AttentionLayout",
    "AudioAsset",
    "AuthorError",
    "Backend",
    "Bound",
    "Budget",
    "BudgetExhausted",
    "BudgetFacts",
    "Cancelled",
    "CapabilityError",
    "CheckpointConflict",
    "CheckpointDeclaration",
    "CheckpointRef",
    "CheckpointSave",
    "CheckpointSinkUnbuilt",
    "CheckpointUnnormalized",
    "Checkpoints",
    "ChildCallError",
    "Clamp",
    "Config",
    "ConformanceError",
    "ConstructionIdentity",
    "ConstructionRecord",
    "Context",
    "DeadlineExceeded",
    "DecodeLimits",
    "DecodedAudio",
    "DecodedAudioChunk",
    "DecodedAudioFormat",
    "DecodedImage",
    "DecodedMediaEvent",
    "DecodedMediaHeader",
    "DecodedMediaStream",
    "DecodedVideo",
    "DecodedVideoFormat",
    "DecodedVideoFrame",
    "DecoderUnavailable",
    "DefaultResolutionError",
    "DerivedCache",
    "Device",
    "Egress",
    "EgressResponse",
    "ExecutionEnvironment",
    "ExecutionObservation",
    "FileAsset",
    "Fit",
    "Image",
    "ImageAsset",
    "ImageFrame",
    "ImagePreparation",
    "InvalidRequest",
    "Invocation",
    "InvocationResult",
    "Loader",
    "MediaDecodeError",
    "MediaDecoder",
    "MemoDistribution",
    "MemoResource",
    "Mixed",
    "Model",
    "ModelArtifact",
    "ModelAssets",
    "ModelBinding",
    "ModelDefault",
    "ModelFitRefused",
    "ModelRegistry",
    "ModelTestHarness",
    "ModuleLike",
    "ObjectRef",
    "Outcome",
    "OutputError",
    "Outputs",
    "Overlay",
    "PendingCall",
    "Preflight",
    "PreflightViolation",
    "PreparedRequest",
    "Recipe",
    "Registration",
    "RegistrationError",
    "ReleaseReceipt",
    "RequestFeatures",
    "RequestView",
    "SavedAudioFacts",
    "SavedVideo",
    "Scheduler",
    "ScopeCall",
    "Scratch",
    "ScriptContext",
    "Secrets",
    "Settings",
    "Shape",
    "SourceArtifact",
    "Surface",
    "Telemetry",
    "TensorSpec",
    "ThreadPoolExecutor",
    "Tree",
    "UnsupportedInput",
    "VideoAsset",
    "VideoJoin",
    "WeightsOutput",
    "WeightsReader",
    "WeightsReceipt",
    "WeightsView",
    "assert_declaration_shape",
    "attach_assessment",
    "attempt",
    "attention_scope",
    "canonical_json",
    "classify",
    "concurrently",
    "data_values",
    "decode_request",
    "describe",
    "expect_attention",
    "invocable",
    "invoke",
    "placeable",
    "prefetch",
    "prepare",
    "publish_release",
    "register_adapter",
    "registered_adapters",
    "script_app",
    "sequence_parallel",
    "spread",
    "upload_checkpoint",
    "uses_components",
]
