[project]
name = "pagerduty"
version = "7.0.1"
description = "Clients for PagerDuty's Public APIs"
requires-python = ">=3.10"
dependencies = ["httpx2"]

[[project.maintainers]]
name = "Demitri Morgan"
email = "demitri@pagerduty.com"

[[project.maintainers]]
name = "PagerDuty Community Team"
email = "community-team@pagerduty.com"

[project.scripts]
pagerduty = "pagerduty.cli:main"

[project.urls]
Documentation = "https://pagerduty.github.io/python-pagerduty"
Repository = "https://github.com/PagerDuty/python-pagerduty"
PyPI = "https://pypi.org/project/pagerduty"

[tool.setuptools.packages.find]
where = ["."]
include = ["pagerduty"]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
ignore = [
    "E731",
    "TRY004",
    "RUF012",
    "UP031",
    "DTZ007",
    "YTT204",
]

[tool.uv.build-backend]
module-name = "pagerduty"
module-root = ""

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff",
    "sphinx",
    "sphinxcontrib-websupport",
    "sphinx-rtd-theme",
    "twine",
    "virtualenv",
]
