[build-system]
requires = ["flit-core >=3.11, <4"]
build-backend = "flit_core.buildapi"

[project]
name = "tempora"
version = "5.10.0"
description = ""
readme = "README.md"
requires-python = ">= 3.10"
dependencies = ["pytest-freezer; extra == \"test\"", "backports.zoneinfo; python_version < \"3.9\" and extra == \"test\"", "tzdata; platform_system == \"Windows\" and extra == \"test\"", "types-python-dateutil; extra == \"test\"", "python-dateutil", "jaraco.collections", "jaraco.context", "jaraco.functools", "typing_extensions", "freezegun; extra==\"test\"", "pytest; extra==\"test\""]
classifiers = ["Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only"]
license = "Apache-2.0"

[[project.authors]]
name = "Jason R. Coombs"
email = "jaraco@jaraco.com"

[project.urls]
Source = "https://github.com/jaraco/tempora"

[project.entry-points]

[project.scripts]
calc-prorate = "tempora:calculate_prorated_values"
