# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.82
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class RecommendationCoverage(BaseModel):
    """
    What share of the namespace's traffic these recommendations were computed from.  Index recommendations are derived only from queries that FILTERED on a field (``length(filter_fields) > 0``), since an index is only meaningful for a filtered field. Without this block an empty ``recommendations`` list is indistinguishable from \"this namespace is fine\", and on 2026-08-22 that is exactly how it read: 184 slow queries in ``ns_7aa8b538a5`` against a ``NO ACTION - Low usage`` verdict computed from 8.
    """ # noqa: E501
    total_queries: StrictInt = Field(description="All queries in the window")
    filtered_queries: StrictInt = Field(description="Queries carrying at least one filter field. These, and only these, are what the recommendations above were computed from.")
    slow_queries: StrictInt = Field(description="Queries over the slow threshold, filtered or not")
    slow_filtered_queries: StrictInt = Field(description="Slow queries carrying a filter field. The gap between this and `slow_queries` is slow traffic no index recommendation can address — look at embedding, vector search or stage cost for those.")
    threshold_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=500, description="Latency above which a query counts as slow here")
    __properties: ClassVar[List[str]] = ["total_queries", "filtered_queries", "slow_queries", "slow_filtered_queries", "threshold_ms"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecommendationCoverage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecommendationCoverage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_queries": obj.get("total_queries"),
            "filtered_queries": obj.get("filtered_queries"),
            "slow_queries": obj.get("slow_queries"),
            "slow_filtered_queries": obj.get("slow_filtered_queries"),
            "threshold_ms": obj.get("threshold_ms") if obj.get("threshold_ms") is not None else 500
        })
        return _obj


