# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.82
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mixpeek.models.shared_triggers_models_trigger_status import SharedTriggersModelsTriggerStatus
from typing import Optional, Set
from typing_extensions import Self

class SharedTriggersModelsUpdateTriggerRequest(BaseModel):
    """
    Request to update an existing trigger.  Only provided fields will be updated. Unknown fields are refused (extra=\"forbid\"): this endpoint cannot update action_config, and a body carrying it used to 200 while changing nothing, so the caller read success and moved on. A field the endpoint cannot act on is an error, not a no-op.
    """ # noqa: E501
    schedule_config: Optional[Dict[str, Any]] = Field(default=None, description="Updated schedule configuration")
    name: Optional[StrictStr] = Field(default=None, description="Updated trigger name")
    description: Optional[StrictStr] = Field(default=None, description="Updated description")
    status: Optional[SharedTriggersModelsTriggerStatus] = Field(default=None, description="Updated status")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["schedule_config", "name", "description", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SharedTriggersModelsUpdateTriggerRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SharedTriggersModelsUpdateTriggerRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schedule_config": obj.get("schedule_config"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "status": obj.get("status")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


