# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.82
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SuggestedConfigResponse(BaseModel):
    """
    The org's signup-time suggested namespace, if one was provisioned.  Studio uses this to badge the suggested namespace with a \"suggested from our research\" indicator. ``exists`` is False when the signup was skipped (personal domain, no enrichment signal, feature disabled) or the org predates the feature; ``manifest_applied`` is False when a suggestion was generated but provisioning failed — show no indicator in either case.
    """ # noqa: E501
    exists: StrictBool = Field(description="Whether a suggestion record exists for this org.")
    namespace_name: Optional[StrictStr] = Field(default=None, description="Name of the suggested (and provisioned) namespace.")
    rationale: Optional[StrictStr] = Field(default=None, description="One-sentence, user-facing reason this setup was suggested.")
    manifest_applied: Optional[StrictBool] = Field(default=False, description="True only if the suggested namespace was actually provisioned.")
    applied_at: Optional[datetime] = None
    sample_queries: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["exists", "namespace_name", "rationale", "manifest_applied", "applied_at", "sample_queries"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SuggestedConfigResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SuggestedConfigResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "exists": obj.get("exists"),
            "namespace_name": obj.get("namespace_name"),
            "rationale": obj.get("rationale"),
            "manifest_applied": obj.get("manifest_applied") if obj.get("manifest_applied") is not None else False,
            "applied_at": obj.get("applied_at"),
            "sample_queries": obj.get("sample_queries")
        })
        return _obj


