# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentry_protos/billing/v1/services/account_status/v1/endpoint_upsert_account_status.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sentry_protos.billing.v1.services.account_status.v1 import account_status_pb2 as sentry__protos_dot_billing_dot_v1_dot_services_dot_account__status_dot_v1_dot_account__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nXsentry_protos/billing/v1/services/account_status/v1/endpoint_upsert_account_status.proto\x12\x33sentry_protos.billing.v1.services.account_status.v1\x1aHsentry_protos/billing/v1/services/account_status/v1/account_status.proto\"\xbf\x02\n\x1aUpsertAccountStatusRequest\x12\x17\n\x0forganization_id\x18\x01 \x01(\x04\x12P\n\x06status\x18\x02 \x01(\x0e\x32;.sentry_protos.billing.v1.services.account_status.v1.StatusH\x00\x88\x01\x01\x12\x1e\n\x11suspension_reason\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x61\n\x0fondemand_status\x18\x04 \x01(\x0e\x32\x43.sentry_protos.billing.v1.services.account_status.v1.OnDemandStatusH\x02\x88\x01\x01\x42\t\n\x07_statusB\x14\n\x12_suspension_reasonB\x12\n\x10_ondemand_status\".\n\x1bUpsertAccountStatusResponse\x12\x0f\n\x07updated\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentry_protos.billing.v1.services.account_status.v1.endpoint_upsert_account_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPSERTACCOUNTSTATUSREQUEST']._serialized_start=220
  _globals['_UPSERTACCOUNTSTATUSREQUEST']._serialized_end=539
  _globals['_UPSERTACCOUNTSTATUSRESPONSE']._serialized_start=541
  _globals['_UPSERTACCOUNTSTATUSRESPONSE']._serialized_end=587
# @@protoc_insertion_point(module_scope)
