kubernetes:
  remote_identity: SERVICE_ACCOUNT
  pod_config:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - env:
          - name: MY_VAR
            value: 'my_var'
          - name: NCCL_IB_SPLIT_DATA_ON_QPS
            value: "0"
          - name: NCCL_IB_QPS_PER_CONNECTION
            value: "4"
          - name: NCCL_IB_TC
            value: "41"
          - name: NCCL_IB_SL
            value: "0"
          - name: NCCL_IB_TIMEOUT
            value: "22"
          - name: NCCL_IB_HCA
            value: "=mlx5_0,mlx5_1,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7,mlx5_8,mlx5_9,mlx5_10,mlx5_12,mlx5_13,mlx5_14,mlx5_15,mlx5_16,mlx5_17"
          - name: NCCL_IB_GID_INDEX
            value: "3"
          - name: NCCL_NET_PLUGIN
            value: "none"
          - name: GLOO_SOCKET_IFNAME
            value: "eth0"
          - name: NCCL_SOCKET_IFNAME
            value: "eth0"
          - name: NCCL_CUMEM_ENABLE
            value: "0"
          volumeMounts:
            - name: infiniband
              mountPath: /dev/infiniband
            - name: ibdevnetdev
              mountPath: /usr/sbin/ibdev2netdev
            - name: showgids
              mountPath: /usr/sbin/show_gids
            - name: hostsys
              mountPath: /sys
          securityContext:
            privileged: true
            capabilities:
              add:
              - IPC_LOCK
              - CAP_SYS_ADMIN
              - NET_RAW
      volumes:
        - name: infiniband
          hostPath:
            path: /dev/infiniband
            type: Directory
        - name: ibdevnetdev
          hostPath:
            path: /usr/sbin/ibdev2netdev
        - name: showgids
          hostPath:
            path: /usr/sbin/show_gids
        - name: hostsys
          hostPath:
            path: /sys
