"""
Type annotations for wellarchitected service literal definitions.

[Documentation](https://youtype.github.io/types_boto3_docs/types_boto3_wellarchitected/literals/)

Copyright 2026 Vlad Emelianov

Usage::

    ```python
    from types_boto3_wellarchitected.literals import AccountJiraIssueManagementStatusType

    data: AccountJiraIssueManagementStatusType = "DISABLED"
    ```
"""

import sys

if sys.version_info >= (3, 12):
    from typing import Literal
else:
    from typing_extensions import Literal


__all__ = (
    "AccountJiraIssueManagementStatusType",
    "AdditionalResourceTypeType",
    "AnswerReasonType",
    "ApplicationTypeType",
    "CheckFailureReasonType",
    "CheckProviderType",
    "CheckStatusType",
    "ChoiceReasonType",
    "ChoiceStatusType",
    "ContextTypeType",
    "CriticalityType",
    "DefinitionTypeType",
    "DifferenceStatusType",
    "DiscoveryIntegrationStatusType",
    "EffortType",
    "FeedbackCategoryType",
    "GenerationStatusType",
    "ImpactCategoryType",
    "ImportLensStatusType",
    "IntegratingServiceType",
    "IntegrationStatusInputType",
    "IntegrationStatusType",
    "IssueManagementTypeType",
    "LensStatusType",
    "LensStatusTypeType",
    "LensTypeType",
    "ListAgentContextsPaginatorName",
    "ListAgentGoalsPaginatorName",
    "ListAgentProfilesPaginatorName",
    "ListAgentRecommendationGenerationsPaginatorName",
    "ListAgentRecommendationItemsPaginatorName",
    "ListAgentRecommendationsPaginatorName",
    "MetricTypeType",
    "NotificationTypeType",
    "OrganizationSharingStatusType",
    "PaginatorName",
    "PermissionTypeType",
    "PillarType",
    "PriorityType",
    "ProfileNotificationTypeType",
    "ProfileOwnerTypeType",
    "QuestionPriorityType",
    "QuestionType",
    "QuestionTypeType",
    "RecommendationFeedbackTypeType",
    "RecommendationItemTypeType",
    "RecommendationSourceType",
    "RecommendationStateType",
    "RecommendationStatusType",
    "RecommendationTypeType",
    "RegionName",
    "RemediationTypeType",
    "ReportFormatType",
    "ResourceServiceName",
    "ReviewTemplateAnswerStatusType",
    "ReviewTemplateUpdateStatusType",
    "RiskRatingType",
    "RiskType",
    "ServiceName",
    "ShareInvitationActionType",
    "ShareResourceTypeType",
    "ShareStatusType",
    "TrustedAdvisorIntegrationStatusType",
    "WellArchitectedServiceName",
    "WorkloadEnvironmentType",
    "WorkloadImprovementStatusType",
    "WorkloadIssueManagementStatusType",
)


AccountJiraIssueManagementStatusType = Literal["DISABLED", "ENABLED"]
AdditionalResourceTypeType = Literal["HELPFUL_RESOURCE", "IMPROVEMENT_PLAN"]
AnswerReasonType = Literal[
    "ARCHITECTURE_CONSTRAINTS", "BUSINESS_PRIORITIES", "NONE", "OTHER", "OUT_OF_SCOPE"
]
ApplicationTypeType = Literal["DESKTOP_APPLICATION", "OTHER", "SAS"]
CheckFailureReasonType = Literal[
    "ACCESS_DENIED", "ASSUME_ROLE_ERROR", "PREMIUM_SUPPORT_REQUIRED", "UNKNOWN_ERROR"
]
CheckProviderType = Literal["TRUSTED_ADVISOR"]
CheckStatusType = Literal["ERROR", "FETCH_FAILED", "NOT_AVAILABLE", "OKAY", "WARNING"]
ChoiceReasonType = Literal[
    "ARCHITECTURE_CONSTRAINTS", "BUSINESS_PRIORITIES", "NONE", "OTHER", "OUT_OF_SCOPE"
]
ChoiceStatusType = Literal["NOT_APPLICABLE", "SELECTED", "UNSELECTED"]
ContextTypeType = Literal["APPLICATION"]
CriticalityType = Literal[
    "BUSINESS_CRITICAL", "MISSION_CRITICAL", "NON_CRITICAL", "TEST_DEVELOPMENT"
]
DefinitionTypeType = Literal["APP_REGISTRY", "WORKLOAD_METADATA"]
DifferenceStatusType = Literal["DELETED", "NEW", "UPDATED"]
DiscoveryIntegrationStatusType = Literal["DISABLED", "ENABLED"]
EffortType = Literal["LARGE", "MEDIUM", "SMALL"]
FeedbackCategoryType = Literal[
    "OTHER",
    "RECOMMENDATION_INCORRECT",
    "RECOMMENDATION_NOT_RELEVANT",
    "RESOURCE_NOT_IMPORTANT",
    "RESOURCE_TYPE_NOT_IMPORTANT",
]
GenerationStatusType = Literal["COMPLETED", "ERROR", "IN_PROGRESS", "QUEUED"]
ImpactCategoryType = Literal["HIGH", "LOW", "MEDIUM"]
ImportLensStatusType = Literal["COMPLETE", "ERROR", "IN_PROGRESS"]
IntegratingServiceType = Literal["JIRA"]
IntegrationStatusInputType = Literal["NOT_CONFIGURED"]
IntegrationStatusType = Literal["CONFIGURED", "NOT_CONFIGURED"]
IssueManagementTypeType = Literal["AUTO", "MANUAL"]
LensStatusType = Literal["CURRENT", "DELETED", "DEPRECATED", "NOT_CURRENT", "UNSHARED"]
LensStatusTypeType = Literal["ALL", "DRAFT", "PUBLISHED"]
LensTypeType = Literal["AWS_OFFICIAL", "CUSTOM_SELF", "CUSTOM_SHARED"]
ListAgentContextsPaginatorName = Literal["list_agent_contexts"]
ListAgentGoalsPaginatorName = Literal["list_agent_goals"]
ListAgentProfilesPaginatorName = Literal["list_agent_profiles"]
ListAgentRecommendationGenerationsPaginatorName = Literal["list_agent_recommendation_generations"]
ListAgentRecommendationItemsPaginatorName = Literal["list_agent_recommendation_items"]
ListAgentRecommendationsPaginatorName = Literal["list_agent_recommendations"]
MetricTypeType = Literal["WORKLOAD"]
NotificationTypeType = Literal["LENS_VERSION_DEPRECATED", "LENS_VERSION_UPGRADED"]
OrganizationSharingStatusType = Literal["DISABLED", "ENABLED"]
PermissionTypeType = Literal["CONTRIBUTOR", "READONLY"]
PillarType = Literal[
    "COST_OPTIMIZATION", "OPERATIONAL_EXCELLENCE", "PERFORMANCE", "RESILIENCE", "SECURITY"
]
PriorityType = Literal["HIGH", "LOW", "MEDIUM"]
ProfileNotificationTypeType = Literal["PROFILE_ANSWERS_UPDATED", "PROFILE_DELETED"]
ProfileOwnerTypeType = Literal["SELF", "SHARED"]
QuestionPriorityType = Literal["NONE", "PRIORITIZED"]
QuestionType = Literal["ANSWERED", "UNANSWERED"]
QuestionTypeType = Literal["NON_PRIORITIZED", "PRIORITIZED"]
RecommendationFeedbackTypeType = Literal["NOT_USEFUL", "USEFUL"]
RecommendationItemTypeType = Literal["AWS_RESOURCE", "RECOMMENDATION"]
RecommendationSourceType = Literal[
    "CLOUDWATCH",
    "COST_EXPLORER",
    "CUSTOMER_IAC",
    "TRUSTED_ADVISOR",
    "WELL_ARCHITECTED_AGENT",
    "WELL_ARCHITECTED_TOOL",
]
RecommendationStateType = Literal["CLOSED", "OPEN"]
RecommendationStatusType = Literal["ACTIVE", "COMPLETED", "SUPPRESSED"]
RecommendationTypeType = Literal["APPLICATION", "ARCHITECTURE", "RESOURCE"]
RemediationTypeType = Literal["AUTO_REMEDIATION", "CLI", "CONSOLE", "IAC", "MCP", "SDK"]
ReportFormatType = Literal["JSON", "PDF"]
ReviewTemplateAnswerStatusType = Literal["ANSWERED", "UNANSWERED"]
ReviewTemplateUpdateStatusType = Literal["CURRENT", "LENS_NOT_CURRENT"]
RiskRatingType = Literal["HIGH", "LOW", "MEDIUM"]
RiskType = Literal["HIGH", "MEDIUM", "NONE", "NOT_APPLICABLE", "UNANSWERED"]
ShareInvitationActionType = Literal["ACCEPT", "REJECT"]
ShareResourceTypeType = Literal["LENS", "PROFILE", "TEMPLATE", "WORKLOAD"]
ShareStatusType = Literal[
    "ACCEPTED", "ASSOCIATED", "ASSOCIATING", "EXPIRED", "FAILED", "PENDING", "REJECTED", "REVOKED"
]
TrustedAdvisorIntegrationStatusType = Literal["DISABLED", "ENABLED"]
WorkloadEnvironmentType = Literal["PREPRODUCTION", "PRODUCTION"]
WorkloadImprovementStatusType = Literal[
    "COMPLETE", "IN_PROGRESS", "NOT_APPLICABLE", "NOT_STARTED", "RISK_ACKNOWLEDGED"
]
WorkloadIssueManagementStatusType = Literal["DISABLED", "ENABLED", "INHERIT"]
WellArchitectedServiceName = Literal["wellarchitected"]
ServiceName = Literal[
    "accessanalyzer",
    "account",
    "account-access",
    "acm",
    "acm-pca",
    "agent-registry",
    "agent-registry-control",
    "aiops",
    "amp",
    "amplify",
    "amplifybackend",
    "amplifyuibuilder",
    "apigateway",
    "apigatewaymanagementapi",
    "apigatewayv2",
    "appconfig",
    "appconfigdata",
    "appfabric",
    "appflow",
    "appintegrations",
    "application-autoscaling",
    "application-insights",
    "application-signals",
    "applicationcostprofiler",
    "appmesh",
    "apprunner",
    "appstream",
    "appsync",
    "arc-region-switch",
    "arc-zonal-shift",
    "artifact",
    "athena",
    "auditmanager",
    "autoscaling",
    "autoscaling-plans",
    "b2bi",
    "backup",
    "backup-gateway",
    "backupsearch",
    "batch",
    "bcm-dashboards",
    "bcm-data-exports",
    "bcm-pricing-calculator",
    "bcm-recommended-actions",
    "bedrock",
    "bedrock-agent",
    "bedrock-agent-runtime",
    "bedrock-agentcore",
    "bedrock-agentcore-control",
    "bedrock-data-automation",
    "bedrock-data-automation-runtime",
    "bedrock-runtime",
    "billing",
    "billingconductor",
    "braket",
    "budgets",
    "ce",
    "chatbot",
    "chime",
    "chime-sdk-identity",
    "chime-sdk-media-pipelines",
    "chime-sdk-meetings",
    "chime-sdk-messaging",
    "chime-sdk-voice",
    "cleanrooms",
    "cleanroomsml",
    "cloud9",
    "cloudcontrol",
    "clouddirectory",
    "cloudformation",
    "cloudfront",
    "cloudfront-keyvaluestore",
    "cloudhsm",
    "cloudhsmv2",
    "cloudsearch",
    "cloudsearchdomain",
    "cloudtrail",
    "cloudtrail-data",
    "cloudwatch",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codeconnections",
    "codedeploy",
    "codeguru-reviewer",
    "codeguru-security",
    "codeguruprofiler",
    "codepipeline",
    "codestar-connections",
    "codestar-notifications",
    "cognito-identity",
    "cognito-idp",
    "cognito-sync",
    "comprehend",
    "comprehendmedical",
    "compute-optimizer",
    "compute-optimizer-automation",
    "config",
    "connect",
    "connect-contact-lens",
    "connectcampaigns",
    "connectcampaignsv2",
    "connectcases",
    "connecthealth",
    "connectparticipant",
    "controlcatalog",
    "controltower",
    "cost-optimization-hub",
    "cur",
    "customer-profiles",
    "databrew",
    "dataexchange",
    "datapipeline",
    "datasync",
    "datazone",
    "dax",
    "deadline",
    "detective",
    "devicefarm",
    "devops-agent",
    "devops-guru",
    "directconnect",
    "discovery",
    "dlm",
    "dms",
    "docdb",
    "docdb-elastic",
    "drs",
    "ds",
    "ds-data",
    "dsql",
    "dynamodb",
    "dynamodbstreams",
    "ebs",
    "ec2",
    "ec2-instance-connect",
    "ecr",
    "ecr-public",
    "ecs",
    "efs",
    "eks",
    "eks-auth",
    "elasticache",
    "elasticbeanstalk",
    "elb",
    "elbv2",
    "elementalinference",
    "emr",
    "emr-containers",
    "emr-serverless",
    "entityresolution",
    "es",
    "events",
    "evs",
    "finspace",
    "finspace-data",
    "firehose",
    "fis",
    "fms",
    "forecast",
    "forecastquery",
    "frauddetector",
    "freetier",
    "fsx",
    "gamelift",
    "gameliftstreams",
    "geo-maps",
    "geo-places",
    "geo-routes",
    "glacier",
    "globalaccelerator",
    "glue",
    "grafana",
    "greengrass",
    "greengrassv2",
    "groundstation",
    "guardduty",
    "health",
    "healthlake",
    "iam",
    "iam-toolbox",
    "identitystore",
    "imagebuilder",
    "importexport",
    "inspector",
    "inspector-scan",
    "inspector2",
    "interconnect",
    "internetmonitor",
    "invoicing",
    "iot",
    "iot-data",
    "iot-jobs-data",
    "iot-managed-integrations",
    "iotdeviceadvisor",
    "iotfleetwise",
    "iotsecuretunneling",
    "iotsitewise",
    "iotthingsgraph",
    "iottwinmaker",
    "iotwireless",
    "ivs",
    "ivs-realtime",
    "ivschat",
    "kafka",
    "kafkaconnect",
    "kendra",
    "kendra-ranking",
    "keyspaces",
    "keyspacesstreams",
    "kinesis",
    "kinesis-video-archived-media",
    "kinesis-video-media",
    "kinesis-video-signaling",
    "kinesis-video-webrtc-storage",
    "kinesisanalytics",
    "kinesisanalyticsv2",
    "kinesisvideo",
    "kms",
    "lakeformation",
    "lambda",
    "lambda-core",
    "lambda-microvms",
    "launch-wizard",
    "lex-models",
    "lex-runtime",
    "lexv2-models",
    "lexv2-runtime",
    "license-manager",
    "license-manager-linux-subscriptions",
    "license-manager-user-subscriptions",
    "lightsail",
    "location",
    "logs",
    "lookoutequipment",
    "m2",
    "machinelearning",
    "macie2",
    "mailmanager",
    "managedblockchain",
    "managedblockchain-query",
    "marketplace-agreement",
    "marketplace-catalog",
    "marketplace-deployment",
    "marketplace-discovery",
    "marketplace-entitlement",
    "marketplace-reporting",
    "marketplacecommerceanalytics",
    "mediaconnect",
    "mediaconvert",
    "medialive",
    "mediapackage",
    "mediapackage-vod",
    "mediapackagev2",
    "mediastore",
    "mediastore-data",
    "mediatailor",
    "medical-imaging",
    "memorydb",
    "meteringmarketplace",
    "mgh",
    "mgn",
    "migration-hub-refactor-spaces",
    "migrationhub-config",
    "migrationhuborchestrator",
    "migrationhubstrategy",
    "mpa",
    "mq",
    "mturk",
    "mwaa",
    "mwaa-serverless",
    "neptune",
    "neptune-graph",
    "neptunedata",
    "network-firewall",
    "networkflowmonitor",
    "networkmanager",
    "networkmonitor",
    "notifications",
    "notificationscontacts",
    "nova-act",
    "oam",
    "observabilityadmin",
    "odb",
    "omics",
    "opensearch",
    "opensearchserverless",
    "organizations",
    "osis",
    "outposts",
    "partnercentral-account",
    "partnercentral-benefits",
    "partnercentral-channel",
    "partnercentral-revenue-measurement",
    "partnercentral-selling",
    "payment-cryptography",
    "payment-cryptography-data",
    "pca-connector-ad",
    "pca-connector-scep",
    "pcs",
    "personalize",
    "personalize-events",
    "personalize-runtime",
    "pi",
    "pinpoint",
    "pinpoint-email",
    "pinpoint-sms-voice",
    "pinpoint-sms-voice-v2",
    "pipes",
    "polly",
    "pricing",
    "pricing-plan-manager",
    "proton",
    "qapps",
    "qbusiness",
    "qconnect",
    "quicksight",
    "ram",
    "rbin",
    "rds",
    "rds-data",
    "redshift",
    "redshift-data",
    "redshift-serverless",
    "rekognition",
    "repostspace",
    "resiliencehub",
    "resiliencehubv2",
    "resource-explorer-2",
    "resource-groups",
    "resourcegroupstaggingapi",
    "rolesanywhere",
    "route53",
    "route53-recovery-cluster",
    "route53-recovery-control-config",
    "route53-recovery-readiness",
    "route53domains",
    "route53globalresolver",
    "route53profiles",
    "route53resolver",
    "rtbfabric",
    "rum",
    "s3",
    "s3control",
    "s3files",
    "s3outposts",
    "s3tables",
    "s3vectors",
    "sagemaker",
    "sagemaker-a2i-runtime",
    "sagemaker-edge",
    "sagemaker-featurestore-runtime",
    "sagemaker-geospatial",
    "sagemaker-metrics",
    "sagemaker-runtime",
    "sagemakerjobruntime",
    "savingsplans",
    "scheduler",
    "schemas",
    "sdb",
    "secretsmanager",
    "security-ir",
    "securityagent",
    "securityhub",
    "securitylake",
    "serverlessrepo",
    "service-quotas",
    "servicecatalog",
    "servicecatalog-appregistry",
    "servicediscovery",
    "ses",
    "sesv2",
    "shield",
    "signer",
    "signer-data",
    "signin",
    "simpledbv2",
    "snow-device-management",
    "snowball",
    "sns",
    "socialmessaging",
    "sqs",
    "ssm",
    "ssm-contacts",
    "ssm-guiconnect",
    "ssm-incidents",
    "ssm-quicksetup",
    "ssm-sap",
    "sso",
    "sso-admin",
    "sso-oidc",
    "stepfunctions",
    "storagegateway",
    "sts",
    "supplychain",
    "support",
    "support-app",
    "supportauthz",
    "sustainability",
    "swf",
    "synthetics",
    "taxsettings",
    "textract",
    "timestream-influxdb",
    "timestream-query",
    "timestream-write",
    "tnb",
    "transcribe",
    "transfer",
    "translate",
    "trustedadvisor",
    "uxc",
    "verifiedpermissions",
    "voice-id",
    "vpc-lattice",
    "waf",
    "waf-regional",
    "wafv2",
    "wellarchitected",
    "wickr",
    "wisdom",
    "workdocs",
    "workmail",
    "workmailmessageflow",
    "workspaces",
    "workspaces-instances",
    "workspaces-thin-client",
    "workspaces-web",
    "xray",
]
ResourceServiceName = Literal[
    "cloudformation", "cloudwatch", "dynamodb", "ec2", "glacier", "iam", "s3", "sns", "sqs"
]
PaginatorName = Literal[
    "list_agent_contexts",
    "list_agent_goals",
    "list_agent_profiles",
    "list_agent_recommendation_generations",
    "list_agent_recommendation_items",
    "list_agent_recommendations",
]
RegionName = Literal[
    "ap-east-1",
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-south-1",
    "ap-southeast-1",
    "ap-southeast-2",
    "ca-central-1",
    "eu-central-1",
    "eu-north-1",
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "me-south-1",
    "sa-east-1",
    "us-east-1",
    "us-east-2",
    "us-west-1",
    "us-west-2",
]
