# pytest.ini
[pytest]
filterwarnings =
    ignore::DeprecationWarning
asyncio_mode=auto
markers =
    integration: marks tests that require a live Postgres instance (deselect with '-m not integration')
