[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.9.6,<0.13.0"]

[project]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Framework :: Django :: 6.1",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
]
dependencies = ["Django>=5.2"]
description = "Bootstrap 5 for Django"
keywords = [
    "django",
    "bootstrap",
    "bootstrap5",
]
license = "BSD-3-Clause"
license-files = [
    "LICENSE",
    "AUTHORS",
]
name = "django-bootstrap5"
readme = "README.md"
requires-python = ">=3.10"
version = "26.3"

[[project.authors]]
name = "Dylan Verheul"
email = "dylan@dyve.net"

[project.optional-dependencies]
jinja = ["Jinja2>=3.0,<4"]

[project.urls]
Changelog = "https://github.com/zostera/django-bootstrap5/blob/main/CHANGELOG.md"
Documentation = "https://django-bootstrap5.readthedocs.io/"
Homepage = "https://github.com/zostera/django-bootstrap5"
Issues = "https://github.com/zostera/django-bootstrap5/issues"
Source = "https://github.com/zostera/django-bootstrap5"

[tool.ruff]
fix = false
line-length = 120
src = ["src"]

[tool.ruff.lint]
fixable = [
    "I001",
    "F",
    "D",
    "UP",
]
ignore = [
    "D1",
    "D203",
    "D212",
    "D301",
]
select = [
    "D",
    "E",
    "F",
    "I",
    "UP",
]
unfixable = ["F8"]

[tool.ruff.lint.isort]
known-first-party = [
    "django_bootstrap5",
    "app",
]
known-third-party = ["django"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.paths]
package = [
    "src/django_bootstrap5",
    "*/django_bootstrap5/src/django_bootstrap5",
]

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.uv.build-backend]
source-exclude = [
    "**/.DS_Store",
    "docs/_build",
    "example/db.sqlite3",
    "uv.lock",
]
source-include = [
    ".editorconfig",
    ".readthedocs.yaml",
    "FUNDING.yml",
    "manage.py",
    "justfile",
    "*.md",
    "example/**",
    "tests/**",
    "tox.ini",
    "docs/**",
]

[tool.check-manifest]
ignore = [
    "uv.lock",
    "pyproject.toml.orig",
]

[tool.typos.default]
extend-ignore-re = ['sha\d+-[A-Za-z0-9+/=]{40,}']

[dependency-groups]
docs = [
    "furo>=2024.8.6",
    "myst-parser>=3.0.1",
    "sphinx>=7.1.2",
]
test = [
    "coverage[toml]>=7.6.1",
    "beautifulsoup4>=4.12.3",
    "coverage[toml]>=7.6.1",
    "pillow>=11.0.0",
]

[[dependency-groups.dev]]
include-group = "test"

[[dependency-groups.dev]]
include-group = "docs"
