"""Compose package namespace — re-exports only, no business logic."""

# Re-export model types for convenience
from ..models import (
    INFRA_ALL_TYPES,
    INFRA_CATEGORIES,
    INFRA_DATABASES,
    ComposeSpec,
    InfraNode,
    PresetDefinition,
    ServiceAugment,
    ServiceNode,
    StyleDefinition,
    WorkspaceAugment,
    find_service_by_name,
    find_service_by_role,
)
from .augments import (
    AUGMENT_REGISTRY,
    ROLE_REGISTRY,
    AugmentDescriptor,
    OptionPrompt,
    ProxySpec,
    RoleDescriptor,
    augment_for,
    augments_for_scope,
)
from .infra import (
    INFRA_REGISTRY,
    INFRA_RENDERERS,
    InfraDescriptor,
    descriptor_for,
    descriptors_for_feature,
    detect_configured_db,
)
from .loader import (
    SPEC_FILENAME,
    default_spec,
    load_spec,
    save_spec,
    spec_file_path,
)
from .operations import (
    add_infra,
    add_service,
    add_service_augment,
    add_workspace_augment,
    apply,
    available_infra,
    available_service_augments,
    available_workspace_augments,
    configured_infra,
    next_available_port,
    remove_infra,
    remove_service,
    remove_service_augment,
    rename_service,
    render_workspace,
    validate,
)
from .presets import (
    PRESET_REGISTRY,
    list_presets,
    members_for_category,
)
from .scaffolder import scaffold_augment, scaffold_service, scaffold_services
from .yaml_editor import (
    deep_merge,
    dumps_yaml,
    ensure_list_item,
    load_yaml,
    save_yaml,
    set_key,
)

__all__ = [
    "AUGMENT_REGISTRY",
    "INFRA_ALL_TYPES",
    "INFRA_CATEGORIES",
    "INFRA_DATABASES",
    "INFRA_REGISTRY",
    "INFRA_RENDERERS",
    "PRESET_REGISTRY",
    "ROLE_REGISTRY",
    "SPEC_FILENAME",
    "AugmentDescriptor",
    "ComposeSpec",
    "InfraDescriptor",
    "InfraNode",
    "OptionPrompt",
    "PresetDefinition",
    "ProxySpec",
    "RoleDescriptor",
    "ServiceAugment",
    "ServiceNode",
    "StyleDefinition",
    "WorkspaceAugment",
    "add_infra",
    "add_service",
    "add_service_augment",
    "add_workspace_augment",
    "apply",
    "augment_for",
    "augments_for_scope",
    "available_infra",
    "available_service_augments",
    "available_workspace_augments",
    "configured_infra",
    "deep_merge",
    "default_spec",
    "descriptor_for",
    "descriptors_for_feature",
    "detect_configured_db",
    "dumps_yaml",
    "ensure_list_item",
    "find_service_by_name",
    "find_service_by_role",
    "list_presets",
    "load_spec",
    "load_yaml",
    "members_for_category",
    "next_available_port",
    "remove_infra",
    "remove_service",
    "remove_service_augment",
    "rename_service",
    "render_workspace",
    "save_spec",
    "save_yaml",
    "scaffold_augment",
    "scaffold_service",
    "scaffold_services",
    "set_key",
    "spec_file_path",
    "validate",
]
