[build-system]
build-backend = "uv_build"
requires = ["uv-build>=0.12.3,<0.13.0"]

[project]
name = "pyproject2conda"
version = "0.23.2"
description = "A script to convert a Python project declared on a pyproject.toml to a conda environment."
readme = "README.md"
keywords = ["pyproject2conda"]
license = "NIST-PD"
license-files = ["LICENSE"]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "packaging>=26.1",
    "pydantic>=2.12.5",
    "tomli; python_version<'3.11'",
    "typer>=0.26.2",
    "typing-extensions; python_version<'3.12'",
]

[[project.authors]]
name = "William P. Krekelberg"
email = "wpk@nist.gov"

[project.scripts]
p2c = "pyproject2conda.cli:app"
pyproject2conda = "pyproject2conda.cli:app"

[project.urls]
Documentation = "https://pages.nist.gov/pyproject2conda/"
Homepage = "https://github.com/usnistgov/pyproject2conda"

[dependency-groups]
test = [
    "pytest-cov",
    "pytest-sugar",
    "pytest-xdist",
    { include-group = "pytest" },
]
docs = [
    "autodocsumm",
    "myst-parser",
    "sphinx>=5.3.0",
    "sphinx-autodoc-typehints",
    "sphinx-book-theme",
    "sphinx-copybutton",
    "sphinxcontrib-typer",
]
basedpyright = ["basedpyright>=1.39.9"]
docs-live = [
    "sphinx-autobuild",
    { include-group = "docs" },
]
docs-spelling = [
    "pyenchant",
    "sphinxcontrib-spelling",
    { include-group = "docs" },
]
ipython = ["ipython"]
mypy = ["mypy[faster-cache]>=2.3.0"]
nox = ["nox>=2026.8.10"]
pylint = ["pylint"]
pytest = ["pytest"]
pytest-accept = ["pytest-accept"]
typecheck-runner = ["typecheck-runner>=0.2.0; python_version>'3.9'"]

[[dependency-groups.dev]]
include-group = "mypy"

[[dependency-groups.dev]]
include-group = "nox"

[[dependency-groups.dev]]
include-group = "pytest-accept"

[[dependency-groups.dev]]
include-group = "test"

[[dependency-groups.dev]]
include-group = "type"

[[dependency-groups.type]]
include-group = "nox"

[[dependency-groups.type]]
include-group = "pylint"

[[dependency-groups.type]]
include-group = "pytest"

[[dependency-groups.type]]
include-group = "typecheck-runner"

[[dependency-groups.test-extras]]
include-group = "test"

[tool.uv]
required-version = ">=0.11.8"
default-groups = ["dev"]
fork-strategy = "requires-python"
exclude-newer = "7 days"
managed = true

[tool.uv.build-backend]
source-exclude = [".*cache"]
source-include = ["tests/**"]

[tool.uv.pip]
annotation-style = "line"
generate-hashes = true

[tool.uv.dependency-groups.dev]
requires-python = ">=3.14"

[tool.uv.dependency-groups.docs]
requires-python = ">=3.14"

[tool.uv.dependency-groups.docs-live]
requires-python = ">=3.14"

[tool.uv.dependency-groups.docs-spelling]
requires-python = ">=3.14"

[tool.uv.dependency-groups.ipython]
requires-python = ">=3.14"

[tool.uv.dependency-groups.mypy]
requires-python = ">=3.14"

[tool.uv.dependency-groups.nox]
requires-python = ">=3.14"

[tool.ruff]
extend-include = ["*.ipynb"]
extend-exclude = [
    "**vendored",
    ".numba_cache",
    ".venv",
    "dist-conda",
]
fix = true
unsafe-fixes = true

[tool.ruff.format]
docstring-code-format = true
preview = true

[tool.ruff.lint]
preview = true
select = ["ALL"]
unfixable = [
    "PLR6104",
    "ERA",
    "T",
]
ignore = [
    "ANN401",
    "COM",
    "CPY",
    "D105",
    "D107",
    "D203",
    "D205",
    "D212",
    "D400",
    "D401",
    "DOC201",
    "DOC501",
    "E501",
    "E731",
    "FBT",
    "PLC0415",
    "S404",
    "S603",
    "S607",
    "TID252",
]

[tool.ruff.lint.isort]
known-first-party = ["pyproject2conda"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.pylint]
max-args = 15
max-positional-args = 15
max-public-methods = 30

[tool.ruff.lint.ruff]
strictly-empty-init-modules = false

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel"]

[tool.ruff.lint.per-file-ignores]
"src/**" = [
    "NPY",
    "PD",
]
"tests/**" = [
    "D",
    "S101",
    "ANN",
    "PLC2701",
]

[tool.repo-review]
ignore = [
    "NOX103",
    "PC111",
    "PC140",
    "PC160",
    "PC170",
]

[tool.check-wheel-contents]
src_dir = ["src"]
toplevel = ["pyproject2conda"]

[tool.pyproject-fmt]
indent = 4
keep_full_version = true
expand_tables = [
    "project.entry-points",
    "project.optional-dependencies",
    "project.scripts",
    "project.urls",
    "tool.mypy.overrides",
    "tool.pyproject2conda",
    "tool.pyright.executionEnvironments",
    "tool.pytest",
    "tool.ruff.format",
    "tool.ruff.lint",
    "tool.ruff.lint.per-file-ignores",
    "tool.ty.overrides",
    "tool.typos",
    "tool.uv.dependency-groups",
    "tool.uv.exclude-newer-package",
]

[tool.typos.default.extend-identifiers]
CPY = "CPY"

[tool.mypy]
files = [
    "noxfile.py",
    "src",
    "tests",
    "tools",
]
check_untyped_defs = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
enable_error_code = [
    "ignore-without-code",
    "redundant-expr",
    "truthy-bool",
]
strict = true
warn_unused_configs = true

[tool.pyrefly]
enabled-ignores = ["pyrefly"]
project-includes = [
    "noxfile.py",
    "src",
    "tests",
    "tools",
]
search-path = ["."]

[tool.pyright]
typeCheckingMode = "strict"
include = [
    "noxfile.py",
    "src",
    "tests",
    "tools",
]
exclude = [
    "**/.mypy_cache",
    "**/.mypy_cache",
    "**/.numba_cache",
    "**/.numba_cache/",
    "**/__pycache__",
    "**/vendored/**",
    ".nox/**",
    ".tox/**",
    ".venv/**",
]
enableTypeIgnoreComments = false
deprecateTypingAliases = true
reportCallInDefaultInitializer = true
reportImplicitOverride = true
reportImplicitStringConcatenation = false
reportImportCycles = true
reportOverlappingOverload = true
reportPrivateImportUsage = false
reportPrivateUsage = false
reportPropertyTypeMismatch = true
reportUninitializedInstanceVariable = true
reportUnnecessaryTypeIgnoreComment = true
reportUnreachable = "warning"
reportUntypedClassDecorator = true
reportUntypedFunctionDecorator = true
reportUnusedCallResult = true
reportUnusedImport = false
reportUnusedVariable = false
enableReachabilityAnalysis = false

[[tool.pyright.executionEnvironments]]
root = "tests"
reportUnusedCallResult = false
reportMissingParameterType = false
reportUnknownParameterType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownVariableType = false

[tool.ty.src]
include = [
    "noxfile.py",
    "src",
    "tests",
    "tools",
]

[tool.ty.analysis]
respect-type-ignore-comments = false

[tool.pytest.ini_options]
addopts = [
    "--cov-config=pyproject.toml",
    "--doctest-glob=*.md",
    "--doctest-modules",
    "--pyargs",
    "--strict-config",
    "--strict-markers",
    "-ra",
]
testpaths = [
    "README.md",
    "pyproject2conda",
    "tests",
]
filterwarnings = ["error"]
log_cli_level = "INFO"
log_level = "INFO"
minversion = "8"
strict_xfail = "true"

[tool.coverage.run]
branch = true
source = ["pyproject2conda"]

[tool.coverage.paths]
source = [
    "src/",
    ".nox/**/site-packages/",
    "*/.nox/**/site-packages",
    "*/src",
]

[tool.coverage.report]
exclude_also = [
    "@overload",
    "if TYPE_CHECKING:",
]
include = ["src/*"]
omit = [
    "*/__main__.py",
    "*/_typing.py",
    "*/vendored/*",
]
show_missing = true

[tool.commitizen]
use_shortcuts = true

[tool.pyproject2conda]
template-python = "requirements/py{py}-{env}"
template = "requirements/{env}"
name = "py{py}-{env}"
python = "default"
channels = "conda-forge"
style = "yaml"
conda-deps = "pip"

[tool.pyproject2conda.dependencies.pytest-accept]
pip = true

[tool.pyproject2conda.envs.dev]
groups = "dev"

[tool.pyproject2conda.envs.test]
groups = "test"
python = "all"

[tool.pyproject2conda.envs.test-extras]
groups = "test-extras"
python = "all"
skip-package = true

[tool.pyproject2conda.envs.uvx-tools]
pip-deps = [
    "conda-lock>=4.0.2",
    "copier-template-extensions>=0.3.3",
    "copier>=9.17.1",
    "grayskull>=3.1.1",
    "prek>=0.4.13",
    "pyrefly>=1.2.0",
    "pyright>=1.1.411",
    "rooster>=0.1.1",
    "twine>=7.0.0",
    "ty>=0.0.70",
]
groups = [
    "basedpyright",
    "mypy",
    "nox",
    "typecheck-runner",
]
skip-package = true
style = "requirements"

[tool.uv-locker]
scripts = [
    "noxfile.py",
    "tools/check_dist_version.py",
    "tools/cog_runner.py",
]

[[tool.uv-locker.requirements]]
path = "requirements/uvx-tools.txt"
output-file = "requirements/lock/uvx-tools.txt"
python = "min"
options = [
    "--no-deps",
    "--no-strip-extras",
    "--universal",
]

[tool.rooster]
changelog_contributors = true
major-labels = ["breaking"]
minor_labels = ["enhancement"]
patch-labels = [
    "bug",
    "documentation",
]
ignore-labels = ["internal"]
require-labels = [
    "breaking",
    "bug",
    "documentation",
    "enhancement",
]
version_files = ["pyproject.toml"]

[tool.rooster.section-labels]
"Breaking changes" = ["breaking"]
"Bug fixes" = ["bug"]
Documentation = ["documentation"]
Enhancements = ["enhancement"]
Internal = ["internal"]
"Other changes" = ["__unknown__"]
