"""Auto-generated stub for module: layers."""
from typing import Any, Optional

# Functions
def build_norm_layer(norm_type: Any) -> Any.Any.Any: ...

# Classes
class AddCoords:
    # Add coords to a tensor, modified from paper: https://arxiv.org/abs/1807.03247

    def __init__(self: Any, with_r: Any = False) -> None: ...

    def build(self: Any, input_shape: Any) -> Any: ...

    def call(self: Any, input_tensor: Any) -> Any:
        """
        input_tensor: (batch, x_dim, y_dim, c)
        """
        ...

class CoordConv2D:
    # CoordConv2D layer as in the paper, modified from paper: https://arxiv.org/abs/1807.03247

    def __init__(self: Any, with_r: bool = False, **conv_kwargs: Any) -> None: ...

    def call(self: Any, inputs: Any) -> Any: ...

    def get_config(self: Any) -> Any: ...

class DyT:
    # Dynamic Tanh (DyT) is an element-wise operation as a drop-in replacement for normalization
    # layers in Transformers.
    #
    # Paper: https://arxiv.org/abs/2503.10622.

    def __init__(self: Any, alpha_init_value: float = 0.5, **kwargs: Any) -> None: ...

    def build(self: Any, input_shape: Any) -> Any: ...

    def call(self: Any, x: Any) -> Any: ...

    def get_config(self: Any) -> Any: ...

class MLP:
    def __init__(self: Any, hidden_units: Any, dropout_rate: float = 0.1, activation: str = 'gelu', use_bias: bool = True, **kwargs: Any) -> None: ...

    def build(self: Any, input_shape: Any) -> Any: ...

    def call(self: Any, inputs: Any, training: Any = None) -> Any: ...

    def get_config(self: Any) -> Any: ...

class MaxBlurPooling2D:
    def __init__(self: Any, pool_size: int = 2, filter_size: int = 3, padding: str = 'same', **kwargs: Any) -> None: ...

    def build(self: Any, input_shape: Any) -> Any: ...

    def call(self: Any, x: Any) -> Any: ...

    def compute_output_shape(self: Any, input_shape: Any) -> Any: ...

    def get_config(self: Any) -> Any: ...

class PatchExtractor:
    # Extract non-overlapping patches from an image and flatten them.
    #
    # Modified from https://keras.io/examples/vision/image_classification_with_vision_transformer.

    def __init__(self: Any, patch_size: Any, **kwargs: Any) -> None: ...

    def call(self: Any, images: Any) -> Any: ...

    def get_config(self: Any) -> Any: ...

class PositionEmbedding:
    def __init__(self: Any, sequence_length: Any, initializer: Any = 'glorot_uniform', **kwargs: Any) -> None: ...

    def build(self: Any, input_shape: Any) -> Any: ...

    def call(self: Any, inputs: Any, start_index: Any = 0) -> Any: ...

    def compute_output_shape(self: Any, input_shape: Any) -> Any: ...

    def get_config(self: Any) -> Any: ...

class SqueezeExcite:
    # Applies squeeze and excitation to input feature maps as seen in https://arxiv.org/abs/1709.01507
    #
    # Note: this was taken from https://keras.io/examples/vision/patch_convnet.

    def __init__(self: Any, ratio: float = 1.0, **kwargs: Any) -> None: ...

    def build(self: Any, input_shape: Any) -> Any: ...

    def call(self: Any, x: Any) -> Any: ...

    def get_config(self: Any) -> Any: ...

class StochasticDepth:
    def __init__(self: Any, drop_prob: float, **kwargs: Any) -> None: ...

    def call(self: Any, x: Any, training: Any = None) -> Any: ...

    def get_config(self: Any) -> Any: ...

class TokenReducer:
    def __init__(self: Any, num_tokens: Any, projection_dim: Any, num_heads: Any = 2, **kwargs: Any) -> None: ...

    def build(self: Any, input_shape: Any) -> Any: ...

    def call(self: Any, inputs: Any) -> Any:
        """
        inputs: Tensor of shape (batch_size, seq_length, projection_dim)
        returns: Tensor of shape (batch_size, num_tokens, projection_dim)
        """
        ...

    def compute_output_shape(self: Any, input_shape: Any) -> Any: ...

    def get_config(self: Any) -> Any: ...

class TransformerBlock:
    def __init__(self: Any, projection_dim: int, num_heads: int, mlp_units: Any[int], attention_dropout: float, mlp_dropout: float, drop_path_rate: float, norm_type: Optional[str] = 'layer_norm', activation: str = 'gelu', **kwargs: Any) -> None: ...

    def build(self: Any, input_shape: Any) -> None: ...

    def call(self: Any, x: Any, training: Any = None) -> Any: ...

    def get_config(self: Any) -> Any: ...

class VocabularyProjection:
    def __init__(self: Any, vocabulary_size: int, dropout_rate: Optional[float] = None, **kwargs: Any) -> None: ...

    def build(self: Any, input_shape: Any) -> Any: ...

    def call(self: Any, x: Any, training: Any = None) -> Any: ...

    def get_config(self: Any) -> Any: ...

