
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2026-05-28T09:57:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e49a6e9bd8ff6e19d93ed43f5550da6c9018a5df",
 "version": "1.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
