[project]
name = "dify-plugin"
version = "0.10.2"
description = "Dify Plugin SDK"
dependencies = [
    "Flask>=3.1.3",
    "Werkzeug>=3.1.8",
    "gevent>=26.4.0",
    "h11>=0.16.0",
    "httpx>=0.28.1",
    "pydantic_settings>=2.14.2",
    "pydantic>=2.13.4",
    "pyyaml>=6.0.3",
    "requests>=2.33.1",
    "socksio>=1.0.0",
    "tiktoken>=0.12.0",
    "yarl>=1.23.0",
    "packaging>=26.2",
]
requires-python = ">=3.12"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
keywords = [
    "dify",
    "plugin",
    "sdk",
]

[[project.authors]]
name = "langgenius"
email = "hello@dify.ai"

[project.urls]
source = "https://github.com/langgenius/dify-plugin-sdks"
homepage = "https://github.com/langgenius/dify-plugin-sdks"
issues = "https://github.com/langgenius/dify-plugin-sdks/issues"

[build-system]
requires = ["uv_build~=0.12.1"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "prek",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "pytest-xprocess",
    "ruff",
    "ty",
]

[tool.uv]
default-groups = ["dev"]

[tool.pytest]
minversion = "9.0"
testpaths = ["tests"]

[tool.ruff]
preview = true
required-version = ">=0.15.22"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "too-many-statements",
    "commented-out-code",
    "too-many-branches",
    "too-many-locals",
    "raise-vanilla-class",
    "blind-except",
    "raise-within-try",
    "too-many-arguments",
    "too-many-positional-arguments",
    "complex-structure",
    "FBT",
    "TC",
    "relative-imports",
    "no-self-use",
    "missing-trailing-comma",
    "CPY",
    "D",
]

[tool.ruff.lint.pydoclint]
ignore-one-line-docstrings = true

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "assert",
    "private-member-access",
    "magic-value-comparison",
]
