[build-system]
requires = ['setuptools>=64', 'wheel', 'plux>=1.12', "setuptools_scm>=8.1"]
build-backend = "setuptools.build_meta"

[project]
name = "localstack"
authors = [
    { name = "LocalStack Contributors", email = "info@localstack.cloud" }
]
description = "The LocalStack Command Line Interface"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.10"
dependencies = [
    "asn1crypto",
    "cachetools>=5.0",
    "click>=8.2.0",
    "cryptography",
    "dnslib>=0.9.10",
    "dnspython>=1.16.0",
    "docker>=6.1.1",
    "plux>=1.14.0",
    "psutil>=5.4.8",
    "python-dotenv>=0.19.1",
    "pyyaml>=5.1",
    "rich>=12.3.0",
    "requests>=2.20.0",
    "semver>=2.10",
    "tabulate",
    "packaging",
    "pyotp>=2.9.0",
    "PyJWT[crypto]>=1.7.0",
    "python-dateutil>=2.8",
    "windows-curses;platform_system=='Windows'",
]
dynamic = ["version", "entry-points"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet",
    "Topic :: Software Development :: Testing",
]

[project.scripts]
localstack = "localstack_cli.cli.main:main"

[tool.setuptools_scm]
version_file = "localstack_cli/version.py"
local_scheme = "no-local-version"

[project.urls]
Homepage = "https://localstack.cloud"
Documentation = "https://docs.localstack.cloud"
Repository = "https://github.com/localstack/localstack.git"
Issues = "https://github.com/localstack/localstack/issues"

[project.optional-dependencies]
test = [
    "pytest>=7.4.2",
    "pytest-httpserver>=1.1.2",
    "pytest-tinybird>=0.5.0",
    "boto3",
    "jsonpatch",
    "xmltodict",
    "cbor2",
    "hypercorn",
    "flask",
    "rolo",
]

dev = [
    "localstack[test]",
    "libcst",
    "ruff>=0.3.3",
    "pre-commit>=3.5.0",
]

[tool.setuptools]
include-package-data = false
package-dir = { "" = "." }

[tool.setuptools.dynamic]
entry-points = { file = ["plux.ini"] }

[tool.setuptools.packages.find]
where = ["."]
include = ["localstack_cli*"]
exclude = ["tests*"]

[tool.ruff]
target-version = "py310"
line-length = 100
src = ["localstack_cli", "tests"]

[tool.plux]
entrypoint_build_mode = "manual"

[tool.pytest.ini_options]
log_cli = false
log_level = "DEBUG"
testpaths = ["tests"]
