"""
Type annotations for geo-routes service literal definitions.

[Documentation](https://youtype.github.io/boto3_stubs_docs/mypy_boto3_geo_routes/literals/)

Copyright 2026 Vlad Emelianov

Usage::

    ```python
    from mypy_boto3_geo_routes.literals import DayOfWeekType

    data: DayOfWeekType = "Friday"
    ```
"""

import sys

if sys.version_info >= (3, 12):
    from typing import Literal
else:
    from typing_extensions import Literal


__all__ = (
    "DayOfWeekType",
    "GeometryFormatType",
    "IsolineEngineTypeType",
    "IsolineHazardousCargoTypeType",
    "IsolineOptimizationObjectiveType",
    "IsolineTravelModeType",
    "IsolineTruckTypeType",
    "IsolineZoneCategoryType",
    "LocationServiceRoutesV2ServiceName",
    "MatchingStrategyType",
    "MeasurementSystemType",
    "ResourceServiceName",
    "RoadSnapHazardousCargoTypeType",
    "RoadSnapNoticeCodeType",
    "RoadSnapTravelModeType",
    "RouteAccessibilityAttributeType",
    "RouteAccessibilityAvailabilityType",
    "RouteAttributionTypeType",
    "RouteDirectionType",
    "RouteEngineTypeType",
    "RouteFerryAfterTravelStepTypeType",
    "RouteFerryBeforeTravelStepTypeType",
    "RouteFerryNoticeCodeType",
    "RouteFerryTravelStepTypeType",
    "RouteHazardousCargoTypeType",
    "RouteIntermodalEnabledLegsType",
    "RouteLegAdditionalFeatureType",
    "RouteLegTravelModeType",
    "RouteLegTypeType",
    "RouteMatrixErrorCodeType",
    "RouteMatrixHazardousCargoTypeType",
    "RouteMatrixTravelModeType",
    "RouteMatrixTruckTypeType",
    "RouteMatrixZoneCategoryType",
    "RouteNoticeImpactType",
    "RoutePedestrianAfterTravelStepTypeType",
    "RoutePedestrianNoticeCodeType",
    "RoutePedestrianPlaceTypeType",
    "RoutePedestrianTravelStepTypeType",
    "RouteRentalAfterTravelStepTypeType",
    "RouteRentalBeforeTravelStepTypeType",
    "RouteRentalModeType",
    "RouteRentalPlaceTypeType",
    "RouteRentalTravelStepTypeType",
    "RouteResponseNoticeCodeType",
    "RouteRoadTypeType",
    "RouteSideOfStreetType",
    "RouteSpanAdditionalFeatureType",
    "RouteSpanCarAccessAttributeType",
    "RouteSpanGateAttributeType",
    "RouteSpanPedestrianAccessAttributeType",
    "RouteSpanRailwayCrossingAttributeType",
    "RouteSpanRoadAttributeType",
    "RouteSpanScooterAccessAttributeType",
    "RouteSpanTruckAccessAttributeType",
    "RouteSteeringDirectionType",
    "RouteTaxiAfterTravelStepTypeType",
    "RouteTaxiBeforeTravelStepTypeType",
    "RouteTaxiModeType",
    "RouteTaxiNoticeCodeType",
    "RouteTaxiPlaceTypeType",
    "RouteTaxiTravelStepTypeType",
    "RouteTollPassValidityPeriodTypeType",
    "RouteTollPaymentMethodType",
    "RouteTollVehicleCategoryType",
    "RouteTransitAfterTravelStepTypeType",
    "RouteTransitBeforeTravelStepTypeType",
    "RouteTransitIncidentEffectType",
    "RouteTransitIncidentTypeType",
    "RouteTransitIntermediateStopAttributeType",
    "RouteTransitModeType",
    "RouteTransitNoticeCodeType",
    "RouteTransitPlaceTypeType",
    "RouteTransitTravelStepTypeType",
    "RouteTransitTripStatusType",
    "RouteTravelModeType",
    "RouteTravelStepTypeType",
    "RouteTruckTypeType",
    "RouteTurnIntensityType",
    "RouteVehicleAfterTravelStepTypeType",
    "RouteVehicleIncidentSeverityType",
    "RouteVehicleIncidentTypeType",
    "RouteVehicleModeType",
    "RouteVehicleNoticeCodeType",
    "RouteVehiclePlaceTypeType",
    "RouteVehicleTravelStepTypeType",
    "RouteWebLinkDeviceTypeType",
    "RouteWeightConstraintTypeType",
    "RouteZoneCategoryType",
    "RoutingObjectiveType",
    "ServiceName",
    "SideOfStreetMatchingStrategyType",
    "TrafficUsageType",
    "WaypointOptimizationClusteringAlgorithmType",
    "WaypointOptimizationConstraintType",
    "WaypointOptimizationHazardousCargoTypeType",
    "WaypointOptimizationSequencingObjectiveType",
    "WaypointOptimizationServiceTimeTreatmentType",
    "WaypointOptimizationTravelModeType",
    "WaypointOptimizationTruckTypeType",
)


DayOfWeekType = Literal[
    "Friday", "Monday", "Saturday", "Sunday", "Thursday", "Tuesday", "Wednesday"
]
GeometryFormatType = Literal["FlexiblePolyline", "Simple"]
IsolineEngineTypeType = Literal["Electric", "InternalCombustion", "PluginHybrid"]
IsolineHazardousCargoTypeType = Literal[
    "Combustible",
    "Corrosive",
    "Explosive",
    "Flammable",
    "Gas",
    "HarmfulToWater",
    "Organic",
    "Other",
    "Poison",
    "PoisonousInhalation",
    "Radioactive",
]
IsolineOptimizationObjectiveType = Literal[
    "AccurateCalculation", "BalancedCalculation", "FastCalculation"
]
IsolineTravelModeType = Literal["Car", "Pedestrian", "Scooter", "Truck"]
IsolineTruckTypeType = Literal["LightTruck", "StraightTruck", "Tractor"]
IsolineZoneCategoryType = Literal["CongestionPricing", "Environmental", "Vignette"]
MatchingStrategyType = Literal["MatchAny", "MatchMostSignificantRoad"]
MeasurementSystemType = Literal["Imperial", "Metric"]
RoadSnapHazardousCargoTypeType = Literal[
    "Combustible",
    "Corrosive",
    "Explosive",
    "Flammable",
    "Gas",
    "HarmfulToWater",
    "Organic",
    "Other",
    "Poison",
    "PoisonousInhalation",
    "Radioactive",
]
RoadSnapNoticeCodeType = Literal[
    "TracePointsHeadingIgnored",
    "TracePointsIgnored",
    "TracePointsMovedByLargeDistance",
    "TracePointsNotMatched",
    "TracePointsOutOfSequence",
    "TracePointsSpeedEstimated",
    "TracePointsSpeedIgnored",
]
RoadSnapTravelModeType = Literal["Car", "Pedestrian", "Scooter", "Truck"]
RouteAccessibilityAttributeType = Literal["Wheelchair"]
RouteAccessibilityAvailabilityType = Literal["Available", "Limited", "Unavailable", "Unknown"]
RouteAttributionTypeType = Literal["Disclaimer", "Tariff"]
RouteDirectionType = Literal["East", "North", "South", "West"]
RouteEngineTypeType = Literal["Electric", "InternalCombustion", "PluginHybrid"]
RouteFerryAfterTravelStepTypeType = Literal["Deboard"]
RouteFerryBeforeTravelStepTypeType = Literal["Board"]
RouteFerryNoticeCodeType = Literal[
    "AccuratePolylineUnavailable",
    "NoSchedule",
    "Other",
    "PotentialViolatedVehicleRestrictionUsage",
    "SeasonalClosure",
    "ViolatedAvoidAreas",
    "ViolatedAvoidFerry",
    "ViolatedAvoidRailFerry",
    "ViolatedVehicleRestriction",
]
RouteFerryTravelStepTypeType = Literal["Arrive", "Continue", "Depart"]
RouteHazardousCargoTypeType = Literal[
    "Combustible",
    "Corrosive",
    "Explosive",
    "Flammable",
    "Gas",
    "HarmfulToWater",
    "Organic",
    "Other",
    "Poison",
    "PoisonousInhalation",
    "Radioactive",
]
RouteIntermodalEnabledLegsType = Literal["EntireRoute", "FirstLeg", "LastLeg", "None"]
RouteLegAdditionalFeatureType = Literal[
    "Bookings",
    "Elevation",
    "Incidents",
    "IntermediateStops",
    "NextDepartures",
    "PassThroughWaypoints",
    "Summary",
    "Tolls",
    "TravelStepInstructions",
    "TruckRoadTypes",
    "TypicalDuration",
    "Zones",
]
RouteLegTravelModeType = Literal[
    "AerialTramway",
    "Airplane",
    "Bus",
    "BusRapidTransit",
    "Car",
    "CarShuttleTrain",
    "CityTrain",
    "Ferry",
    "FunicularRailway",
    "HighSpeedTrain",
    "IntercityTrain",
    "InterregionalTrain",
    "LightRail",
    "Monorail",
    "Pedestrian",
    "PrivateBus",
    "RegionalTrain",
    "Scooter",
    "Subway",
    "Truck",
]
RouteLegTypeType = Literal["Ferry", "Pedestrian", "Rental", "Taxi", "Transit", "Vehicle"]
RouteMatrixErrorCodeType = Literal[
    "NoMatch",
    "NoMatchDestination",
    "NoMatchOrigin",
    "NoRoute",
    "Other",
    "OutOfBounds",
    "OutOfBoundsDestination",
    "OutOfBoundsOrigin",
    "Violation",
]
RouteMatrixHazardousCargoTypeType = Literal[
    "Combustible",
    "Corrosive",
    "Explosive",
    "Flammable",
    "Gas",
    "HarmfulToWater",
    "Organic",
    "Other",
    "Poison",
    "PoisonousInhalation",
    "Radioactive",
]
RouteMatrixTravelModeType = Literal["Car", "Pedestrian", "Scooter", "Truck"]
RouteMatrixTruckTypeType = Literal["LightTruck", "StraightTruck", "Tractor"]
RouteMatrixZoneCategoryType = Literal["CongestionPricing", "Environmental", "Vignette"]
RouteNoticeImpactType = Literal["High", "Low"]
RoutePedestrianAfterTravelStepTypeType = Literal["Wait"]
RoutePedestrianNoticeCodeType = Literal[
    "AccuratePolylineUnavailable",
    "Other",
    "ViolatedAvoidAreas",
    "ViolatedAvoidDirtRoad",
    "ViolatedAvoidTunnel",
    "ViolatedPedestrianOption",
]
RoutePedestrianPlaceTypeType = Literal["AccessPoint", "DockingStation", "ParkingLot", "Station"]
RoutePedestrianTravelStepTypeType = Literal[
    "Arrive",
    "Continue",
    "Depart",
    "Keep",
    "RoundaboutEnter",
    "RoundaboutExit",
    "RoundaboutPass",
    "Turn",
]
RouteRentalAfterTravelStepTypeType = Literal["Park"]
RouteRentalBeforeTravelStepTypeType = Literal["Setup"]
RouteRentalModeType = Literal["All", "Car"]
RouteRentalPlaceTypeType = Literal["AccessPoint", "DockingStation", "ParkingLot", "Station"]
RouteRentalTravelStepTypeType = Literal[
    "Arrive",
    "Continue",
    "Depart",
    "Exit",
    "Keep",
    "Ramp",
    "RoundaboutEnter",
    "RoundaboutExit",
    "RoundaboutPass",
    "Turn",
    "UTurn",
]
RouteResponseNoticeCodeType = Literal[
    "MainLanguageNotFound",
    "NoTransitStationsFound",
    "Other",
    "TransitDataUnavailable",
    "TransitRouteUnavailable",
    "TravelTimeExceedsDriverWorkHours",
]
RouteRoadTypeType = Literal["Highway", "Rural", "Urban"]
RouteSideOfStreetType = Literal["Left", "Right"]
RouteSpanAdditionalFeatureType = Literal[
    "BestCaseDuration",
    "CarAccess",
    "Consumption",
    "Country",
    "Distance",
    "Duration",
    "DynamicSpeed",
    "FunctionalClassification",
    "Gates",
    "Incidents",
    "Names",
    "Notices",
    "PedestrianAccess",
    "RailwayCrossings",
    "Region",
    "RoadAttributes",
    "RouteNumbers",
    "ScooterAccess",
    "SpeedLimit",
    "TollSystems",
    "TruckAccess",
    "TruckRoadTypes",
    "TypicalDuration",
    "Zones",
]
RouteSpanCarAccessAttributeType = Literal["Allowed", "NoThroughTraffic", "TollRoad"]
RouteSpanGateAttributeType = Literal["Emergency", "KeyAccess", "PermissionRequired"]
RouteSpanPedestrianAccessAttributeType = Literal[
    "Allowed", "Indoors", "NoThroughTraffic", "Park", "Stairs", "TollRoad"
]
RouteSpanRailwayCrossingAttributeType = Literal["Protected", "Unprotected"]
RouteSpanRoadAttributeType = Literal[
    "Bridge",
    "BuiltUpArea",
    "ControlledAccessHighway",
    "DirtRoad",
    "DividedRoad",
    "Motorway",
    "PrivateRoad",
    "Ramp",
    "RightHandTraffic",
    "Roundabout",
    "Tunnel",
    "UnderConstruction",
]
RouteSpanScooterAccessAttributeType = Literal["Allowed", "NoThroughTraffic", "TollRoad"]
RouteSpanTruckAccessAttributeType = Literal["Allowed", "NoThroughTraffic", "TollRoad"]
RouteSteeringDirectionType = Literal["Left", "Right", "Straight"]
RouteTaxiAfterTravelStepTypeType = Literal["Park"]
RouteTaxiBeforeTravelStepTypeType = Literal["Wait"]
RouteTaxiModeType = Literal["All", "Car"]
RouteTaxiNoticeCodeType = Literal["AccuratePolylineUnavailable", "Other"]
RouteTaxiPlaceTypeType = Literal["AccessPoint", "Station"]
RouteTaxiTravelStepTypeType = Literal[
    "Arrive",
    "Continue",
    "Depart",
    "Exit",
    "Keep",
    "Ramp",
    "RoundaboutEnter",
    "RoundaboutExit",
    "RoundaboutPass",
    "Turn",
    "UTurn",
]
RouteTollPassValidityPeriodTypeType = Literal[
    "Annual", "Days", "ExtendedAnnual", "Minutes", "Months"
]
RouteTollPaymentMethodType = Literal[
    "BankCard",
    "Cash",
    "CashExact",
    "CreditCard",
    "PassSubscription",
    "Transponder",
    "TravelCard",
    "VideoToll",
]
RouteTollVehicleCategoryType = Literal["Minibus"]
RouteTransitAfterTravelStepTypeType = Literal["Deboard"]
RouteTransitBeforeTravelStepTypeType = Literal["Board"]
RouteTransitIncidentEffectType = Literal[
    "Delayed",
    "Detoured",
    "Other",
    "ServiceAdded",
    "ServiceCancelled",
    "ServiceModified",
    "ServiceReduced",
    "StopMoved",
]
RouteTransitIncidentTypeType = Literal[
    "Accident",
    "Construction",
    "Demonstration",
    "Holiday",
    "Maintenance",
    "MedicalEmergency",
    "Other",
    "PoliceActivity",
    "Strike",
    "TechnicalProblem",
    "Weather",
]
RouteTransitIntermediateStopAttributeType = Literal["NoEntry", "NoExit"]
RouteTransitModeType = Literal[
    "AerialTramway",
    "Airplane",
    "All",
    "Bus",
    "BusRapidTransit",
    "CityTrain",
    "Ferry",
    "FunicularRailway",
    "HighSpeedTrain",
    "IntercityTrain",
    "InterregionalTrain",
    "LightRail",
    "Monorail",
    "PrivateBus",
    "RegionalTrain",
    "Subway",
]
RouteTransitNoticeCodeType = Literal[
    "AccuratePolylineUnavailable",
    "IntermediateStopsUnavailable",
    "NoSchedule",
    "Other",
    "PotentialViolatedVehicleRestrictionUsage",
    "ScheduledTimes",
    "SeasonalClosure",
    "ViolatedAvoidAreas",
    "ViolatedAvoidFerry",
    "ViolatedAvoidRailFerry",
    "ViolatedExcludedTransitMode",
    "ViolatedVehicleRestriction",
]
RouteTransitPlaceTypeType = Literal["Station"]
RouteTransitTravelStepTypeType = Literal["Depart"]
RouteTransitTripStatusType = Literal["Added", "Cancelled", "Replaced", "Scheduled"]
RouteTravelModeType = Literal["Car", "Intermodal", "Pedestrian", "Scooter", "Transit", "Truck"]
RouteTravelStepTypeType = Literal["Default", "TurnByTurn"]
RouteTruckTypeType = Literal["LightTruck", "StraightTruck", "Tractor"]
RouteTurnIntensityType = Literal["Sharp", "Slight", "Typical"]
RouteVehicleAfterTravelStepTypeType = Literal["Park"]
RouteVehicleIncidentSeverityType = Literal["Critical", "High", "Low", "Medium"]
RouteVehicleIncidentTypeType = Literal[
    "Accident",
    "Congestion",
    "Construction",
    "DisabledVehicle",
    "LaneRestriction",
    "MassTransit",
    "Other",
    "PlannedEvent",
    "RoadClosure",
    "RoadHazard",
    "Weather",
]
RouteVehicleModeType = Literal["All", "Car"]
RouteVehicleNoticeCodeType = Literal[
    "AccuratePolylineUnavailable",
    "Other",
    "PotentialViolatedAvoidTollRoadUsage",
    "PotentialViolatedCarpoolUsage",
    "PotentialViolatedTurnRestrictionUsage",
    "PotentialViolatedVehicleRestrictionUsage",
    "PotentialViolatedZoneRestrictionUsage",
    "SeasonalClosure",
    "TollTransponder",
    "TollsDataTemporarilyUnavailable",
    "TollsDataUnavailable",
    "TravelTimeExceedsDriverWorkHours",
    "ViolatedAvoidControlledAccessHighway",
    "ViolatedAvoidDifficultTurns",
    "ViolatedAvoidDirtRoad",
    "ViolatedAvoidSeasonalClosure",
    "ViolatedAvoidTollRoad",
    "ViolatedAvoidTollTransponder",
    "ViolatedAvoidTruckRoadType",
    "ViolatedAvoidTunnel",
    "ViolatedAvoidUTurns",
    "ViolatedBlockedRoad",
    "ViolatedCarpool",
    "ViolatedEmergencyGate",
    "ViolatedStartDirection",
    "ViolatedTurnRestriction",
    "ViolatedVehicleRestriction",
    "ViolatedZoneRestriction",
]
RouteVehiclePlaceTypeType = Literal["AccessPoint", "DockingStation", "ParkingLot", "Station"]
RouteVehicleTravelStepTypeType = Literal[
    "Arrive",
    "Continue",
    "ContinueHighway",
    "Depart",
    "EnterHighway",
    "Exit",
    "Keep",
    "Ramp",
    "RoundaboutEnter",
    "RoundaboutExit",
    "RoundaboutPass",
    "Turn",
    "UTurn",
]
RouteWebLinkDeviceTypeType = Literal["Android", "Ios", "Web"]
RouteWeightConstraintTypeType = Literal["Current", "Gross", "Unknown"]
RouteZoneCategoryType = Literal["CongestionPricing", "Environmental", "Vignette"]
RoutingObjectiveType = Literal["FastestRoute", "ShortestRoute"]
SideOfStreetMatchingStrategyType = Literal["AnyStreet", "DividedStreetOnly"]
TrafficUsageType = Literal["IgnoreTrafficData", "UseTrafficData"]
WaypointOptimizationClusteringAlgorithmType = Literal["DrivingDistance", "TopologySegment"]
WaypointOptimizationConstraintType = Literal[
    "AccessHours", "AppointmentTime", "Before", "Heading", "ServiceDuration", "SideOfStreet"
]
WaypointOptimizationHazardousCargoTypeType = Literal[
    "Combustible",
    "Corrosive",
    "Explosive",
    "Flammable",
    "Gas",
    "HarmfulToWater",
    "Organic",
    "Other",
    "Poison",
    "PoisonousInhalation",
    "Radioactive",
]
WaypointOptimizationSequencingObjectiveType = Literal["FastestRoute", "ShortestRoute"]
WaypointOptimizationServiceTimeTreatmentType = Literal["Rest", "Work"]
WaypointOptimizationTravelModeType = Literal["Car", "Pedestrian", "Scooter", "Truck"]
WaypointOptimizationTruckTypeType = Literal["StraightTruck", "Tractor"]
LocationServiceRoutesV2ServiceName = Literal["geo-routes"]
ServiceName = Literal[
    "accessanalyzer",
    "account",
    "acm",
    "acm-pca",
    "aiops",
    "amp",
    "amplify",
    "amplifybackend",
    "amplifyuibuilder",
    "apigateway",
    "apigatewaymanagementapi",
    "apigatewayv2",
    "appconfig",
    "appconfigdata",
    "appfabric",
    "appflow",
    "appintegrations",
    "application-autoscaling",
    "application-insights",
    "application-signals",
    "applicationcostprofiler",
    "appmesh",
    "apprunner",
    "appstream",
    "appsync",
    "arc-region-switch",
    "arc-zonal-shift",
    "artifact",
    "athena",
    "auditmanager",
    "autoscaling",
    "autoscaling-plans",
    "b2bi",
    "backup",
    "backup-gateway",
    "backupsearch",
    "batch",
    "bcm-dashboards",
    "bcm-data-exports",
    "bcm-pricing-calculator",
    "bcm-recommended-actions",
    "bedrock",
    "bedrock-agent",
    "bedrock-agent-runtime",
    "bedrock-agentcore",
    "bedrock-agentcore-control",
    "bedrock-data-automation",
    "bedrock-data-automation-runtime",
    "bedrock-runtime",
    "billing",
    "billingconductor",
    "braket",
    "budgets",
    "ce",
    "chatbot",
    "chime",
    "chime-sdk-identity",
    "chime-sdk-media-pipelines",
    "chime-sdk-meetings",
    "chime-sdk-messaging",
    "chime-sdk-voice",
    "cleanrooms",
    "cleanroomsml",
    "cloud9",
    "cloudcontrol",
    "clouddirectory",
    "cloudformation",
    "cloudfront",
    "cloudfront-keyvaluestore",
    "cloudhsm",
    "cloudhsmv2",
    "cloudsearch",
    "cloudsearchdomain",
    "cloudtrail",
    "cloudtrail-data",
    "cloudwatch",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codeconnections",
    "codedeploy",
    "codeguru-reviewer",
    "codeguru-security",
    "codeguruprofiler",
    "codepipeline",
    "codestar-connections",
    "codestar-notifications",
    "cognito-identity",
    "cognito-idp",
    "cognito-sync",
    "comprehend",
    "comprehendmedical",
    "compute-optimizer",
    "compute-optimizer-automation",
    "config",
    "connect",
    "connect-contact-lens",
    "connectcampaigns",
    "connectcampaignsv2",
    "connectcases",
    "connecthealth",
    "connectparticipant",
    "controlcatalog",
    "controltower",
    "cost-optimization-hub",
    "cur",
    "customer-profiles",
    "databrew",
    "dataexchange",
    "datapipeline",
    "datasync",
    "datazone",
    "dax",
    "deadline",
    "detective",
    "devicefarm",
    "devops-agent",
    "devops-guru",
    "directconnect",
    "discovery",
    "dlm",
    "dms",
    "docdb",
    "docdb-elastic",
    "drs",
    "ds",
    "ds-data",
    "dsql",
    "dynamodb",
    "dynamodbstreams",
    "ebs",
    "ec2",
    "ec2-instance-connect",
    "ecr",
    "ecr-public",
    "ecs",
    "efs",
    "eks",
    "eks-auth",
    "elasticache",
    "elasticbeanstalk",
    "elb",
    "elbv2",
    "elementalinference",
    "emr",
    "emr-containers",
    "emr-serverless",
    "entityresolution",
    "es",
    "events",
    "evs",
    "finspace",
    "finspace-data",
    "firehose",
    "fis",
    "fms",
    "forecast",
    "forecastquery",
    "frauddetector",
    "freetier",
    "fsx",
    "gamelift",
    "gameliftstreams",
    "geo-maps",
    "geo-places",
    "geo-routes",
    "glacier",
    "globalaccelerator",
    "glue",
    "grafana",
    "greengrass",
    "greengrassv2",
    "groundstation",
    "guardduty",
    "health",
    "healthlake",
    "iam",
    "identitystore",
    "imagebuilder",
    "importexport",
    "inspector",
    "inspector-scan",
    "inspector2",
    "interconnect",
    "internetmonitor",
    "invoicing",
    "iot",
    "iot-data",
    "iot-jobs-data",
    "iot-managed-integrations",
    "iotdeviceadvisor",
    "iotfleetwise",
    "iotsecuretunneling",
    "iotsitewise",
    "iotthingsgraph",
    "iottwinmaker",
    "iotwireless",
    "ivs",
    "ivs-realtime",
    "ivschat",
    "kafka",
    "kafkaconnect",
    "kendra",
    "kendra-ranking",
    "keyspaces",
    "keyspacesstreams",
    "kinesis",
    "kinesis-video-archived-media",
    "kinesis-video-media",
    "kinesis-video-signaling",
    "kinesis-video-webrtc-storage",
    "kinesisanalytics",
    "kinesisanalyticsv2",
    "kinesisvideo",
    "kms",
    "lakeformation",
    "lambda",
    "lambda-core",
    "lambda-microvms",
    "launch-wizard",
    "lex-models",
    "lex-runtime",
    "lexv2-models",
    "lexv2-runtime",
    "license-manager",
    "license-manager-linux-subscriptions",
    "license-manager-user-subscriptions",
    "lightsail",
    "location",
    "logs",
    "lookoutequipment",
    "m2",
    "machinelearning",
    "macie2",
    "mailmanager",
    "managedblockchain",
    "managedblockchain-query",
    "marketplace-agreement",
    "marketplace-catalog",
    "marketplace-deployment",
    "marketplace-discovery",
    "marketplace-entitlement",
    "marketplace-reporting",
    "marketplacecommerceanalytics",
    "mediaconnect",
    "mediaconvert",
    "medialive",
    "mediapackage",
    "mediapackage-vod",
    "mediapackagev2",
    "mediastore",
    "mediastore-data",
    "mediatailor",
    "medical-imaging",
    "memorydb",
    "meteringmarketplace",
    "mgh",
    "mgn",
    "migration-hub-refactor-spaces",
    "migrationhub-config",
    "migrationhuborchestrator",
    "migrationhubstrategy",
    "mpa",
    "mq",
    "mturk",
    "mwaa",
    "mwaa-serverless",
    "neptune",
    "neptune-graph",
    "neptunedata",
    "network-firewall",
    "networkflowmonitor",
    "networkmanager",
    "networkmonitor",
    "notifications",
    "notificationscontacts",
    "nova-act",
    "oam",
    "observabilityadmin",
    "odb",
    "omics",
    "opensearch",
    "opensearchserverless",
    "organizations",
    "osis",
    "outposts",
    "partnercentral-account",
    "partnercentral-benefits",
    "partnercentral-channel",
    "partnercentral-revenue-measurement",
    "partnercentral-selling",
    "payment-cryptography",
    "payment-cryptography-data",
    "pca-connector-ad",
    "pca-connector-scep",
    "pcs",
    "personalize",
    "personalize-events",
    "personalize-runtime",
    "pi",
    "pinpoint",
    "pinpoint-email",
    "pinpoint-sms-voice",
    "pinpoint-sms-voice-v2",
    "pipes",
    "polly",
    "pricing",
    "pricing-plan-manager",
    "proton",
    "qapps",
    "qbusiness",
    "qconnect",
    "quicksight",
    "ram",
    "rbin",
    "rds",
    "rds-data",
    "redshift",
    "redshift-data",
    "redshift-serverless",
    "rekognition",
    "repostspace",
    "resiliencehub",
    "resiliencehubv2",
    "resource-explorer-2",
    "resource-groups",
    "resourcegroupstaggingapi",
    "rolesanywhere",
    "route53",
    "route53-recovery-cluster",
    "route53-recovery-control-config",
    "route53-recovery-readiness",
    "route53domains",
    "route53globalresolver",
    "route53profiles",
    "route53resolver",
    "rtbfabric",
    "rum",
    "s3",
    "s3control",
    "s3files",
    "s3outposts",
    "s3tables",
    "s3vectors",
    "sagemaker",
    "sagemaker-a2i-runtime",
    "sagemaker-edge",
    "sagemaker-featurestore-runtime",
    "sagemaker-geospatial",
    "sagemaker-metrics",
    "sagemaker-runtime",
    "sagemakerjobruntime",
    "savingsplans",
    "scheduler",
    "schemas",
    "sdb",
    "secretsmanager",
    "security-ir",
    "securityagent",
    "securityhub",
    "securitylake",
    "serverlessrepo",
    "service-quotas",
    "servicecatalog",
    "servicecatalog-appregistry",
    "servicediscovery",
    "ses",
    "sesv2",
    "shield",
    "signer",
    "signer-data",
    "signin",
    "simpledbv2",
    "snow-device-management",
    "snowball",
    "sns",
    "socialmessaging",
    "sqs",
    "ssm",
    "ssm-contacts",
    "ssm-guiconnect",
    "ssm-incidents",
    "ssm-quicksetup",
    "ssm-sap",
    "sso",
    "sso-admin",
    "sso-oidc",
    "stepfunctions",
    "storagegateway",
    "sts",
    "supplychain",
    "support",
    "support-app",
    "supportauthz",
    "sustainability",
    "swf",
    "synthetics",
    "taxsettings",
    "textract",
    "timestream-influxdb",
    "timestream-query",
    "timestream-write",
    "tnb",
    "transcribe",
    "transfer",
    "translate",
    "trustedadvisor",
    "uxc",
    "verifiedpermissions",
    "voice-id",
    "vpc-lattice",
    "waf",
    "waf-regional",
    "wafv2",
    "wellarchitected",
    "wickr",
    "wisdom",
    "workdocs",
    "workmail",
    "workmailmessageflow",
    "workspaces",
    "workspaces-instances",
    "workspaces-thin-client",
    "workspaces-web",
    "xray",
]
ResourceServiceName = Literal[
    "cloudformation", "cloudwatch", "dynamodb", "ec2", "glacier", "iam", "s3", "sns", "sqs"
]
