"""
Type annotations for securityagent service literal definitions.

[Documentation](https://youtype.github.io/types_boto3_docs/types_boto3_securityagent/literals/)

Copyright 2026 Vlad Emelianov

Usage::

    ```python
    from types_boto3_securityagent.literals import AccessTypeType

    data: AccessTypeType = "PRIVATE"
    ```
"""

import sys

if sys.version_info >= (3, 12):
    from typing import Literal
else:
    from typing_extensions import Literal


__all__ = (
    "AccessTypeType",
    "ArtifactTypeType",
    "AuthenticationProviderTypeType",
    "CleanUpStrategyType",
    "CodeRemediationStrategyType",
    "CodeRemediationTaskStatusType",
    "ConfidenceLevelType",
    "ContextTypeType",
    "DNSRecordTypeType",
    "DomainVerificationMethodType",
    "ErrorCodeType",
    "FindingStatusType",
    "GitLabTokenTypeType",
    "IpAddressTypeType",
    "JobStatusType",
    "ListAgentSpacesPaginatorName",
    "ListApplicationsPaginatorName",
    "ListArtifactsPaginatorName",
    "ListCodeReviewJobTasksPaginatorName",
    "ListCodeReviewJobsForCodeReviewPaginatorName",
    "ListCodeReviewsPaginatorName",
    "ListDiscoveredEndpointsPaginatorName",
    "ListFindingsPaginatorName",
    "ListIntegratedResourcesPaginatorName",
    "ListIntegrationsPaginatorName",
    "ListMembershipsPaginatorName",
    "ListPentestJobTasksPaginatorName",
    "ListPentestJobsForPentestPaginatorName",
    "ListPentestsPaginatorName",
    "ListPrivateConnectionsPaginatorName",
    "ListSecurityRequirementPacksPaginatorName",
    "ListSecurityRequirementsPaginatorName",
    "ListTargetDomainsPaginatorName",
    "ListThreatModelJobTasksPaginatorName",
    "ListThreatModelJobsPaginatorName",
    "ListThreatModelsPaginatorName",
    "ListThreatsPaginatorName",
    "LogTypeType",
    "ManagementTypeType",
    "MembershipTypeFilterType",
    "MembershipTypeType",
    "NetworkTrafficRuleEffectType",
    "NetworkTrafficRuleTypeType",
    "PaginatorName",
    "PrivateConnectionStatusType",
    "PrivateConnectionTypeType",
    "ProviderType",
    "ProviderTypeType",
    "ResourceConfigDnsResolutionType",
    "ResourceServiceName",
    "ResourceTypeType",
    "RiskLevelType",
    "RiskTypeType",
    "SecurityAgentServiceName",
    "SecurityRequirementArtifactFormatType",
    "SecurityRequirementPackImportStatusType",
    "SecurityRequirementPackStatusType",
    "ServiceName",
    "SkillTypeType",
    "StepNameType",
    "StepStatusType",
    "StrideCategoryType",
    "TargetDomainStatusType",
    "TaskExecutionStatusType",
    "ThreatActorType",
    "ThreatSeverityType",
    "ThreatStatusType",
    "UserRoleType",
    "ValidationModeType",
    "ValidationStatusType",
)


AccessTypeType = Literal["PRIVATE", "PUBLIC"]
ArtifactTypeType = Literal["DOC", "DOCX", "JPEG", "JSON", "MD", "PDF", "PNG", "TXT", "YAML"]
AuthenticationProviderTypeType = Literal[
    "AWS_IAM_ROLE", "AWS_INTERNAL", "AWS_LAMBDA", "SECRETS_MANAGER"
]
CleanUpStrategyType = Literal["BEST_EFFORT_DELETE", "RETAIN_ALL"]
CodeRemediationStrategyType = Literal["AUTOMATIC", "DISABLED"]
CodeRemediationTaskStatusType = Literal["COMPLETED", "FAILED", "IN_PROGRESS"]
ConfidenceLevelType = Literal["FALSE_POSITIVE", "HIGH", "LOW", "MEDIUM", "UNCONFIRMED"]
ContextTypeType = Literal["CLIENT_ERROR", "ERROR", "INFO", "WARNING"]
DNSRecordTypeType = Literal["TXT"]
DomainVerificationMethodType = Literal["DNS_TXT", "HTTP_ROUTE", "PRIVATE_VPC"]
ErrorCodeType = Literal["CLIENT_ERROR", "INTERNAL_ERROR", "STOPPED_BY_USER"]
FindingStatusType = Literal["ACCEPTED", "ACTIVE", "FALSE_POSITIVE", "RESOLVED"]
GitLabTokenTypeType = Literal["GROUP", "PERSONAL"]
IpAddressTypeType = Literal["DUAL_STACK", "IPV4", "IPV6"]
JobStatusType = Literal["COMPLETED", "FAILED", "IN_PROGRESS", "STOPPED", "STOPPING"]
ListAgentSpacesPaginatorName = Literal["list_agent_spaces"]
ListApplicationsPaginatorName = Literal["list_applications"]
ListArtifactsPaginatorName = Literal["list_artifacts"]
ListCodeReviewJobTasksPaginatorName = Literal["list_code_review_job_tasks"]
ListCodeReviewJobsForCodeReviewPaginatorName = Literal["list_code_review_jobs_for_code_review"]
ListCodeReviewsPaginatorName = Literal["list_code_reviews"]
ListDiscoveredEndpointsPaginatorName = Literal["list_discovered_endpoints"]
ListFindingsPaginatorName = Literal["list_findings"]
ListIntegratedResourcesPaginatorName = Literal["list_integrated_resources"]
ListIntegrationsPaginatorName = Literal["list_integrations"]
ListMembershipsPaginatorName = Literal["list_memberships"]
ListPentestJobTasksPaginatorName = Literal["list_pentest_job_tasks"]
ListPentestJobsForPentestPaginatorName = Literal["list_pentest_jobs_for_pentest"]
ListPentestsPaginatorName = Literal["list_pentests"]
ListPrivateConnectionsPaginatorName = Literal["list_private_connections"]
ListSecurityRequirementPacksPaginatorName = Literal["list_security_requirement_packs"]
ListSecurityRequirementsPaginatorName = Literal["list_security_requirements"]
ListTargetDomainsPaginatorName = Literal["list_target_domains"]
ListThreatModelJobTasksPaginatorName = Literal["list_threat_model_job_tasks"]
ListThreatModelJobsPaginatorName = Literal["list_threat_model_jobs"]
ListThreatModelsPaginatorName = Literal["list_threat_models"]
ListThreatsPaginatorName = Literal["list_threats"]
LogTypeType = Literal["CLOUDWATCH"]
ManagementTypeType = Literal["AWS_MANAGED", "CUSTOMER_MANAGED"]
MembershipTypeFilterType = Literal["ALL", "USER"]
MembershipTypeType = Literal["USER"]
NetworkTrafficRuleEffectType = Literal["ALLOW", "DENY"]
NetworkTrafficRuleTypeType = Literal["URL"]
PrivateConnectionStatusType = Literal[
    "ACTIVE", "CREATE_FAILED", "CREATE_IN_PROGRESS", "DELETE_FAILED", "DELETE_IN_PROGRESS"
]
PrivateConnectionTypeType = Literal["SELF_MANAGED", "SERVICE_MANAGED"]
ProviderType = Literal["BITBUCKET", "CONFLUENCE", "GITHUB", "GITLAB"]
ProviderTypeType = Literal["DOCUMENTATION", "SOURCE_CODE"]
ResourceConfigDnsResolutionType = Literal["IN_VPC", "PUBLIC"]
ResourceTypeType = Literal["CODE_REPOSITORY", "DOCUMENT"]
RiskLevelType = Literal["CRITICAL", "HIGH", "INFORMATIONAL", "LOW", "MEDIUM", "UNKNOWN"]
RiskTypeType = Literal[
    "ARBITRARY_FILE_UPLOAD",
    "BUSINESS_LOGIC_VULNERABILITIES",
    "CODE_INJECTION",
    "COMMAND_INJECTION",
    "CROSS_SITE_SCRIPTING",
    "CRYPTOGRAPHIC_VULNERABILITIES",
    "DATABASE_ACCESS",
    "DATABASE_MODIFICATION",
    "DEFAULT_CREDENTIALS",
    "DENIAL_OF_SERVICE",
    "FILE_ACCESS",
    "FILE_CREATION",
    "FILE_DELETION",
    "GRAPHQL_VULNERABILITIES",
    "INFORMATION_DISCLOSURE",
    "INSECURE_DESERIALIZATION",
    "INSECURE_DIRECT_OBJECT_REFERENCE",
    "JSON_WEB_TOKEN_VULNERABILITIES",
    "LOCAL_FILE_INCLUSION",
    "OTHER",
    "OUTBOUND_SERVICE_REQUEST",
    "PATH_TRAVERSAL",
    "PRIVILEGE_ESCALATION",
    "SERVER_SIDE_REQUEST_FORGERY",
    "SERVER_SIDE_TEMPLATE_INJECTION",
    "SQL_INJECTION",
    "UNKNOWN",
    "XML_EXTERNAL_ENTITY",
]
SecurityRequirementArtifactFormatType = Literal["DOC", "DOCX", "MD", "PDF", "TXT"]
SecurityRequirementPackImportStatusType = Literal["COMPLETED", "FAILED", "IN_PROGRESS", "PENDING"]
SecurityRequirementPackStatusType = Literal["DISABLED", "ENABLED"]
SkillTypeType = Literal["FINDING_PERSONALIZATION", "LOGIN_OPTIMIZATION"]
StepNameType = Literal["FINALIZING", "PENTEST", "PREFLIGHT", "STATIC_ANALYSIS", "VALIDATION"]
StepStatusType = Literal["COMPLETED", "FAILED", "IN_PROGRESS", "NOT_STARTED", "STOPPED"]
StrideCategoryType = Literal[
    "DENIAL_OF_SERVICE",
    "ELEVATION_OF_PRIVILEGE",
    "INFORMATION_DISCLOSURE",
    "REPUDIATION",
    "SPOOFING",
    "TAMPERING",
]
TargetDomainStatusType = Literal["FAILED", "PENDING", "UNREACHABLE", "VERIFIED"]
TaskExecutionStatusType = Literal["ABORTED", "COMPLETED", "FAILED", "INTERNAL_ERROR", "IN_PROGRESS"]
ThreatActorType = Literal["AGENT", "CUSTOMER"]
ThreatSeverityType = Literal["CRITICAL", "HIGH", "INFO", "LOW", "MEDIUM"]
ThreatStatusType = Literal["DISMISSED", "OPEN", "RESOLVED"]
UserRoleType = Literal["MEMBER"]
ValidationModeType = Literal["DISABLED", "SIMULATED"]
ValidationStatusType = Literal[
    "CONFIRMED", "NOT_REPRODUCED", "NOT_VALIDATED", "VALIDATING", "VALIDATION_FAILED"
]
SecurityAgentServiceName = Literal["securityagent"]
ServiceName = Literal[
    "accessanalyzer",
    "account",
    "acm",
    "acm-pca",
    "aiops",
    "amp",
    "amplify",
    "amplifybackend",
    "amplifyuibuilder",
    "apigateway",
    "apigatewaymanagementapi",
    "apigatewayv2",
    "appconfig",
    "appconfigdata",
    "appfabric",
    "appflow",
    "appintegrations",
    "application-autoscaling",
    "application-insights",
    "application-signals",
    "applicationcostprofiler",
    "appmesh",
    "apprunner",
    "appstream",
    "appsync",
    "arc-region-switch",
    "arc-zonal-shift",
    "artifact",
    "athena",
    "auditmanager",
    "autoscaling",
    "autoscaling-plans",
    "b2bi",
    "backup",
    "backup-gateway",
    "backupsearch",
    "batch",
    "bcm-dashboards",
    "bcm-data-exports",
    "bcm-pricing-calculator",
    "bcm-recommended-actions",
    "bedrock",
    "bedrock-agent",
    "bedrock-agent-runtime",
    "bedrock-agentcore",
    "bedrock-agentcore-control",
    "bedrock-data-automation",
    "bedrock-data-automation-runtime",
    "bedrock-runtime",
    "billing",
    "billingconductor",
    "braket",
    "budgets",
    "ce",
    "chatbot",
    "chime",
    "chime-sdk-identity",
    "chime-sdk-media-pipelines",
    "chime-sdk-meetings",
    "chime-sdk-messaging",
    "chime-sdk-voice",
    "cleanrooms",
    "cleanroomsml",
    "cloud9",
    "cloudcontrol",
    "clouddirectory",
    "cloudformation",
    "cloudfront",
    "cloudfront-keyvaluestore",
    "cloudhsm",
    "cloudhsmv2",
    "cloudsearch",
    "cloudsearchdomain",
    "cloudtrail",
    "cloudtrail-data",
    "cloudwatch",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codeconnections",
    "codedeploy",
    "codeguru-reviewer",
    "codeguru-security",
    "codeguruprofiler",
    "codepipeline",
    "codestar-connections",
    "codestar-notifications",
    "cognito-identity",
    "cognito-idp",
    "cognito-sync",
    "comprehend",
    "comprehendmedical",
    "compute-optimizer",
    "compute-optimizer-automation",
    "config",
    "connect",
    "connect-contact-lens",
    "connectcampaigns",
    "connectcampaignsv2",
    "connectcases",
    "connecthealth",
    "connectparticipant",
    "controlcatalog",
    "controltower",
    "cost-optimization-hub",
    "cur",
    "customer-profiles",
    "databrew",
    "dataexchange",
    "datapipeline",
    "datasync",
    "datazone",
    "dax",
    "deadline",
    "detective",
    "devicefarm",
    "devops-agent",
    "devops-guru",
    "directconnect",
    "discovery",
    "dlm",
    "dms",
    "docdb",
    "docdb-elastic",
    "drs",
    "ds",
    "ds-data",
    "dsql",
    "dynamodb",
    "dynamodbstreams",
    "ebs",
    "ec2",
    "ec2-instance-connect",
    "ecr",
    "ecr-public",
    "ecs",
    "efs",
    "eks",
    "eks-auth",
    "elasticache",
    "elasticbeanstalk",
    "elb",
    "elbv2",
    "elementalinference",
    "emr",
    "emr-containers",
    "emr-serverless",
    "entityresolution",
    "es",
    "events",
    "evs",
    "finspace",
    "finspace-data",
    "firehose",
    "fis",
    "fms",
    "forecast",
    "forecastquery",
    "frauddetector",
    "freetier",
    "fsx",
    "gamelift",
    "gameliftstreams",
    "geo-maps",
    "geo-places",
    "geo-routes",
    "glacier",
    "globalaccelerator",
    "glue",
    "grafana",
    "greengrass",
    "greengrassv2",
    "groundstation",
    "guardduty",
    "health",
    "healthlake",
    "iam",
    "identitystore",
    "imagebuilder",
    "importexport",
    "inspector",
    "inspector-scan",
    "inspector2",
    "interconnect",
    "internetmonitor",
    "invoicing",
    "iot",
    "iot-data",
    "iot-jobs-data",
    "iot-managed-integrations",
    "iotdeviceadvisor",
    "iotfleetwise",
    "iotsecuretunneling",
    "iotsitewise",
    "iotthingsgraph",
    "iottwinmaker",
    "iotwireless",
    "ivs",
    "ivs-realtime",
    "ivschat",
    "kafka",
    "kafkaconnect",
    "kendra",
    "kendra-ranking",
    "keyspaces",
    "keyspacesstreams",
    "kinesis",
    "kinesis-video-archived-media",
    "kinesis-video-media",
    "kinesis-video-signaling",
    "kinesis-video-webrtc-storage",
    "kinesisanalytics",
    "kinesisanalyticsv2",
    "kinesisvideo",
    "kms",
    "lakeformation",
    "lambda",
    "lambda-core",
    "lambda-microvms",
    "launch-wizard",
    "lex-models",
    "lex-runtime",
    "lexv2-models",
    "lexv2-runtime",
    "license-manager",
    "license-manager-linux-subscriptions",
    "license-manager-user-subscriptions",
    "lightsail",
    "location",
    "logs",
    "lookoutequipment",
    "m2",
    "machinelearning",
    "macie2",
    "mailmanager",
    "managedblockchain",
    "managedblockchain-query",
    "marketplace-agreement",
    "marketplace-catalog",
    "marketplace-deployment",
    "marketplace-discovery",
    "marketplace-entitlement",
    "marketplace-reporting",
    "marketplacecommerceanalytics",
    "mediaconnect",
    "mediaconvert",
    "medialive",
    "mediapackage",
    "mediapackage-vod",
    "mediapackagev2",
    "mediastore",
    "mediastore-data",
    "mediatailor",
    "medical-imaging",
    "memorydb",
    "meteringmarketplace",
    "mgh",
    "mgn",
    "migration-hub-refactor-spaces",
    "migrationhub-config",
    "migrationhuborchestrator",
    "migrationhubstrategy",
    "mpa",
    "mq",
    "mturk",
    "mwaa",
    "mwaa-serverless",
    "neptune",
    "neptune-graph",
    "neptunedata",
    "network-firewall",
    "networkflowmonitor",
    "networkmanager",
    "networkmonitor",
    "notifications",
    "notificationscontacts",
    "nova-act",
    "oam",
    "observabilityadmin",
    "odb",
    "omics",
    "opensearch",
    "opensearchserverless",
    "organizations",
    "osis",
    "outposts",
    "partnercentral-account",
    "partnercentral-benefits",
    "partnercentral-channel",
    "partnercentral-revenue-measurement",
    "partnercentral-selling",
    "payment-cryptography",
    "payment-cryptography-data",
    "pca-connector-ad",
    "pca-connector-scep",
    "pcs",
    "personalize",
    "personalize-events",
    "personalize-runtime",
    "pi",
    "pinpoint",
    "pinpoint-email",
    "pinpoint-sms-voice",
    "pinpoint-sms-voice-v2",
    "pipes",
    "polly",
    "pricing",
    "proton",
    "qapps",
    "qbusiness",
    "qconnect",
    "quicksight",
    "ram",
    "rbin",
    "rds",
    "rds-data",
    "redshift",
    "redshift-data",
    "redshift-serverless",
    "rekognition",
    "repostspace",
    "resiliencehub",
    "resiliencehubv2",
    "resource-explorer-2",
    "resource-groups",
    "resourcegroupstaggingapi",
    "rolesanywhere",
    "route53",
    "route53-recovery-cluster",
    "route53-recovery-control-config",
    "route53-recovery-readiness",
    "route53domains",
    "route53globalresolver",
    "route53profiles",
    "route53resolver",
    "rtbfabric",
    "rum",
    "s3",
    "s3control",
    "s3files",
    "s3outposts",
    "s3tables",
    "s3vectors",
    "sagemaker",
    "sagemaker-a2i-runtime",
    "sagemaker-edge",
    "sagemaker-featurestore-runtime",
    "sagemaker-geospatial",
    "sagemaker-metrics",
    "sagemaker-runtime",
    "sagemakerjobruntime",
    "savingsplans",
    "scheduler",
    "schemas",
    "sdb",
    "secretsmanager",
    "security-ir",
    "securityagent",
    "securityhub",
    "securitylake",
    "serverlessrepo",
    "service-quotas",
    "servicecatalog",
    "servicecatalog-appregistry",
    "servicediscovery",
    "ses",
    "sesv2",
    "shield",
    "signer",
    "signer-data",
    "signin",
    "simpledbv2",
    "snow-device-management",
    "snowball",
    "sns",
    "socialmessaging",
    "sqs",
    "ssm",
    "ssm-contacts",
    "ssm-guiconnect",
    "ssm-incidents",
    "ssm-quicksetup",
    "ssm-sap",
    "sso",
    "sso-admin",
    "sso-oidc",
    "stepfunctions",
    "storagegateway",
    "sts",
    "supplychain",
    "support",
    "support-app",
    "supportauthz",
    "sustainability",
    "swf",
    "synthetics",
    "taxsettings",
    "textract",
    "timestream-influxdb",
    "timestream-query",
    "timestream-write",
    "tnb",
    "transcribe",
    "transfer",
    "translate",
    "trustedadvisor",
    "uxc",
    "verifiedpermissions",
    "voice-id",
    "vpc-lattice",
    "waf",
    "waf-regional",
    "wafv2",
    "wellarchitected",
    "wickr",
    "wisdom",
    "workdocs",
    "workmail",
    "workmailmessageflow",
    "workspaces",
    "workspaces-instances",
    "workspaces-thin-client",
    "workspaces-web",
    "xray",
]
ResourceServiceName = Literal[
    "cloudformation", "cloudwatch", "dynamodb", "ec2", "glacier", "iam", "s3", "sns", "sqs"
]
PaginatorName = Literal[
    "list_agent_spaces",
    "list_applications",
    "list_artifacts",
    "list_code_review_job_tasks",
    "list_code_review_jobs_for_code_review",
    "list_code_reviews",
    "list_discovered_endpoints",
    "list_findings",
    "list_integrated_resources",
    "list_integrations",
    "list_memberships",
    "list_pentest_job_tasks",
    "list_pentest_jobs_for_pentest",
    "list_pentests",
    "list_private_connections",
    "list_security_requirement_packs",
    "list_security_requirements",
    "list_target_domains",
    "list_threat_model_job_tasks",
    "list_threat_model_jobs",
    "list_threat_models",
    "list_threats",
]
