[project]
name = "datadog-logger"
version = "1.0.3"
description = "Python logging handler for DataDog events"
authors = [{name = "uStudio Developers", email = "dev@ustudio.com"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.poetry]
requires-poetry = ">=2.4.1"
packages = [{include = "datadog_logger"}]

[tool.poetry.dependencies]
datadog = ">=0.52.2"

[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"
flake8 = "^7.3.0"
mypy = "^2.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
