import modal.client
import typing_extensions

class _ServerManager:
    def __init__(self, client: modal.client._Client):
        """Initialize self.  See help(type(self)) for accurate signature."""
        ...

    async def _start(self): ...
    async def stop(self): ...
    async def close(self): ...

class ServerManager:
    def __init__(self, client: modal.client.Client): ...

    class ___start_spec(typing_extensions.Protocol):
        def __call__(self, /): ...
        async def aio(self, /): ...

    _start: ___start_spec

    class __stop_spec(typing_extensions.Protocol):
        def __call__(self, /): ...
        async def aio(self, /): ...

    stop: __stop_spec

    class __close_spec(typing_extensions.Protocol):
        def __call__(self, /): ...
        async def aio(self, /): ...

    close: __close_spec

class __server_forward_spec(typing_extensions.Protocol):
    def __call__(self, /) -> ServerManager: ...
    async def aio(self, /) -> ServerManager: ...

server_forward: __server_forward_spec
