"""Live model evaluation with portable, uncertainty-aware evidence."""

from .core import (
    SCHEMA_VERSION,
    Arena,
    BradleyTerryStanding,
    Contestant,
    Match,
    Result,
    Standing,
    expected_score,
    round_robin,
)
from .errors import (
    JudgeParseError,
    LocalArenaError,
    ProviderAuthError,
    ProviderConfigurationError,
    ProviderConnectionError,
    ProviderError,
    ProviderRateLimitError,
    ProviderResponseError,
    ProviderTimeoutError,
)
from .evaluation import (
    RUN_SCHEMA_VERSION,
    EvaluationRecord,
    EvaluationRun,
    EvaluationRunner,
    ModelJudge,
    ModelTarget,
    generation_from_dict,
    run_from_dict,
)
from .generation import (
    ChatMessage,
    GenerationRequest,
    GenerationResult,
    ModelInfo,
    TokenUsage,
)
from .providers import (
    GenerationProvider,
    ModelProvider,
    OpenAICompatibleProvider,
    Provider,
    RequestPolicy,
    create_provider,
    provider_names,
)
from .report import render_html_report, write_html_report
from .tasks import (
    ChoiceMatch,
    Contains,
    Evaluator,
    ExactMatch,
    ExtractMatch,
    JsonMatch,
    NumericMatch,
    PromptTask,
    RegexMatch,
    Score,
    TextMatch,
    TokenF1,
    evaluator_from_config,
)
from .taskpacks import (
    TASK_PACK_SCHEMA_VERSION,
    TaskPack,
    load_task_pack,
    parse_task_pack,
    task_pack_digest,
)

__all__ = [
    "SCHEMA_VERSION",
    "RUN_SCHEMA_VERSION",
    "Arena",
    "BradleyTerryStanding",
    "ChatMessage",
    "ChoiceMatch",
    "Contestant",
    "Contains",
    "EvaluationRecord",
    "EvaluationRun",
    "EvaluationRunner",
    "Evaluator",
    "ExactMatch",
    "ExtractMatch",
    "GenerationProvider",
    "GenerationRequest",
    "GenerationResult",
    "JsonMatch",
    "JudgeParseError",
    "LocalArenaError",
    "Match",
    "ModelInfo",
    "ModelJudge",
    "ModelProvider",
    "ModelTarget",
    "NumericMatch",
    "OpenAICompatibleProvider",
    "PromptTask",
    "Provider",
    "ProviderAuthError",
    "ProviderConfigurationError",
    "ProviderConnectionError",
    "ProviderError",
    "ProviderRateLimitError",
    "ProviderResponseError",
    "ProviderTimeoutError",
    "RegexMatch",
    "RequestPolicy",
    "Result",
    "Score",
    "Standing",
    "TASK_PACK_SCHEMA_VERSION",
    "TaskPack",
    "TextMatch",
    "TokenF1",
    "TokenUsage",
    "create_provider",
    "evaluator_from_config",
    "expected_score",
    "generation_from_dict",
    "load_task_pack",
    "parse_task_pack",
    "provider_names",
    "render_html_report",
    "round_robin",
    "run_from_dict",
    "task_pack_digest",
    "write_html_report",
]

__version__ = "0.4.0"
