[build-system]
requires = ["meson-python", "ninja", "numpy>=2.0"]
build-backend = "mesonpy"

[project]
name = "mi_proyecto_joaquin_vft"
dynamic = ["version"]
authors = [
  { name = "Joaquin Lopez" },
]
description = "Software in Fortran with f2py interface"
readme = "readme.md"
license = {text = "GPL-3.0"}
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Fortran",
]

dependencies = ["numpy"]

[tool.meson-python.args]
# Esto asegura que los argumentos se pasen correctamente durante la compilación
setup = []

[project.optional-dependencies]

