"""nx_oauth_endpoints.py — GENERATED real OAuth2 endpoints (verified sweep).
Each entry: a provider's actual authorize/token endpoints so NX opens the
real login + completes the loopback exchange. Regenerate from the sweep."""

OAUTH_ENDPOINTS = {
    "Airtable": {
        "authorize": "https://airtable.com/oauth2/v1/authorize",
        "token": "https://airtable.com/oauth2/v1/token",
        "scopes": ["data.records:read", "data.records:write", "schema.bases:read", "schema.bases:write", "user.email:read"],
        "pkce": True,
    },
    "Asana": {
        "authorize": "https://app.asana.com/-/oauth_authorize",
        "token": "https://app.asana.com/-/oauth_token",
        "scopes": ["default", "openid", "email", "profile"],
        "pkce": False,
    },
    "Atlassian Confluence": {
        "authorize": "https://auth.atlassian.com/authorize",
        "token": "https://auth.atlassian.com/oauth/token",
        "scopes": ["read:confluence-content.all", "write:confluence-content", "read:confluence-space.summary", "offline_access"],
        "pkce": False,
    },
    "Atlassian Jira": {
        "authorize": "https://auth.atlassian.com/authorize",
        "token": "https://auth.atlassian.com/oauth/token",
        "scopes": ["read:jira-work", "write:jira-work", "read:jira-user", "manage:jira-project", "offline_access"],
        "pkce": False,
    },
    "Calendly": {
        "authorize": "https://auth.calendly.com/oauth/authorize",
        "token": "https://auth.calendly.com/oauth/token",
        "scopes": ["default"],
        "pkce": False,
    },
    "Canva": {
        "authorize": "https://www.canva.com/api/oauth/authorize",
        "token": "https://api.canva.com/rest/v1/oauth/token",
        "scopes": ["design:content:read", "design:content:write", "design:meta:read", "asset:read", "asset:write", "profile:read"],
        "pkce": True,
    },
    "Clio": {
        "authorize": "https://app.clio.com/oauth/authorize",
        "token": "https://app.clio.com/oauth/token",
        "scopes": ["all"],
        "pkce": False,
    },
    "Confluence": {
        "authorize": "https://auth.atlassian.com/authorize",
        "token": "https://auth.atlassian.com/oauth/token",
        "scopes": ["read:confluence-content.all", "write:confluence-content", "read:confluence-space.summary", "search:confluence", "read:me", "offline_access"],
        "pkce": False,
    },
    "DocuSign": {
        "authorize": "https://account.docusign.com/oauth/auth",
        "token": "https://account.docusign.com/oauth/token",
        "scopes": ["signature", "extended", "impersonation"],
        "pkce": True,
    },
    "Figma": {
        "authorize": "https://www.figma.com/oauth",
        "token": "https://api.figma.com/v1/oauth/token",
        "scopes": ["file_read", "files:read", "file_variables:read", "file_comments:write", "current_user:read"],
        "pkce": False,
    },
    "Figshare": {
        "authorize": "https://figshare.com/account/applications/authorize",
        "token": "https://api.figshare.com/v2/token",
        "scopes": ["all"],
        "pkce": False,
    },
    "GitHub": {
        "authorize": "https://github.com/login/oauth/authorize",
        "token": "https://github.com/login/oauth/access_token",
        "scopes": ["repo", "read:org", "user", "gist", "workflow"],
        "pkce": False,
    },
    "GitLab": {
        "authorize": "https://gitlab.com/oauth/authorize",
        "token": "https://gitlab.com/oauth/token",
        "scopes": ["api", "read_api", "read_user", "read_repository", "write_repository", "openid", "profile", "email"],
        "pkce": True,
    },
    "Gmail": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/gmail.readonly", "https://www.googleapis.com/auth/gmail.send", "https://www.googleapis.com/auth/gmail.modify", "https://mail.google.com/", "openid", "email", "profile"],
        "pkce": True,
    },
    "Gong": {
        "authorize": "https://app.gong.io/oauth2/authorize",
        "token": "https://app.gong.io/oauth2/generate-customer-token",
        "scopes": ["api:calls:read:basic", "api:calls:read:extensive", "api:users:read", "api:stats:user-actions"],
        "pkce": False,
    },
    "Google Ads": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/adwords"],
        "pkce": False,
    },
    "Google Analytics 4": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/analytics.readonly", "https://www.googleapis.com/auth/analytics"],
        "pkce": False,
    },
    "Google Calendar": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/calendar", "https://www.googleapis.com/auth/calendar.readonly", "https://www.googleapis.com/auth/calendar.events"],
        "pkce": False,
    },
    "Google Drive": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/drive", "https://www.googleapis.com/auth/drive.file", "https://www.googleapis.com/auth/drive.readonly"],
        "pkce": False,
    },
    "Google Search Console": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/webmasters.readonly", "https://www.googleapis.com/auth/webmasters"],
        "pkce": False,
    },
    "Google Workspace": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["openid", "email", "profile", "https://www.googleapis.com/auth/userinfo.email"],
        "pkce": False,
    },
    "Google Workspace (Docs/Sheets/Slides)": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/documents", "https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/presentations", "https://www.googleapis.com/auth/drive.file"],
        "pkce": False,
    },
    "Google Workspace (Gmail & Calendar)": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/gmail.readonly", "https://www.googleapis.com/auth/gmail.modify", "https://mail.google.com/", "https://www.googleapis.com/auth/calendar", "https://www.googleapis.com/auth/calendar.events"],
        "pkce": False,
    },
    "Google Workspace (Gmail, Docs, Sheets, Drive)": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/gmail.modify", "https://www.googleapis.com/auth/documents", "https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive", "openid", "email", "profile"],
        "pkce": True,
    },
    "Google Workspace (Gmail, Drive, Docs, Calendar)": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/gmail.modify", "https://www.googleapis.com/auth/drive", "https://www.googleapis.com/auth/documents", "https://www.googleapis.com/auth/calendar", "openid", "email", "profile"],
        "pkce": True,
    },
    "Gusto": {
        "authorize": "https://api.gusto.com/oauth/authorize",
        "token": "https://api.gusto.com/oauth/token",
        "scopes": [],
        "pkce": True,
    },
    "HubSpot": {
        "authorize": "https://app.hubspot.com/oauth/authorize",
        "token": "https://api.hubapi.com/oauth/v1/token",
        "scopes": ["crm.objects.contacts.read", "crm.objects.contacts.write", "crm.objects.deals.read", "crm.objects.companies.read", "oauth"],
        "pkce": False,
    },
    "Indeed": {
        "authorize": "https://secure.indeed.com/oauth/v2/authorize",
        "token": "https://apis.indeed.com/oauth/v2/tokens",
        "scopes": ["email", "offline_access"],
        "pkce": False,
    },
    "Intercom": {
        "authorize": "https://app.intercom.com/oauth",
        "token": "https://api.intercom.io/auth/eagle/token",
        "scopes": [],
        "pkce": False,
    },
    "Jira": {
        "authorize": "https://auth.atlassian.com/authorize",
        "token": "https://auth.atlassian.com/oauth/token",
        "scopes": ["read:jira-work", "write:jira-work", "read:jira-user", "offline_access"],
        "pkce": True,
    },
    "Lever": {
        "authorize": "https://auth.lever.co/authorize",
        "token": "https://auth.lever.co/oauth/token",
        "scopes": ["applications:read:admin", "opportunities:read:admin", "postings:read:admin", "offline_access"],
        "pkce": False,
    },
    "Linear": {
        "authorize": "https://linear.app/oauth/authorize",
        "token": "https://api.linear.app/oauth/token",
        "scopes": ["read", "write", "issues:create", "comments:create"],
        "pkce": False,
    },
    "LinkedIn": {
        "authorize": "https://www.linkedin.com/oauth/v2/authorization",
        "token": "https://www.linkedin.com/oauth/v2/accessToken",
        "scopes": ["openid", "profile", "email", "w_member_social", "r_liteprofile", "r_emailaddress"],
        "pkce": False,
    },
    "LinkedIn Marketing (Lead Gen Forms)": {
        "authorize": "https://www.linkedin.com/oauth/v2/authorization",
        "token": "https://www.linkedin.com/oauth/v2/accessToken",
        "scopes": ["r_marketing_leadgen_automation", "rw_ads", "r_ads", "r_ads_reporting", "r_organization_admin"],
        "pkce": False,
    },
    "LinkedIn Marketing API": {
        "authorize": "https://www.linkedin.com/oauth/v2/authorization",
        "token": "https://www.linkedin.com/oauth/v2/accessToken",
        "scopes": ["rw_ads", "r_ads", "r_ads_reporting", "rw_organization_admin", "r_organization_social", "w_organization_social"],
        "pkce": False,
    },
    "Mailchimp": {
        "authorize": "https://login.mailchimp.com/oauth2/authorize",
        "token": "https://login.mailchimp.com/oauth2/token",
        "scopes": [],
        "pkce": False,
    },
    "Meta (Facebook & Instagram) Graph/Marketing API": {
        "authorize": "https://www.facebook.com/v23.0/dialog/oauth",
        "token": "https://graph.facebook.com/v23.0/oauth/access_token",
        "scopes": ["public_profile", "email", "ads_management", "ads_read", "business_management", "pages_show_list", "instagram_basic"],
        "pkce": False,
    },
    "Meta (Facebook & Instagram) Marketing": {
        "authorize": "https://www.facebook.com/v23.0/dialog/oauth",
        "token": "https://graph.facebook.com/v23.0/oauth/access_token",
        "scopes": ["ads_management", "ads_read", "business_management", "pages_show_list", "instagram_basic", "instagram_manage_insights"],
        "pkce": False,
    },
    "Meta (Facebook/Instagram)": {
        "authorize": "https://www.facebook.com/v23.0/dialog/oauth",
        "token": "https://graph.facebook.com/v23.0/oauth/access_token",
        "scopes": ["public_profile", "email", "pages_show_list", "instagram_basic"],
        "pkce": False,
    },
    "Meta (Facebook/Instagram) Ads": {
        "authorize": "https://www.facebook.com/v23.0/dialog/oauth",
        "token": "https://graph.facebook.com/v23.0/oauth/access_token",
        "scopes": ["ads_management", "ads_read", "business_management"],
        "pkce": False,
    },
    "Meta (Facebook/Instagram) Lead Ads": {
        "authorize": "https://www.facebook.com/v23.0/dialog/oauth",
        "token": "https://graph.facebook.com/v23.0/oauth/access_token",
        "scopes": ["leads_retrieval", "pages_manage_ads", "pages_read_engagement", "pages_show_list", "ads_management", "business_management"],
        "pkce": False,
    },
    "Microsoft Word (Microsoft 365 / Graph)": {
        "authorize": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "token": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
        "scopes": ["openid", "profile", "offline_access", "Files.ReadWrite", "Files.ReadWrite.All", "Sites.ReadWrite.All", "User.Read"],
        "pkce": True,
    },
    "NetSuite": {
        "authorize": "https://system.netsuite.com/app/login/oauth2/authorize.nl",
        "token": "https://<ACCOUNT_ID>.suitetalk.api.netsuite.com/services/rest/auth/oauth2/v1/token",
        "scopes": ["rest_webservices", "restlets", "suite_analytics"],
        "pkce": True,
    },
    "Notion": {
        "authorize": "https://api.notion.com/v1/oauth/authorize",
        "token": "https://api.notion.com/v1/oauth/token",
        "scopes": [],
        "pkce": False,
    },
    "ORCID": {
        "authorize": "https://orcid.org/oauth/authorize",
        "token": "https://orcid.org/oauth/token",
        "scopes": ["/authenticate", "/read-limited", "/activities/update", "/person/update", "openid"],
        "pkce": False,
    },
    "Okta": {
        "authorize": "https://<YOUR_OKTA_DOMAIN>/oauth2/v1/authorize",
        "token": "https://<YOUR_OKTA_DOMAIN>/oauth2/v1/token",
        "scopes": ["openid", "profile", "email", "offline_access"],
        "pkce": True,
    },
    "PagerDuty": {
        "authorize": "https://identity.pagerduty.com/oauth/authorize",
        "token": "https://identity.pagerduty.com/oauth/token",
        "scopes": ["openid", "read", "write", "offline_access"],
        "pkce": True,
    },
    "QuickBooks Online": {
        "authorize": "https://appcenter.intuit.com/connect/oauth2",
        "token": "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
        "scopes": ["com.intuit.quickbooks.accounting", "com.intuit.quickbooks.payment", "openid", "profile", "email", "phone", "address"],
        "pkce": False,
    },
    "Salesforce": {
        "authorize": "https://login.salesforce.com/services/oauth2/authorize",
        "token": "https://login.salesforce.com/services/oauth2/token",
        "scopes": ["api", "refresh_token", "openid", "offline_access", "full"],
        "pkce": True,
    },
    "Sentry": {
        "authorize": "https://sentry.io/oauth/authorize/",
        "token": "https://sentry.io/oauth/token/",
        "scopes": ["org:read", "project:read", "project:write", "event:read", "member:read", "team:read"],
        "pkce": False,
    },
    "Slack": {
        "authorize": "https://slack.com/oauth/v2/authorize",
        "token": "https://slack.com/api/oauth.v2.access",
        "scopes": ["channels:read", "chat:write", "users:read", "team:read", "channels:history"],
        "pkce": False,
    },
    "Vanta": {
        "authorize": "https://app.vanta.com/oauth/authorize",
        "token": "https://api.vanta.com/oauth/token",
        "scopes": ["connectors.self:read-resource", "connectors.self:write-resource"],
        "pkce": False,
    },
    "X (Twitter)": {
        "authorize": "https://twitter.com/i/oauth2/authorize",
        "token": "https://api.twitter.com/2/oauth2/token",
        "scopes": ["tweet.read", "tweet.write", "users.read", "offline.access", "follows.read", "follows.write", "like.read", "like.write"],
        "pkce": True,
    },
    "X (Twitter) API": {
        "authorize": "https://twitter.com/i/oauth2/authorize",
        "token": "https://api.twitter.com/2/oauth2/token",
        "scopes": ["tweet.read", "tweet.write", "users.read", "offline.access", "follows.read", "like.read"],
        "pkce": True,
    },
    "Xero": {
        "authorize": "https://login.xero.com/identity/connect/authorize",
        "token": "https://identity.xero.com/connect/token",
        "scopes": ["openid", "profile", "email", "offline_access", "accounting.transactions", "accounting.contacts", "accounting.settings"],
        "pkce": True,
    },
    "YouTube": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/youtube", "https://www.googleapis.com/auth/youtube.readonly", "https://www.googleapis.com/auth/youtube.upload", "https://www.googleapis.com/auth/youtube.force-ssl"],
        "pkce": True,
    },
    "YouTube Data API": {
        "authorize": "https://accounts.google.com/o/oauth2/v2/auth",
        "token": "https://oauth2.googleapis.com/token",
        "scopes": ["https://www.googleapis.com/auth/youtube.readonly", "https://www.googleapis.com/auth/youtube", "https://www.googleapis.com/auth/youtube.upload", "https://www.googleapis.com/auth/youtube.force-ssl", "https://www.googleapis.com/auth/youtubepartner"],
        "pkce": True,
    },
    "Zendesk": {
        "authorize": "https://{subdomain}.zendesk.com/oauth/authorizations/new",
        "token": "https://{subdomain}.zendesk.com/oauth/tokens",
        "scopes": ["read", "write", "tickets:read", "tickets:write", "users:read", "users:write", "hc:read", "hc:write"],
        "pkce": False,
    },
    "Zendesk Guide / Help Center": {
        "authorize": "https://{subdomain}.zendesk.com/oauth/authorizations/new",
        "token": "https://{subdomain}.zendesk.com/oauth/tokens",
        "scopes": ["hc:read", "hc:write", "read", "write"],
        "pkce": False,
    },
    # ── Proven live against real provider logins with real test app credentials
    #    (nx-credential-prooftest, 2026-06-23). Each reached the provider's actual
    #    consent/login page with the NX loopback redirect. Added so operators can
    #    connect them. Snowflake omitted: its authorize host is per-account.
    "Discord": {
        "authorize": "https://discord.com/oauth2/authorize",
        "token": "https://discord.com/api/oauth2/token",
        "scopes": ["identify", "email", "guilds"],
        "pkce": False,
    },
    "Zoom": {
        "authorize": "https://zoom.us/oauth/authorize",
        "token": "https://zoom.us/oauth/token",
        "scopes": ["user:read", "meeting:read", "meeting:write"],
        "pkce": False,
    },
    "Dropbox": {
        "authorize": "https://www.dropbox.com/oauth2/authorize",
        "token": "https://api.dropboxapi.com/oauth2/token",
        "scopes": ["files.metadata.read", "files.content.read", "files.content.write"],
        "pkce": False,
    },
    "Box": {
        "authorize": "https://account.box.com/api/oauth2/authorize",
        "token": "https://api.box.com/oauth2/token",
        "scopes": ["root_readwrite"],
        "pkce": False,
    },
    "Snapchat": {
        "authorize": "https://accounts.snapchat.com/login/oauth2/authorize",
        "token": "https://accounts.snapchat.com/login/oauth2/access_token",
        "scopes": ["https://auth.snapchat.com/oauth2/api/user.display_name"],
        "pkce": False,
    },
    "TikTok": {
        # TikTok's authorize uses `client_key`, not `client_id`; verified the
        # login page is reached with the loopback redirect.
        "authorize": "https://www.tiktok.com/v2/auth/authorize/",
        "token": "https://open.tiktokapis.com/v2/oauth/token/",
        "scopes": ["user.info.basic"],
        "pkce": True,
    },
    "Zoho Desk": {
        "authorize": "https://accounts.zoho.com/oauth/v2/auth",
        "token": "https://accounts.zoho.com/oauth/v2/token",
        "scopes": ["Desk.tickets.READ", "Desk.contacts.READ"],
        "pkce": False,
    },
    "Grafana": {
        "authorize": "https://grafana.com/oauth2/authorize",
        "token": "https://grafana.com/api/oauth2/token",
        "scopes": ["profile", "email"],
        "pkce": False,
    },
    "QuickBooks": {
        "authorize": "https://appcenter.intuit.com/connect/oauth2",
        "token": "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
        "scopes": ["com.intuit.quickbooks.accounting"],
        "pkce": False,
    },
    "Pipedrive": {
        "authorize": "https://oauth.pipedrive.com/oauth/authorize",
        "token": "https://oauth.pipedrive.com/oauth/token",
        "scopes": ["deals:read", "contacts:read"],
        "pkce": False,
    },
}
