# flake8: noqa
from ._version import __version__
from .client import Client
from .context import Context
from .enums import (
    AUTOPILOT_MODE,
    KeyValueCategory,
    KeyValueEntityType,
    KeyValueType,
    NETWORK_EGRESS_POLICY,
    PredictionEnvironmentPlatform,
    QUEUE_STATUS,
    SCORING_TYPE,
    SNAPSHOT_POLICY,
    TARGET_TYPE,
    VERBOSITY_LEVEL,
)
from .errors import AppPlatformError
from .helpers import *
from .models import (
    Application,
    AutomatedDocument,
    CustomApplication,
    CustomApplicationSource,
    BatchMonitoringJob,
    BatchMonitoringJobDefinition,
    BatchPredictionJob,
    BatchPredictionJobDefinition,
    BlenderModel,
    Blueprint,
    BlueprintChart,
    BlueprintTaskDocument,
    CalendarFile,
    Cluster,
    ClusteringModel,
    ClusterInsight,
    CombinedModel,
    ComplianceDocTemplate,
    Connector,
    Credential,
    CustomInferenceModel,
    CustomModelTest,
    CustomModelVersion,
    CustomModelVersionDependencyBuild,
    CustomTask,
    CustomTaskVersion,
    CustomTemplate,
    DataDriver,
    DataEngineQueryGenerator,
    Dataset,
    DatasetDetails,
    DatasetFeature,
    DatasetFeatureHistogram,
    DatasetFeaturelist,
    DataSlice,
    DataSliceSizeInfo,
    DataSource,
    DataSourceParameters,
    DataStore,
    DatetimeModel,
    Deployment,
    ExecutionEnvironment,
    ExecutionEnvironmentVersion,
    ExternalConfusionChart,
    ExternalLiftChart,
    ExternalMulticlassLiftChart,
    ExternalResidualsChart,
    ExternalRocCurve,
    ExternalScores,
    Event,
    Feature,
    FeatureAssociationFeaturelists,
    FeatureAssociationMatrix,
    FeatureAssociationMatrixDetails,
    FeatureHistogram,
    FeatureImpactJob,
    FeatureLineage,
    Featurelist,
    Files,
    FilesCatalogSearch,
    FilesDetails,
    FrozenModel,
    genai,
    InteractionFeature,
    Job,
    KeyValue,
    MemorySpace,
    Model,
    ModelBlueprintChart,
    ModelingFeature,
    ModelingFeaturelist,
    ModelJob,
    ModelRecommendation,
    OCREngineSpecificParameters,
    OCRJobDatasetLanguage,
    OCRJobResource,
    OCRJobStatusEnum,
    PayoffMatrix,
    PredictionDataset,
    PredictionEnvironment,
    PredictionExplanations,
    PredictionExplanationsInitialization,
    Predictions,
    PredictionServer,
    PredictJob,
    PrimeFile,
    PrimeModel,
    Project,
    RatingTable,
    RatingTableModel,
    Recipe,
    RegisteredModel,
    RegisteredModelVersion,
    registry,
    RelationshipsConfiguration,
    Ruleset,
    SecondaryDatasetConfigurations,
    SegmentationTask,
    SegmentInfo,
    Session,
    ShapImpact,
    ShapMatrix,
    ShapMatrixJob,
    SharingAccess,
    SharingRole,
    StartOCRJobResponse,
    TrainingPredictions,
    TrainingPredictionsJob,
    UseCase,
    UserBlueprint,
    JdbcPreview,
    JdbcPreviewData,
    JdbcResultSchemaEntry,
)

DR_TRACKABLE = True

# Pipelines surface -- available only when [pipelines] is installed (or when the
# weekly wheel ships the vendored covalent / covalent-cloud under datarobot/_vendor/).
# Importing datarobot._vendor runs the path-shim that prepends the vendored
# packages to sys.path so the subsequent `import covalent` resolves to the
# bundled copy. On a base install without the [pipelines] extra and without a
# populated _vendor/ dir, this is effectively a no-op.
# If covalent still isn't importable the whole block is skipped and
# `import datarobot` still works.
try:
    # Side-effect import: prepends datarobot/_vendor/ to sys.path so the
    # subsequent `import covalent` (inside the pipelines package) resolves
    # to the bundled copy when the wheel ships it. Using `from ... import`
    # avoids leaking the top-level `datarobot` name into our own namespace
    # (which would otherwise break the dir(dr) inventory test).
    from datarobot import _vendor  # noqa: F401

    from datarobot._experimental.pipelines import (  # noqa: E402
        task as task,
        pipeline as pipeline,
        wait as wait,
        get_context as get_context,
        dispatch as dispatch,
        dispatch_sync as dispatch_sync,
        get_result as get_result,
        executor as executor,
        fs as fs,
        fs_strategies as fs_strategies,
        DepsBash as DepsBash,
        DepsCall as DepsCall,
        DepsModule as DepsModule,
        DepsPip as DepsPip,
        CloudExecutor as CloudExecutor,
        PipelineTaskExecutor as PipelineTaskExecutor,
        Pipeline as Pipeline,
        PipelineVersion as PipelineVersion,
        PipelineTask as PipelineTask,
        TaskParameter as TaskParameter,
        PipelineDispatch as PipelineDispatch,
        PipelineInput as PipelineInput,
        PipelineSchedule as PipelineSchedule,
        PipelineImage as PipelineImage,
        PipelineImageVersion as PipelineImageVersion,
        PipelineTaskExecution as PipelineTaskExecution,
        PipelineMode as PipelineMode,
        PipelineVersionStatus as PipelineVersionStatus,
        PipelineDispatchStatus as PipelineDispatchStatus,
        PipelineDispatchTrigger as PipelineDispatchTrigger,
        PipelineInputState as PipelineInputState,
        PipelineScheduleStatus as PipelineScheduleStatus,
        PipelineImageStatus as PipelineImageStatus,
        TaskExecutionStatus as TaskExecutionStatus,
        Pipelines as Pipelines,
    )
except ImportError:
    pass
