# coding: utf-8

"""
    Seeq REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 66.175.0-v202608061153-CD
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
from six import iteritems
import re


class BoardOutputListV1(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'boards': 'list[BoardOutputV1]'
    }

    attribute_map = {
        'boards': 'boards'
    }

    def __init__(self, boards=None):
        """
        BoardOutputListV1 - a model defined in Swagger
        """

        self._boards = None

        if boards is not None:
          self.boards = boards

    @property
    def boards(self):
        """
        Gets the boards of this BoardOutputListV1.
        The list of boards

        :return: The boards of this BoardOutputListV1.
        :rtype: list[BoardOutputV1]
        """
        return self._boards

    @boards.setter
    def boards(self, boards):
        """
        Sets the boards of this BoardOutputListV1.
        The list of boards

        :param boards: The boards of this BoardOutputListV1.
        :type: list[BoardOutputV1]
        """
        if boards is None:
            raise ValueError("Invalid value for `boards`, must not be `None`")

        self._boards = boards

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, BoardOutputListV1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
