# coding: utf-8

"""
    Seeq REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 66.190.0-v202609031147-CD
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import annotations

from typing import Any, ClassVar, Dict, List, Optional, Set, TYPE_CHECKING

if TYPE_CHECKING:
    from . import *  # noqa: F401,F403


class ColumnRuleDescendantInputV1(object):
    swagger_types: ClassVar[Dict[str, str]] = ...
    attribute_map: ClassVar[Dict[str, str]] = ...

    _column_index: int
    _item_type: Optional[str]
    _level: Optional[int]
    _property_match_operator: str
    _property_name: str
    _property_value: str


    def __init__(
        self,
        column_index: Optional[int] = None,
        item_type: Optional[str] = None,
        level: Optional[int] = None,
        property_match_operator: Optional[str] = None,
        property_name: Optional[str] = None,
        property_value: Optional[str] = None,
    ) -> None: ...

    @property
    def column_index(self) -> int: ...

    @column_index.setter
    def column_index(self, column_index: int) -> None: ...

    @property
    def item_type(self) -> Optional[str]: ...

    @item_type.setter
    def item_type(self, item_type: Optional[str]) -> None: ...

    @property
    def level(self) -> Optional[int]: ...

    @level.setter
    def level(self, level: Optional[int]) -> None: ...

    @property
    def property_match_operator(self) -> str: ...

    @property_match_operator.setter
    def property_match_operator(self, property_match_operator: str) -> None: ...

    @property
    def property_name(self) -> str: ...

    @property_name.setter
    def property_name(self, property_name: str) -> None: ...

    @property
    def property_value(self) -> str: ...

    @property_value.setter
    def property_value(self, property_value: str) -> None: ...

    def to_dict(self) -> Dict[str, Any]: ...
    def to_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
