# coding: utf-8

"""
    Seeq REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 66.189.0-v202609020455-CD
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import annotations

from typing import Any, ClassVar, Dict, List, Optional, Set, TYPE_CHECKING

if TYPE_CHECKING:
    from . import *  # noqa: F401,F403


class ContextConditionOutputListV1(object):
    swagger_types: ClassVar[Dict[str, str]] = ...
    attribute_map: ClassVar[Dict[str, str]] = ...

    _context_conditions: Optional[List[ContextConditionOutputV1]]


    def __init__(
        self,
        context_conditions: Optional[List[ContextConditionOutputV1]] = None,
    ) -> None: ...

    @property
    def context_conditions(self) -> Optional[List[ContextConditionOutputV1]]: ...

    @context_conditions.setter
    def context_conditions(self, context_conditions: Optional[List[ContextConditionOutputV1]]) -> None: ...

    def to_dict(self) -> Dict[str, Any]: ...
    def to_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
