# coding: utf-8

"""
    Seeq REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 66.125.2-v202604161027-CD
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import annotations

from typing import Any, ClassVar, Dict, List, Optional, Set, TYPE_CHECKING

if TYPE_CHECKING:
    from . import *  # noqa: F401,F403


class GetAllContextInputV1(object):
    swagger_types: ClassVar[Dict[str, str]] = ...
    attribute_map: ClassVar[Dict[str, str]] = ...

    _comment_filter: Optional[Filter]
    _ids: List[ContextIdInputV1]
    _label_filter: Optional[Filter]
    _numeric_filter: Optional[Filter]
    _opaque_filter: Optional[Filter]


    def __init__(
        self,
        comment_filter: Optional[Filter] = None,
        ids: Optional[List[ContextIdInputV1]] = None,
        label_filter: Optional[Filter] = None,
        numeric_filter: Optional[Filter] = None,
        opaque_filter: Optional[Filter] = None,
    ) -> None: ...

    @property
    def comment_filter(self) -> Optional[Filter]: ...

    @comment_filter.setter
    def comment_filter(self, comment_filter: Optional[Filter]) -> None: ...

    @property
    def ids(self) -> List[ContextIdInputV1]: ...

    @ids.setter
    def ids(self, ids: List[ContextIdInputV1]) -> None: ...

    @property
    def label_filter(self) -> Optional[Filter]: ...

    @label_filter.setter
    def label_filter(self, label_filter: Optional[Filter]) -> None: ...

    @property
    def numeric_filter(self) -> Optional[Filter]: ...

    @numeric_filter.setter
    def numeric_filter(self, numeric_filter: Optional[Filter]) -> None: ...

    @property
    def opaque_filter(self) -> Optional[Filter]: ...

    @opaque_filter.setter
    def opaque_filter(self, opaque_filter: Optional[Filter]) -> None: ...

    def to_dict(self) -> Dict[str, Any]: ...
    def to_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
