# coding: utf-8

"""
    Seeq REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 66.146.0-v202605220817-CD
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import annotations

from typing import Any, ClassVar, Dict, List, Optional, Set, TYPE_CHECKING

if TYPE_CHECKING:
    from . import *  # noqa: F401,F403


class ScalingTableUUIDColumnSearchV1(object):
    swagger_types: ClassVar[Dict[str, str]] = ...
    attribute_map: ClassVar[Dict[str, str]] = ...

    _column_definition_id: str
    _is_include: bool
    _row_ids: Optional[List[str]]
    _search_order: Optional[int]
    _search_type: str
    _table_definition_id: str
    _types: Optional[List[str]]


    def __init__(
        self,
        column_definition_id: Optional[str] = None,
        is_include: Optional[bool] = None,
        row_ids: Optional[List[str]] = None,
        search_order: Optional[int] = None,
        search_type: Optional[str] = None,
        table_definition_id: Optional[str] = None,
        types: Optional[List[str]] = None,
    ) -> None: ...

    @property
    def column_definition_id(self) -> str: ...

    @column_definition_id.setter
    def column_definition_id(self, column_definition_id: str) -> None: ...

    @property
    def is_include(self) -> bool: ...

    @is_include.setter
    def is_include(self, is_include: bool) -> None: ...

    @property
    def row_ids(self) -> Optional[List[str]]: ...

    @row_ids.setter
    def row_ids(self, row_ids: Optional[List[str]]) -> None: ...

    @property
    def search_order(self) -> Optional[int]: ...

    @search_order.setter
    def search_order(self, search_order: Optional[int]) -> None: ...

    @property
    def search_type(self) -> str: ...

    @search_type.setter
    def search_type(self, search_type: str) -> None: ...

    @property
    def table_definition_id(self) -> str: ...

    @table_definition_id.setter
    def table_definition_id(self, table_definition_id: str) -> None: ...

    @property
    def types(self) -> Optional[List[str]]: ...

    @types.setter
    def types(self, types: Optional[List[str]]) -> None: ...

    def to_dict(self) -> Dict[str, Any]: ...
    def to_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
