# coding: utf-8

"""
    Seeq REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 66.202.1-v202609241214-CD
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import annotations

from typing import Any, ClassVar, Dict, List, Optional, Set, TYPE_CHECKING

if TYPE_CHECKING:
    from . import *  # noqa: F401,F403


class StatsSummaryComparisonDataOutputV1(object):
    swagger_types: ClassVar[Dict[str, str]] = ...
    attribute_map: ClassVar[Dict[str, str]] = ...

    _fstatistic: Optional[float]
    _mean_difference: Optional[float]
    _mean_p_value: Optional[float]
    _std_dev_difference: Optional[float]
    _tstatistic: Optional[float]
    _variance_p_value: Optional[float]


    def __init__(
        self,
        fstatistic: Optional[float] = None,
        mean_difference: Optional[float] = None,
        mean_p_value: Optional[float] = None,
        std_dev_difference: Optional[float] = None,
        tstatistic: Optional[float] = None,
        variance_p_value: Optional[float] = None,
    ) -> None: ...

    @property
    def fstatistic(self) -> Optional[float]: ...

    @fstatistic.setter
    def fstatistic(self, fstatistic: Optional[float]) -> None: ...

    @property
    def mean_difference(self) -> Optional[float]: ...

    @mean_difference.setter
    def mean_difference(self, mean_difference: Optional[float]) -> None: ...

    @property
    def mean_p_value(self) -> Optional[float]: ...

    @mean_p_value.setter
    def mean_p_value(self, mean_p_value: Optional[float]) -> None: ...

    @property
    def std_dev_difference(self) -> Optional[float]: ...

    @std_dev_difference.setter
    def std_dev_difference(self, std_dev_difference: Optional[float]) -> None: ...

    @property
    def tstatistic(self) -> Optional[float]: ...

    @tstatistic.setter
    def tstatistic(self, tstatistic: Optional[float]) -> None: ...

    @property
    def variance_p_value(self) -> Optional[float]: ...

    @variance_p_value.setter
    def variance_p_value(self, variance_p_value: Optional[float]) -> None: ...

    def to_dict(self) -> Dict[str, Any]: ...
    def to_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
