[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "esdd-client"
version = "0.1.9.0"
description = """API client for the online platform ESDD (evaluation, standardization, and derived data)"""
authors = [
    { name = "Gumar Arutynian", email = "legendary.killtell@gmail.com" },
    { name = "Evgeny Blokhin", email = "eb@tilde.pro" },
]
requires-python = ">=3.11"
dependencies = [
	"httpx>=0.25.1",
	"click>=8.1.7",
	"python-dotenv==1.2.1",
	"keyring>=25.2.0",
	"pyjwt==2.0.0",
	"keyrings.alt==5.0.2"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
]
readme = "README.md"

[project.scripts]
esdd = "app.src.presentation.cli:main"

[tool.flake8]
max-line-length = 100

ignore = ["E402", "F401"]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]
exclude = ["lib*", "tests*", "venv*", ".venv*"]
