# coding: utf-8

"""
    Arthur Scope

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arthur_client.api_bindings.models.fetch_discovered_agents_job_spec import FetchDiscoveredAgentsJobSpec

class TestFetchDiscoveredAgentsJobSpec(unittest.TestCase):
    """FetchDiscoveredAgentsJobSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FetchDiscoveredAgentsJobSpec:
        """Test FetchDiscoveredAgentsJobSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchDiscoveredAgentsJobSpec`
        """
        model = FetchDiscoveredAgentsJobSpec()
        if include_optional:
            return FetchDiscoveredAgentsJobSpec(
                job_type = 'fetch_discovered_agents',
                workspace_id = '',
                data_plane_id = '',
                discovery_source_id = '',
                reported_since = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return FetchDiscoveredAgentsJobSpec(
                workspace_id = '',
                data_plane_id = '',
                discovery_source_id = '',
        )
        """

    def testFetchDiscoveredAgentsJobSpec(self):
        """Test FetchDiscoveredAgentsJobSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
