name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Test
        run: cargo test --release

  fuzz_rust_crash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Install system dependencies
        run: sudo apt-get install build-essential binutils-dev libunwind-dev libblocksruntime-dev liblzma-dev
      - name: Install hfuzz
        run: cd fuzz && cargo install honggfuzz --version 0.5.57 && cd -
      - name: Fuzz
        run: cd fuzz && HFUZZ_RUN_ARGS="--run_time 30 --timeout 3 --verifier --only_printable --crashdir ./hfuzz_workspace/crashes" cargo hfuzz run crash && cd -
      - name: Show crash files
        continue-on-error: true
        run: head -n-0 fuzz/hfuzz_workspace/crashes/*
      - name: Show report
        run: "! [ -f fuzz/hfuzz_workspace/crash/HONGGFUZZ.REPORT.TXT ] || ! cat fuzz/hfuzz_workspace/crash/HONGGFUZZ.REPORT.TXT"

  fuzz_rust_timeout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Install system dependencies
        run: sudo apt-get install build-essential binutils-dev libunwind-dev libblocksruntime-dev liblzma-dev
      - name: Install hfuzz
        run: cd fuzz && cargo install honggfuzz --version 0.5.57 && cd -
      - name: Fuzz
        run: cd fuzz && HFUZZ_RUN_ARGS="--run_time 30 --timeout 10 --verifier --only_printable --crashdir ./hfuzz_workspace/crashes" cargo hfuzz run timeout && cd -
      - name: Show crash files
        continue-on-error: true
        run: head -n-0 fuzz/hfuzz_workspace/crashes/*
      - name: Show report
        run: "! [ -f fuzz/hfuzz_workspace/timeout/HONGGFUZZ.REPORT.TXT ] || ! cat fuzz/hfuzz_workspace/timeout/HONGGFUZZ.REPORT.TXT"

  test_js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium
      - run: pnpm -r build
      - run: pnpm -r test

  check_js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true
      - name: Run Biome
        run: pnpm biome ci --verbose .

  check_rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - name: Check
        run: cargo fmt --check
