depends_on:
  - test
  - ruff
when:
  - event: pull_request
  - event: push
    branch: master
  - event: tag
steps:
  build_docs:
    # The docs are always build to ensure the build process is not broken.
    image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    commands:
      - cd docs
      - uv run --frozen sphinx-build --builder html --doctree-dir /tmp/doctrees-docs source/ build/html/
      - uv run --frozen sphinx-build --builder html --doctree-dir /tmp/doctrees-site site/ build/site/
  pypi:
    # The package is uploaded to PyPI only for tags.
    image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    environment:
      # API token from https://pypi.org/manage/account/
      UV_PUBLISH_TOKEN:
        from_secret: uv_publish_token
      # https://upload.pypi.org/legacy/ or https://test.pypi.org/legacy/
      UV_PUBLISH_URL:
        from_secret: uv_publish_url
    commands:
      - export PACKAGE_VERSION_NUMBER="$(uv version --short)"
      - uv build
      - echo "Publishing version ${PACKAGE_VERSION_NUMBER} to ${UV_PUBLISH_URL}"
      - uv publish
    when:
      - event: tag
  deploy_docs:
    # The docs are deployed for pushes to the main branch and tags.
    # For pushes, the docs are published in preview mode without affecting the actual site.
    # They are accessible via a unique https://xxxxx.vercel.app URL (visible in build logs).
    # For tags, the docs are published in production mode to the real site.
    # This step is not run for PRs to avoid exposing the Vercel API token.
    image: node:22
    environment:
      VERCEL_TELEMETRY_DISABLED: 1
      VERCEL_TOKEN:
        from_secret: vercel_token
      VERCEL_ORG_ID:
        from_secret: vercel_org_id
      VERCEL_DOCS_PROJECT_ID:
        from_secret: vercel_docs_project_id
      VERCEL_SITE_PROJECT_ID:
        from_secret: vercel_site_project_id
      VERCEL_CLI_PACKAGE: vercel@48.1.6
    commands:
      - ls docs/build
      - VERCEL_PROJECT_ID=$VERCEL_DOCS_PROJECT_ID npx $VERCEL_CLI_PACKAGE --token=$VERCEL_TOKEN --cwd docs/build/html/ deploy --yes ${CI_COMMIT_TAG:+--prod}
      - VERCEL_PROJECT_ID=$VERCEL_SITE_PROJECT_ID npx $VERCEL_CLI_PACKAGE --token=$VERCEL_TOKEN --cwd docs/build/site/ deploy --yes ${CI_COMMIT_TAG:+--prod}
    when:
      - event: tag
      - event: push
        branch: master
