when:
  - event: pull_request
  - event: push
    branch: master
  - event: tag
steps:
  check:
    image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    commands:
      - uv run ruff check
    depends_on: []

  format-check:
    image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    commands:
      - uv run ruff format --check
    depends_on: []
