when:
  - event: pull_request
  - event: push
    branch: master
  - event: tag

matrix:
  PYVERSION:
    - 3.8
    - 3.9
    - 3.10
    - 3.11
    - 3.12
    - 3.13

steps:
  pytest:
    image: ghcr.io/astral-sh/uv:python${PYVERSION}-bookworm-slim
    commands:
      - uv sync --frozen
      - uv run pytest -vvv
    depends_on: []
