fail_fast: true

repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        language: system
        entry: ruff format
        require_serial: true
        args: [reflex_enterprise]
        types_or: [python, pyi]

      - id: ruff-check
        name: ruff-check
        language: system
        entry: ruff check
        require_serial: true
        args: ["--fix", "--exit-non-zero-on-fix"]
        exclude: '^integration/benchmarks/'
        types_or: [python, pyi]

      - id: codespell
        name: codespell
        language: system
        entry: codespell
        args: ["reflex_enterprise"]
        require_serial: true
        types_or: [python, pyi, markdown, text]

      # Run pyi check before pyright because pyright can fail if pyi files are wrong.
      - id: update-pyi-files
        name: update-pyi-files
        always_run: true
        language: system
        require_serial: true
        description: 'Update pyi files as needed'
        entry: python3 scripts/make_pyi.py

      - id: pyright
        name: pyright
        language: system
        entry: pyright
        require_serial: true
        args: [reflex_enterprise]
        types_or: [python, pyi]
