apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workflows-worker-internal
  description: Internal Temporal worker base image for Mistral-managed workflows.
  tags: [python]
  annotations:
    mistral.ai/channel-support: C08RZBB9EEM #product-workflows
    mistral.ai/channel-ops: C0A00JTBDKL #eng-alerts-workflows
spec:
  type: library
  lifecycle: production
  owner: engineering-workflows
