[project]
name = "ghdl"
description = "Binary Manager for Github Releases"
authors = [{name = "Imran Khan", email = "imran@khan.ovh"}]
license-files = ["LICENSE"]
requires-python = ">=3.9,<3.15"
dynamic = ["version"]
dependencies = [
  "xtract ==0.1a3",
  "xdg >=4.0.1",
  "python-dateutil >=2.8.1",
  "docopt >=0.6.2",
  "python-magic >=0.4.25",
  "hyrule >=1.0.1",
  "hy >=1.2.0",
  "httpx >=0.28.1"
]

[tool.setuptools]
script-files = ["bin/ghdl", "bin/ghdl-delete-repo"]
include-package-data = true

# only need to do this for wheel, sdist is fine
# [tool.hatch.build.targets.wheel.force-include]
# "bin/" = "ghdl/bin"

[tool.setuptools.dynamic]
version = {attr = "ghdl.__version__"}

[tool.hatch.version]
path = "ghdl/__init__.py"

[tool.uv]
prerelease = "if-necessary-or-explicit"
python-downloads = "never"
python-preference = "system"

[tool.uv.build-backend]
module-name = "ghdl"
module-root = ""

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
# requires = ["hatchling"]
# build-backend = "hatchling.build"
# requires = ["uv_build>=0.9.29,<0.10.0"]
# build-backend = "uv_build"
