APP_NAME_TO_USECASE = {
    "people_counting": "people_counting",
    # fast_people_counting is registered in the use-case registry but was missing
    # here, so PostProcessor(app_name="fast_people_counting") raised
    # "No valid configuration found" on EVERY frame (silent per-frame error path).
    "fast_people_counting": "fast_people_counting",
    "Fast People Counting": "fast_people_counting",
    "Claude People Counting Usecase": "claude_people_counting_usecase",
    "DeepOCSort People Counting": "deep_oc_sort",
    "deep_oc_sort": "deep_oc_sort",
    "DeepOCSort": "deep_oc_sort",
    "drone_traffic_monitoring": "drone_traffic_monitoring",
    "intrusion_detection": "intrusion_detection",
    "proximity_detection": "proximity_detection",
    "mask_detection": "mask_detection",
    "pipeline_detection": "pipeline_detection",
    "vehicle_monitoring": "vehicle_monitoring",
    "Vehicle Type Monitoring": "vehicle_monitoring",
    "Vehicle Monitoring": "vehicle_monitoring",
    "vehicle-monitoring": "vehicle_monitoring",
    "weapon_detection": "weapon_detection",
    "Weapon Human Detection": "weapon_human_detection",
    "weapon_human_detection": "weapon_human_detection",
    "traffic_sign_monitoring": "traffic_sign_monitoring",
    "flare_analysis": "flare_analysis",
    "Flare Detection": "flare_analysis",
    "flare_detection": "flare_analysis",
    # Platform app name is "Gas Flare Detection" -- must match exactly since
    # get_usecase_from_app_name() does an exact-key lookup before falling
    # back to the normalized (lowercased/underscored) form.
    "Gas Flare Detection": "flare_analysis",
    "ppe_compliance": "ppe_compliance",
    "PPE Detection": "ppe_compliance",
    "PPE Compliance": "ppe_compliance",
    "PPE Monitoring": "ppe_compliance",
    "ppe_compliance_detection": "ppe_compliance",
    "Customer Activity Analysis": "advanced_customer_service",
    "assembly_line_detection": "assembly_line_detection",
    "crop_weed_detection": "crop_weed_detection",
    "emergency_vehicle_detection": "emergency_vehicle_detection",
    "fashion_detection": "fashion_detection",
    "gender_detection": "gender_detection",
    "price_tag_detection": "price_tag_detection",
    "windmill_maintenance": "windmill_maintenance",
    "underwater_pollution_detection": "underwater_pollution_detection",
    "solar_panel": "solar_panel",
    "face_emotion": "face_emotion",
    "face_covering_detection_pose": "face_covering_detection_pose",
    "Face Covering Detection Pose": "face_covering_detection_pose",
    "pedestrian_detection": "pedestrian_detection",
    "warehouse_object_segmentation": "warehouse_object_segmentation",
    "flower_segmentation": "flower_segmentation",
    "shopping_cart_analysis": "shopping_cart_analysis",
    "car_part_segmentation": "car_part_segmentation",
    "weld_defect_detection": "weld_defect_detection",
    "fruit_monitoring": "fruit_monitoring",
    "concrete_crack_detection": "concrete_crack_detection",
    "lane_detection": "lane_detection",
    "shelf_inventory": "shelf_inventory",
    "smoker_detection": "smoker_detection",
    "age_detection": "age_detection",
    "defect_detection_products": "defect_detection_products",
    "parking_space_detection": "parking_space_detection",
    "car_damage_detection": "car_damage_detection",
    "car_damage_detection_new": "car_damage_detection",
    "Car Damage Detection New": "car_damage_detection",
    "ppe_compliance_new": "ppe_compliance",
    "PPE Compliance New": "ppe_compliance",
    "license_plate_detection": "license_plate_detection",
    "shoplifting_detection": "shoplifting_detection",
    "cardiomegaly_classification": "cardiomegaly_classification",
    "road_traffic_density": "road_traffic_density",
    "Road Traffic Density Estimation": "road_traffic_density",
    "histopathological_cancer_detection": "histopathological_cancer_detection",
    "road_view_segmentation": "road_view_segmentation",
    "face_recognition": "face_recognition",
    "Face Recognition": "face_recognition",
    "fr_access_control": "fr_access_control",
    "FR-AccessControl": "fr_access_control",
    "FR Access Control": "fr_access_control",
    "Face Recognition - Access Control": "fr_access_control",
    # Normalized: lower + spaces/hyphens → underscores ("face recognition - access control")
    "face_recognition___access_control": "fr_access_control",
    "fr_surveillance": "fr_surveillance",
    "FR-Surveillance": "fr_surveillance",
    "FR Surveillance": "fr_surveillance",
    "Face Recognition - Surveillance": "fr_surveillance",
    "face_recognition___surveillance": "fr_surveillance",
    "drowsy_driver_detection": "drowsy_driver_detection",
    "waterbody_segmentation": "waterbody_segmentation",
    "litter_detection": "litter_detection",
    "leak_detection": "leak_detection",
    "Fire Safety Monitoring": "fire_smoke_detection",
    "human_activity_recognition": "human_activity_recognition",
    "abandoned_object_detection": "abandoned_object_detection",
    "Abandoned Object Detection": "abandoned_object_detection",
    "gas_leak_detection": "gas_leak_detection",
    "color_detection": "color_detection",
    "Color Detection": "color_detection",
    "License Plate Recognition": "license_plate_monitor",
    "License Plate Monitoring": "license_plate_monitor",
    "lpr_access_control": "lpr_access_control",
    "LPR-AccessControl": "lpr_access_control",
    "LPR Access Control": "lpr_access_control",
    "License Plate Recognition - Access Control": "lpr_access_control",
    # Normalized: lower + spaces/hyphens -> underscores. get_usecase_from_app_name()
    # falls back to this form, so these catch any casing/spacing the platform sends
    # ("LPR-Access-Control", "lpr access control", ...). Same pattern as FR above.
    "lpr_access_control_": "lpr_access_control",
    "license_plate_recognition___access_control": "lpr_access_control",
    "lpr___access_control": "lpr_access_control",
    "lpr_surveillance": "lpr_surveillance",
    "LPR-Surveillance": "lpr_surveillance",
    "LPR Surveillance": "lpr_surveillance",
    "License Plate Recognition - Surveillance": "lpr_surveillance",
    "license_plate_recognition___surveillance": "lpr_surveillance",
    "lpr___surveillance": "lpr_surveillance",
    "cell_microscopy_segmentation": "cell_microscopy_segmentation",
    "Dwell Detection": "dwell",
    "age_gender_detection": "age_gender_detection",
    "People Tracking": "people_tracking",
    "wildlife_monitoring": "wildlife_monitoring",
    "pcb_defect_detection": "pcb_defect_detection",
    "underground_pipeline_defect": "underground_pipeline_defect",
    "suspicious_activity_detection": "suspicious_activity_detection",
    "natural_disaster_detection": "natural_disaster_detection",
    "Foot Fall": "footfall",
    "footfall": "footfall",
    "foot_fall": "footfall",
    "Crowdflow": "crowdflow",
    "crowdflow": "crowdflow",
    "HeatMaps": "heatmaps",
    "heatmaps": "heatmaps",
    "Crowd Density HeatMaps": "crowd_density_heatmaps",
    "crowd_density_heatmaps": "crowd_density_heatmaps",
    "Hazard Zone Entry": "hazard_zone_entry",
    "Parking Lot Vehicle Monitoring": "vehicle_monitoring_parking_lot",
    "vehicle_monitoring_parking_lot": "vehicle_monitoring_parking_lot",
    "Vehicle Monitoring Parking Lot": "vehicle_monitoring_parking_lot",
    "Drone view vehicle monitoring": "vehicle_monitoring_drone_view",
    "Parking Lot Analytics": "parking_lot_analytics",
    "Vehicle Monitoring Wrong Way": "vehicle_monitoring_wrong_way",
    "Stopped Vehicle Monitoring": "stopped_vehicle_monitoring",
    # Normalized key covers "Illegal Parking", "Illegal-Parking", etc.
    "illegal_parking": "illegal_parking_detection",
    "illegal_parking_detection": "illegal_parking_detection",
    "Area Utilization": "area_utilization",
    "Loitering Detection": "loitering_detection",
    "Tailgating Detection": "tailgating_detection",
    "Vehicle Color Detection": "vehicle_color_detection",
    "Vehicle Segmentation": "vehicle_segmentation",
    "vehicle_segmentation": "vehicle_segmentation",
    "Vehicle Type Classification": "vehicle_type_classification",
    "Vegetable Detection": "vegetable_detection",
    "Fall Detection": "fall_detection",
    "Running Detection": "running_detection",
    "Liquid Leak Detection": "liquid_leak_detection",
    "Pipe Gas Leak Detection": "pipe_gas_leak_detection",
    "People In Zone Counting": "people_counting_in_zone",
    "Pipe Corrosion Detection": "pipe_corrosion_detection",
    "Overcrowding Detection": "overcrowding_detection",
    "Animal Detection": "animal_detection",
    "Unwanted Animal Detection": "unwanted_animal_detection",
    "unwanted_animal_detection": "unwanted_animal_detection",
    "gloves_boots_detection": "gloves_boots_detection",
    "Burglary Detection": "burglary_detection",
    "Violence Detection": "violence_detection",
    "violence_detection": "violence_detection",
    "Violence Detection Testing": "violence_detection_testing",
    "violence_detection_testing": "violence_detection_testing",
    "Landslide Detection": "landslide_detection",
    "Accident Detection": "accident_detection",
    "accident_detection": "accident_detection",
    "Flood Detection": "flood_detection",
    "flood_detection": "flood_detection",
    "Unauthorized Encampment Detection": "unauthorized_encampment_detection",
    "unauthorized_encampment_detection": "unauthorized_encampment_detection",
    "Drone Detection": "drone_detection",
    "drone_detection": "drone_detection",
    "Street Vendor Detection": "street_vendor_detection",
    "street_vendor_detection": "street_vendor_detection",
    "Bottle Defect Detection": "bottle_defect_detection",
    "Phone Screen Defect Detection": "phone_screen_defect_detection",
    "Package Detection": "package_detection",
    "Fence Climbing Detection": "fence_climbing_detection",
    "fence_climbing_detection": "fence_climbing_detection",
    "fence_climbing_detection_pose": "fence_climbing_detection_pose",
    "Fence Climbing Detection Pose": "fence_climbing_detection_pose",
    "fence_climbing_with_zone": "fence_climbing_with_zone",
    "Fence Climbing With Zone": "fence_climbing_with_zone",
    "Pothole Detection": "pothole_detection",
}

APP_NAME_TO_CATEGORY = {
    "people_counting": "general",
    "fast_people_counting": "general",
    "Fast People Counting": "general",
    "Claude People Counting Usecase": "general",
    "DeepOCSort People Counting": "general",
    "deep_oc_sort": "general",
    "DeepOCSort": "general",
    "drone_traffic_monitoring": "traffic",
    "intrusion_detection": "security",
    "proximity_detection": "security",
    "mask_detection": "mask_detection",
    "pipeline_detection": "pipeline_detection",
    "vehicle_monitoring": "traffic",
    "Vehicle Type Monitoring": "traffic",
    "Vehicle Monitoring": "traffic",
    "vehicle-monitoring": "traffic",
    "weapon_detection": "security",
    "Weapon Human Detection": "security",
    "weapon_human_detection": "security",
    "traffic_sign_monitoring": "traffic",
    "flare_analysis": "flare_detection",
    "Flare Detection": "flare_detection",
    "flare_detection": "flare_detection",
    "Gas Flare Detection": "flare_detection",
    "ppe_compliance": "ppe",
    "PPE Detection": "ppe",
    "PPE Compliance": "ppe",
    "PPE Monitoring": "ppe",
    "ppe_compliance_detection": "ppe",
    "Customer Activity Analysis": "sales",
    "assembly_line_detection": "manufacturing",
    "crop_weed_detection": "agriculture",
    "emergency_vehicle_detection": "traffic",
    "fashion_detection": "retail",
    "gender_detection": "general",
    "price_tag_detection": "retail",
    "windmill_maintenance": "windmill_maintenance",
    "underwater_pollution_detection": "environmental",
    "solar_panel": "energy",
    "face_emotion": "general",
    "face_covering_detection_pose": "general",
    "Face Covering Detection Pose": "general",
    "pedestrian_detection": "pedestrian",
    "warehouse_object_segmentation": "retail",
    "flower_segmentation": "agriculture",
    "shopping_cart_analysis": "retail",
    "car_part_segmentation": "automobile",
    "weld_defect_detection": "weld",
    "fruit_monitoring": "agriculture",
    "vegetable_detection": "agriculture",
    "concrete_crack_detection": "general",
    "lane_detection": "traffic",
    "shelf_inventory": "retail",
    "smoker_detection": "general",
    "age_detection": "general",
    "defect_detection_products": "retail",
    "parking_space_detection": "parking_space",
    "car_damage_detection": "car_damage",
    "car_damage_detection_new": "car_damage",
    "Car Damage Detection New": "car_damage",
    "ppe_compliance_new": "ppe",
    "PPE Compliance New": "ppe",
    "license_plate_detection": "license_plate",
    "shoplifting_detection": "security",
    "cardiomegaly_classification": "healthcare",
    "road_traffic_density": "general",
    "Road Traffic Density Estimation": "general",
    "histopathological_cancer_detection": "healthcare",
    "road_view_segmentation": "automobile",
    "face_recognition": "security",
    "Face Recognition": "security",
    "fr_access_control": "security",
    "FR-AccessControl": "security",
    "FR Access Control": "security",
    "Face Recognition - Access Control": "security",
    "face_recognition___access_control": "security",
    "fr_surveillance": "security",
    "FR-Surveillance": "security",
    "FR Surveillance": "security",
    "Face Recognition - Surveillance": "security",
    "face_recognition___surveillance": "security",
    "drowsy_driver_detection": "automobile",
    "waterbody_segmentation": "agriculture",
    "litter_detection": "litter_detection",
    "leak_detection": "oil_gas",
    "Fire Safety Monitoring": "hazard",
    "human_activity_recognition": "general",
    "abandoned_object_detection": "security",
    "Abandoned Object Detection": "security",
    "gas_leak_detection": "oil_gas",
    "color_detection": "visual_appearance",
    "Color Detection": "visual_appearance",
    "License Plate Recognition": "license_plate_monitor",
    "License Plate Monitoring": "license_plate_monitor",
    "lpr_access_control": "license_plate_monitor",
    "LPR-AccessControl": "license_plate_monitor",
    "LPR Access Control": "license_plate_monitor",
    "License Plate Recognition - Access Control": "license_plate_monitor",
    "license_plate_recognition___access_control": "license_plate_monitor",
    "lpr___access_control": "license_plate_monitor",
    "lpr_surveillance": "license_plate_monitor",
    "LPR-Surveillance": "license_plate_monitor",
    "LPR Surveillance": "license_plate_monitor",
    "License Plate Recognition - Surveillance": "license_plate_monitor",
    "license_plate_recognition___surveillance": "license_plate_monitor",
    "lpr___surveillance": "license_plate_monitor",
    "cell_microscopy_segmentation": "healthcare",
    "Dwell Detection": "general",
    "age_gender_detection": "age_gender_detection",
    "People Tracking": "general",
    "wildlife_monitoring": "environmental",
    "pcb_defect_detection": "manufacturing",
    "underground_pipeline_defect": "general",
    "suspicious_activity_detection": "security",
    "natural_disaster_detection": "environmental",
    "Foot Fall": "retail",
    "footfall": "retail",
    "foot_fall": "retail",
    "Crowdflow": "retail",
    "crowdflow": "retail",
    "HeatMaps": "retail",
    "heatmaps": "retail",
    "Crowd Density HeatMaps": "retail",
    "crowd_density_heatmaps": "retail",
    "Hazard Zone Entry": "general",
    "Parking Lot Vehicle Monitoring": "traffic",
    "vehicle_monitoring_parking_lot": "traffic",
    "Vehicle Monitoring Parking Lot": "traffic",
    "Drone view vehicle monitoring": "traffic",
    "Parking Lot Analytics": "traffic",
    "Vehicle Monitoring Wrong Way": "traffic",
    "Stopped Vehicle Monitoring": "traffic",
    "illegal_parking": "traffic",
    "illegal_parking_detection": "traffic",
    "Area Utilization": "general",
    "Loitering Detection": "general",
    "Tailgating Detection": "security",
    "Vehicle Color Detection": "traffic",
    "Vehicle Segmentation": "traffic",
    "vehicle_segmentation": "traffic",
    "Vehicle Type Classification": "traffic",
    "Fall Detection": "general",
    "Running Detection": "security",
    "Liquid Leak Detection": "security",
    "Pipe Gas Leak Detection": "security",
    "People Counting In Zone": "general",
    "Pipe Corrosion Detection": "security",
    "Overcrowding Detection": "security",
    "Animal Detection": "general",
    "Unwanted Animal Detection": "general",
    "unwanted_animal_detection": "general",
    "gloves_boots_detection": "security",
    "Burglary Detection": "security",
    "Violence Detection": "security",
    "violence_detection": "security",
    "Violence Detection Testing": "security",
    "violence_detection_testing": "security",
    "Landslide Detection": "environmental",
    "Accident Detection": "traffic",
    "accident_detection": "traffic",
    "Flood Detection": "environmental",
    "flood_detection": "environmental",
    "Unauthorized Encampment Detection": "security",
    "unauthorized_encampment_detection": "security",
    "Drone Detection": "aerial",
    "drone_detection": "aerial",
    "Street Vendor Detection": "general",
    "street_vendor_detection": "general",
    "Bottle Defect Detection": "industrial",
    "Phone Screen Defect Detection": "industrial",
    "Package Detection": "manufacturing",
    "Fence Climbing Detection": "general",
    "fence_climbing_detection": "general",
    "fence_climbing_detection_pose": "general",
    "Fence Climbing Detection Pose": "general",
    "fence_climbing_with_zone": "security",
    "Fence Climbing With Zone": "security",
    # Was "Safety" (capitalized) — the only non-lowercase value in this dict;
    # every consumer of get_category_from_app_name() elsewhere gets lowercase.
    "Pothole Detection": "safety",
}


def get_usecase_from_app_name(app_name: str) -> str:
    # Strip stray whitespace first: backend app names sometimes carry trailing
    # spaces (e.g. "Drone-Detection ") which would otherwise normalize to
    # "drone_detection_" and miss the map.
    app_name = (app_name or "").strip()
    normalized_app_name = app_name.lower().replace(" ", "_").replace("-", "_")
    return APP_NAME_TO_USECASE.get(app_name, APP_NAME_TO_USECASE.get(normalized_app_name))


def get_category_from_app_name(app_name: str) -> str:
    app_name = (app_name or "").strip()
    normalized_app_name = app_name.lower().replace(" ", "_").replace("-", "_")
    return APP_NAME_TO_CATEGORY.get(app_name, APP_NAME_TO_CATEGORY.get(normalized_app_name))
