# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentry_protos/billing/v1/services/invoicer/v1/endpoint_create_invoices.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLsentry_protos/billing/v1/services/invoicer/v1/endpoint_create_invoices.proto\x12-sentry_protos.billing.v1.services.invoicer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n\x15\x43reateInvoicesRequest\x12.\n\ncurrent_ts\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x18\n\x16\x43reateInvoicesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentry_protos.billing.v1.services.invoicer.v1.endpoint_create_invoices_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEINVOICESREQUEST']._serialized_start=160
  _globals['_CREATEINVOICESREQUEST']._serialized_end=231
  _globals['_CREATEINVOICESRESPONSE']._serialized_start=233
  _globals['_CREATEINVOICESRESPONSE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
