"""Type stubs for datafusion_query_builder."""

from collections.abc import Sequence
from typing import Protocol

# Anything that can stand in for an expression: an Expr, or a Python scalar/list that
# auto-promotes to a literal.
IntoExpr = Expr | int | float | str | bool | None
IntoSort = Expr | SortExpr | int | float | str | bool

class Expr:
    """A SQL expression. Build with operators, `col`, `lit`, and the `functions` namespace."""

    def alias(self, name: str) -> Expr: ...
    def cast(self, data_type: str) -> Expr: ...
    def is_in(self, values: Sequence[IntoExpr] | Query) -> Expr: ...
    def not_in(self, values: Sequence[IntoExpr] | Query) -> Expr: ...
    def is_null(self) -> Expr: ...
    def is_not_null(self) -> Expr: ...
    def between(self, low: IntoExpr, high: IntoExpr) -> Expr: ...
    # JSONB key-exists operators (`?` / `?|` / `?&`). `has_key` is a cheap presence check that,
    # unlike `col ->> 'k' is not None`, never extracts the value.
    def has_key(self, key: IntoExpr) -> Expr: ...
    def has_any_key(self, keys: Sequence[IntoExpr]) -> Expr: ...
    def has_all_keys(self, keys: Sequence[IntoExpr]) -> Expr: ...
    def asc(self, nulls_first: bool | None = ...) -> SortExpr: ...
    def desc(self, nulls_first: bool | None = ...) -> SortExpr: ...
    # Valid only on a function-call expression:
    def filter(self, cond: IntoExpr) -> Expr: ...
    def over(
        self,
        partition_by: Sequence[IntoExpr] | None = ...,
        order_by: Sequence[IntoSort] | None = ...,
    ) -> Expr: ...
    # Operators build expression trees; comparisons/booleans return Expr, not bool.
    def __add__(self, other: IntoExpr) -> Expr: ...
    def __radd__(self, other: IntoExpr) -> Expr: ...
    def __sub__(self, other: IntoExpr) -> Expr: ...
    def __rsub__(self, other: IntoExpr) -> Expr: ...
    def __mul__(self, other: IntoExpr) -> Expr: ...
    def __rmul__(self, other: IntoExpr) -> Expr: ...
    def __truediv__(self, other: IntoExpr) -> Expr: ...
    def __rtruediv__(self, other: IntoExpr) -> Expr: ...
    def __mod__(self, other: IntoExpr) -> Expr: ...
    def __rmod__(self, other: IntoExpr) -> Expr: ...
    def __neg__(self) -> Expr: ...
    def __eq__(self, other: IntoExpr) -> Expr: ...  # type: ignore[override]
    def __ne__(self, other: IntoExpr) -> Expr: ...  # type: ignore[override]
    def __lt__(self, other: IntoExpr) -> Expr: ...
    def __le__(self, other: IntoExpr) -> Expr: ...
    def __gt__(self, other: IntoExpr) -> Expr: ...
    def __ge__(self, other: IntoExpr) -> Expr: ...
    def __and__(self, other: IntoExpr) -> Expr: ...
    def __rand__(self, other: IntoExpr) -> Expr: ...
    def __or__(self, other: IntoExpr) -> Expr: ...
    def __ror__(self, other: IntoExpr) -> Expr: ...
    def __invert__(self) -> Expr: ...

class SortExpr:
    """An expression with an ordering direction, produced by `Expr.asc()` / `Expr.desc()`."""

class QueryBuilderError(Exception):
    """Base error for the query builder; raised for API misuse."""

class UnparsableSqlError(QueryBuilderError):
    """A raw() fragment or cast type that couldn't be parsed as SQL."""

class Query:
    """A generative SELECT builder. Every method returns a new Query."""

    def select(self, *exprs: IntoExpr) -> Query: ...
    def filter(self, predicate: IntoExpr) -> Query: ...
    def where_(self, predicate: IntoExpr) -> Query: ...
    def group_by(self, *exprs: IntoExpr) -> Query: ...
    def having(self, predicate: IntoExpr) -> Query: ...
    def distinct(self) -> Query: ...
    def from_(self, source: str | Query, alias: str | None = ...) -> Query: ...
    def join(
        self,
        other: str | Query,
        on: IntoExpr | None = ...,
        how: str = ...,
        alias: str | None = ...,
    ) -> Query: ...
    def cross_join(self, other: str | Query, alias: str | None = ...) -> Query: ...
    def with_cte(self, name: str, query: Query) -> Query: ...
    def order_by(self, *sorts: IntoSort) -> Query: ...
    def limit(self, n: int) -> Query: ...
    def offset(self, n: int) -> Query: ...
    def union(self, other: Query, all: bool = ...) -> Query: ...
    def union_all(self, other: Query) -> Query: ...
    def intersect(self, other: Query) -> Query: ...
    def except_(self, other: Query) -> Query: ...
    def scalar(self) -> Expr: ...
    def to_sql(self) -> str: ...
    def validate(self) -> str: ...

class _WhenThen(Protocol):
    def then(self, result: IntoExpr) -> _CaseBuilder: ...

class _CaseBuilder(Protocol):
    def when(self, condition: IntoExpr) -> _WhenThen: ...
    def otherwise(self, result: IntoExpr) -> Expr: ...
    def end(self) -> Expr: ...

def col(name: str, relation: str | None = ...) -> Expr: ...
def lit(value: IntoExpr | Sequence[IntoExpr]) -> Expr: ...
def param(name: str) -> Expr: ...
def raw(sql: str) -> Expr: ...
def table(name: str) -> Query: ...
def query() -> Query: ...
def and_(*exprs: IntoExpr) -> Expr: ...
def or_(*exprs: IntoExpr) -> Expr: ...
def not_(expr: IntoExpr) -> Expr: ...
def when(condition: IntoExpr) -> _WhenThen: ...

class _Functions(Protocol):
    """The `functions` / `f` namespace of SQL function constructors."""

    def count(self, arg: IntoExpr | None = ..., *, distinct: bool = ...) -> Expr: ...
    def call(self, name: str, *args: IntoExpr) -> Expr: ...
    def sum(self, *args: IntoExpr) -> Expr: ...
    def avg(self, *args: IntoExpr) -> Expr: ...
    def min(self, *args: IntoExpr) -> Expr: ...
    def max(self, *args: IntoExpr) -> Expr: ...
    def round(self, *args: IntoExpr) -> Expr: ...
    def coalesce(self, *args: IntoExpr) -> Expr: ...
    def nullif(self, *args: IntoExpr) -> Expr: ...
    def date_bin(self, *args: IntoExpr) -> Expr: ...
    def date_trunc(self, *args: IntoExpr) -> Expr: ...
    def time_bucket(self, *args: IntoExpr) -> Expr: ...
    def approx_distinct(self, *args: IntoExpr) -> Expr: ...
    def approx_percentile_cont(self, *args: IntoExpr) -> Expr: ...
    def json_keys(self, *args: IntoExpr) -> Expr: ...
    def unnest(self, *args: IntoExpr) -> Expr: ...
    def metric_avg(self, *args: IntoExpr) -> Expr: ...
    def metric_sum(self, *args: IntoExpr) -> Expr: ...
    def metric_count(self, *args: IntoExpr) -> Expr: ...
    def metric_min(self, *args: IntoExpr) -> Expr: ...
    def metric_max(self, *args: IntoExpr) -> Expr: ...
    def metric_quantile(self, *args: IntoExpr) -> Expr: ...
    def metric_rate(self, *args: IntoExpr) -> Expr: ...
    def metric_delta(self, *args: IntoExpr) -> Expr: ...
    def metric_increase(self, *args: IntoExpr) -> Expr: ...
    def metric_merge(self, *args: IntoExpr) -> Expr: ...

functions: _Functions
f: _Functions

__all__ = [
    'Expr',
    'Query',
    'QueryBuilderError',
    'SortExpr',
    'UnparsableSqlError',
    'and_',
    'col',
    'f',
    'functions',
    'lit',
    'not_',
    'or_',
    'param',
    'query',
    'raw',
    'table',
    'when',
]
