[project]
name = "spaces"
version = "0.50.2"
description = "Utilities for Hugging Face Spaces"
readme = "README.md"
requires-python = ">=3.10,<3.15"
license = "Apache-2.0"
authors = [
    { name = "Charles Bensimon", email = "charles@huggingface.co" },
]
dependencies = [
    "packaging",
    "typing-extensions>=4,<5",
    "requests>=2.19,<3",
    "gradio", # Actually requires 3.2+ if for `@spaces.GPU`
    "pydantic>=1,<3",
    "httpx>=0.20",
]

[project.urls]
Homepage = "https://huggingface.co"
Repository = "https://github.com/huggingface/huggingface_hub"

[dependency-groups]
dev = [
    "pytest>=7.3.1,<8",
    "pytest-dotenv>=0.5.2,<0.6",
    "pytest-mock>=3.10.0,<4",
    "requests-mock>=1.10.0,<2",
    "pytest-timeout>=2.1.0,<3",
    "poethepoet>=0.20.0,<0.21",
    "coverage>=7.2.6,<8",
    "pyright>=1.1.403,<2",
    "pytest-order>=1.1.0,<2",
    "pynvml>=11.5.0,<12",
    "websockets>=13.0,<14",
    "pytest-asyncio>=0.21.1,<0.22",
    "pytest-httpx>=0.27.0,<0.28",
    "pydantic-to-typescript>=2.0.0,<3",
    "setuptools",
]
test = [
    "diffusers",
    "transformers",
    "accelerate",
    "bitsandbytes",
    "torch==2.9.1",
    "torchao>=0.10.0,<0.11",
    "scipy",
    "peft",
    "kernels>=0.10.2,<0.11",
]

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["tests"]
env_files = ["tests/.env"]

[tool.coverage.run]
source = ["spaces"]
omit = [
    "spaces/zero/api.py",
    "spaces/zero/torch/aoti.py", # For now
    "spaces/zero/torch/patching_legacy.py",
    "spaces/zero/torch/bitsandbytes_legacy.py",
    "spaces/_vendor/*",
]
concurrency = ["thread", "multiprocessing"]

[tool.coverage.report]
fail_under = 100
exclude_also = [
    "^\\s*if TYPE_CHECKING:\\s*$",
    "^\\s*assert_never\\(.*\\)\\s*$",
    "^\\s*debug\\(.*\\)\\s*$",
    "^\\s*\\.\\.\\.\\s*$",
]

[tool.poe.tasks.test]
shell = """set -e
    pyright
    coverage erase
    coverage run -m pytest tests/cpu
    coverage run -m pytest tests/gpu
    find e2e -name '*.py' | xargs -I {} coverage run {}
    coverage combine -q
    coverage xml  || true
    coverage html || true
    coverage report -m
"""

[tool.poe.tasks.publish]
shell = """set -e
    git diff --quiet
    rm -rf dist
    uv build
    uv publish
"""

[tool.pyright]
include = ["spaces", "tests"]
exclude = ["spaces/_vendor"]
pythonVersion = "3.10"
reportPossiblyUnboundVariable = "error"
reportUnnecessaryComparison = true
reportPrivateImportUsage = "information"

[tool.uv]
constraint-dependencies = [
    "numpy<2",
    "peft<0.19",
    "transformers<4.51",
]

[build-system]
requires = ["uv_build>=0.11.6,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "spaces"
module-root = ""
