"""
Type annotations for outposts service literal definitions.

[Documentation](https://youtype.github.io/types_boto3_docs/types_boto3_outposts/literals/)

Copyright 2026 Vlad Emelianov

Usage::

    ```python
    from types_boto3_outposts.literals import AWSServiceNameType

    data: AWSServiceNameType = "AWS"
    ```
"""

import sys

if sys.version_info >= (3, 12):
    from typing import Literal
else:
    from typing_extensions import Literal

__all__ = (
    "AWSServiceNameType",
    "AddressTypeType",
    "AssetStateType",
    "AssetTypeType",
    "BlockingResourceTypeType",
    "CapacityTaskFailureTypeType",
    "CapacityTaskStatusType",
    "CatalogItemClassType",
    "CatalogItemStatusType",
    "ComputeAssetStateType",
    "CurrencyCodeType",
    "DecommissionRequestStatusType",
    "FiberOpticCableTypeType",
    "FormFactorType",
    "GetOutpostBillingInformationPaginatorName",
    "GetOutpostInstanceTypesPaginatorName",
    "GetOutpostSupportedInstanceTypesPaginatorName",
    "LineItemStatusType",
    "ListAssetInstancesPaginatorName",
    "ListAssetsPaginatorName",
    "ListBlockingInstancesForCapacityTaskPaginatorName",
    "ListCapacityTasksPaginatorName",
    "ListCatalogItemsPaginatorName",
    "ListOrderableInstanceTypesPaginatorName",
    "ListOrdersPaginatorName",
    "ListOutpostsPaginatorName",
    "ListQuotesPaginatorName",
    "ListSitesPaginatorName",
    "MaximumSupportedWeightLbsType",
    "OpticalStandardType",
    "OrderStatusType",
    "OrderTypeType",
    "OrderingRequirementStatusType",
    "OrderingRequirementTypeType",
    "OutpostGenerationType",
    "OutpostsServiceName",
    "PaginatorName",
    "PaymentOptionType",
    "PaymentTermType",
    "PowerConnectorType",
    "PowerDrawKvaType",
    "PowerFeedDropType",
    "PowerPhaseType",
    "PricingResultType",
    "QuoteCapacityTypeType",
    "QuoteConstraintTypeType",
    "QuotePricingTypeType",
    "QuoteRackUseTypeType",
    "QuoteSpecificationTypeType",
    "QuoteStatusType",
    "RackUnitHeightType",
    "RegionName",
    "ResourceServiceName",
    "ServiceName",
    "ShipmentCarrierType",
    "SubscriptionStatusType",
    "SubscriptionTypeType",
    "SupportedHardwareTypeType",
    "SupportedStorageEnumType",
    "TaskActionOnBlockingInstancesType",
    "UplinkCountType",
    "UplinkGbpsType",
)

AWSServiceNameType = Literal["AWS", "EC2", "EKS", "ELASTICACHE", "ELB", "RDS", "ROUTE53"]
AddressTypeType = Literal["OPERATING_ADDRESS", "SHIPPING_ADDRESS"]
AssetStateType = Literal["ACTIVE", "INSTALLING", "ISOLATED", "RETIRING"]
AssetTypeType = Literal["COMPUTE", "NETWORKING", "POWERSHELF", "STORAGE", "SWITCH"]
BlockingResourceTypeType = Literal[
    "EC2_INSTANCE",
    "LGW_ROUTE_TABLE",
    "LGW_ROUTING_DOMAIN",
    "LGW_VIRTUAL_INTERFACE_GROUP",
    "OUTPOST_ORDER_CANCELLABLE",
    "OUTPOST_ORDER_INTERVENTION_REQUIRED",
    "OUTPOST_RAM_SHARE",
]
CapacityTaskFailureTypeType = Literal[
    "BLOCKING_INSTANCES_NOT_EVACUATED",
    "INTERNAL_SERVER_ERROR",
    "RESOURCE_NOT_FOUND",
    "UNEXPECTED_ASSET_STATE",
    "UNSUPPORTED_CAPACITY_CONFIGURATION",
]
CapacityTaskStatusType = Literal[
    "CANCELLATION_IN_PROGRESS",
    "CANCELLED",
    "COMPLETED",
    "FAILED",
    "IN_PROGRESS",
    "REQUESTED",
    "WAITING_FOR_EVACUATION",
]
CatalogItemClassType = Literal["RACK", "SERVER"]
CatalogItemStatusType = Literal["AVAILABLE", "DISCONTINUED"]
ComputeAssetStateType = Literal["ACTIVE", "INSTALLING", "ISOLATED", "RETIRING"]
CurrencyCodeType = Literal["USD"]
DecommissionRequestStatusType = Literal["BLOCKED", "REQUESTED", "SKIPPED"]
FiberOpticCableTypeType = Literal["MULTI_MODE", "SINGLE_MODE"]
FormFactorType = Literal["RACK", "SERVER"]
GetOutpostBillingInformationPaginatorName = Literal["get_outpost_billing_information"]
GetOutpostInstanceTypesPaginatorName = Literal["get_outpost_instance_types"]
GetOutpostSupportedInstanceTypesPaginatorName = Literal["get_outpost_supported_instance_types"]
LineItemStatusType = Literal[
    "BUILDING",
    "CANCELLED",
    "DELIVERED",
    "ERROR",
    "INSTALLED",
    "INSTALLING",
    "PREPARING",
    "REPLACED",
    "SHIPPED",
]
ListAssetInstancesPaginatorName = Literal["list_asset_instances"]
ListAssetsPaginatorName = Literal["list_assets"]
ListBlockingInstancesForCapacityTaskPaginatorName = Literal[
    "list_blocking_instances_for_capacity_task"
]
ListCapacityTasksPaginatorName = Literal["list_capacity_tasks"]
ListCatalogItemsPaginatorName = Literal["list_catalog_items"]
ListOrderableInstanceTypesPaginatorName = Literal["list_orderable_instance_types"]
ListOrdersPaginatorName = Literal["list_orders"]
ListOutpostsPaginatorName = Literal["list_outposts"]
ListQuotesPaginatorName = Literal["list_quotes"]
ListSitesPaginatorName = Literal["list_sites"]
MaximumSupportedWeightLbsType = Literal[
    "MAX_1400_LBS", "MAX_1600_LBS", "MAX_1800_LBS", "MAX_2000_LBS", "NO_LIMIT"
]
OpticalStandardType = Literal[
    "OPTIC_1000BASE_LX",
    "OPTIC_1000BASE_SX",
    "OPTIC_100GBASE_CWDM4",
    "OPTIC_100GBASE_LR4",
    "OPTIC_100GBASE_SR4",
    "OPTIC_100G_PSM4_MSA",
    "OPTIC_10GBASE_IR",
    "OPTIC_10GBASE_LR",
    "OPTIC_10GBASE_SR",
    "OPTIC_40GBASE_ESR",
    "OPTIC_40GBASE_IR4_LR4L",
    "OPTIC_40GBASE_LR4",
    "OPTIC_40GBASE_SR",
]
OrderStatusType = Literal[
    "CANCELLED",
    "COMPLETED",
    "DELIVERED",
    "ERROR",
    "FULFILLED",
    "INSTALLING",
    "IN_PROGRESS",
    "PENDING",
    "PREPARING",
    "PROCESSING",
    "RECEIVED",
]
OrderTypeType = Literal["OUTPOST", "REPLACEMENT"]
OrderingRequirementStatusType = Literal["EXEMPT", "FAIL", "PASS"]
OrderingRequirementTypeType = Literal[
    "COUNTRY_CODE_MISMATCH_CHECK_ERROR",
    "ENTERPRISE_SUPPORT_ERROR",
    "MAXIMUM_ALLOWED_ORDERS_CHECK_ERROR",
    "OPERATING_ADDRESS_EXISTENCE_CHECK_ERROR",
    "OUTPOST_ACTIVE_CHECK_ERROR",
    "OUTPOST_GENERATION_MISMATCH_ERROR",
    "OUTPOST_ID_MISSING_ON_QUOTE_ERROR",
    "OUTPOST_NOT_FOUND_ERROR",
    "OUTPOST_RENEWAL_REQUIRED_ERROR",
    "OUTPOST_STATE_CHANGED_ERROR",
    "RACK_PHYSICAL_PROPERTIES_CHECK_ERROR",
    "SHIPPING_ADDRESS_EXISTENCE_CHECK_ERROR",
    "SHIPPING_ADDRESS_MISSING_CONTACT_INFO_ERROR",
    "SHIPPING_ADDRESS_MISSING_CONTACT_NAME_ERROR",
    "SHIPPING_ADDRESS_MISSING_CONTACT_NUMBER_ERROR",
    "UNSUPPORTED",
    "VALID_ZIP_CODE_CHECK_ERROR",
]
OutpostGenerationType = Literal["GENERATION_1", "GENERATION_2"]
PaymentOptionType = Literal["ALL_UPFRONT", "NO_UPFRONT", "PARTIAL_UPFRONT"]
PaymentTermType = Literal["FIVE_YEARS", "ONE_YEAR", "THREE_YEARS"]
PowerConnectorType = Literal["AH530P7W", "AH532P6W", "CS8365C", "IEC309", "L6_30P"]
PowerDrawKvaType = Literal["POWER_10_KVA", "POWER_15_KVA", "POWER_30_KVA", "POWER_5_KVA"]
PowerFeedDropType = Literal["ABOVE_RACK", "BELOW_RACK"]
PowerPhaseType = Literal["SINGLE_PHASE", "THREE_PHASE"]
PricingResultType = Literal["PRICED", "UNABLE_TO_PRICE"]
QuoteCapacityTypeType = Literal["EBS", "EC2", "S3"]
QuoteConstraintTypeType = Literal["RACK_MAXIMUM", "RACK_MAX_POWER_KVA", "RACK_MAX_WEIGHT_LBS"]
QuotePricingTypeType = Literal["SUBSCRIPTION"]
QuoteRackUseTypeType = Literal["COMPUTE", "NETWORKING"]
QuoteSpecificationTypeType = Literal["EXISTING_RACK", "NEW_RACK", "SERVER", "UPDATED_RACK"]
QuoteStatusType = Literal["CREATED", "EXPIRED", "ORDER_SUBMITTED"]
RackUnitHeightType = Literal["HEIGHT_1U", "HEIGHT_2U", "HEIGHT_42U"]
ShipmentCarrierType = Literal["DBS", "DHL", "EXPEDITORS", "FEDEX", "UPS"]
SubscriptionStatusType = Literal["ACTIVE", "CANCELLED", "INACTIVE", "PENDING"]
SubscriptionTypeType = Literal["CAPACITY_INCREASE", "ORIGINAL", "RENEWAL"]
SupportedHardwareTypeType = Literal["RACK", "SERVER"]
SupportedStorageEnumType = Literal["EBS", "S3"]
TaskActionOnBlockingInstancesType = Literal["FAIL_TASK", "WAIT_FOR_EVACUATION"]
UplinkCountType = Literal[
    "UPLINK_COUNT_1",
    "UPLINK_COUNT_12",
    "UPLINK_COUNT_16",
    "UPLINK_COUNT_2",
    "UPLINK_COUNT_3",
    "UPLINK_COUNT_4",
    "UPLINK_COUNT_5",
    "UPLINK_COUNT_6",
    "UPLINK_COUNT_7",
    "UPLINK_COUNT_8",
]
UplinkGbpsType = Literal["UPLINK_100G", "UPLINK_10G", "UPLINK_1G", "UPLINK_40G"]
OutpostsServiceName = Literal["outposts"]
ServiceName = Literal[
    "accessanalyzer",
    "account",
    "acm",
    "acm-pca",
    "agent-registry",
    "agent-registry-control",
    "aiops",
    "amp",
    "amplify",
    "amplifybackend",
    "amplifyuibuilder",
    "apigateway",
    "apigatewaymanagementapi",
    "apigatewayv2",
    "appconfig",
    "appconfigdata",
    "appfabric",
    "appflow",
    "appintegrations",
    "application-autoscaling",
    "application-insights",
    "application-signals",
    "applicationcostprofiler",
    "appmesh",
    "apprunner",
    "appstream",
    "appsync",
    "arc-region-switch",
    "arc-zonal-shift",
    "artifact",
    "athena",
    "auditmanager",
    "autoscaling",
    "autoscaling-plans",
    "b2bi",
    "backup",
    "backup-gateway",
    "backupsearch",
    "batch",
    "bcm-dashboards",
    "bcm-data-exports",
    "bcm-pricing-calculator",
    "bcm-recommended-actions",
    "bedrock",
    "bedrock-agent",
    "bedrock-agent-runtime",
    "bedrock-agentcore",
    "bedrock-agentcore-control",
    "bedrock-data-automation",
    "bedrock-data-automation-runtime",
    "bedrock-runtime",
    "billing",
    "billingconductor",
    "braket",
    "budgets",
    "ce",
    "chatbot",
    "chime",
    "chime-sdk-identity",
    "chime-sdk-media-pipelines",
    "chime-sdk-meetings",
    "chime-sdk-messaging",
    "chime-sdk-voice",
    "cleanrooms",
    "cleanroomsml",
    "cloud9",
    "cloudcontrol",
    "clouddirectory",
    "cloudformation",
    "cloudfront",
    "cloudfront-keyvaluestore",
    "cloudhsm",
    "cloudhsmv2",
    "cloudsearch",
    "cloudsearchdomain",
    "cloudtrail",
    "cloudtrail-data",
    "cloudwatch",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codeconnections",
    "codedeploy",
    "codeguru-reviewer",
    "codeguru-security",
    "codeguruprofiler",
    "codepipeline",
    "codestar-connections",
    "codestar-notifications",
    "cognito-identity",
    "cognito-idp",
    "cognito-sync",
    "comprehend",
    "comprehendmedical",
    "compute-optimizer",
    "compute-optimizer-automation",
    "config",
    "connect",
    "connect-contact-lens",
    "connectcampaigns",
    "connectcampaignsv2",
    "connectcases",
    "connecthealth",
    "connectparticipant",
    "controlcatalog",
    "controltower",
    "cost-optimization-hub",
    "cur",
    "customer-profiles",
    "databrew",
    "dataexchange",
    "datapipeline",
    "datasync",
    "datazone",
    "dax",
    "deadline",
    "detective",
    "devicefarm",
    "devops-agent",
    "devops-guru",
    "directconnect",
    "discovery",
    "dlm",
    "dms",
    "docdb",
    "docdb-elastic",
    "drs",
    "ds",
    "ds-data",
    "dsql",
    "dynamodb",
    "dynamodbstreams",
    "ebs",
    "ec2",
    "ec2-instance-connect",
    "ecr",
    "ecr-public",
    "ecs",
    "efs",
    "eks",
    "eks-auth",
    "elasticache",
    "elasticbeanstalk",
    "elb",
    "elbv2",
    "elementalinference",
    "emr",
    "emr-containers",
    "emr-serverless",
    "entityresolution",
    "es",
    "events",
    "evs",
    "finspace",
    "finspace-data",
    "firehose",
    "fis",
    "fms",
    "forecast",
    "forecastquery",
    "frauddetector",
    "freetier",
    "fsx",
    "gamelift",
    "gameliftstreams",
    "geo-maps",
    "geo-places",
    "geo-routes",
    "glacier",
    "globalaccelerator",
    "glue",
    "grafana",
    "greengrass",
    "greengrassv2",
    "groundstation",
    "guardduty",
    "health",
    "healthlake",
    "iam",
    "identitystore",
    "imagebuilder",
    "importexport",
    "inspector",
    "inspector-scan",
    "inspector2",
    "interconnect",
    "internetmonitor",
    "invoicing",
    "iot",
    "iot-data",
    "iot-jobs-data",
    "iot-managed-integrations",
    "iotdeviceadvisor",
    "iotfleetwise",
    "iotsecuretunneling",
    "iotsitewise",
    "iotthingsgraph",
    "iottwinmaker",
    "iotwireless",
    "ivs",
    "ivs-realtime",
    "ivschat",
    "kafka",
    "kafkaconnect",
    "kendra",
    "kendra-ranking",
    "keyspaces",
    "keyspacesstreams",
    "kinesis",
    "kinesis-video-archived-media",
    "kinesis-video-media",
    "kinesis-video-signaling",
    "kinesis-video-webrtc-storage",
    "kinesisanalytics",
    "kinesisanalyticsv2",
    "kinesisvideo",
    "kms",
    "lakeformation",
    "lambda",
    "lambda-core",
    "lambda-microvms",
    "launch-wizard",
    "lex-models",
    "lex-runtime",
    "lexv2-models",
    "lexv2-runtime",
    "license-manager",
    "license-manager-linux-subscriptions",
    "license-manager-user-subscriptions",
    "lightsail",
    "location",
    "logs",
    "lookoutequipment",
    "m2",
    "machinelearning",
    "macie2",
    "mailmanager",
    "managedblockchain",
    "managedblockchain-query",
    "marketplace-agreement",
    "marketplace-catalog",
    "marketplace-deployment",
    "marketplace-discovery",
    "marketplace-entitlement",
    "marketplace-reporting",
    "marketplacecommerceanalytics",
    "mediaconnect",
    "mediaconvert",
    "medialive",
    "mediapackage",
    "mediapackage-vod",
    "mediapackagev2",
    "mediastore",
    "mediastore-data",
    "mediatailor",
    "medical-imaging",
    "memorydb",
    "meteringmarketplace",
    "mgh",
    "mgn",
    "migration-hub-refactor-spaces",
    "migrationhub-config",
    "migrationhuborchestrator",
    "migrationhubstrategy",
    "mpa",
    "mq",
    "mturk",
    "mwaa",
    "mwaa-serverless",
    "neptune",
    "neptune-graph",
    "neptunedata",
    "network-firewall",
    "networkflowmonitor",
    "networkmanager",
    "networkmonitor",
    "notifications",
    "notificationscontacts",
    "nova-act",
    "oam",
    "observabilityadmin",
    "odb",
    "omics",
    "opensearch",
    "opensearchserverless",
    "organizations",
    "osis",
    "outposts",
    "partnercentral-account",
    "partnercentral-benefits",
    "partnercentral-channel",
    "partnercentral-revenue-measurement",
    "partnercentral-selling",
    "payment-cryptography",
    "payment-cryptography-data",
    "pca-connector-ad",
    "pca-connector-scep",
    "pcs",
    "personalize",
    "personalize-events",
    "personalize-runtime",
    "pi",
    "pinpoint",
    "pinpoint-email",
    "pinpoint-sms-voice",
    "pinpoint-sms-voice-v2",
    "pipes",
    "polly",
    "pricing",
    "pricing-plan-manager",
    "proton",
    "qapps",
    "qbusiness",
    "qconnect",
    "quicksight",
    "ram",
    "rbin",
    "rds",
    "rds-data",
    "redshift",
    "redshift-data",
    "redshift-serverless",
    "rekognition",
    "repostspace",
    "resiliencehub",
    "resiliencehubv2",
    "resource-explorer-2",
    "resource-groups",
    "resourcegroupstaggingapi",
    "rolesanywhere",
    "route53",
    "route53-recovery-cluster",
    "route53-recovery-control-config",
    "route53-recovery-readiness",
    "route53domains",
    "route53globalresolver",
    "route53profiles",
    "route53resolver",
    "rtbfabric",
    "rum",
    "s3",
    "s3control",
    "s3files",
    "s3outposts",
    "s3tables",
    "s3vectors",
    "sagemaker",
    "sagemaker-a2i-runtime",
    "sagemaker-edge",
    "sagemaker-featurestore-runtime",
    "sagemaker-geospatial",
    "sagemaker-metrics",
    "sagemaker-runtime",
    "sagemakerjobruntime",
    "savingsplans",
    "scheduler",
    "schemas",
    "sdb",
    "secretsmanager",
    "security-ir",
    "securityagent",
    "securityhub",
    "securitylake",
    "serverlessrepo",
    "service-quotas",
    "servicecatalog",
    "servicecatalog-appregistry",
    "servicediscovery",
    "ses",
    "sesv2",
    "shield",
    "signer",
    "signer-data",
    "signin",
    "simpledbv2",
    "snow-device-management",
    "snowball",
    "sns",
    "socialmessaging",
    "sqs",
    "ssm",
    "ssm-contacts",
    "ssm-guiconnect",
    "ssm-incidents",
    "ssm-quicksetup",
    "ssm-sap",
    "sso",
    "sso-admin",
    "sso-oidc",
    "stepfunctions",
    "storagegateway",
    "sts",
    "supplychain",
    "support",
    "support-app",
    "supportauthz",
    "sustainability",
    "swf",
    "synthetics",
    "taxsettings",
    "textract",
    "timestream-influxdb",
    "timestream-query",
    "timestream-write",
    "tnb",
    "transcribe",
    "transfer",
    "translate",
    "trustedadvisor",
    "uxc",
    "verifiedpermissions",
    "voice-id",
    "vpc-lattice",
    "waf",
    "waf-regional",
    "wafv2",
    "wellarchitected",
    "wickr",
    "wisdom",
    "workdocs",
    "workmail",
    "workmailmessageflow",
    "workspaces",
    "workspaces-instances",
    "workspaces-thin-client",
    "workspaces-web",
    "xray",
]
ResourceServiceName = Literal[
    "cloudformation", "cloudwatch", "dynamodb", "ec2", "glacier", "iam", "s3", "sns", "sqs"
]
PaginatorName = Literal[
    "get_outpost_billing_information",
    "get_outpost_instance_types",
    "get_outpost_supported_instance_types",
    "list_asset_instances",
    "list_assets",
    "list_blocking_instances_for_capacity_task",
    "list_capacity_tasks",
    "list_catalog_items",
    "list_orderable_instance_types",
    "list_orders",
    "list_outposts",
    "list_quotes",
    "list_sites",
]
RegionName = Literal[
    "af-south-1",
    "ap-east-1",
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-northeast-3",
    "ap-south-1",
    "ap-southeast-1",
    "ap-southeast-2",
    "ap-southeast-3",
    "ca-central-1",
    "eu-central-1",
    "eu-north-1",
    "eu-south-1",
    "eu-south-2",
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "il-central-1",
    "me-central-1",
    "me-south-1",
    "mx-central-1",
    "sa-east-1",
    "us-east-1",
    "us-east-2",
    "us-west-1",
    "us-west-2",
]
