# coding: utf-8

"""
    File Service API v3

    File Service API v3 - All v3 endpoints

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from istari_digital_client.legacy.v3.models.favorite_system_dto import FavoriteSystemDto
from istari_digital_client.legacy.v3.models.favorite_type import FavoriteType
from istari_digital_client.legacy.v3.models.resource_dto import ResourceDto
from typing import Optional, Set
from typing_extensions import Self

class FavoriteDto(BaseModel):
    """
    One favorited target. Exactly one of ``system``/``resource`` is set, matching ``favorite_type``.
    """ # noqa: E501
    favorite_type: FavoriteType
    favorited_at: datetime
    system: Optional[FavoriteSystemDto] = None
    resource: Optional[ResourceDto] = None
    __properties: ClassVar[List[str]] = ["favorite_type", "favorited_at", "system", "resource"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FavoriteDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of system
        if self.system:
            _dict['system'] = self.system.to_dict()
        # override the default output from pydantic by calling `to_dict()` of resource
        if self.resource:
            _dict['resource'] = self.resource.to_dict()
        # set to None if system (nullable) is None
        # and model_fields_set contains the field
        if self.system is None and "system" in self.model_fields_set:
            _dict['system'] = None

        # set to None if resource (nullable) is None
        # and model_fields_set contains the field
        if self.resource is None and "resource" in self.model_fields_set:
            _dict['resource'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FavoriteDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "favorite_type": obj.get("favorite_type"),
            "favorited_at": obj.get("favorited_at"),
            "system": FavoriteSystemDto.from_dict(obj["system"]) if obj.get("system") is not None else None,
            "resource": ResourceDto.from_dict(obj["resource"]) if obj.get("resource") is not None else None
        })
        return _obj
