[project]
name = "otel-ci"
version = "0.4.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.1"
dependencies = [
    "opentelemetry-exporter-otlp>=1.36.0,<1.39.0",
]

[tool.uv]
exclude-newer = "3 days"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "pdbpp>=0.10.3",
    "pre-commit>=4.0.1",
    "ruff>=0.8.3",
]

[project.scripts]
otel-ci = 'otel_ci.cli:main'

[tool.ruff]
