"""
Type annotations for odb service literal definitions.

[Documentation](https://youtype.github.io/types_aiobotocore_docs/types_aiobotocore_odb/literals/)

Copyright 2026 Vlad Emelianov

Usage::

    ```python
    from types_aiobotocore_odb.literals import AccessType

    data: AccessType = "DISABLED"
    ```
"""

import sys

if sys.version_info >= (3, 12):
    from typing import Literal
else:
    from typing_extensions import Literal


__all__ = (
    "AccessType",
    "AutonomousDatabaseBackupStatusType",
    "AutonomousDatabaseBackupTypeType",
    "AutonomousDatabaseResourceStatusType",
    "AutonomousDatabaseWalletStatusType",
    "AutonomousMaintenanceScheduleTypeType",
    "CharacterSetTypeType",
    "CloneTypeType",
    "ComputeModelType",
    "DataGuardRoleType",
    "DataSafeStatusType",
    "DatabaseEditionType",
    "DatabaseManagementStatusType",
    "DatabaseTypeType",
    "DayOfWeekNameType",
    "DbNodeMaintenanceTypeType",
    "DbNodeResourceStatusType",
    "DbServerPatchingStatusType",
    "DbWorkloadType",
    "DisasterRecoveryTypeType",
    "DiskRedundancyType",
    "EncryptionKeyProviderInputType",
    "EncryptionKeyProviderType",
    "ExternalIdTypeType",
    "IamRoleStatusType",
    "IormLifecycleStateType",
    "LicenseModelType",
    "ListAutonomousDatabaseBackupsPaginatorName",
    "ListAutonomousDatabaseCharacterSetsPaginatorName",
    "ListAutonomousDatabaseClonesPaginatorName",
    "ListAutonomousDatabasePeersPaginatorName",
    "ListAutonomousDatabaseVersionsPaginatorName",
    "ListAutonomousDatabasesPaginatorName",
    "ListAutonomousVirtualMachinesPaginatorName",
    "ListCloudAutonomousVmClustersPaginatorName",
    "ListCloudExadataInfrastructuresPaginatorName",
    "ListCloudVmClustersPaginatorName",
    "ListDbNodesPaginatorName",
    "ListDbServersPaginatorName",
    "ListDbSystemShapesPaginatorName",
    "ListGiVersionsPaginatorName",
    "ListOdbNetworksPaginatorName",
    "ListOdbPeeringConnectionsPaginatorName",
    "ListSystemVersionsPaginatorName",
    "ManagedResourceStatusType",
    "MonthNameType",
    "NetServicesArchitectureType",
    "ObjectiveType",
    "OciAwsIntegrationType",
    "OciOnboardingStatusType",
    "OdbServiceName",
    "OpenModeType",
    "OperationsInsightsStatusType",
    "PaginatorName",
    "PatchingModeTypeType",
    "PermissionLevelType",
    "PreferenceTypeType",
    "RefreshableModeType",
    "RefreshableStatusType",
    "RepeatCadenceType",
    "ResourceServiceName",
    "ResourceStatusType",
    "ServiceName",
    "ShapeTypeType",
    "SourceTypeType",
    "StandbyAllowlistedIpsSourceType",
    "SupportedAwsIntegrationType",
    "VpcEndpointTypeType",
    "WalletTypeType",
)


AccessType = Literal["DISABLED", "ENABLED"]
AutonomousDatabaseBackupStatusType = Literal["ACTIVE", "CREATING", "DELETING", "FAILED", "UPDATING"]
AutonomousDatabaseBackupTypeType = Literal[
    "CUMULATIVE_INCREMENTAL",
    "FULL",
    "INCREMENTAL",
    "LONGTERM",
    "ROLL_FORWARD_IMAGE_COPY",
    "VIRTUAL_FULL",
]
AutonomousDatabaseResourceStatusType = Literal[
    "AVAILABLE",
    "AVAILABLE_NEEDS_ATTENTION",
    "BACKUP_IN_PROGRESS",
    "FAILED",
    "INACCESSIBLE",
    "MAINTENANCE_IN_PROGRESS",
    "PROVISIONING",
    "RECREATING",
    "RESTARTING",
    "RESTORE_FAILED",
    "RESTORE_IN_PROGRESS",
    "ROLE_CHANGE_IN_PROGRESS",
    "SCALE_IN_PROGRESS",
    "STANDBY",
    "STARTING",
    "STOPPED",
    "STOPPING",
    "TERMINATED",
    "TERMINATING",
    "UNAVAILABLE",
    "UPDATING",
    "UPGRADING",
]
AutonomousDatabaseWalletStatusType = Literal["ACTIVE", "UPDATING"]
AutonomousMaintenanceScheduleTypeType = Literal["EARLY", "REGULAR"]
CharacterSetTypeType = Literal["DATABASE", "NATIONAL"]
CloneTypeType = Literal["FULL", "METADATA", "PARTIAL"]
ComputeModelType = Literal["ECPU", "OCPU"]
DataGuardRoleType = Literal[
    "BACKUP_COPY", "DISABLED_STANDBY", "PRIMARY", "SNAPSHOT_STANDBY", "STANDBY"
]
DataSafeStatusType = Literal[
    "DEREGISTERING", "FAILED", "NOT_REGISTERED", "REGISTERED", "REGISTERING"
]
DatabaseEditionType = Literal["ENTERPRISE_EDITION", "STANDARD_EDITION"]
DatabaseManagementStatusType = Literal[
    "DISABLING", "ENABLED", "ENABLING", "FAILED_DISABLING", "FAILED_ENABLING", "NOT_ENABLED"
]
DatabaseTypeType = Literal["CLONE", "REGULAR"]
DayOfWeekNameType = Literal[
    "FRIDAY", "MONDAY", "SATURDAY", "SUNDAY", "THURSDAY", "TUESDAY", "WEDNESDAY"
]
DbNodeMaintenanceTypeType = Literal["VMDB_REBOOT_MIGRATION"]
DbNodeResourceStatusType = Literal[
    "AVAILABLE",
    "FAILED",
    "PROVISIONING",
    "STARTING",
    "STOPPED",
    "STOPPING",
    "TERMINATED",
    "TERMINATING",
    "UPDATING",
]
DbServerPatchingStatusType = Literal["COMPLETE", "FAILED", "MAINTENANCE_IN_PROGRESS", "SCHEDULED"]
DbWorkloadType = Literal["AJD", "APEX", "LH", "OLTP"]
DisasterRecoveryTypeType = Literal["ADG", "BACKUP_BASED"]
DiskRedundancyType = Literal["HIGH", "NORMAL"]
EncryptionKeyProviderInputType = Literal["AWS_KMS", "ORACLE_MANAGED"]
EncryptionKeyProviderType = Literal["AWS_KMS", "OCI", "OKV", "ORACLE_MANAGED"]
ExternalIdTypeType = Literal["compartment_ocid", "database_ocid", "tenant_ocid"]
IamRoleStatusType = Literal[
    "ASSOCIATING",
    "CONNECTED",
    "DISASSOCIATING",
    "DISCONNECTED",
    "FAILED",
    "PARTIALLY_CONNECTED",
    "UNKNOWN",
]
IormLifecycleStateType = Literal["BOOTSTRAPPING", "DISABLED", "ENABLED", "FAILED", "UPDATING"]
LicenseModelType = Literal["BRING_YOUR_OWN_LICENSE", "LICENSE_INCLUDED"]
ListAutonomousDatabaseBackupsPaginatorName = Literal["list_autonomous_database_backups"]
ListAutonomousDatabaseCharacterSetsPaginatorName = Literal[
    "list_autonomous_database_character_sets"
]
ListAutonomousDatabaseClonesPaginatorName = Literal["list_autonomous_database_clones"]
ListAutonomousDatabasePeersPaginatorName = Literal["list_autonomous_database_peers"]
ListAutonomousDatabaseVersionsPaginatorName = Literal["list_autonomous_database_versions"]
ListAutonomousDatabasesPaginatorName = Literal["list_autonomous_databases"]
ListAutonomousVirtualMachinesPaginatorName = Literal["list_autonomous_virtual_machines"]
ListCloudAutonomousVmClustersPaginatorName = Literal["list_cloud_autonomous_vm_clusters"]
ListCloudExadataInfrastructuresPaginatorName = Literal["list_cloud_exadata_infrastructures"]
ListCloudVmClustersPaginatorName = Literal["list_cloud_vm_clusters"]
ListDbNodesPaginatorName = Literal["list_db_nodes"]
ListDbServersPaginatorName = Literal["list_db_servers"]
ListDbSystemShapesPaginatorName = Literal["list_db_system_shapes"]
ListGiVersionsPaginatorName = Literal["list_gi_versions"]
ListOdbNetworksPaginatorName = Literal["list_odb_networks"]
ListOdbPeeringConnectionsPaginatorName = Literal["list_odb_peering_connections"]
ListSystemVersionsPaginatorName = Literal["list_system_versions"]
ManagedResourceStatusType = Literal["DISABLED", "DISABLING", "ENABLED", "ENABLING"]
MonthNameType = Literal[
    "APRIL",
    "AUGUST",
    "DECEMBER",
    "FEBRUARY",
    "JANUARY",
    "JULY",
    "JUNE",
    "MARCH",
    "MAY",
    "NOVEMBER",
    "OCTOBER",
    "SEPTEMBER",
]
NetServicesArchitectureType = Literal["DEDICATED", "SHARED"]
ObjectiveType = Literal["AUTO", "BALANCED", "BASIC", "HIGH_THROUGHPUT", "LOW_LATENCY"]
OciAwsIntegrationType = Literal["KmsTde"]
OciOnboardingStatusType = Literal[
    "ACTIVATING",
    "ACTIVE",
    "ACTIVE_IN_HOME_REGION",
    "ACTIVE_LIMITED",
    "CANCELED",
    "FAILED",
    "NOT_STARTED",
    "PENDING_CUSTOMER_ACTION",
    "PENDING_INITIALIZATION",
    "PENDING_LINK_GENERATION",
    "PUBLIC_OFFER_UNSUPPORTED",
    "SUSPENDED",
]
OpenModeType = Literal["READ_ONLY", "READ_WRITE"]
OperationsInsightsStatusType = Literal[
    "DISABLING", "ENABLED", "ENABLING", "FAILED_DISABLING", "FAILED_ENABLING", "NOT_ENABLED"
]
PatchingModeTypeType = Literal["NONROLLING", "ROLLING"]
PermissionLevelType = Literal["RESTRICTED", "UNRESTRICTED"]
PreferenceTypeType = Literal["CUSTOM_PREFERENCE", "NO_PREFERENCE"]
RefreshableModeType = Literal["AUTOMATIC", "MANUAL"]
RefreshableStatusType = Literal["NOT_REFRESHING", "REFRESHING"]
RepeatCadenceType = Literal["MONTHLY", "ONE_TIME", "WEEKLY", "YEARLY"]
ResourceStatusType = Literal[
    "AVAILABLE",
    "FAILED",
    "MAINTENANCE_IN_PROGRESS",
    "PROVISIONING",
    "TERMINATED",
    "TERMINATING",
    "UPDATING",
]
ShapeTypeType = Literal["AMD", "AMPERE_FLEX_A1", "INTEL", "INTEL_FLEX_X9"]
SourceTypeType = Literal[
    "BACKUP_FROM_ID",
    "BACKUP_FROM_TIMESTAMP",
    "CLONE_TO_REFRESHABLE",
    "CROSS_REGION_DATAGUARD",
    "CROSS_REGION_DISASTER_RECOVERY",
    "DATABASE",
    "NONE",
]
StandbyAllowlistedIpsSourceType = Literal["NOT_APPLICABLE", "PRIMARY", "SEPARATE"]
SupportedAwsIntegrationType = Literal["KmsTde"]
VpcEndpointTypeType = Literal["SERVICENETWORK"]
WalletTypeType = Literal["INSTANCE", "REGIONAL"]
OdbServiceName = Literal["odb"]
ServiceName = Literal[
    "accessanalyzer",
    "account",
    "acm",
    "acm-pca",
    "aiops",
    "amp",
    "amplify",
    "amplifybackend",
    "amplifyuibuilder",
    "apigateway",
    "apigatewaymanagementapi",
    "apigatewayv2",
    "appconfig",
    "appconfigdata",
    "appfabric",
    "appflow",
    "appintegrations",
    "application-autoscaling",
    "application-insights",
    "application-signals",
    "applicationcostprofiler",
    "appmesh",
    "apprunner",
    "appstream",
    "appsync",
    "arc-region-switch",
    "arc-zonal-shift",
    "artifact",
    "athena",
    "auditmanager",
    "autoscaling",
    "autoscaling-plans",
    "b2bi",
    "backup",
    "backup-gateway",
    "backupsearch",
    "batch",
    "bcm-dashboards",
    "bcm-data-exports",
    "bcm-pricing-calculator",
    "bcm-recommended-actions",
    "bedrock",
    "bedrock-agent",
    "bedrock-agent-runtime",
    "bedrock-agentcore",
    "bedrock-agentcore-control",
    "bedrock-data-automation",
    "bedrock-data-automation-runtime",
    "bedrock-runtime",
    "billing",
    "billingconductor",
    "braket",
    "budgets",
    "ce",
    "chatbot",
    "chime",
    "chime-sdk-identity",
    "chime-sdk-media-pipelines",
    "chime-sdk-meetings",
    "chime-sdk-messaging",
    "chime-sdk-voice",
    "cleanrooms",
    "cleanroomsml",
    "cloud9",
    "cloudcontrol",
    "clouddirectory",
    "cloudformation",
    "cloudfront",
    "cloudfront-keyvaluestore",
    "cloudhsm",
    "cloudhsmv2",
    "cloudsearch",
    "cloudsearchdomain",
    "cloudtrail",
    "cloudtrail-data",
    "cloudwatch",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codeconnections",
    "codedeploy",
    "codeguru-reviewer",
    "codeguru-security",
    "codeguruprofiler",
    "codepipeline",
    "codestar-connections",
    "codestar-notifications",
    "cognito-identity",
    "cognito-idp",
    "cognito-sync",
    "comprehend",
    "comprehendmedical",
    "compute-optimizer",
    "compute-optimizer-automation",
    "config",
    "connect",
    "connect-contact-lens",
    "connectcampaigns",
    "connectcampaignsv2",
    "connectcases",
    "connecthealth",
    "connectparticipant",
    "controlcatalog",
    "controltower",
    "cost-optimization-hub",
    "cur",
    "customer-profiles",
    "databrew",
    "dataexchange",
    "datapipeline",
    "datasync",
    "datazone",
    "dax",
    "deadline",
    "detective",
    "devicefarm",
    "devops-agent",
    "devops-guru",
    "directconnect",
    "discovery",
    "dlm",
    "dms",
    "docdb",
    "docdb-elastic",
    "drs",
    "ds",
    "ds-data",
    "dsql",
    "dynamodb",
    "dynamodbstreams",
    "ebs",
    "ec2",
    "ec2-instance-connect",
    "ecr",
    "ecr-public",
    "ecs",
    "efs",
    "eks",
    "eks-auth",
    "elasticache",
    "elasticbeanstalk",
    "elb",
    "elbv2",
    "elementalinference",
    "emr",
    "emr-containers",
    "emr-serverless",
    "entityresolution",
    "es",
    "events",
    "evs",
    "finspace",
    "finspace-data",
    "firehose",
    "fis",
    "fms",
    "forecast",
    "forecastquery",
    "frauddetector",
    "freetier",
    "fsx",
    "gamelift",
    "gameliftstreams",
    "geo-maps",
    "geo-places",
    "geo-routes",
    "glacier",
    "globalaccelerator",
    "glue",
    "grafana",
    "greengrass",
    "greengrassv2",
    "groundstation",
    "guardduty",
    "health",
    "healthlake",
    "iam",
    "identitystore",
    "imagebuilder",
    "importexport",
    "inspector",
    "inspector-scan",
    "inspector2",
    "interconnect",
    "internetmonitor",
    "invoicing",
    "iot",
    "iot-data",
    "iot-jobs-data",
    "iot-managed-integrations",
    "iotdeviceadvisor",
    "iotfleetwise",
    "iotsecuretunneling",
    "iotsitewise",
    "iotthingsgraph",
    "iottwinmaker",
    "iotwireless",
    "ivs",
    "ivs-realtime",
    "ivschat",
    "kafka",
    "kafkaconnect",
    "kendra",
    "kendra-ranking",
    "keyspaces",
    "keyspacesstreams",
    "kinesis",
    "kinesis-video-archived-media",
    "kinesis-video-media",
    "kinesis-video-signaling",
    "kinesis-video-webrtc-storage",
    "kinesisanalytics",
    "kinesisanalyticsv2",
    "kinesisvideo",
    "kms",
    "lakeformation",
    "lambda",
    "lambda-core",
    "lambda-microvms",
    "launch-wizard",
    "lex-models",
    "lex-runtime",
    "lexv2-models",
    "lexv2-runtime",
    "license-manager",
    "license-manager-linux-subscriptions",
    "license-manager-user-subscriptions",
    "lightsail",
    "location",
    "logs",
    "lookoutequipment",
    "m2",
    "machinelearning",
    "macie2",
    "mailmanager",
    "managedblockchain",
    "managedblockchain-query",
    "marketplace-agreement",
    "marketplace-catalog",
    "marketplace-deployment",
    "marketplace-discovery",
    "marketplace-entitlement",
    "marketplace-reporting",
    "marketplacecommerceanalytics",
    "mediaconnect",
    "mediaconvert",
    "medialive",
    "mediapackage",
    "mediapackage-vod",
    "mediapackagev2",
    "mediastore",
    "mediastore-data",
    "mediatailor",
    "medical-imaging",
    "memorydb",
    "meteringmarketplace",
    "mgh",
    "mgn",
    "migration-hub-refactor-spaces",
    "migrationhub-config",
    "migrationhuborchestrator",
    "migrationhubstrategy",
    "mpa",
    "mq",
    "mturk",
    "mwaa",
    "mwaa-serverless",
    "neptune",
    "neptune-graph",
    "neptunedata",
    "network-firewall",
    "networkflowmonitor",
    "networkmanager",
    "networkmonitor",
    "notifications",
    "notificationscontacts",
    "nova-act",
    "oam",
    "observabilityadmin",
    "odb",
    "omics",
    "opensearch",
    "opensearchserverless",
    "organizations",
    "osis",
    "outposts",
    "partnercentral-account",
    "partnercentral-benefits",
    "partnercentral-channel",
    "partnercentral-revenue-measurement",
    "partnercentral-selling",
    "payment-cryptography",
    "payment-cryptography-data",
    "pca-connector-ad",
    "pca-connector-scep",
    "pcs",
    "personalize",
    "personalize-events",
    "personalize-runtime",
    "pi",
    "pinpoint",
    "pinpoint-email",
    "pinpoint-sms-voice",
    "pinpoint-sms-voice-v2",
    "pipes",
    "polly",
    "pricing",
    "proton",
    "qapps",
    "qbusiness",
    "qconnect",
    "quicksight",
    "ram",
    "rbin",
    "rds",
    "rds-data",
    "redshift",
    "redshift-data",
    "redshift-serverless",
    "rekognition",
    "repostspace",
    "resiliencehub",
    "resiliencehubv2",
    "resource-explorer-2",
    "resource-groups",
    "resourcegroupstaggingapi",
    "rolesanywhere",
    "route53",
    "route53-recovery-cluster",
    "route53-recovery-control-config",
    "route53-recovery-readiness",
    "route53domains",
    "route53globalresolver",
    "route53profiles",
    "route53resolver",
    "rtbfabric",
    "rum",
    "s3",
    "s3control",
    "s3files",
    "s3outposts",
    "s3tables",
    "s3vectors",
    "sagemaker",
    "sagemaker-a2i-runtime",
    "sagemaker-edge",
    "sagemaker-featurestore-runtime",
    "sagemaker-geospatial",
    "sagemaker-metrics",
    "sagemaker-runtime",
    "sagemakerjobruntime",
    "savingsplans",
    "scheduler",
    "schemas",
    "sdb",
    "secretsmanager",
    "security-ir",
    "securityagent",
    "securityhub",
    "securitylake",
    "serverlessrepo",
    "service-quotas",
    "servicecatalog",
    "servicecatalog-appregistry",
    "servicediscovery",
    "ses",
    "sesv2",
    "shield",
    "signer",
    "signer-data",
    "signin",
    "simpledbv2",
    "snow-device-management",
    "snowball",
    "sns",
    "socialmessaging",
    "sqs",
    "ssm",
    "ssm-contacts",
    "ssm-guiconnect",
    "ssm-incidents",
    "ssm-quicksetup",
    "ssm-sap",
    "sso",
    "sso-admin",
    "sso-oidc",
    "stepfunctions",
    "storagegateway",
    "sts",
    "supplychain",
    "support",
    "support-app",
    "supportauthz",
    "sustainability",
    "swf",
    "synthetics",
    "taxsettings",
    "textract",
    "timestream-influxdb",
    "timestream-query",
    "timestream-write",
    "tnb",
    "transcribe",
    "transfer",
    "translate",
    "trustedadvisor",
    "uxc",
    "verifiedpermissions",
    "voice-id",
    "vpc-lattice",
    "waf",
    "waf-regional",
    "wafv2",
    "wellarchitected",
    "wickr",
    "wisdom",
    "workdocs",
    "workmail",
    "workmailmessageflow",
    "workspaces",
    "workspaces-instances",
    "workspaces-thin-client",
    "workspaces-web",
    "xray",
]
ResourceServiceName = Literal[
    "cloudformation", "cloudwatch", "dynamodb", "ec2", "glacier", "iam", "s3", "sns", "sqs"
]
PaginatorName = Literal[
    "list_autonomous_database_backups",
    "list_autonomous_database_character_sets",
    "list_autonomous_database_clones",
    "list_autonomous_database_peers",
    "list_autonomous_database_versions",
    "list_autonomous_databases",
    "list_autonomous_virtual_machines",
    "list_cloud_autonomous_vm_clusters",
    "list_cloud_exadata_infrastructures",
    "list_cloud_vm_clusters",
    "list_db_nodes",
    "list_db_servers",
    "list_db_system_shapes",
    "list_gi_versions",
    "list_odb_networks",
    "list_odb_peering_connections",
    "list_system_versions",
]
