[package]
name = "oai-statsig-grpc"
description = "Statsig with gRPC support."
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
async-trait = "0.1.92"
tonic = { version = "0.14.6", features = ["tls-ring"] }
parking_lot = "0.12.5"
prost = "0.14.4"
tonic-prost = "0.14.6"
log = "0.4.34"
chrono = "0.4.45"
lazy_static = "1.5.0"

[build-dependencies]
tonic-prost-build = "0.14.6"

[[bin]]
name = "mock_grpc_server"
path = "src/mock_forward_proxy.rs"
