[project]
[project.markdown_extensions]
admonition = {}
abbr = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
"mkdocs-click" = {}

# [project.markdown_extensions.zensical.extensions.macros]
# module_name = "macros"
# macros_file = "src/atlasdocs/atlasdocs/macros/main.py"

[project.markdown_extensions.pymdownx.snippets]
base_path = ["docs/", "."]
restrict_base_path = false

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.betterem]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.highlight]
auto_title = true
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]

[project.markdown_extensions.tables]

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions.pymdownx.tilde]

[project.markdown_extensions."zen_macros_ext:MacroExtension"]
project_dir = "."
docs_dir = "docs"
macros_file = "src/atlasdocs/atlasdocs/macros/main.py"