"""Cortex: Modular neural stack library for stateful memory cores and composable scaffolds."""

from cortex.cells import (
    AGaLiTeCellConfig,
    AxonCellConfig,
    CausalConv1dCellConfig,
    CellConfig,
    LSTMCellConfig,
    XLCellConfig,
    default_cells,
    mLSTMCellConfig,
    sLSTMCellConfig,
)
from cortex.cognitive_substrate import (
    DecisionBox,
    DefaultDecisionBox,
    DefaultPredictiveBox,
    DefaultSuccessorBox,
    PredictiveBox,
    SuccessorBox,
    future_valid_mask,
    masked_kl_from_target_log_probs,
    masked_mean,
    masked_mse,
    successor_intrinsic_reward,
)
from cortex.config import (
    AdapterScaffoldConfig,
    AGaLiTeCoreConfig,
    AxonCoreConfig,
    CausalConv1dCoreConfig,
    ColumnScaffoldConfig,
    CoreConfig,
    CortexStackConfig,
    LSTMCoreConfig,
    MultiScaleLayerConfig,
    MultiScaleStackConfig,
    PassThroughScaffoldConfig,
    PostUpGatedScaffoldConfig,
    PostUpScaffoldConfig,
    PreUpGatedScaffoldConfig,
    PreUpScaffoldConfig,
    RoutedAdapterConfig,
    RouterConfig,
    ScaffoldConfig,
    XLCoreConfig,
    mLSTMCoreConfig,
    sLSTMCoreConfig,
)
from cortex.consistent_dropout import (
    ConsistentDropout,
    ConsistentDropoutModule,
    reset_consistent_dropout,
)
from cortex.cores import (
    AxonCore,
    AxonLayer,
    CausalConv1dCore,
    LSTMCore,
    MemoryCore,
    XLCore,
    build_core,
    mLSTMCore,
    register_core,
    sLSTMCore,
)
from cortex.fabric import (
    AnatomySpec,
    Fabric,
    FabricConfig,
    FabricFamilyConfig,
    FabricRuntime,
    FabricSpec,
    build_fabric,
    init_fabric,
)
from cortex.factory import build_cortex, build_from_dict
from cortex.prewarm import prewarm_policy_kernels
from cortex.routed_adapter import (
    RoutedAdapterHeadwiseLinearExpand,
    RoutedAdapterLinear,
    apply_routed_adapter_,
    get_route_ids,
    set_trunk_lr_mult_,
    use_route_ids,
)
from cortex.scaffolds import (
    AdapterScaffold,
    BaseScaffold,
    ColumnScaffold,
    PassThroughScaffold,
    PostUpGatedScaffold,
    PostUpScaffold,
    PreUpGatedScaffold,
    PreUpScaffold,
    build_column_auto_config,
    build_column_auto_scaffold,
    build_scaffold,
    register_scaffold,
)
from cortex.stacks import (
    CortexStack,
    MultiScaleStack,
    build_multiscale_stack,
    build_multiscale_stack_config,
)
from cortex.types import MaybeState, ResetMask, State, Tensor
from cortex.utils import TRITON_AVAILABLE, select_backend

__all__ = [
    # Configuration
    "ScaffoldConfig",
    "AdapterScaffoldConfig",
    "RoutedAdapterConfig",
    "ColumnScaffoldConfig",
    "PassThroughScaffoldConfig",
    "PreUpScaffoldConfig",
    "PreUpGatedScaffoldConfig",
    "PostUpScaffoldConfig",
    "PostUpGatedScaffoldConfig",
    "RouterConfig",
    "CortexStackConfig",
    "MultiScaleLayerConfig",
    "MultiScaleStackConfig",
    "CoreConfig",
    "CellConfig",
    "AGaLiTeCellConfig",
    "AxonCellConfig",
    "CausalConv1dCellConfig",
    "LSTMCellConfig",
    "XLCellConfig",
    "mLSTMCellConfig",
    "sLSTMCellConfig",
    "default_cells",
    "AGaLiTeCoreConfig",
    "AxonCoreConfig",
    "CausalConv1dCoreConfig",
    "LSTMCoreConfig",
    "XLCoreConfig",
    "mLSTMCoreConfig",
    "sLSTMCoreConfig",
    # Main classes
    "CortexStack",
    "MultiScaleStack",
    "Fabric",
    "FabricRuntime",
    # Cores
    "MemoryCore",
    "AxonCore",
    "AxonLayer",
    "CausalConv1dCore",
    "LSTMCore",
    "XLCore",
    "mLSTMCore",
    "sLSTMCore",
    "register_core",
    "build_core",
    # Scaffolds
    "BaseScaffold",
    "AdapterScaffold",
    "ColumnScaffold",
    "build_column_auto_config",
    "build_column_auto_scaffold",
    "PassThroughScaffold",
    "PreUpScaffold",
    "PreUpGatedScaffold",
    "PostUpScaffold",
    "PostUpGatedScaffold",
    "register_scaffold",
    "build_scaffold",
    # Routed adapters
    "RoutedAdapterLinear",
    "RoutedAdapterHeadwiseLinearExpand",
    "apply_routed_adapter_",
    "get_route_ids",
    "set_trunk_lr_mult_",
    "use_route_ids",
    # Types
    "MaybeState",
    "ResetMask",
    "State",
    "Tensor",
    # Factory functions
    "build_cortex",
    "build_from_dict",
    "prewarm_policy_kernels",
    "build_multiscale_stack",
    "build_multiscale_stack_config",
    "build_fabric",
    "init_fabric",
    # Cognitive substrate
    "DecisionBox",
    "PredictiveBox",
    "SuccessorBox",
    "DefaultDecisionBox",
    "DefaultPredictiveBox",
    "DefaultSuccessorBox",
    "future_valid_mask",
    "masked_mean",
    "masked_mse",
    "masked_kl_from_target_log_probs",
    "successor_intrinsic_reward",
    # Utils
    "TRITON_AVAILABLE",
    "select_backend",
    # Dropout
    "ConsistentDropout",
    "ConsistentDropoutModule",
    "reset_consistent_dropout",
    # Fabric
    "AnatomySpec",
    "FabricConfig",
    "FabricFamilyConfig",
    "FabricSpec",
]
