[project]
name = "cement"
description = "Application Framework for Python"
readme = "README.md"
keywords = [
    "python",
    "module",
    "cli framework",
]
authors = [
    { name = "Data Folk Labs, LLC", email = "derks@datafolklabs.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
]
dynamic = [
    "README",
]
requires-python = ">=3.10"
dependencies = []
version = "3.0.16"

[project.license]
file = "LICENSE"

[project.optional-dependencies]
alarm = []
argparse = []
colorlog = [
    "colorlog",
]
configparser = []
daemon = []
docs = [
    "sphinx",
    "sphinx_rtd_theme",
    "guzzle_sphinx_theme",
    "sphinxcontrib-napoleon",
]
dummy = []
generate = [
    "pyYaml",
]
jinja2 = [
    "jinja2",
]
json = []
logging = []
memcached = [
    "pylibmc",
]
mustache = [
    "pystache",
]
plugin = []
print = []
redis = [
    "redis",
]
scrub = []
smtp = []
tabulate = [
    "tabulate",
]
watchdog = [
    "watchdog",
]
yaml = [
    "pyYaml",
]
cli = [
    "cement[yaml,jinja2]",
]

[project.scripts]
cement = "cement.cli.main:main"

[project.urls]
homepage = "https://builtoncement.com"
documentation = "https://docs.builtoncement.com"
repository = "https://github.com/datafolklabs/cement"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = "-v --cov-report=term --cov-report=html:coverage-report --cov-fail-under=100 --capture=sys tests/"
python_files = "test_*.py"

[tool.coverage.run]
source = [
    "cement",
]
omit = [
    "cement/cli/templates/*",
    "cement/cli/contrib/*",
]

[tool.coverage.report]
precision = 2
fail_under = 100

[tool.ruff]
target-version = "py310"
line-length = 100
indent-width = 4
exclude = [
    ".git",
    "cement/cli/templates",
    "cement/cli/contrib",
]
include = [
    "cement/**/*.py",
    "tests/**/*.py",
]

[tool.ruff.lint]
preview = false
extend-select = [
    "E",
    "F",
    "W",
    "B",
    "I",
    "A",
    "C90",
    "N",
    "PT",
    "T20",
    "YTT",
    "UP",
    "FA",
]
ignore = [
    "A001",
    "A002",
    "C901",
]
fixable = [
    "ALL",
]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "N806",
    "N805",
    "PT012",
    "PT013",
]

[tool.mypy]
python_version = "3.10"
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_any_unimported = false
disallow_incomplete_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true
disable_error_code = [
    "attr-defined",
]
files = [
    "cement/",
]
exclude = "(?x)(\n    ^cement/cli/templates |\n    ^.git/ |\n    ^tests\n  )"

[tool.pdm.scripts.cement]
call = "cement.cli.main:main"

[tool.pdm.build]
package-dir = "."
includes = [
    "cement/",
    "cement/cli/templates/generate/",
    "CONTRIBUTORS.md",
    "CHANGELOG.md",
]
excludes = [
    "tests/",
]

[tool.pdm.version]
source = "call"
getter = "cement.utils.version:get_version"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "coverage>=7.13.5",
    "mypy~=1.20.2",
    "ruff~=0.15.12",
    "mock>=5.1.0",
    "pypng>=0.20220715.0",
    "requests>=2.31.0",
    "commitizen>=4.10.1",
]
