[build-system]
requires = [
    "pdm-backend",
    "acres",
    "pyyaml",
]
build-backend = "pdm.backend"

[project]
name = "bidsschematools"
description = "Python tools for working with the BIDS schema."
authors = [
    { name = "bids-standard developers" },
]
maintainers = [
    { name = "bids-standard developers", email = "bids.maintenance@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "acres>=0.5",
    "click>=8.1",
    "pyyaml>=6.0",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dynamic = []
version = "1.2.2"

[project.license]
text = "MIT"

[project.optional-dependencies]
expressions = [
    "pyparsing>=3.2",
]
render = [
    "tabulate>=0.9",
    "numpy>=1.26",
    "pandas>=2.0",
    "markdown-it-py>=3.0",
    "pymdown-extensions>=9.2",
]
validation = [
    "jsonschema[format]>=4.22",
]
all = [
    "bidsschematools[expressions,render,validation]",
]

[project.scripts]
bst = "bidsschematools.__main__:cli"

[project.urls]
Homepage = "https://github.com/bids-standard/bids-specification"

[dependency-groups]
dev = [
    "ruff>=0.15.6",
]
tests = [
    "bidsschematools[all]",
    "check-jsonschema>=0.36.2",
    "coverage[toml]>=7.10.7",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-xdist>=3.8.0",
]
types = [
    "lxml>=6.0.2",
    "mypy>=1.18.2",
    "pandas-stubs>=2.2.2.240807",
    "types-jsonschema>=4.25.1.20251009",
    "types-pyyaml>=6.0.12.20250915",
    "types-tabulate>=0.9.0.20241207",
]

[tool.pdm.build]
excludes = [
    ".gitignore",
    "**/.gitignore",
]

[tool.black]
exclude = "*"

[tool.pytest.ini_options]
addopts = "-ra --strict-markers --strict-config"
log_cli = true
log_cli_level = "INFO"
markers = [
    "validate_schema: tests that validate the schema itself",
]
minversion = "6.0"
xfail_strict = true

[tool.coverage.paths]
source = [
    "src/bidsschematools",
    "**/site-packages/bidsschematools",
]

[tool.coverage.run]
parallel = true

[tool.coverage.report]
exclude_also = [
    "if.*TYPE_CHECKING:",
]

[tool.bumpversion]
current_version = "1.2.2"
parse = "(?x)\n    (?P<major>[0-9]+)\n    \\.(?P<minor>[0-9]+)\n    \\.(?P<patch>[0-9]+)\n    (?:-(?P<pre_label>dev))?\n"
serialize = [
    "{major}.{minor}.{patch}-{pre_label}",
    "{major}.{minor}.{patch}",
]
commit = true
message = "chore: Bump schema package to {new_version}"
tag = false
tag_name = "schema-{new_version}"
tag_message = "Schema release {new_version}"
files = [
    { filename = "../../src/schema/SCHEMA_VERSION" },
]

[tool.bumpversion.parts.pre_label]
values = [
    "dev",
    "final",
]
optional_value = "final"

[tool.ruff]
line-length = 99

[tool.ruff.lint]
typing-modules = [
    "bidsschematools._lazytypes",
]
select = [
    "E",
    "W",
    "F",
    "PLE",
    "I",
    "LOG",
    "G",
    "Q",
    "YTT",
    "ISC",
    "UP",
]

[tool.ruff.lint.extend-per-file-ignores]
"*/__init__.py" = [
    "F401",
]
