[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "anomalo"
version = "0.46.0"
description = "Python bindings for the Anomalo API"
readme = "README.public.md"
license = "Apache-2.0"
requires-python = ">=3.9"
authors = [{ name = "Anomalo", email = "support@anomalo.com" }]
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "dataclasses-json>=0.5.7",
    "fire>=0.7.0",
    "pyyaml>=6.0.1",
    "requests>=2.20.0",
    "tenacity>=8.1.0",
    "casefy>=1.1.0",
]

[project.optional-dependencies]
shacl = ["pyshacl>=0.29.0", "rdflib>=7.6.0"]

[project.scripts]
anomalo = "anomalo.anomalo:main"

[project.urls]
Homepage = "https://anomalo.com"

[tool.hatch.build.targets.wheel]
packages = ["anomalo"]

[tool.uv]
exclude-newer = "4 days"

[tool.ruff]
extend = "../../pyproject.toml"
target-version = "py38"

# vim: ft=cfg
