[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "datazets"
dynamic = ["version"]
authors = [{ name = "Erdogan Taskesen", email = "erdogant@gmail.com" },]
description = "Datazets is a python package to import well known example data sets."
readme = "README.md"
requires-python = ">=3"
license = "MIT"
keywords = [
    "Python",
    "datasets",
    "data",
    "example datasets",
    "sample data",
    "machine learning",
    "data science",
    "import",
    "open data",
    "benchmark",
    "testing",
    "education",
    "research"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: Unix",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    'numpy',
    'pandas',
    'requests',
]

[project.urls]
Homepage = "https://erdogant.github.io/datazets"
Download = "https://github.com/erdogant/datazets/archive/{version}.tar.gz"

[tool.setuptools]
packages = ["datazets"]
include-package-data = true

[tool.setuptools.dynamic]
version = { attr = "datazets.__version__" }
