# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from chalk._gen.chalk.sandbox.v1 import runtime_service_pb2 as chalk_dot_sandbox_dot_v1_dot_runtime__service__pb2


class SandboxRuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutePython = channel.stream_stream(
            "/chalk.sandbox.v1.SandboxRuntimeService/ExecutePython",
            request_serializer=chalk_dot_sandbox_dot_v1_dot_runtime__service__pb2.ExecutePythonRequest.SerializeToString,
            response_deserializer=chalk_dot_sandbox_dot_v1_dot_runtime__service__pb2.ExecutePythonResponse.FromString,
        )


class SandboxRuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecutePython(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SandboxRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecutePython": grpc.stream_stream_rpc_method_handler(
            servicer.ExecutePython,
            request_deserializer=chalk_dot_sandbox_dot_v1_dot_runtime__service__pb2.ExecutePythonRequest.FromString,
            response_serializer=chalk_dot_sandbox_dot_v1_dot_runtime__service__pb2.ExecutePythonResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "chalk.sandbox.v1.SandboxRuntimeService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class SandboxRuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecutePython(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/chalk.sandbox.v1.SandboxRuntimeService/ExecutePython",
            chalk_dot_sandbox_dot_v1_dot_runtime__service__pb2.ExecutePythonRequest.SerializeToString,
            chalk_dot_sandbox_dot_v1_dot_runtime__service__pb2.ExecutePythonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
