from __future__ import annotations

from chalk.features._encoding._feature_converters import (  # noqa: F401
    _DEFAULT_FEATURE_ENCODING_OPTIONS,
    _FROM_NEW,
    _UNSUPPORTED_MISSING_VALUE_STRATEGY_MESSAGE,
    BoolFeatureConverter,
    BytesFeatureConverter,
    DataclassFeatureConverter,
    Date32FeatureConverter,
    Date64FeatureConverter,
    DatetimeFeatureConverter,
    FeatureConverter,
    Float32FeatureConverter,
    Float64FeatureConverter,
    GenericFeatureConverter,
    Int32FeatureConverter,
    Int64FeatureConverter,
    JSONCodec,
    LargeBinaryFeatureConverter,
    LargeStringFeatureConverter,
    ListFeatureConverter,
    MissingValueError,
    PrimitiveFeatureConverter,
    StringFeatureConverter,
    TDecoder,
    TEncoder,
    Time32msFeatureConverter,
    Time32sFeatureConverter,
    Time64nsFeatureConverter,
    Time64usFeatureConverter,
    TimedeltaFeatureConverter,
    _build_dc_to_dict,
    _build_dict_to_dc,
    _build_to_primitive_converter,
    _build_to_rich_converter,
    _decode_json,
    _encode_json,
    _FeatureConverterArrowProtoHelpers,
    _identity,
    _logger,
    _raise_unsupported_missing_value_strategy,
    _recursively_unwrap,
    _to_old_style_type,
    _TPrim,
    _TPrimCo,
    _TPrimCon,
    _TRich,
    _TRichCo,
    _TRichCon,
    _TScalar,
    _unwrap_scalar_value,
    canonicalize_typ,
    make_feature_converter,
    make_primitive_converter,
)

# Also re-export items that were previously transitively importable from this module.
from chalk.features._encoding.primitive import TPrimitive  # noqa: F401
from chalk.features._encoding.pyarrow import pyarrow_to_polars  # noqa: F401

# pyright: reportPrivateUsage=false


# This file is a backward-compatibility shim.
# All implementation has been moved to chalk.features._encoding._feature_converters.
# Any existing `from chalk.features._encoding.converter import X` will continue to work.


__all__ = [
    "TPrimitive",
    "pyarrow_to_polars",
    "_DEFAULT_FEATURE_ENCODING_OPTIONS",
    "_FROM_NEW",
    "_FeatureConverterArrowProtoHelpers",
    "_TPrim",
    "_TPrimCo",
    "_TPrimCon",
    "_TRich",
    "_TRichCo",
    "_TRichCon",
    "_TScalar",
    "_identity",
    "_logger",
    "_raise_unsupported_missing_value_strategy",
    "_unwrap_scalar_value",
    "_UNSUPPORTED_MISSING_VALUE_STRATEGY_MESSAGE",
    "FeatureConverter",
    "MissingValueError",
    "BoolFeatureConverter",
    "BytesFeatureConverter",
    "LargeBinaryFeatureConverter",
    "DataclassFeatureConverter",
    "Date32FeatureConverter",
    "Date64FeatureConverter",
    "DatetimeFeatureConverter",
    "_build_dc_to_dict",
    "_build_dict_to_dc",
    "_build_to_primitive_converter",
    "_build_to_rich_converter",
    "make_feature_converter",
    "make_primitive_converter",
    "GenericFeatureConverter",
    "JSONCodec",
    "TDecoder",
    "TEncoder",
    "_decode_json",
    "_encode_json",
    "_to_old_style_type",
    "canonicalize_typ",
    "Float32FeatureConverter",
    "Float64FeatureConverter",
    "Int32FeatureConverter",
    "LargeStringFeatureConverter",
    "Int64FeatureConverter",
    "ListFeatureConverter",
    "PrimitiveFeatureConverter",
    "_recursively_unwrap",
    "StringFeatureConverter",
    "Time32sFeatureConverter",
    "Time32msFeatureConverter",
    "Time64usFeatureConverter",
    "Time64nsFeatureConverter",
    "TimedeltaFeatureConverter",
]
