"""Auto-generated stub for module: 1-5_align_phase."""
from typing import Any, Dict

# Constants
VERIFY_COLORS: Dict[Any, Any]
state: Dict[Any, Any]

# Functions
def clamp_di(i: Any) -> Any: ...
def class_label(cid: Any) -> Any: ...
def color_for(cid: Any) -> Any: ...
def draw_box(img: Any, det: Any, w: Any, h: Any) -> Any: ...
def draw_overlay(img: Any) -> Any: ...
def get_dets(src_idx: Any) -> Any: ...
def main() -> Any: ...
def move_detection(delta: Any) -> Any: ...
def move_video(delta: Any) -> Any: ...
def read_video_frame(idx: Any) -> Any: ...
def render() -> Any: ...
def save_aligned(out_path: Any) -> Any: ...
def src_idx_now() -> Any: ...
def toggle_set() -> Any: ...
def wrap_vf(v: Any) -> Any: ...
