"""Auto-generated stub for module: 2_verify."""
from typing import Any, Dict

# Constants
VERIFY_COLORS: Dict[Any, Any]
state: Dict[Any, Any]

# Functions
def adjust_phase(delta: Any) -> Any:
    """
    Nudge the constant Case-B rotation S used to seek the video (wraps mod N).
    """
    ...
def class_label(cid: Any) -> Any: ...
def color_for(cid: Any) -> Any: ...
def draw_box(img: Any, det: Any, w: Any, h: Any) -> Any: ...
def draw_overlay(img: Any) -> Any: ...
def ensure_opencv_gui() -> Any: ...
def export_annotated(video_path: Any, out_path: Any) -> Any:
    """
    Render saved boxes onto ONLY the sampled frames, written in sample order.
    """
    ...
def find_box_at(src_idx: Any, x: Any, y: Any) -> Any: ...
def get_dets(src_idx: Any) -> Any: ...
def main() -> Any: ...
def on_mouse(event: Any, x: Any, y: Any, flags: Any, _userdata: Any) -> Any: ...
def read_video_frame(video_frame_idx: Any) -> Any: ...
def render_frame() -> Any: ...
def save_json() -> Any: ...
def src_idx_now() -> Any: ...
def video_frame_now() -> Any: ...
