"""Auto-generated stub for module: 3_track."""
from typing import Any

# Functions
def assign_track_ids(data: Any, frame_rate: Any, track_thresh: Any, match_thresh: Any, lost_buffer: Any) -> Any: ...
def color_for(tid: Any, class_id: Any = 0) -> Any: ...
def main() -> Any: ...
def parse_args() -> Any: ...
def render(video_path: Any, out_path: Any, data: Any, phase_offset: Any) -> Any: ...
