[build-system]
requires = ["uv_build>=0.9.6,<1.0"]
build-backend = "uv_build"

[project]
name = "bioversions"
version = "0.10.96"
description = "Get the current version for biological databases"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Framework :: Pytest",
    "Framework :: tox",
    "Framework :: Sphinx",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Typing :: Typed",
]
keywords = [
    "snekpack",
    "cookiecutter",
    "databases",
    "biological databases",
    "biomedical databases",
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = [
    "requests",
    "beautifulsoup4",
    "pystow[bs4]>=0.8.0",
    "click",
    "click-default-group",
    "tabulate",
    "more_click",
    "pyyaml",
    "tqdm",
    "bioregistry[align]>=0.13.47",
    "lxml",
    "pydantic>=2.0",
    "psycopg2-binary",
    "python-dateutil",
    "class-resolver>=0.7.1",
    "ror-downloader>=0.0.4",
]

[[project.authors]]
name = "Charles Tapley Hoyt"
email = "cthoyt@gmail.com"

[[project.maintainers]]
name = "Charles Tapley Hoyt"
email = "cthoyt@gmail.com"

[project.optional-dependencies]
slack = ["slack_sdk"]
twitter = ["tweepy"]
charts = [
    "matplotlib",
    "seaborn",
]
web = [
    "flask",
    "bootstrap-flask",
]

[project.urls]
"Bug Tracker" = "https://github.com/biopragmatics/bioversions/issues"
Homepage = "https://github.com/biopragmatics/bioversions"
Repository = "https://github.com/biopragmatics/bioversions.git"
Documentation = "https://bioversions.readthedocs.io"
Funding = "https://github.com/sponsors/cthoyt"

[project.scripts]
bioversions = "bioversions.cli:main"

[dependency-groups]
tests = [
    "pytest",
    "coverage[toml]",
]
docs = [
    "sphinx>=8",
    "sphinx-rtd-theme>=3.0",
    "sphinx-click",
    "sphinx-automodapi",
]
lint = ["ruff"]
typing = [
    { include-group = "tests" },
    "mypy>=1.20.2",
    "pydantic",
    "types-PyYAML",
    "types-python-dateutil",
    "types-requests",
    "types-tabulate",
    "types-click",
]
docs-lint = [
    { include-group = "docs" },
    "doc8",
]
format-docs = [
    { include-group = "docs" },
    "docstrfmt",
]
doctests = [
    "xdoctest",
    "pygments",
]
pyroma = [
    "pyroma",
    "pygments",
]
bump = ["bump-my-version"]
build = [
    "uv>=0.9.6",
    "uv-build>=0.9.6",
]
release = [
    { include-group = "build" },
    "uv",
    "keyring",
]

[tool.cruft]
skip = [
    "**/__init__.py",
    "tests/*",
]

[tool.mypy]
plugins = ["pydantic.mypy"]

[tool.doc8]
max-line-length = 120

[tool.pytest.ini_options]
markers = ["""slow: marks tests as slow (deselect with '-m "not slow"')"""]

[tool.coverage.run]
branch = true
source = ["bioversions"]
omit = [
    "tests/*",
    "docs/*",
    "src/bioversions/version.py",
    "src/bioversions/__main__.py",
    "src/bioversions/cli.py",
]

[tool.coverage.paths]
source = [
    "src/bioversions",
    ".tox/*/lib/python*/site-packages/bioversions",
]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    'if __name__ == "__main__":',
    "if TYPE_CHECKING:",
    "def __str__",
    "def __repr__",
]

[tool.ruff]
line-length = 100
extend-include = ["*.ipynb"]

[tool.ruff.lint]
extend-select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "UP",
    "D",
    "DOC",
    "B",
    "S",
    "T20",
    "N",
    "ERA",
    "NPY",
    "RUF",
    "C4",
]
ignore = [
    "D105",
    "E203",
    "S321",
]

[tool.ruff.lint.per-file-ignores]
"src/bioversions/version.py" = [
    "S603",
    "S607",
]
"docs/source/conf.py" = ["ERA001"]
"notebooks/**/*.ipynb" = ["T201"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.isort]
relative-imports-order = "closest-to-furthest"
known-third-party = ["tqdm"]
known-first-party = [
    "bioversions",
    "tests",
]

[tool.ruff.format]
docstring-code-format = true

[tool.bumpversion]
current_version = "0.10.96"
parse = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(?:-(?P<release>[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+(?P<build>[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?'
serialize = [
    "{major}.{minor}.{patch}-{release}+{build}",
    "{major}.{minor}.{patch}+{build}",
    "{major}.{minor}.{patch}-{release}",
    "{major}.{minor}.{patch}",
]
commit = true
tag = false

[tool.bumpversion.parts.release]
optional_value = "production"
first_value = "dev"
values = [
    "dev",
    "production",
]

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "docs/source/conf.py"
search = 'release = "{current_version}"'
replace = 'release = "{new_version}"'

[[tool.bumpversion.files]]
filename = "src/bioversions/version.py"
search = 'VERSION = "{current_version}"'
replace = 'VERSION = "{new_version}"'
