"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from abc import (
    ABCMeta,
    abstractmethod,
)
from chalk._gen.chalk.server.v1.log_pb2 import (
    GetAccessLogFacetValuesRequest,
    GetAccessLogFacetValuesResponse,
    GetAccessLogFacetsRequest,
    GetAccessLogFacetsResponse,
    GetLogFacetValuesRequest,
    GetLogFacetValuesResponse,
    GetLogFacetsRequest,
    GetLogFacetsResponse,
    SearchAccessLogEntriesAggregatedRequest,
    SearchAccessLogEntriesAggregatedResponse,
    SearchAccessLogEntriesRequest,
    SearchAccessLogEntriesResponse,
    SearchLogEntriesAggregatedRequest,
    SearchLogEntriesAggregatedResponse,
    SearchLogEntriesRequest,
    SearchLogEntriesResponse,
    StreamSearchAccessLogEntriesRequest,
    StreamSearchAccessLogEntriesResponse,
    StreamSearchLogEntriesRequest,
    StreamSearchLogEntriesResponse,
)
from collections.abc import (
    Iterator,
)
from grpc import (
    Channel,
    Server,
    ServicerContext,
    UnaryStreamMultiCallable,
    UnaryUnaryMultiCallable,
)

class LogSearchServiceStub:
    def __init__(self, channel: Channel) -> None: ...
    SearchLogEntries: UnaryUnaryMultiCallable[
        SearchLogEntriesRequest,
        SearchLogEntriesResponse,
    ]
    StreamSearchLogEntries: UnaryStreamMultiCallable[
        StreamSearchLogEntriesRequest,
        StreamSearchLogEntriesResponse,
    ]
    """Server-streaming variant of SearchLogEntries. Each streamed
    StreamSearchLogEntriesResponse carries a chunk of log_entries; the
    final message may also carry next_page_token.
    """
    SearchLogEntriesAggregated: UnaryUnaryMultiCallable[
        SearchLogEntriesAggregatedRequest,
        SearchLogEntriesAggregatedResponse,
    ]
    GetLogFacets: UnaryUnaryMultiCallable[
        GetLogFacetsRequest,
        GetLogFacetsResponse,
    ]
    GetLogFacetValues: UnaryUnaryMultiCallable[
        GetLogFacetValuesRequest,
        GetLogFacetValuesResponse,
    ]
    SearchAccessLogEntries: UnaryUnaryMultiCallable[
        SearchAccessLogEntriesRequest,
        SearchAccessLogEntriesResponse,
    ]
    StreamSearchAccessLogEntries: UnaryStreamMultiCallable[
        StreamSearchAccessLogEntriesRequest,
        StreamSearchAccessLogEntriesResponse,
    ]
    """Server-streaming variant of SearchAccessLogEntries. Each streamed
    StreamSearchAccessLogEntriesResponse carries a chunk of access_log_entries;
    the final message may also carry next_page_token.
    """
    SearchAccessLogEntriesAggregated: UnaryUnaryMultiCallable[
        SearchAccessLogEntriesAggregatedRequest,
        SearchAccessLogEntriesAggregatedResponse,
    ]
    GetAccessLogFacets: UnaryUnaryMultiCallable[
        GetAccessLogFacetsRequest,
        GetAccessLogFacetsResponse,
    ]
    GetAccessLogFacetValues: UnaryUnaryMultiCallable[
        GetAccessLogFacetValuesRequest,
        GetAccessLogFacetValuesResponse,
    ]

class LogSearchServiceServicer(metaclass=ABCMeta):
    @abstractmethod
    def SearchLogEntries(
        self,
        request: SearchLogEntriesRequest,
        context: ServicerContext,
    ) -> SearchLogEntriesResponse: ...
    @abstractmethod
    def StreamSearchLogEntries(
        self,
        request: StreamSearchLogEntriesRequest,
        context: ServicerContext,
    ) -> Iterator[StreamSearchLogEntriesResponse]:
        """Server-streaming variant of SearchLogEntries. Each streamed
        StreamSearchLogEntriesResponse carries a chunk of log_entries; the
        final message may also carry next_page_token.
        """
    @abstractmethod
    def SearchLogEntriesAggregated(
        self,
        request: SearchLogEntriesAggregatedRequest,
        context: ServicerContext,
    ) -> SearchLogEntriesAggregatedResponse: ...
    @abstractmethod
    def GetLogFacets(
        self,
        request: GetLogFacetsRequest,
        context: ServicerContext,
    ) -> GetLogFacetsResponse: ...
    @abstractmethod
    def GetLogFacetValues(
        self,
        request: GetLogFacetValuesRequest,
        context: ServicerContext,
    ) -> GetLogFacetValuesResponse: ...
    @abstractmethod
    def SearchAccessLogEntries(
        self,
        request: SearchAccessLogEntriesRequest,
        context: ServicerContext,
    ) -> SearchAccessLogEntriesResponse: ...
    @abstractmethod
    def StreamSearchAccessLogEntries(
        self,
        request: StreamSearchAccessLogEntriesRequest,
        context: ServicerContext,
    ) -> Iterator[StreamSearchAccessLogEntriesResponse]:
        """Server-streaming variant of SearchAccessLogEntries. Each streamed
        StreamSearchAccessLogEntriesResponse carries a chunk of access_log_entries;
        the final message may also carry next_page_token.
        """
    @abstractmethod
    def SearchAccessLogEntriesAggregated(
        self,
        request: SearchAccessLogEntriesAggregatedRequest,
        context: ServicerContext,
    ) -> SearchAccessLogEntriesAggregatedResponse: ...
    @abstractmethod
    def GetAccessLogFacets(
        self,
        request: GetAccessLogFacetsRequest,
        context: ServicerContext,
    ) -> GetAccessLogFacetsResponse: ...
    @abstractmethod
    def GetAccessLogFacetValues(
        self,
        request: GetAccessLogFacetValuesRequest,
        context: ServicerContext,
    ) -> GetAccessLogFacetValuesResponse: ...

def add_LogSearchServiceServicer_to_server(servicer: LogSearchServiceServicer, server: Server) -> None: ...
