"""Seltz Python SDK for interacting with the Seltz API."""

from ._types import OMIT, Omit
from .exceptions import (
    SeltzAPIError,
    SeltzAuthenticationError,
    SeltzConfigurationError,
    SeltzConnectionError,
    SeltzError,
    SeltzRateLimitError,
    SeltzTimeoutError,
)
from .seltz import AsyncSeltz, Seltz
from .services import (
    AnswerResponse,
    AnswerStreamResponse,
    Citation,
    Citations,
    Document,
    ListRecordsResponse,
    ListRunsResponse,
    CreateMonitorResponse,
    ListMonitorsResponse,
    ListRunRecordsResponse,
    DeleteMonitorResponse,
    GetMonitorResponse,
    GetRunResponse,
    ListRunRequestsResponse,
    StreamRecordsResponse,
    UpdateMonitorResponse,
    Monitor,
    MonitorSearchRequest,
    MonitorStatus,
    Record,
    RecordType,
    RequestStatus,
    Run,
    RunRequest,
    RunState,
    RunStatus,
    SearchRequest,
    SearchResponse,
    SortOrder,
    Webhook,
    WebhookStatus,
)

__all__ = [
    # Main client
    "Seltz",
    "AsyncSeltz",
    # Types (protobuf)
    "SearchResponse",
    "Document",
    "AnswerResponse",
    "AnswerStreamResponse",
    "Citation",
    "Citations",
    # Types (Monitor)
    "SearchRequest",
    "Monitor",
    "MonitorSearchRequest",
    "Webhook",
    "Run",
    "RunRequest",
    "Record",
    "ListRecordsResponse",
    "ListRunsResponse",
    "CreateMonitorResponse",
    "ListMonitorsResponse",
    "ListRunRecordsResponse",
    "DeleteMonitorResponse",
    "GetMonitorResponse",
    "GetRunResponse",
    "ListRunRequestsResponse",
    "StreamRecordsResponse",
    "UpdateMonitorResponse",
    # Monitor enums are values, not just types: a caller passing `status` or
    # `sort` needs the variant.
    "MonitorStatus",
    "RunStatus",
    "RecordType",
    "RequestStatus",
    "SortOrder",
    "RunState",
    "WebhookStatus",
    # Sentinel
    "OMIT",
    "Omit",
    # Exceptions
    "SeltzError",
    "SeltzConfigurationError",
    "SeltzAuthenticationError",
    "SeltzConnectionError",
    "SeltzAPIError",
    "SeltzTimeoutError",
    "SeltzRateLimitError",
]
