"""Seltz Python SDK for interacting with the Seltz API."""

from ._types import OMIT, Omit
from .exceptions import (
    SeltzAPIError,
    SeltzAuthenticationError,
    SeltzConfigurationError,
    SeltzConnectionError,
    SeltzError,
    SeltzRateLimitError,
    SeltzTimeoutError,
)
from .seltz import AsyncSeltz, Seltz
from .services import (
    AgentRun,
    AgentRunCitation,
    AgentRunGrounding,
    AgentRunOutput,
    AgentRunRequest,
    AgentRunSource,
    AgentRunStatus,
    AgentRunStopReason,
    AnswerResponse,
    AnswerStreamResponse,
    Citation,
    Citations,
    CreateMonitorResponse,
    DeleteMonitorResponse,
    Document,
    FetchError,
    FetchResponse,
    FetchResult,
    FetchStatus,
    GetMonitorResponse,
    GetRunResponse,
    ListAgentRunsResponse,
    ListMonitorsResponse,
    ListRecordsResponse,
    ListRunRecordsResponse,
    ListRunRequestsResponse,
    ListRunsResponse,
    Monitor,
    MonitorSearchRequest,
    MonitorStatus,
    Record,
    RecordType,
    RequestStatus,
    Run,
    RunRequest,
    RunState,
    RunStatus,
    SearchRequest,
    SearchResponse,
    SortOrder,
    StreamRecordsResponse,
    UpdateMonitorResponse,
    Webhook,
    WebhookStatus,
)

__all__ = [
    # Main client
    "Seltz",
    "AsyncSeltz",
    # Types (protobuf)
    "SearchResponse",
    "Document",
    "AnswerResponse",
    "AnswerStreamResponse",
    "Citation",
    "Citations",
    # Types (Agent). Prefixed in the contract because the Monitor API owns
    # the bare Run names below.
    "AgentRun",
    "AgentRunRequest",
    "AgentRunOutput",
    "AgentRunSource",
    "AgentRunGrounding",
    "AgentRunCitation",
    "ListAgentRunsResponse",
    # Agent enums are values, not just types: reading `status` or
    # `stop_reason` off a run needs the variant.
    "AgentRunStatus",
    "AgentRunStopReason",
    # Types (Fetch). FetchStatus is a value, not just a type: a caller
    # branching on `result.status` needs the variant.
    "FetchResponse",
    "FetchResult",
    "FetchError",
    "FetchStatus",
    # Types (Monitor)
    "SearchRequest",
    "Monitor",
    "MonitorSearchRequest",
    "Webhook",
    "Run",
    "RunRequest",
    "Record",
    "ListRecordsResponse",
    "ListRunsResponse",
    "CreateMonitorResponse",
    "ListMonitorsResponse",
    "ListRunRecordsResponse",
    "DeleteMonitorResponse",
    "GetMonitorResponse",
    "GetRunResponse",
    "ListRunRequestsResponse",
    "StreamRecordsResponse",
    "UpdateMonitorResponse",
    # Monitor enums are values, not just types: a caller passing `status` or
    # `sort` needs the variant.
    "MonitorStatus",
    "RunStatus",
    "RecordType",
    "RequestStatus",
    "SortOrder",
    "RunState",
    "WebhookStatus",
    # Sentinel
    "OMIT",
    "Omit",
    # Exceptions
    "SeltzError",
    "SeltzConfigurationError",
    "SeltzAuthenticationError",
    "SeltzConnectionError",
    "SeltzAPIError",
    "SeltzTimeoutError",
    "SeltzRateLimitError",
]
