[package]
name = "tensorfs-py"
version.workspace = true
edition.workspace = true

[lib]
name = "_ext"
crate-type = ["cdylib", "rlib"]

[dependencies]
tensorfs-core = { path = "../tensorfs-core" }
tensorfs-plane = { path = "../tensorfs-plane" }
pyo3 = { version = "0.29.2", features = ["abi3-py312"] }

[features]
extension-module = ["pyo3/extension-module"]
