# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentry_protos/billing/v1/common/v1/pricing_tier.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5sentry_protos/billing/v1/common/v1/pricing_tier.proto\x12\"sentry_protos.billing.v1.common.v1\"D\n\x0bPricingTier\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\x12\x19\n\x11rate_per_unit_cpe\x18\x03 \x01(\x03\"S\n\x11TieredPricingRate\x12>\n\x05tiers\x18\x01 \x03(\x0b\x32/.sentry_protos.billing.v1.common.v1.PricingTierb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentry_protos.billing.v1.common.v1.pricing_tier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICINGTIER']._serialized_start=93
  _globals['_PRICINGTIER']._serialized_end=161
  _globals['_TIEREDPRICINGRATE']._serialized_start=163
  _globals['_TIEREDPRICINGRATE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
