"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Card(google.protobuf.message.Message):
    """Card payment method details."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LAST_4_FIELD_NUMBER: builtins.int
    last_4: builtins.str
    def __init__(
        self,
        *,
        last_4: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["last_4", b"last_4"]) -> None: ...

global___Card = Card

@typing.final
class PaymentMethodDetails(google.protobuf.message.Message):
    """Provider-specific payment method information attached to a charge."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CARD_FIELD_NUMBER: builtins.int
    @property
    def card(self) -> global___Card: ...
    def __init__(
        self,
        *,
        card: global___Card | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["card", b"card", "details", b"details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["card", b"card", "details", b"details"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["details", b"details"]) -> typing.Literal["card"] | None: ...

global___PaymentMethodDetails = PaymentMethodDetails

@typing.final
class StripeCharge(google.protobuf.message.Message):
    """A snapshot of a Stripe charge object. Used as the payload when reacting
    to Stripe webhook events.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    REFUNDED_FIELD_NUMBER: builtins.int
    PAID_FIELD_NUMBER: builtins.int
    AMOUNT_REFUNDED_FIELD_NUMBER: builtins.int
    CREATED_ST_FIELD_NUMBER: builtins.int
    FAILURE_CODE_FIELD_NUMBER: builtins.int
    PAYMENT_METHOD_DETAILS_FIELD_NUMBER: builtins.int
    id: builtins.str
    amount: builtins.int
    refunded: builtins.bool
    paid: builtins.bool
    amount_refunded: builtins.int
    created_st: builtins.int
    """Stripe's "created" field, expressed as Unix epoch seconds."""
    failure_code: builtins.str
    @property
    def payment_method_details(self) -> global___PaymentMethodDetails: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        amount: builtins.int = ...,
        refunded: builtins.bool = ...,
        paid: builtins.bool = ...,
        amount_refunded: builtins.int = ...,
        created_st: builtins.int = ...,
        failure_code: builtins.str | None = ...,
        payment_method_details: global___PaymentMethodDetails | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_failure_code", b"_failure_code", "failure_code", b"failure_code", "payment_method_details", b"payment_method_details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_failure_code", b"_failure_code", "amount", b"amount", "amount_refunded", b"amount_refunded", "created_st", b"created_st", "failure_code", b"failure_code", "id", b"id", "paid", b"paid", "payment_method_details", b"payment_method_details", "refunded", b"refunded"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_failure_code", b"_failure_code"]) -> typing.Literal["failure_code"] | None: ...

global___StripeCharge = StripeCharge
