name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - os: ubuntu-22.04
            flake: ==6.1
            python-version: 3.9
          - flake: ==7.3
            os: ubuntu-latest
            python-version: 3.14

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -e . flake8${{ matrix.flake }} six
      - name: Run tests
        run: python -m unittest -v
