[package]
name = "discord-markdown"
description = "Discord Markdown parser"
version = "0.1.0"
edition = "2021"
license = "MIT"
resolver = "2"

[workspace]
members = ["ffi/py", "packages/confusables", "packages/emoji", "packages/variant-struct"]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
discord-confusables = { version = "0.1.0", path = "packages/confusables" }
discord-emoji = { version = "0.1.0", path = "packages/emoji" }
enumset = { version = "1.1.5", features = ["alloc"] }
icu_properties = "2.0.1"
itertools = "0.14.0"
memchr = "2.7.4"
nom = "8.0.0"
owned_chars = "0.3.2"
phf = "0.12.1"
serde = { version = "1.0.204", optional = true, features = ["derive"] }
tracing = "0.1.41"
url = "2.5.0"
variant-struct = { version = "0.1.0", path = "packages/variant-struct" }

[dev-dependencies]
criterion = "0.5.1"
discord-markdown = { path = ".", features = ["serde"] }
nom-language = "0.1.0"
ntest = "^0.9"
pretty_assertions = "1.4.0"
serde_json = "1.0.120"

[[bench]]
name = "block"
harness = false

[profile.release]
lto = true
strip = "symbols"

[features]
serde = ["dep:serde", "url/serde", "enumset/serde"]
