"""Shared embedding provider contracts and local-service helpers."""

from .inventory import EMBEDDING_SURFACES
from .runtime import (
    AEGIS_EMBED_MODEL_ID,
    AEGIS_EMBED_MODEL_ROOT,
    AEGIS_EMBED_ONLINE_DIMENSIONS,
    AEGIS_EMBED_PROVIDER_ID,
    AEGIS_EMBED_SOURCE_URL,
    DefaultEmbeddingService,
    EmbeddingBatch,
    EmbeddingHealth,
    EmbeddingModelRegistry,
    EmbeddingPreloadEntry,
    EmbeddingPreloadState,
    EmbeddingProvider,
    EmbeddingRequest,
    EmbeddingService,
    EmbeddingVector,
    InMemoryEmbeddingModelRegistry,
    SentenceTransformerEmbeddingProvider,
    build_default_embedding_service,
    cosine_similarity,
    embedding_runtime_is_loaded,
    embedding_runtime_state,
    embedding_mode_for_dimensions,
    embedding_mode_for_latency,
    embedding_model_root_path,
    embedding_root_is_healthy,
    resolve_embedding_dimensions,
    sentence_transformers_dependencies_ready,
)

__all__ = [
    "AEGIS_EMBED_MODEL_ID",
    "AEGIS_EMBED_MODEL_ROOT",
    "AEGIS_EMBED_ONLINE_DIMENSIONS",
    "AEGIS_EMBED_PROVIDER_ID",
    "AEGIS_EMBED_SOURCE_URL",
    "DefaultEmbeddingService",
    "EMBEDDING_SURFACES",
    "EmbeddingBatch",
    "EmbeddingHealth",
    "EmbeddingModelRegistry",
    "EmbeddingPreloadEntry",
    "EmbeddingPreloadState",
    "EmbeddingProvider",
    "EmbeddingRequest",
    "EmbeddingService",
    "EmbeddingVector",
    "InMemoryEmbeddingModelRegistry",
    "SentenceTransformerEmbeddingProvider",
    "build_default_embedding_service",
    "cosine_similarity",
    "embedding_runtime_is_loaded",
    "embedding_runtime_state",
    "embedding_mode_for_dimensions",
    "embedding_mode_for_latency",
    "embedding_model_root_path",
    "embedding_root_is_healthy",
    "resolve_embedding_dimensions",
    "sentence_transformers_dependencies_ready",
]
