"""Public inventory of embedding package surfaces."""

EMBEDDING_SURFACES = (
    "AEGIS_EMBED_PROVIDER_ID",
    "AEGIS_EMBED_MODEL_ID",
    "AEGIS_EMBED_SOURCE_URL",
    "AEGIS_EMBED_MODEL_ROOT",
    "AEGIS_EMBED_ONLINE_DIMENSIONS",
    "EmbeddingRequest",
    "EmbeddingVector",
    "EmbeddingBatch",
    "EmbeddingHealth",
    "EmbeddingPreloadEntry",
    "EmbeddingPreloadState",
    "EmbeddingProvider",
    "EmbeddingService",
    "EmbeddingModelRegistry",
    "InMemoryEmbeddingModelRegistry",
    "SentenceTransformerEmbeddingProvider",
    "DefaultEmbeddingService",
    "build_default_embedding_service",
    "embedding_model_root_path",
    "embedding_root_is_healthy",
    "sentence_transformers_dependencies_ready",
    "resolve_embedding_dimensions",
    "embedding_mode_for_dimensions",
    "embedding_mode_for_latency",
    "cosine_similarity",
)
