[project]
name = "tuspyserver"
version = "4.2.13"
description = "A Python tus server implementation as a FastAPI router"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["fastapi>=0.110.0"]

[[project.authors]]
name = "Edi Hasaj"
email = "edi.hasaj@applifyer.com"

[build-system]
requires = ["uv_build>=0.6,<0.12"]
build-backend = "uv_build"

[tool.uv.workspace]
members = ["example"]
