"""Shared defensive caps for Windows-host WSL scanning."""

MAX_WSL_DISTROS = 16
MAX_WSL_HOMES = 4
MAX_WSL_HOMES_TOTAL = MAX_WSL_DISTROS * MAX_WSL_HOMES
MAX_WSL_HOME_PROBES = 32
MAX_WSL_CLIENT_CONTEXTS = MAX_WSL_DISTROS * (MAX_WSL_HOMES + 1)
