"""Analytics category-processor framework."""

from .base_processor import BaseMetricProcessor
from .engine import AnalyticsEngine
from .engine_session import AnalyticsEngineSession
from .geometry import (
    assign_detections_to_zones,
    build_zone_polygons_px,
    create_counter_from_zone_config,
    denormalize_zone_config,
)
from .incident_lifecycle import IncidentLifecycle
from .processors.incident import IncidentProcessor, calculate_severity
from .quant_strategies import compute_quant
from .redis_publisher import AnalyticsRedisPublisher
from .schemas import (
    SEVERITY_ORDER,
    AggregationResult,
    BoundingBox,
    DetectionEntry,
    FrameResult,
    FrameSummaryEntry,
    IncidentDetail,
    IncidentEvent,
    IncidentFrameResult,
    IncidentLifecycleState,
    IncidentMessage,
    IncidentProcessorConfig,
    IncidentThreshold,
    IncidentTypeConfig,
    InputStreamEntry,
    InputStreamInfo,
    LifecycleConfig,
    MetricEntry,
    ProcessorAggregationOutput,
    ProcessorFrameOutput,
    QuantStrategyConfig,
    ResultValue,
    ResultWrapper,
    SeverityLevel,
    StreamInfo,
    TrackingStats,
    ZoneConfig,
)

__all__ = [
    "SEVERITY_ORDER",
    "AggregationResult",
    "AnalyticsEngine",
    "AnalyticsEngineSession",
    "AnalyticsRedisPublisher",
    "BaseMetricProcessor",
    "BoundingBox",
    "DetectionEntry",
    "FrameResult",
    "FrameSummaryEntry",
    "IncidentDetail",
    "IncidentEvent",
    "IncidentFrameResult",
    "IncidentLifecycle",
    "IncidentLifecycleState",
    "IncidentMessage",
    "IncidentProcessor",
    "IncidentProcessorConfig",
    "IncidentThreshold",
    "IncidentTypeConfig",
    "InputStreamEntry",
    "InputStreamInfo",
    "LifecycleConfig",
    "MetricEntry",
    "ProcessorAggregationOutput",
    "ProcessorFrameOutput",
    "QuantStrategyConfig",
    "ResultValue",
    "ResultWrapper",
    "SeverityLevel",
    "StreamInfo",
    "TrackingStats",
    "ZoneConfig",
    "assign_detections_to_zones",
    "build_zone_polygons_px",
    "calculate_severity",
    "compute_quant",
    "create_counter_from_zone_config",
    "denormalize_zone_config",
]
