# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.82
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.import_response import ImportResponse

class TestImportResponse(unittest.TestCase):
    """ImportResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportResponse:
        """Test ImportResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportResponse`
        """
        model = ImportResponse()
        if include_optional:
            return ImportResponse(
                imported = 56,
                reconstructed = 56,
                skipped = 56,
                dry_run = True,
                errors = [
                    mixpeek.models.import_row_error.ImportRowError(
                        row = 56, 
                        error = '', )
                    ],
                warnings = [
                    ''
                    ]
            )
        else:
            return ImportResponse(
        )
        """

    def testImportResponse(self):
        """Test ImportResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
