# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.82
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.bulk_annotation_create import BulkAnnotationCreate

class TestBulkAnnotationCreate(unittest.TestCase):
    """BulkAnnotationCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkAnnotationCreate:
        """Test BulkAnnotationCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkAnnotationCreate`
        """
        model = BulkAnnotationCreate()
        if include_optional:
            return BulkAnnotationCreate(
                document_id = '',
                collection_id = '',
                label = '0',
                confidence = 0.0,
                reasoning = '',
                payload = { },
                retriever_id = '',
                execution_id = '',
                stage_name = ''
            )
        else:
            return BulkAnnotationCreate(
                document_id = '',
                label = '0',
        )
        """

    def testBulkAnnotationCreate(self):
        """Test BulkAnnotationCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
