# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.82
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.bulk_submitted_batch import BulkSubmittedBatch

class TestBulkSubmittedBatch(unittest.TestCase):
    """BulkSubmittedBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkSubmittedBatch:
        """Test BulkSubmittedBatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkSubmittedBatch`
        """
        model = BulkSubmittedBatch()
        if include_optional:
            return BulkSubmittedBatch(
                batch_id = '',
                status = '',
                object_count = 56,
                queue_position = 56,
                error = ''
            )
        else:
            return BulkSubmittedBatch(
                batch_id = '',
                status = '',
                object_count = 56,
        )
        """

    def testBulkSubmittedBatch(self):
        """Test BulkSubmittedBatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
