# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.82
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.execute_batch_request import ExecuteBatchRequest

class TestExecuteBatchRequest(unittest.TestCase):
    """ExecuteBatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExecuteBatchRequest:
        """Test ExecuteBatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExecuteBatchRequest`
        """
        model = ExecuteBatchRequest()
        if include_optional:
            return ExecuteBatchRequest(
                queries = [
                    mixpeek.models.batch_query_item.BatchQueryItem(
                        inputs = { }, 
                        filters = { }, )
                    ],
                settings = { },
                concurrency = 1.0,
                return_presigned_urls = True,
                return_vectors = True,
                stream = True
            )
        else:
            return ExecuteBatchRequest(
                queries = [
                    mixpeek.models.batch_query_item.BatchQueryItem(
                        inputs = { }, 
                        filters = { }, )
                    ],
        )
        """

    def testExecuteBatchRequest(self):
        """Test ExecuteBatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
