# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.82
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.trigger_action_config_batch_rerun import TriggerActionConfigBatchRerun

class TestTriggerActionConfigBatchRerun(unittest.TestCase):
    """TriggerActionConfigBatchRerun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TriggerActionConfigBatchRerun:
        """Test TriggerActionConfigBatchRerun
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TriggerActionConfigBatchRerun`
        """
        model = TriggerActionConfigBatchRerun()
        if include_optional:
            return TriggerActionConfigBatchRerun(
                batch_id = '',
                filters = {
                    'key' : null
                    },
                retry_failed_only = True
            )
        else:
            return TriggerActionConfigBatchRerun(
                batch_id = '',
        )
        """

    def testTriggerActionConfigBatchRerun(self):
        """Test TriggerActionConfigBatchRerun"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
