# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.82
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.evo_c_params import EVoCParams

class TestEVoCParams(unittest.TestCase):
    """EVoCParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EVoCParams:
        """Test EVoCParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EVoCParams`
        """
        model = EVoCParams()
        if include_optional:
            return EVoCParams(
                noise_level = 0.0,
                base_min_cluster_size = 2.0,
                approx_n_clusters = 2.0,
                n_neighbors = 2.0,
                min_samples = 1.0,
                random_state = 56
            )
        else:
            return EVoCParams(
        )
        """

    def testEVoCParams(self):
        """Test EVoCParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
