# coding: utf-8

# Copyright (c) The OGX Contributors.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

"""
    OGX Specification - Stable & Experimental APIs

    This is the specification of the OGX that provides                     a set of endpoints and their corresponding interfaces that are     tailored to                     best leverage Llama Models.      **🔗 COMBINED**: This specification includes both stable production-ready APIs     and experimental pre-release APIs. Use stable APIs for production deployments     and experimental APIs for testing new features.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import httpx
import json
import os

from typing import Any, Mapping
from ._version import __version__

from ogx_client.api_client import ApiClient
from ogx_client.async_api_client import AsyncApiClient
from ogx_client.configuration import Configuration
from ogx_client.api.admin_api import AdminApi
from ogx_client.api.alpha_api import AlphaApi
from ogx_client.api.batches_api import BatchesApi
from ogx_client.api.chat_api import ChatApi
from ogx_client.api.chat_completions_api import ChatCompletionsApi
from ogx_client.api.completions_api import CompletionsApi
from ogx_client.api.connectors_api import ConnectorsApi
from ogx_client.api.conversations_api import ConversationsApi
from ogx_client.api.embeddings_api import EmbeddingsApi
from ogx_client.api.file_batches_api import FileBatchesApi
from ogx_client.api.file_processors_api import FileProcessorsApi
from ogx_client.api.files_api import FilesApi
from ogx_client.api.inference_api import InferenceApi
from ogx_client.api.input_items_api import InputItemsApi
from ogx_client.api.inspect_api import InspectApi
from ogx_client.api.interactions_api import InteractionsApi
from ogx_client.api.items_api import ItemsApi
from ogx_client.api.messages_api import MessagesApi
from ogx_client.api.models_api import ModelsApi
from ogx_client.api.openai_api import OpenaiApi
from ogx_client.api.prompts_api import PromptsApi
from ogx_client.api.providers_api import ProvidersApi
from ogx_client.api.responses_api import ResponsesApi
from ogx_client.api.routes_api import RoutesApi
from ogx_client.api.skills_api import SkillsApi
from ogx_client.api.tools_api import ToolsApi
from ogx_client.api.vector_io_api import VectorIoApi
from ogx_client.api.vector_stores_api import VectorStoresApi
from ogx_client.api.vector_stores_files_api import VectorStoresFilesApi
from ogx_client.api.versions_api import VersionsApi



def _parse_custom_headers_env() -> dict[str, str]:
    """Parse the OGX_CLIENT_CUSTOM_HEADERS environment variable.

    Format: newline-separated ``Header-Name: value`` pairs.
    Lines without a colon are silently skipped.
    """
    raw = os.environ.get("OGX_CLIENT_CUSTOM_HEADERS")
    if raw is None:
        return {}
    parsed: dict[str, str] = {}
    for line in raw.split("\n"):
        colon = line.find(":")
        if colon >= 0:
            parsed[line[:colon].strip()] = line[colon + 1:].strip()
    return parsed


class OgxClient:
    """
    OGX unified client that provides access to all API endpoints.

    This client creates instances of all available API classes and provides
    them as attributes for easy access.

    Example:
        >>> from ogx_client import Configuration, OgxClient
        >>>
        >>> config = Configuration(host="http://localhost:8000")
        >>> client = OgxClient(config)
        >>>
        >>> # Access specific APIs through the client
        >>> client.admin  # Access AdminApi
        
    """

    def __init__(
        self,
        configuration: Configuration | None = None,
        header_name: str | None = None,
        header_value: str | None = None,
        cookie: str | None = None,
        default_headers: Mapping[str, str] | None = None,
        provider_data: Mapping[str, Any] | None = None,
        api_key: str | None = None,
        **kwargs,
    ) -> None:
        """
        Initialize the OgxClient.

        Args:
            configuration: Configuration object or string URL. If string, creates
                Configuration with that host. If None, uses default configuration.
            header_name: Optional header name for authentication.
            header_value: Optional header value for authentication.
            cookie: Optional cookie string for authentication.
            default_headers: Optional mapping of default HTTP headers. Overrides
                headers from the ``OGX_CLIENT_CUSTOM_HEADERS`` env var for
                duplicate keys.
            provider_data: Optional provider data dict, serialised as JSON in the
                ``X-OGX-Provider-Data`` header.
            api_key: Optional API key. When set, an ``Authorization: Bearer <key>``
                header is added (overriding any Authorization header from
                *default_headers* or the environment). Falls back to the
                ``OGX_CLIENT_API_KEY`` environment variable when *None*.

        Environment variables:
            OGX_CLIENT_API_KEY: Fallback API key when *api_key* is not supplied.
            OGX_CLIENT_BASE_URL: Fallback base URL when neither *configuration*
                nor *base_url*/*host* kwargs are supplied.
            OGX_CLIENT_CUSTOM_HEADERS: Newline-separated ``Header-Name: value``
                pairs added as default headers (constructor *default_headers*
                override for duplicate keys).
        """
        # Resolve api_key: constructor arg > OGX_CLIENT_API_KEY env > None
        if api_key is None:
            api_key = os.environ.get("OGX_CLIENT_API_KEY")
        self.api_key = api_key

        # Resolve base_url from OGX_CLIENT_BASE_URL env if not provided
        if configuration is None and "base_url" not in kwargs and "host" not in kwargs:
            env_base_url = os.environ.get("OGX_CLIENT_BASE_URL")
            if env_base_url is not None:
                kwargs["base_url"] = env_base_url

        # Handle string URL as configuration
        if isinstance(configuration, str):
            configuration = Configuration(host=configuration)
        elif configuration is None:
            if kwargs is not None and kwargs != {}:
                configuration = Configuration(**kwargs)
            else:
                configuration = Configuration.get_default_copy()

        self.configuration = configuration
        self.base_url = self.configuration.base_url

        # Create the API client
        self.api_client = ApiClient(
            configuration=configuration,
            header_name=header_name,
            header_value=header_value,
            cookie=cookie,
        )

        # Store reference to parent client for _prepare_request hook
        self.api_client._parent_client = self
        if hasattr(self.api_client, 'rest_client'):
            self.api_client.rest_client._parent_client = self
        elif hasattr(self.api_client, '_client'):
            self.api_client._client._parent_client = self

        # Build headers: env custom headers as base, constructor default_headers
        # override for duplicate keys, api_key-derived Authorization trumps all
        custom_headers = {**_parse_custom_headers_env(), **(default_headers or {})}
        custom_headers["X-OGX-Client-Version"] = __version__
        if api_key is not None:
            custom_headers["Authorization"] = f"Bearer {api_key}"
        if provider_data is not None:
            custom_headers["X-OGX-Provider-Data"] = json.dumps(provider_data)

        for header_k, header_v in custom_headers.items():
            self.api_client.set_default_header(header_k, header_v)

        # Initialize all API instances
        self.admin = AdminApi(self.api_client)
        self.alpha = AlphaApi(self.api_client)
        self.batches = BatchesApi(self.api_client)
        self.chat = ChatApi(self.api_client)
        self.chat_completions = ChatCompletionsApi(self.api_client)
        self.completions = CompletionsApi(self.api_client)
        self.connectors = ConnectorsApi(self.api_client)
        self.conversations = ConversationsApi(self.api_client)
        self.embeddings = EmbeddingsApi(self.api_client)
        self.file_batches = FileBatchesApi(self.api_client)
        self.file_processors = FileProcessorsApi(self.api_client)
        self.files = FilesApi(self.api_client)
        self.inference = InferenceApi(self.api_client)
        self.input_items = InputItemsApi(self.api_client)
        self.inspect = InspectApi(self.api_client)
        self.interactions = InteractionsApi(self.api_client)
        self.items = ItemsApi(self.api_client)
        self.messages = MessagesApi(self.api_client)
        self.models = ModelsApi(self.api_client)
        self.openai = OpenaiApi(self.api_client)
        self.prompts = PromptsApi(self.api_client)
        self.providers = ProvidersApi(self.api_client)
        self.responses = ResponsesApi(self.api_client)
        self.routes = RoutesApi(self.api_client)
        self.skills = SkillsApi(self.api_client)
        self.tools = ToolsApi(self.api_client)
        self.vector_io = VectorIoApi(self.api_client)
        self.vector_stores = VectorStoresApi(self.api_client)
        self.vector_stores_files = VectorStoresFilesApi(self.api_client)
        self.versions = VersionsApi(self.api_client)

        # Nested API structure
        # Wire up parent-child API relationships
        self.chat.chat_completions = self.chat_completions
        self.chat.__dict__['completions'] = self.chat_completions
        self.chat_completions.messages = self.messages
        self.conversations.items = self.items
        self.models.openai = self.openai
        self.prompts.versions = self.versions
        self.responses.input_items = self.input_items
        self.vector_stores.file_batches = self.file_batches
        self.vector_stores.vector_stores_files = self.vector_stores_files
        self.vector_stores.__dict__['files'] = self.vector_stores_files
        self.alpha.inference = self.inference
        self.alpha.admin = self.admin
        self.admin.connectors = self.connectors

    def __enter__(self):
        """Context manager entry."""
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        """Context manager exit."""
        self.close()

    def close(self):
        """Close the API client and release resources."""
        if hasattr(self, 'api_client'):
            self.api_client.close()

    def _prepare_request(self, request: httpx.Request) -> None:
        return None


class AsyncOgxClient:
    """
    Async OGX unified client that provides access to all API endpoints.

    This async client creates instances of all available API classes and provides
    them as attributes for easy access with async/await support.

    Example:
        >>> from ogx_client import Configuration, AsyncOgxClient
        >>>
        >>> config = Configuration(host="http://localhost:8000")
        >>> async with AsyncOgxClient(config) as client:
        >>>     # Access specific APIs through the client
        >>>     await client.admin.some_method()  # Access AdminApi
        
    """

    def __init__(
        self,
        configuration: Configuration | None = None,
        header_name: str | None = None,
        header_value: str | None = None,
        cookie: str | None = None,
        default_headers: Mapping[str, str] | None = None,
        provider_data: Mapping[str, Any] | None = None,
        api_key: str | None = None,
        **kwargs,
    ) -> None:
        """
        Initialize the AsyncOgxClient.

        Args:
            configuration: Configuration object or string URL. If string, creates
                Configuration with that host. If None, uses default configuration.
            header_name: Optional header name for authentication.
            header_value: Optional header value for authentication.
            cookie: Optional cookie string for authentication.
            default_headers: Optional mapping of default HTTP headers. Overrides
                headers from the ``OGX_CLIENT_CUSTOM_HEADERS`` env var for
                duplicate keys.
            provider_data: Optional provider data dict, serialised as JSON in the
                ``X-OGX-Provider-Data`` header.
            api_key: Optional API key. When set, an ``Authorization: Bearer <key>``
                header is added (overriding any Authorization header from
                *default_headers* or the environment). Falls back to the
                ``OGX_CLIENT_API_KEY`` environment variable when *None*.

        Environment variables:
            OGX_CLIENT_API_KEY: Fallback API key when *api_key* is not supplied.
            OGX_CLIENT_BASE_URL: Fallback base URL when neither *configuration*
                nor *base_url*/*host* kwargs are supplied.
            OGX_CLIENT_CUSTOM_HEADERS: Newline-separated ``Header-Name: value``
                pairs added as default headers (constructor *default_headers*
                override for duplicate keys).
        """
        # Resolve api_key: constructor arg > OGX_CLIENT_API_KEY env > None
        if api_key is None:
            api_key = os.environ.get("OGX_CLIENT_API_KEY")
        self.api_key = api_key

        # Resolve base_url from OGX_CLIENT_BASE_URL env if not provided
        if configuration is None and "base_url" not in kwargs and "host" not in kwargs:
            env_base_url = os.environ.get("OGX_CLIENT_BASE_URL")
            if env_base_url is not None:
                kwargs["base_url"] = env_base_url

        # Handle string URL as configuration
        if isinstance(configuration, str):
            configuration = Configuration(host=configuration)
        elif configuration is None:
            if kwargs is not None and kwargs != {}:
                configuration = Configuration(**kwargs)
            else:
                configuration = Configuration.get_default_copy()

        self.configuration = configuration

        # Create the async API client
        self.api_client = AsyncApiClient(
            configuration=configuration,
            header_name=header_name,
            header_value=header_value,
            cookie=cookie,
        )

        # Store reference to parent client for _prepare_request hook
        self.api_client._parent_client = self
        if hasattr(self.api_client, 'rest_client'):
            self.api_client.rest_client._parent_client = self
        elif hasattr(self.api_client, '_client'):
            self.api_client._client._parent_client = self

        # Build headers: env custom headers as base, constructor default_headers
        # override for duplicate keys, api_key-derived Authorization trumps all
        custom_headers = {**_parse_custom_headers_env(), **(default_headers or {})}
        custom_headers["X-OGX-Client-Version"] = __version__
        if api_key is not None:
            custom_headers["Authorization"] = f"Bearer {api_key}"
        if provider_data is not None:
            custom_headers["X-OGX-Provider-Data"] = json.dumps(provider_data)

        for header_k, header_v in custom_headers.items():
            self.api_client.set_default_header(header_k, header_v)

        # Initialize all API instances
        self.admin = AdminApi(self.api_client)
        self.alpha = AlphaApi(self.api_client)
        self.batches = BatchesApi(self.api_client)
        self.chat = ChatApi(self.api_client)
        self.chat_completions = ChatCompletionsApi(self.api_client)
        self.completions = CompletionsApi(self.api_client)
        self.connectors = ConnectorsApi(self.api_client)
        self.conversations = ConversationsApi(self.api_client)
        self.embeddings = EmbeddingsApi(self.api_client)
        self.file_batches = FileBatchesApi(self.api_client)
        self.file_processors = FileProcessorsApi(self.api_client)
        self.files = FilesApi(self.api_client)
        self.inference = InferenceApi(self.api_client)
        self.input_items = InputItemsApi(self.api_client)
        self.inspect = InspectApi(self.api_client)
        self.interactions = InteractionsApi(self.api_client)
        self.items = ItemsApi(self.api_client)
        self.messages = MessagesApi(self.api_client)
        self.models = ModelsApi(self.api_client)
        self.openai = OpenaiApi(self.api_client)
        self.prompts = PromptsApi(self.api_client)
        self.providers = ProvidersApi(self.api_client)
        self.responses = ResponsesApi(self.api_client)
        self.routes = RoutesApi(self.api_client)
        self.skills = SkillsApi(self.api_client)
        self.tools = ToolsApi(self.api_client)
        self.vector_io = VectorIoApi(self.api_client)
        self.vector_stores = VectorStoresApi(self.api_client)
        self.vector_stores_files = VectorStoresFilesApi(self.api_client)
        self.versions = VersionsApi(self.api_client)

        # Nested API structure

    async def __aenter__(self):
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_value, traceback):
        """Async context manager exit."""
        await self.close()

    async def close(self):
        """Close the async API client and release resources."""
        if hasattr(self, 'api_client'):
            await self.api_client.close()

    async def _prepare_request(self, request: httpx.Request) -> None:
        return None
