# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ArchiveAssetResponseOut(UniversalBaseModel):
    """
    Response model for asset archival.
    """

    archived: bool = pydantic.Field()
    """
    Whether the asset was successfully archived (always true on success)
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the archived asset
    """

    title: str = pydantic.Field()
    """
    Title of the archived asset
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
