# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SemanticModelTokenResponseOut(UniversalBaseModel):
    """
    Response containing a short-lived Cube API token.
    """

    cube_url: str = pydantic.Field()
    """
    Base URL of the Cube instance
    """

    expires_at: str = pydantic.Field()
    """
    ISO 8601 timestamp when the token expires
    """

    token: str = pydantic.Field()
    """
    JWT for direct Cube REST API access
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
