"""Backward-compatibility re-exports from matrx_connect.context.

New code should import from matrx_connect.context directly.
"""

from matrx_connect.context import (
    AppContext,
    CitationPayload,
    ChunkPayload,
    CompletionPayload,
    RenderBlockPayload,
    ConversationLabeledData,
    DataPayload,
    Emitter,
    EndPayload,
    ErrorPayload,
    EventType,
    HeartbeatPayload,
    InitPayload,
    InvalidEventError,
    Operation,
    PAYLOAD_REGISTRY,
    Phase,
    PhasePayload,
    StreamEvent,
    ToolEventPayload,
    VALID_EVENT_TYPES,
    build_event,
    clear_app_context,
    get_app_context,
    set_app_context,
    try_get_app_context,
    validate_event_dict,
)

__all__ = [
    "AppContext",
    "CitationPayload",
    "ChunkPayload",
    "CompletionPayload",
    "RenderBlockPayload",
    "ConversationLabeledData",
    "DataPayload",
    "Emitter",
    "EndPayload",
    "ErrorPayload",
    "EventType",
    "HeartbeatPayload",
    "InitPayload",
    "InvalidEventError",
    "Operation",
    "PAYLOAD_REGISTRY",
    "Phase",
    "PhasePayload",
    "StreamEvent",
    "ToolEventPayload",
    "VALID_EVENT_TYPES",
    "build_event",
    "clear_app_context",
    "get_app_context",
    "set_app_context",
    "try_get_app_context",
    "validate_event_dict",
]
