"""SpecKit pipeline retry & reconciliation logic.

Provides a reusable, provider-abstracted reconciliation engine that retries
failed workflow runs and escalates when retry limits are reached.
"""

from agentic_devtools.cli.ci.reconciliation.config import (
    MAX_RUN_ATTEMPTS,
    RECONCILIATION_WINDOW_HOURS,
    RETRIABLE_CONCLUSIONS,
)
from agentic_devtools.cli.ci.reconciliation.dispatch import (
    DispatchConflictError,
    DispatchResult,
    acquire_dispatch_claim,
    dispatch_due_work,
    evaluate_dispatch_eligibility,
    evaluate_eligibility,
    select_due_work,
)
from agentic_devtools.cli.ci.reconciliation.engine import reconcile
from agentic_devtools.cli.ci.reconciliation.exceptions import UnmappableContextError
from agentic_devtools.cli.ci.reconciliation.integrator import (
    IntegrationResult,
    SinglePRIntegrator,
    SpecialistOutput,
    StaleWriterError,
)
from agentic_devtools.cli.ci.reconciliation.loop_control import AdmissionBlockedError, LoopController
from agentic_devtools.cli.ci.reconciliation.models import (
    AdmissionController,
    AdmissionDecision,
    AdmissionFence,
    AdmissionRequestStatus,
    EffectRecord,
    EffectStatus,
    EligibilityDecision,
    PermitRequest,
    PermitStatus,
    ProviderCapacityObservation,
    ReconciliationAction,
    ReconciliationResult,
    RunEventContext,
    WorkerPermit,
    WorkflowRun,
)
from agentic_devtools.cli.ci.reconciliation.orchestrator import (
    IntegratedLoopOrchestrator,
    ReliabilitySliceEvent,
    ReliabilitySliceResult,
    coalesce_wakeups,
)
from agentic_devtools.cli.ci.reconciliation.recovery import (
    RecoveryExhaustedError,
    confirm_recovery,
    enforce_retry_limit,
    handle_pagination_exhaustion,
    reclaim_leases,
    record_provider_failure,
    rehydrate_state,
)
from agentic_devtools.cli.ci.reconciliation.reliability_metrics import ReliabilityMetrics, calculate_reliability_metrics
from agentic_devtools.cli.ci.reconciliation.specialists import (
    DEFAULT_SPECIALIST_PROFILES,
    SpecialistProfile,
    SpecialistRole,
    SpecialistTask,
    dispatch_specialist,
    recovery_profile,
    route_specialist,
)
from agentic_devtools.cli.ci.reconciliation.status_reporter import (
    STATUS_MARKER,
    render_check_details,
    render_status_comment,
    sync_status_comment,
)
from agentic_devtools.cli.ci.reconciliation.supervisor import (
    IncidentManager,
    ProposalEvaluation,
    RecoveryActionType,
    SharedIncident,
    StaleProposalError,
    SupervisorDecision,
    SupervisorGovernor,
    SupervisorProposal,
    evaluate_supervisor_proposal,
    proposal_from_dict,
    propose_controller_repair,
)
from agentic_devtools.cli.ci.reconciliation.views import (
    GlobalMetricsView,
    PRSummaryView,
    project_global_metrics,
    project_pr_summary,
)
from agentic_devtools.cli.ci.reconciliation.wp3 import (
    Disposition,
    DispositionDecision,
    DispositionEvidence,
    EffectReceipt,
    IssueEffectCoordinator,
    description_hash,
    evaluate_disposition,
    update_description_guarded,
)

__all__ = [
    "DispatchConflictError",
    "DispatchResult",
    "AdmissionController",
    "AdmissionBlockedError",
    "EffectRecord",
    "EffectStatus",
    "EligibilityDecision",
    "AdmissionDecision",
    "AdmissionFence",
    "AdmissionRequestStatus",
    "MAX_RUN_ATTEMPTS",
    "RECONCILIATION_WINDOW_HOURS",
    "RETRIABLE_CONCLUSIONS",
    "ReconciliationAction",
    "ReconciliationResult",
    "PermitRequest",
    "PermitStatus",
    "ProviderCapacityObservation",
    "RecoveryExhaustedError",
    "RunEventContext",
    "UnmappableContextError",
    "WorkflowRun",
    "WorkerPermit",
    "acquire_dispatch_claim",
    "confirm_recovery",
    "dispatch_due_work",
    "enforce_retry_limit",
    "evaluate_dispatch_eligibility",
    "evaluate_eligibility",
    "handle_pagination_exhaustion",
    "reconcile",
    "LoopController",
    "IntegratedLoopOrchestrator",
    "ReliabilitySliceEvent",
    "ReliabilitySliceResult",
    "coalesce_wakeups",
    "reclaim_leases",
    "record_provider_failure",
    "rehydrate_state",
    "select_due_work",
    "Disposition",
    "DispositionDecision",
    "DispositionEvidence",
    "EffectReceipt",
    "IssueEffectCoordinator",
    "description_hash",
    "evaluate_disposition",
    "update_description_guarded",
    "IntegrationResult",
    "SinglePRIntegrator",
    "SpecialistOutput",
    "StaleWriterError",
    "DEFAULT_SPECIALIST_PROFILES",
    "SpecialistProfile",
    "SpecialistRole",
    "SpecialistTask",
    "dispatch_specialist",
    "recovery_profile",
    "route_specialist",
    "IncidentManager",
    "ProposalEvaluation",
    "RecoveryActionType",
    "SharedIncident",
    "StaleProposalError",
    "SupervisorDecision",
    "SupervisorGovernor",
    "SupervisorProposal",
    "evaluate_supervisor_proposal",
    "propose_controller_repair",
    "proposal_from_dict",
    "ReliabilityMetrics",
    "calculate_reliability_metrics",
    "STATUS_MARKER",
    "render_check_details",
    "render_status_comment",
    "sync_status_comment",
    "GlobalMetricsView",
    "PRSummaryView",
    "project_global_metrics",
    "project_pr_summary",
]
