# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.aop_async_execute_response_out import AopAsyncExecuteResponseOut
from ..types.aop_config_response_out import AopConfigResponseOut
from ..types.aop_config_update_response_out import AopConfigUpdateResponseOut
from ..types.aop_create_response_out import AopCreateResponseOut
from ..types.aop_execute_request_in import AopExecuteRequestIn
from ..types.aop_execute_response_out import AopExecuteResponseOut

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawAopClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self,
        *,
        agent_id: typing.Optional[str] = OMIT,
        agent_config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        description: typing.Optional[str] = OMIT,
        icon: typing.Optional[str] = OMIT,
        parent_folder_id: typing.Optional[str] = OMIT,
        prompt: typing.Optional[str] = OMIT,
        section: typing.Optional[str] = OMIT,
        structured_output: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        title: typing.Optional[str] = OMIT,
        user_notification_configs: typing.Optional[
            typing.Dict[str, typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]]
        ] = OMIT,
        workspace_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AopCreateResponseOut]:
        """
        Create a new AOP (Agent Operating Procedure) asset with the given configuration. The created AOP can then be executed via /aop/execute-async, inspected via /aop/{asset_id}/config, and updated via PUT /aop/{asset_id}/config. Use [[ placeholder ]] syntax in the prompt for user inputs supplied at execution time.

        Parameters
        ----------
        agent_id : typing.Optional[str]
            ID of the agent to use for execution

        agent_config : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Full agent configuration override for this AOP

        description : typing.Optional[str]
            Human-readable description of what the AOP does

        icon : typing.Optional[str]
            Icon identifier for UI display

        parent_folder_id : typing.Optional[str]
            ID of the folder to create the AOP in (workspace root if omitted)

        prompt : typing.Optional[str]
            The main prompt/instructions for the AOP. Use [[ placeholder ]] syntax for user inputs supplied at execution time

        section : typing.Optional[str]
            Section/category for organization

        structured_output : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            JSON schema for structured output

        title : typing.Optional[str]
            Title of the AOP (defaults to 'Untitled AOP')

        user_notification_configs : typing.Optional[typing.Dict[str, typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]]]
            Per-user notification preferences. Map of user_id -> notification config controlling who receives AOP result notifications

        workspace_id : typing.Optional[str]
            ID of the workspace to create the AOP in. If not provided, the parent folder's workspace is used when parent_folder_id is provided; otherwise the AOP is created in the user's current workspace. The user must be a member of the specified workspace.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AopCreateResponseOut]
            AOP created successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v0/aop/create",
            method="POST",
            json={
                "agentId": agent_id,
                "agent_config": agent_config,
                "description": description,
                "icon": icon,
                "parent_folder_id": parent_folder_id,
                "prompt": prompt,
                "section": section,
                "structured_output": structured_output,
                "title": title,
                "user_notification_configs": user_notification_configs,
                "workspace_id": workspace_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AopCreateResponseOut,
                    parse_obj_as(
                        type_=AopCreateResponseOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def execute(
        self, *, request: AopExecuteRequestIn, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[AopExecuteResponseOut]:
        """
        DEPRECATED: This endpoint is deprecated. Please use /aop/execute-async instead for better performance and reliability. Execute an existing Agent Operating Procedure (AOP) asset with optional user inputs. AOPs are pre-configured AI workflows that can perform complex tasks like research, analysis, and content generation.

        Parameters
        ----------
        request : AopExecuteRequestIn

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AopExecuteResponseOut]
            AOP execution started successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v0/aop/execute",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=AopExecuteRequestIn, direction="write"
            ),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AopExecuteResponseOut,
                    parse_obj_as(
                        type_=AopExecuteResponseOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def execute_async(
        self, *, request: AopExecuteRequestIn, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[AopAsyncExecuteResponseOut]:
        """
        Start execution of an Agent Operating Procedure (AOP) asset asynchronously. Returns immediately with a thread_id for tracking execution progress without waiting for completion.

        Parameters
        ----------
        request : AopExecuteRequestIn

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AopAsyncExecuteResponseOut]
            AOP execution started successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v0/aop/execute-async",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=AopExecuteRequestIn, direction="write"
            ),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AopAsyncExecuteResponseOut,
                    parse_obj_as(
                        type_=AopAsyncExecuteResponseOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_config(
        self, asset_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[AopConfigResponseOut]:
        """
        Retrieve the full configuration of an AOP asset by its ID. Returns prompt, agent config, structured output schema, and other settings.

        Parameters
        ----------
        asset_id : str
            Unique identifier of the AOP asset

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AopConfigResponseOut]
            AOP configuration retrieved successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v0/aop/{jsonable_encoder(asset_id)}/config",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AopConfigResponseOut,
                    parse_obj_as(
                        type_=AopConfigResponseOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_config(
        self,
        asset_id: str,
        *,
        agent_id: typing.Optional[str] = OMIT,
        agent_config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        description: typing.Optional[str] = OMIT,
        icon: typing.Optional[str] = OMIT,
        prompt: typing.Optional[str] = OMIT,
        section: typing.Optional[str] = OMIT,
        structured_output: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        user_notification_configs: typing.Optional[
            typing.Dict[str, typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]]
        ] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AopConfigUpdateResponseOut]:
        """
        Overwrite the configuration of an existing AOP asset. Replaces the entire AOP configuration (prompt, agent config, structured output, etc.) with the provided values. Fields not included in the request body will be reset to their defaults, except user_notification_configs, which is preserved from the existing configuration when omitted; send an explicit null to clear it.

        Parameters
        ----------
        asset_id : str
            Unique identifier of the AOP asset to update

        agent_id : typing.Optional[str]
            ID of the agent to use for execution

        agent_config : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Full agent configuration override for this AOP

        description : typing.Optional[str]
            Human-readable description of what the AOP does

        icon : typing.Optional[str]
            Icon identifier for UI display

        prompt : typing.Optional[str]
            The main prompt/instructions for the AOP

        section : typing.Optional[str]
            Section/category for organization

        structured_output : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            JSON schema for structured output

        user_notification_configs : typing.Optional[typing.Dict[str, typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]]]
            Per-user notification preferences. Map of user_id -> notification config controlling who receives AOP result notifications. When omitted, the AOP's existing notification configs are preserved; send an explicit null to clear them

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AopConfigUpdateResponseOut]
            AOP configuration updated successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v0/aop/{jsonable_encoder(asset_id)}/config",
            method="PUT",
            json={
                "agentId": agent_id,
                "agent_config": agent_config,
                "description": description,
                "icon": icon,
                "prompt": prompt,
                "section": section,
                "structured_output": structured_output,
                "user_notification_configs": user_notification_configs,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AopConfigUpdateResponseOut,
                    parse_obj_as(
                        type_=AopConfigUpdateResponseOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAopClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self,
        *,
        agent_id: typing.Optional[str] = OMIT,
        agent_config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        description: typing.Optional[str] = OMIT,
        icon: typing.Optional[str] = OMIT,
        parent_folder_id: typing.Optional[str] = OMIT,
        prompt: typing.Optional[str] = OMIT,
        section: typing.Optional[str] = OMIT,
        structured_output: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        title: typing.Optional[str] = OMIT,
        user_notification_configs: typing.Optional[
            typing.Dict[str, typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]]
        ] = OMIT,
        workspace_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AopCreateResponseOut]:
        """
        Create a new AOP (Agent Operating Procedure) asset with the given configuration. The created AOP can then be executed via /aop/execute-async, inspected via /aop/{asset_id}/config, and updated via PUT /aop/{asset_id}/config. Use [[ placeholder ]] syntax in the prompt for user inputs supplied at execution time.

        Parameters
        ----------
        agent_id : typing.Optional[str]
            ID of the agent to use for execution

        agent_config : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Full agent configuration override for this AOP

        description : typing.Optional[str]
            Human-readable description of what the AOP does

        icon : typing.Optional[str]
            Icon identifier for UI display

        parent_folder_id : typing.Optional[str]
            ID of the folder to create the AOP in (workspace root if omitted)

        prompt : typing.Optional[str]
            The main prompt/instructions for the AOP. Use [[ placeholder ]] syntax for user inputs supplied at execution time

        section : typing.Optional[str]
            Section/category for organization

        structured_output : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            JSON schema for structured output

        title : typing.Optional[str]
            Title of the AOP (defaults to 'Untitled AOP')

        user_notification_configs : typing.Optional[typing.Dict[str, typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]]]
            Per-user notification preferences. Map of user_id -> notification config controlling who receives AOP result notifications

        workspace_id : typing.Optional[str]
            ID of the workspace to create the AOP in. If not provided, the parent folder's workspace is used when parent_folder_id is provided; otherwise the AOP is created in the user's current workspace. The user must be a member of the specified workspace.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AopCreateResponseOut]
            AOP created successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v0/aop/create",
            method="POST",
            json={
                "agentId": agent_id,
                "agent_config": agent_config,
                "description": description,
                "icon": icon,
                "parent_folder_id": parent_folder_id,
                "prompt": prompt,
                "section": section,
                "structured_output": structured_output,
                "title": title,
                "user_notification_configs": user_notification_configs,
                "workspace_id": workspace_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AopCreateResponseOut,
                    parse_obj_as(
                        type_=AopCreateResponseOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def execute(
        self, *, request: AopExecuteRequestIn, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[AopExecuteResponseOut]:
        """
        DEPRECATED: This endpoint is deprecated. Please use /aop/execute-async instead for better performance and reliability. Execute an existing Agent Operating Procedure (AOP) asset with optional user inputs. AOPs are pre-configured AI workflows that can perform complex tasks like research, analysis, and content generation.

        Parameters
        ----------
        request : AopExecuteRequestIn

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AopExecuteResponseOut]
            AOP execution started successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v0/aop/execute",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=AopExecuteRequestIn, direction="write"
            ),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AopExecuteResponseOut,
                    parse_obj_as(
                        type_=AopExecuteResponseOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def execute_async(
        self, *, request: AopExecuteRequestIn, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[AopAsyncExecuteResponseOut]:
        """
        Start execution of an Agent Operating Procedure (AOP) asset asynchronously. Returns immediately with a thread_id for tracking execution progress without waiting for completion.

        Parameters
        ----------
        request : AopExecuteRequestIn

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AopAsyncExecuteResponseOut]
            AOP execution started successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v0/aop/execute-async",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=AopExecuteRequestIn, direction="write"
            ),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AopAsyncExecuteResponseOut,
                    parse_obj_as(
                        type_=AopAsyncExecuteResponseOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_config(
        self, asset_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[AopConfigResponseOut]:
        """
        Retrieve the full configuration of an AOP asset by its ID. Returns prompt, agent config, structured output schema, and other settings.

        Parameters
        ----------
        asset_id : str
            Unique identifier of the AOP asset

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AopConfigResponseOut]
            AOP configuration retrieved successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v0/aop/{jsonable_encoder(asset_id)}/config",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AopConfigResponseOut,
                    parse_obj_as(
                        type_=AopConfigResponseOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_config(
        self,
        asset_id: str,
        *,
        agent_id: typing.Optional[str] = OMIT,
        agent_config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        description: typing.Optional[str] = OMIT,
        icon: typing.Optional[str] = OMIT,
        prompt: typing.Optional[str] = OMIT,
        section: typing.Optional[str] = OMIT,
        structured_output: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        user_notification_configs: typing.Optional[
            typing.Dict[str, typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]]
        ] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AopConfigUpdateResponseOut]:
        """
        Overwrite the configuration of an existing AOP asset. Replaces the entire AOP configuration (prompt, agent config, structured output, etc.) with the provided values. Fields not included in the request body will be reset to their defaults, except user_notification_configs, which is preserved from the existing configuration when omitted; send an explicit null to clear it.

        Parameters
        ----------
        asset_id : str
            Unique identifier of the AOP asset to update

        agent_id : typing.Optional[str]
            ID of the agent to use for execution

        agent_config : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Full agent configuration override for this AOP

        description : typing.Optional[str]
            Human-readable description of what the AOP does

        icon : typing.Optional[str]
            Icon identifier for UI display

        prompt : typing.Optional[str]
            The main prompt/instructions for the AOP

        section : typing.Optional[str]
            Section/category for organization

        structured_output : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            JSON schema for structured output

        user_notification_configs : typing.Optional[typing.Dict[str, typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]]]
            Per-user notification preferences. Map of user_id -> notification config controlling who receives AOP result notifications. When omitted, the AOP's existing notification configs are preserved; send an explicit null to clear them

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AopConfigUpdateResponseOut]
            AOP configuration updated successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v0/aop/{jsonable_encoder(asset_id)}/config",
            method="PUT",
            json={
                "agentId": agent_id,
                "agent_config": agent_config,
                "description": description,
                "icon": icon,
                "prompt": prompt,
                "section": section,
                "structured_output": structured_output,
                "user_notification_configs": user_notification_configs,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AopConfigUpdateResponseOut,
                    parse_obj_as(
                        type_=AopConfigUpdateResponseOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
