[build-system]
requires = ["uv_build>=0.6.6,<1.0"]
build-backend = "uv_build"

[project]
name = "pystow"
version = "0.9.0"
description = "Easily pick a place to store data for your Python code"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Framework :: Pytest",
    "Framework :: tox",
    "Framework :: Sphinx",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Typing :: Typed",
]
keywords = [
    "snekpack",
    "cookiecutter",
    "caching",
    "file management",
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
dependencies = [
    "tqdm",
    "typing-extensions",
    "backports.zstd; python_version < '3.14'",
]

[[project.authors]]
name = "Charles Tapley Hoyt"
email = "cthoyt@gmail.com"

[[project.maintainers]]
name = "Charles Tapley Hoyt"
email = "cthoyt@gmail.com"

[project.optional-dependencies]
rdf = ["rdflib"]
xml = ["lxml"]
pandas = ["pandas"]
aws = ["boto3"]
ratelimit = [
    "ratelimit",
    "requests",
]
bs4 = [
    "bs4",
    "requests",
]
yaml = ["pyyaml"]
pydantic = ["pydantic"]
cli = ["click"]
requests = ["requests"]

[project.urls]
"Bug Tracker" = "https://github.com/cthoyt/pystow/issues"
Homepage = "https://github.com/cthoyt/pystow"
Repository = "https://github.com/cthoyt/pystow.git"
Documentation = "https://pystow.readthedocs.io"
Funding = "https://github.com/sponsors/cthoyt"

[project.scripts]
pystow = "pystow.cli:main"

[dependency-groups]
tests = [
    "pytest",
    "coverage[toml]",
    "requests-file",
]
typing = [
    "mypy",
    "pydantic",
    "types-requests",
    "types-ratelimit",
    "types-PyYAML",
]
docs = [
    "sphinx>=8",
    "sphinx-rtd-theme>=3.0",
    "sphinx-click",
    "sphinx-automodapi",
]

[tool.cruft]
skip = [
    "**/__init__.py",
    "tests/*",
]

[tool.mypy]
plugins = []

[tool.doc8]
max-line-length = 120

[tool.pytest.ini_options]
markers = ["""slow: marks tests as slow (deselect with '-m "not slow"')"""]
filterwarnings = ["ignore::pyparsing.exceptions.PyparsingDeprecationWarning"]

[tool.coverage.run]
branch = true
source = ["pystow"]
omit = [
    "tests/*",
    "docs/*",
]

[tool.coverage.paths]
source = [
    "src/pystow",
    ".tox/*/lib/python*/site-packages/pystow",
]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    'if __name__ == "__main__":',
    "if TYPE_CHECKING:",
    "def __str__",
    "def __repr__",
]

[tool.ruff]
line-length = 100
extend-include = ["*.ipynb"]

[tool.ruff.lint]
extend-select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "UP",
    "D",
    "DOC",
    "B",
    "S",
    "T20",
    "N",
    "ERA",
    "NPY",
    "RUF",
    "C4",
]
ignore = [
    "D105",
    "E203",
    "S301",
]

[tool.ruff.lint.per-file-ignores]
"src/pystow/version.py" = [
    "S603",
    "S607",
]
"docs/source/conf.py" = ["ERA001"]
"notebooks/**/*.ipynb" = ["T201"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.isort]
relative-imports-order = "closest-to-furthest"
known-third-party = ["tqdm"]
known-first-party = [
    "pystow",
    "tests",
]

[tool.ruff.format]
docstring-code-format = true

[tool.bumpversion]
current_version = "0.9.0"
parse = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(?:-(?P<release>[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+(?P<build>[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?'
serialize = [
    "{major}.{minor}.{patch}-{release}+{build}",
    "{major}.{minor}.{patch}+{build}",
    "{major}.{minor}.{patch}-{release}",
    "{major}.{minor}.{patch}",
]
commit = true
tag = false

[tool.bumpversion.parts.release]
optional_value = "production"
first_value = "dev"
values = [
    "dev",
    "production",
]

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "docs/source/conf.py"
search = 'release = "{current_version}"'
replace = 'release = "{new_version}"'

[[tool.bumpversion.files]]
filename = "src/pystow/version.py"
search = 'VERSION = "{current_version}"'
replace = 'VERSION = "{new_version}"'
