# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import image_pb2 as image__pb2
from . import shared_pb2 as shared__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in image_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Allocate = channel.unary_unary(
                '/one.image.ImageService/Allocate',
                request_serializer=image__pb2.AllocateRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/one.image.ImageService/Delete',
                request_serializer=image__pb2.DeleteRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/one.image.ImageService/Info',
                request_serializer=image__pb2.InfoRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseXML.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/one.image.ImageService/Update',
                request_serializer=image__pb2.UpdateRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.Rename = channel.unary_unary(
                '/one.image.ImageService/Rename',
                request_serializer=image__pb2.RenameRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.Chmod = channel.unary_unary(
                '/one.image.ImageService/Chmod',
                request_serializer=image__pb2.ChmodRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.Chown = channel.unary_unary(
                '/one.image.ImageService/Chown',
                request_serializer=image__pb2.ChownRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.Lock = channel.unary_unary(
                '/one.image.ImageService/Lock',
                request_serializer=image__pb2.LockRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.Unlock = channel.unary_unary(
                '/one.image.ImageService/Unlock',
                request_serializer=image__pb2.UnlockRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.Clone = channel.unary_unary(
                '/one.image.ImageService/Clone',
                request_serializer=image__pb2.CloneRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.Enable = channel.unary_unary(
                '/one.image.ImageService/Enable',
                request_serializer=image__pb2.EnableRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.Persistent = channel.unary_unary(
                '/one.image.ImageService/Persistent',
                request_serializer=image__pb2.PersistentRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.Chtype = channel.unary_unary(
                '/one.image.ImageService/Chtype',
                request_serializer=image__pb2.ChtypeRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.SnapshotDelete = channel.unary_unary(
                '/one.image.ImageService/SnapshotDelete',
                request_serializer=image__pb2.SnapshotDeleteRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.SnapshotRevert = channel.unary_unary(
                '/one.image.ImageService/SnapshotRevert',
                request_serializer=image__pb2.SnapshotRevertRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.SnapshotFlatten = channel.unary_unary(
                '/one.image.ImageService/SnapshotFlatten',
                request_serializer=image__pb2.SnapshotFlattenRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.Restore = channel.unary_unary(
                '/one.image.ImageService/Restore',
                request_serializer=image__pb2.RestoreRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseXML.FromString,
                _registered_method=True)
        self.PoolInfo = channel.unary_unary(
                '/one.image.ImageService/PoolInfo',
                request_serializer=image__pb2.PoolInfoRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseXML.FromString,
                _registered_method=True)


class ImageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Allocate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rename(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chmod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Persistent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chtype(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotRevert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotFlatten(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PoolInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Allocate': grpc.unary_unary_rpc_method_handler(
                    servicer.Allocate,
                    request_deserializer=image__pb2.AllocateRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=image__pb2.DeleteRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=image__pb2.InfoRequest.FromString,
                    response_serializer=shared__pb2.ResponseXML.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=image__pb2.UpdateRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'Rename': grpc.unary_unary_rpc_method_handler(
                    servicer.Rename,
                    request_deserializer=image__pb2.RenameRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'Chmod': grpc.unary_unary_rpc_method_handler(
                    servicer.Chmod,
                    request_deserializer=image__pb2.ChmodRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'Chown': grpc.unary_unary_rpc_method_handler(
                    servicer.Chown,
                    request_deserializer=image__pb2.ChownRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'Lock': grpc.unary_unary_rpc_method_handler(
                    servicer.Lock,
                    request_deserializer=image__pb2.LockRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'Unlock': grpc.unary_unary_rpc_method_handler(
                    servicer.Unlock,
                    request_deserializer=image__pb2.UnlockRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'Clone': grpc.unary_unary_rpc_method_handler(
                    servicer.Clone,
                    request_deserializer=image__pb2.CloneRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'Enable': grpc.unary_unary_rpc_method_handler(
                    servicer.Enable,
                    request_deserializer=image__pb2.EnableRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'Persistent': grpc.unary_unary_rpc_method_handler(
                    servicer.Persistent,
                    request_deserializer=image__pb2.PersistentRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'Chtype': grpc.unary_unary_rpc_method_handler(
                    servicer.Chtype,
                    request_deserializer=image__pb2.ChtypeRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'SnapshotDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotDelete,
                    request_deserializer=image__pb2.SnapshotDeleteRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'SnapshotRevert': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotRevert,
                    request_deserializer=image__pb2.SnapshotRevertRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'SnapshotFlatten': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotFlatten,
                    request_deserializer=image__pb2.SnapshotFlattenRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'Restore': grpc.unary_unary_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=image__pb2.RestoreRequest.FromString,
                    response_serializer=shared__pb2.ResponseXML.SerializeToString,
            ),
            'PoolInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.PoolInfo,
                    request_deserializer=image__pb2.PoolInfoRequest.FromString,
                    response_serializer=shared__pb2.ResponseXML.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'one.image.ImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('one.image.ImageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Allocate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Allocate',
            image__pb2.AllocateRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Delete',
            image__pb2.DeleteRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Info',
            image__pb2.InfoRequest.SerializeToString,
            shared__pb2.ResponseXML.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Update',
            image__pb2.UpdateRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Rename',
            image__pb2.RenameRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chmod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Chmod',
            image__pb2.ChmodRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Chown',
            image__pb2.ChownRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Lock',
            image__pb2.LockRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Unlock',
            image__pb2.UnlockRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Clone',
            image__pb2.CloneRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Enable',
            image__pb2.EnableRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Persistent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Persistent',
            image__pb2.PersistentRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chtype(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Chtype',
            image__pb2.ChtypeRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/SnapshotDelete',
            image__pb2.SnapshotDeleteRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotRevert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/SnapshotRevert',
            image__pb2.SnapshotRevertRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotFlatten(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/SnapshotFlatten',
            image__pb2.SnapshotFlattenRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/Restore',
            image__pb2.RestoreRequest.SerializeToString,
            shared__pb2.ResponseXML.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PoolInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.image.ImageService/PoolInfo',
            image__pb2.PoolInfoRequest.SerializeToString,
            shared__pb2.ResponseXML.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
