# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import shared_pb2 as shared__pb2
from . import system_pb2 as system__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in system_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SystemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Version = channel.unary_unary(
                '/one.system.SystemService/Version',
                request_serializer=system__pb2.VersionRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseXML.FromString,
                _registered_method=True)
        self.Config = channel.unary_unary(
                '/one.system.SystemService/Config',
                request_serializer=system__pb2.ConfigRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseXML.FromString,
                _registered_method=True)
        self.Sql = channel.unary_unary(
                '/one.system.SystemService/Sql',
                request_serializer=system__pb2.SqlRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseID.FromString,
                _registered_method=True)
        self.SqlQuery = channel.unary_unary(
                '/one.system.SystemService/SqlQuery',
                request_serializer=system__pb2.SqlQueryRequest.SerializeToString,
                response_deserializer=shared__pb2.ResponseXML.FromString,
                _registered_method=True)


class SystemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Config(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sql(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SqlQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=system__pb2.VersionRequest.FromString,
                    response_serializer=shared__pb2.ResponseXML.SerializeToString,
            ),
            'Config': grpc.unary_unary_rpc_method_handler(
                    servicer.Config,
                    request_deserializer=system__pb2.ConfigRequest.FromString,
                    response_serializer=shared__pb2.ResponseXML.SerializeToString,
            ),
            'Sql': grpc.unary_unary_rpc_method_handler(
                    servicer.Sql,
                    request_deserializer=system__pb2.SqlRequest.FromString,
                    response_serializer=shared__pb2.ResponseID.SerializeToString,
            ),
            'SqlQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.SqlQuery,
                    request_deserializer=system__pb2.SqlQueryRequest.FromString,
                    response_serializer=shared__pb2.ResponseXML.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'one.system.SystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('one.system.SystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.system.SystemService/Version',
            system__pb2.VersionRequest.SerializeToString,
            shared__pb2.ResponseXML.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Config(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.system.SystemService/Config',
            system__pb2.ConfigRequest.SerializeToString,
            shared__pb2.ResponseXML.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sql(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.system.SystemService/Sql',
            system__pb2.SqlRequest.SerializeToString,
            shared__pb2.ResponseID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SqlQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/one.system.SystemService/SqlQuery',
            system__pb2.SqlQueryRequest.SerializeToString,
            shared__pb2.ResponseXML.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
