# coding: utf-8

# Copyright (c) The OGX Contributors.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

"""
    OGX Specification - Stable & Experimental APIs

    This is the specification of the OGX that provides                     a set of endpoints and their corresponding interfaces that are     tailored to                     best leverage Llama Models.      **🔗 COMBINED**: This specification includes both stable production-ready APIs     and experimental pre-release APIs. Use stable APIs for production deployments     and experimental APIs for testing new features.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ogx_client.models.list_message_batches_response import ListMessageBatchesResponse

class TestListMessageBatchesResponse(unittest.TestCase):
    """ListMessageBatchesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListMessageBatchesResponse:
        """Test ListMessageBatchesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListMessageBatchesResponse`
        """
        model = ListMessageBatchesResponse()
        if include_optional:
            return ListMessageBatchesResponse(
                data = [
                    ogx_client.models.message_batch.MessageBatch(
                        id = '', 
                        type = 'message_batch', 
                        processing_status = 'in_progress', 
                        request_counts = ogx_client.models.message_batch_request_counts.MessageBatchRequestCounts(
                            processing = 56, 
                            succeeded = 56, 
                            errored = 56, 
                            canceled = 56, 
                            expired = 56, ), 
                        created_at = '', 
                        expires_at = '', 
                        cancel_initiated_at = '', 
                        ended_at = '', 
                        archived_at = '', 
                        results_url = '', )
                    ],
                has_more = True,
                first_id = '',
                last_id = ''
            )
        else:
            return ListMessageBatchesResponse(
                data = [
                    ogx_client.models.message_batch.MessageBatch(
                        id = '', 
                        type = 'message_batch', 
                        processing_status = 'in_progress', 
                        request_counts = ogx_client.models.message_batch_request_counts.MessageBatchRequestCounts(
                            processing = 56, 
                            succeeded = 56, 
                            errored = 56, 
                            canceled = 56, 
                            expired = 56, ), 
                        created_at = '', 
                        expires_at = '', 
                        cancel_initiated_at = '', 
                        ended_at = '', 
                        archived_at = '', 
                        results_url = '', )
                    ],
                has_more = True,
        )
        """

    def testListMessageBatchesResponse(self):
        """Test ListMessageBatchesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
