# coding: utf-8

# Copyright (c) The OGX Contributors.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

"""
    OGX Specification - Stable & Experimental APIs

    This is the specification of the OGX that provides                     a set of endpoints and their corresponding interfaces that are     tailored to                     best leverage Llama Models.      **🔗 COMBINED**: This specification includes both stable production-ready APIs     and experimental pre-release APIs. Use stable APIs for production deployments     and experimental APIs for testing new features.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ogx_client.models.tool_choice_auto4_variants import ToolChoiceAuto4Variants

class TestToolChoiceAuto4Variants(unittest.TestCase):
    """ToolChoiceAuto4Variants unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolChoiceAuto4Variants:
        """Test ToolChoiceAuto4Variants
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolChoiceAuto4Variants`
        """
        model = ToolChoiceAuto4Variants()
        if include_optional:
            return ToolChoiceAuto4Variants(
                type = 'tool',
                disable_parallel_tool_use = True,
                name = ''
            )
        else:
            return ToolChoiceAuto4Variants(
                name = '',
        )
        """

    def testToolChoiceAuto4Variants(self):
        """Test ToolChoiceAuto4Variants"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
