name: Primo Bot Information
description: Loading Primo Product Info
steps:
  - LangchainLoader:
      path: /home/ubuntu/symbits/primo/bot/
      source_type: "Product-Knowledge"
      extensions: ['.xlsx']
      loader: QAFileLoader
      chunk_size: 4096
      chunk_overlap: 20
  - PgVectorOutput:
      table: bot_training
      schema: primo
      embedding_model:
          model: thenlper/gte-base
          model_type: transformers
      id_column: "primo_id"
      vector_column: 'embedding'
      pk: source_type
      create_table:
          create: true
          use_uuid: true
      upsert: false
