######################################################################################################
#                                 Auto-generated Metaflow stub file                                  #
# MF version: 2.19.37.2+obcheckpoint(0.2.10);<unk>(<unk>);ob(v1)                                     #
# Generated on 2026-09-04T00:14:52.326901                                                            #
######################################################################################################

from __future__ import annotations

import typing
if typing.TYPE_CHECKING:
    import metaflow.mf_extensions.outerbounds.plugins.fast_bakery.fast_bakery


class FastBakeryException(Exception, metaclass=type):
    ...

class SolverStats(object, metaclass=type):
    def __init__(self, stats):
        ...
    @property
    def duration_ms(self):
        ...
    @property
    def packages_in_solved_environment(self):
        ...
    ...

class BakingStats(object, metaclass=type):
    def __init__(self, stats):
        ...
    @property
    def solver_stats(self) -> typing.Union[metaflow.mf_extensions.outerbounds.plugins.fast_bakery.fast_bakery.SolverStats, None]:
        ...
    ...

class FastBakeryApiResponse(object, metaclass=type):
    def __init__(self, response):
        ...
    @property
    def python_path(self) -> typing.Union[str, None]:
        ...
    @property
    def container_image(self) -> typing.Union[str, None]:
        ...
    @property
    def success(self) -> bool:
        ...
    @property
    def baking_stats(self) -> typing.Union[metaflow.mf_extensions.outerbounds.plugins.fast_bakery.fast_bakery.BakingStats, None]:
        ...
    @property
    def failure(self) -> bool:
        ...
    ...

class FastBakery(object, metaclass=type):
    def __init__(self, url: str):
        ...
    def python_version(self, version: str):
        ...
    def pypi_packages(self, packages: typing.Dict[str, str]):
        ...
    def conda_packages(self, packages: typing.Dict[str, str]):
        ...
    def default_conda_channel(self, channel: str):
        ...
    def conda_channels(self, channels: list):
        ...
    def base_image(self, image: str):
        ...
    def image_kind(self, kind: str):
        ...
    def ignore_cache(self):
        ...
    def platform(self, os, arch):
        ...
    def extra_configs(self, configs: typing.Dict[str, str]):
        ...
    def index_strategy(self, strategy: str):
        ...
    def bake(self) -> FastBakeryApiResponse:
        ...
    ...

