"""App manifests: the Pydantic schema (``08``), the loader (``09`` §5) and the generated JSON Schema.

The public surface is deliberately small::

    from matrice_analytics.engine.manifest import load_app

    manifest = load_app("ppe_compliance")        # raises AppLoadError if anything is wrong

:mod:`~matrice_analytics.engine.manifest.models` is the source of truth for what an ``app.yaml``
may contain; :mod:`~matrice_analytics.engine.manifest.jsonschema` derives an editor schema from it.
"""

from __future__ import annotations

from .loader import (
    AppFetchError,
    AppLoadError,
    AppRef,
    AppResolveError,
    AppUnpackError,
    CustomCodeError,
    CustomImpl,
    LoadedApp,
    ManifestValidationError,
    cache_root,
    load_app,
    load_app_bundle,
    load_manifest_file,
    resolve_ref,
)
from .models import (
    AGG_TYPES,
    ANALYTICS_CATEGORIES,
    MANIFEST_SCHEMA_VERSION,
    MIN_CONFIRM_FRAMES,
    PRIMITIVES,
    SEVERITY_LEVELS,
    UNIT_DIMENSIONS,
    AppManifest,
    AppSpec,
    CustomConfig,
    DetectConfig,
    DwellConfig,
    EmissionSpec,
    GeometryRequirement,
    IdentityMatchConfig,
    IncidentLifecycle,
    IncidentQuantiseConfig,
    IncidentSpec,
    IncidentType,
    KeypointPoseConfig,
    LineCrossingConfig,
    MetricSpec,
    MetricThreshold,
    ModelSpec,
    PipelineStage,
    PrimitiveConfig,
    ProximityConfig,
    QuantiseLevel,
    RatioComplianceConfig,
    ResolvedSource,
    SegmentationAreaConfig,
    SmoothingConfig,
    StateMachineConfig,
    TestsSpec,
    TrackConfig,
    UniqueCountConfig,
    VelocityStateConfig,
    ZoneOccupancyConfig,
    ZonesSpec,
    resolve_source,
)

__all__ = [
    "AGG_TYPES",
    "ANALYTICS_CATEGORIES",
    "MANIFEST_SCHEMA_VERSION",
    "MIN_CONFIRM_FRAMES",
    "PRIMITIVES",
    "SEVERITY_LEVELS",
    "UNIT_DIMENSIONS",
    "AppFetchError",
    "AppLoadError",
    "AppManifest",
    "AppRef",
    "AppResolveError",
    "AppSpec",
    "AppUnpackError",
    "CustomCodeError",
    "CustomConfig",
    "CustomImpl",
    "DetectConfig",
    "DwellConfig",
    "EmissionSpec",
    "GeometryRequirement",
    "IdentityMatchConfig",
    "IncidentLifecycle",
    "IncidentQuantiseConfig",
    "IncidentSpec",
    "IncidentType",
    "KeypointPoseConfig",
    "LineCrossingConfig",
    "LoadedApp",
    "ManifestValidationError",
    "MetricSpec",
    "MetricThreshold",
    "ModelSpec",
    "PipelineStage",
    "PrimitiveConfig",
    "ProximityConfig",
    "QuantiseLevel",
    "RatioComplianceConfig",
    "ResolvedSource",
    "SegmentationAreaConfig",
    "SmoothingConfig",
    "StateMachineConfig",
    "TestsSpec",
    "TrackConfig",
    "UniqueCountConfig",
    "VelocityStateConfig",
    "ZoneOccupancyConfig",
    "ZonesSpec",
    "cache_root",
    "load_app",
    "load_app_bundle",
    "load_manifest_file",
    "resolve_ref",
    "resolve_source",
]
