[metadata]
name = qonnx
description = Frontend and utilities for QONNX
license = Apache-2.0
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8
url = https://github.com/fastmachinelearning/qonnx
project_urls = 
	Documentation = https://pyscaffold.org/
platforms = any
classifiers = 
	Development Status :: 4 - Beta
	Programming Language :: Python

[options]
zip_safe = False
packages = find_namespace:
include_package_data = True
package_dir = 
	=src
install_requires = 
	importlib-metadata
	attrs>=22.2.0
	clize>=5.0.1
	protobuf>=3.20.3
	bitstring>=3.1.7
	numpy>=1.24.1
	onnx; python_version>='3.11'
	onnx<=1.17; python_version<'3.11'
	onnxruntime>=1.16.1
	onnxscript>=0.1.0
	sigtools>=4.0.1
	toposort>=1.7.0

[options.packages.find]
where = src
exclude = 
	tests

[options.extras_require]
testing = 
	setuptools
	pytest
	pytest-xdist
	pytest-cov
	pytest-randomly
	mock
notebooks = 
	jupyter
	netron

[options.entry_points]
console_scripts = 
	qonnx-cleanup = qonnx.util.cleanup:main
	qonnx-exec = qonnx.util.exec_qonnx:main
	qonnx-to-channels-last = qonnx.util.to_channels_last:main
	qonnx-inference-cost = qonnx.util.inference_cost:main
	qonnx-convert = qonnx.util.convert:main
	qonnx-range-analysis = qonnx.util.range_analysis:main
	qonnx-prune-channels = qonnx.util.prune_channels:main
	qonnx-download-model = qonnx.util.test:qonnx_download_model
	qonnx-tensor-stats = qonnx.analysis.tensor_stats:main
pytest_randomly.random_seeder = 
	qonnx = qonnx.util.random_reseed:reseed

[tool:pytest]
addopts = 
	--verbose
norecursedirs = 
	dist
	build
	.tox
testpaths = tests

[bdist_wheel]
universal = 1

[devpi:upload]
no_vcs = 1
formats = bdist_wheel

[flake8]
max_line_length = 125
extend_ignore = E203, W503
exclude = 
	.tox
	build
	dist
	.eggs
	docs/conf.py

[pyscaffold]
version = 4.0.2
package = qonnx
extensions = 

[egg_info]
tag_build = 
tag_date = 0

