[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bio"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.10,<3.15"
license = "MIT"
keywords = []
authors = [
  { name = "Istvan Albert", email = "istvan.albert@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

dependencies = [
        'biopython >= 1.80',
        'requests',
        'tqdm',
        'mygene',
        'pandas',
        'pooch',
        'gprofiler-official'
]

[project.scripts]
"bio" = "biorun.__main__:run"
"fasta_filter.py" = "biorun.scripts.fasta_filter:run"

[project.urls]
Documentation = "https://github.com/ialbert/bio#readme"
Issues = "https://github.com/ialbert/bio/issues"
Source = "https://github.com/ialbert/bio/"

[tool.hatch.version]
path = "src/biorun/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/biorun"]

[dependency-groups]
dev = [
  "coverage[toml]>=6.5",
  "pytest",
  "mypy>=1.0.0",
]

[tool.coverage.run]
source_pkgs = ["src/biorun", "tests"]
branch = true
parallel = true
omit = [
  "src/biorun/__about__.py",
]

[tool.coverage.paths]
bio = ["src/biorun", ]
tests = ["tests", ]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
