from .file_filters import (
    imports,
    re,
    os,
    get_args,
    load_dotenv,
    jsonify,
    secure_filename,
    make_list,
    get_media_exts,
    is_media_type,
    MIME_TYPES,
    is_str,
    if_not_bool_default,
    get_from_kwargs,
    eatAll,
    eatOuter,
    get_sleep,
    get_caller,
    get_caller_path,
    get_caller_dir,
    SingletonMeta,
    run_pruned_func,
    get_pass_from_key,
    get_password,
    get_print_sudo_cmd,
    get_password_cmd,
    get_sudo_cmd,
    get_raw_password_sudo_cmd,
    get_remote_bash,
    get_remote_ssh,
    get_remote_cmd,
    execute_cmd,
    run_local_cmd,
    run_remote_cmd,
    run_cmd,
    run_ssh_cmd,
    remote_cmd,
    ssh_cmd,
    local_cmd,
    run_any_cmd,
    any_cmd,
    cmd_run,
    PathBackend,
    LocalFS,
    SSHFS,
    REMOTE_RE,
    normalize_items,
    get_output,
    get_cmd_out,
    cmd_input,
    get_output_text,
    get_env_value,
    print_cmd,
    get_sudo_password,
    cmd_run_sudo,
    pexpect_cmd_with_args,
    get_user_pass_host_key,
    execute_cmd_input,
    exec_sudo_capture,
    exec_sudo,
    exec_expect,
    is_remote_file,
    is_remote_dir,
    is_local_file,
    is_local_dir,
    is_file,
    is_dir,
    is_exists,
    check_path_type,
    abstractEnv,
    eatInner,
    safe_split,
    line_contains,
    is_list,
    is_bool,
    get_slash,
    path_join,
    if_not_last_child_join,
    get_home_folder,
    simple_path_join,
    DEFAULT_FILE_NAME,
    DEFAULT_KEY,
    find_and_read_env_file,
    search_for_env_key,
    check_env_file,
    safe_env_load,
    split_eq,
    dotenv_load,
    AbstractEnv,
    get_env_path,
    read_from_file,
    write_to_file,
    get_logFile,
    if_none_default,
    if_none_change,
    get_initial_caller_dir,
    import_tag,
    from_tag,
    DEFAULT_ALLOWED_EXTS,
    DEFAULT_EXCLUDE_TYPES,
    DEFAULT_EXCLUDE_EXTS,
    DEFAULT_EXCLUDE_DIRS,
    DEFAULT_EXCLUDE_PATTERNS,
    AllowedPredicate,
    DEFAULT_EXCLUDE_FILE_PATTERNS,
    DEFAULT_ALLOWED_PATTERNS,
    DEFAULT_ALLOWED_DIRS,
    DEFAULT_ALLOWED_TYPES,
    CANONICAL_MAP,
    DEFAULT_ALLOWED_EXCLUDE_MAP,
    DEFAULT_CANONICAL_MAP,
    ScanConfig,
    SearchParams,
    AllParams,
    get_item_check_cmd,
    get_all_item_check_cmd,
    is_any,
    get_spec_kwargs,
    try_group,
    eatElse,
    clean_line,
    is_line_import,
    is_line_from_import,
    is_from_group_start,
    is_from_group_end,
    clean_imports,
    combine_lone_imports,
    merge_from_import_groups,
    clean_imports_pipeline,
    combine_params,
    get_safe_kwargs,
    create_canonical_map,
    get_safe_canonical_kwargs,
    get_dir_filter_kwargs,
    get_file_filter_kwargs,
    normalize_listlike,
    ensure_exts,
    ensure_patterns,
    ensure_directories,
    get_proper_type_str,
    get_allowed_predicate,
    get_globs,
    get_allowed_files,
    get_allowed_dirs,
    get_filtered_files,
    get_filtered_dirs,
    get_all_allowed_files,
    get_all_allowed_dirs,
    make_allowed_predicate,
    filter_allowed_items,
    derive_all_defaults,
    derive_file_defaults,
    define_defaults,
    get_file_filters,
)
from .reader_utils import (
    imports,
    re,
    os,
    get_args,
    load_dotenv,
    jsonify,
    secure_filename,
    make_list,
    get_media_exts,
    is_media_type,
    MIME_TYPES,
    is_str,
    if_not_bool_default,
    get_from_kwargs,
    eatAll,
    eatOuter,
    get_sleep,
    get_caller,
    get_caller_path,
    get_caller_dir,
    SingletonMeta,
    run_pruned_func,
    get_pass_from_key,
    get_password,
    get_print_sudo_cmd,
    get_password_cmd,
    get_sudo_cmd,
    get_raw_password_sudo_cmd,
    get_remote_bash,
    get_remote_ssh,
    get_remote_cmd,
    execute_cmd,
    run_local_cmd,
    run_remote_cmd,
    run_cmd,
    run_ssh_cmd,
    remote_cmd,
    ssh_cmd,
    local_cmd,
    run_any_cmd,
    any_cmd,
    cmd_run,
    PathBackend,
    LocalFS,
    SSHFS,
    REMOTE_RE,
    normalize_items,
    get_output,
    get_cmd_out,
    cmd_input,
    get_output_text,
    get_env_value,
    print_cmd,
    get_sudo_password,
    cmd_run_sudo,
    pexpect_cmd_with_args,
    get_user_pass_host_key,
    execute_cmd_input,
    exec_sudo_capture,
    exec_sudo,
    exec_expect,
    is_remote_file,
    is_remote_dir,
    is_local_file,
    is_local_dir,
    is_file,
    is_dir,
    is_exists,
    check_path_type,
    abstractEnv,
    eatInner,
    safe_split,
    line_contains,
    is_list,
    is_bool,
    get_slash,
    path_join,
    if_not_last_child_join,
    get_home_folder,
    simple_path_join,
    DEFAULT_FILE_NAME,
    DEFAULT_KEY,
    find_and_read_env_file,
    search_for_env_key,
    check_env_file,
    safe_env_load,
    split_eq,
    dotenv_load,
    AbstractEnv,
    get_env_path,
    read_from_file,
    write_to_file,
    get_logFile,
    if_none_default,
    if_none_change,
    get_initial_caller_dir,
    import_tag,
    from_tag,
    DEFAULT_ALLOWED_EXTS,
    DEFAULT_EXCLUDE_TYPES,
    DEFAULT_EXCLUDE_EXTS,
    DEFAULT_EXCLUDE_DIRS,
    DEFAULT_EXCLUDE_PATTERNS,
    AllowedPredicate,
    DEFAULT_EXCLUDE_FILE_PATTERNS,
    DEFAULT_ALLOWED_PATTERNS,
    DEFAULT_ALLOWED_DIRS,
    DEFAULT_ALLOWED_TYPES,
    CANONICAL_MAP,
    DEFAULT_ALLOWED_EXCLUDE_MAP,
    DEFAULT_CANONICAL_MAP,
    ScanConfig,
    SearchParams,
    AllParams,
    get_item_check_cmd,
    get_all_item_check_cmd,
    is_any,
    get_spec_kwargs,
    try_group,
    eatElse,
    clean_line,
    is_line_import,
    is_line_from_import,
    is_from_group_start,
    is_from_group_end,
    clean_imports,
    combine_lone_imports,
    merge_from_import_groups,
    clean_imports_pipeline,
    combine_params,
    get_safe_kwargs,
    create_canonical_map,
    get_safe_canonical_kwargs,
    get_dir_filter_kwargs,
    get_file_filter_kwargs,
    normalize_listlike,
    ensure_exts,
    ensure_patterns,
    ensure_directories,
    get_proper_type_str,
    get_allowed_predicate,
    get_globs,
    get_allowed_files,
    get_allowed_dirs,
    get_filtered_files,
    get_filtered_dirs,
    get_all_allowed_files,
    get_all_allowed_dirs,
    make_allowed_predicate,
    filter_allowed_items,
    derive_all_defaults,
    derive_file_defaults,
    define_defaults,
    get_file_filters,
    if_none_return,
    write_pdf,
    read_pdf,
    is_pdf_path,
    get_pdf_obj,
    get_separate_pages,
    get_pdf_pages,
    save_pdf,
    split_pdf,
    pdf_to_img_list,
    img_to_txt_list,
    open_pdf_file,
    get_pdfs_in_directory,
    get_all_pdf_in_directory,
    collate_pdfs,
    convert_date_string,
    source_engine_for_ext,
    is_valid_file_path,
    is_dataframe,
    create_dataframe,
    read_ods_file,
    read_ods_as_excel,
    filter_df,
    read_shape_file,
    pdf_to_text,
    get_df,
    read_any_file,
    read_file_as_text,
    read_files,
    read_directory,
    shoudSkipManager,
    SKIP_MGR,
    should_skip,
    re_initialize_skip_mgr,
)
from .find_collect import (
    imports,
    re,
    os,
    get_args,
    load_dotenv,
    jsonify,
    secure_filename,
    make_list,
    get_media_exts,
    is_media_type,
    MIME_TYPES,
    is_str,
    if_not_bool_default,
    get_from_kwargs,
    eatAll,
    eatOuter,
    get_sleep,
    get_caller,
    get_caller_path,
    get_caller_dir,
    SingletonMeta,
    run_pruned_func,
    get_pass_from_key,
    get_password,
    get_print_sudo_cmd,
    get_password_cmd,
    get_sudo_cmd,
    get_raw_password_sudo_cmd,
    get_remote_bash,
    get_remote_ssh,
    get_remote_cmd,
    execute_cmd,
    run_local_cmd,
    run_remote_cmd,
    run_cmd,
    run_ssh_cmd,
    remote_cmd,
    ssh_cmd,
    local_cmd,
    run_any_cmd,
    any_cmd,
    cmd_run,
    PathBackend,
    LocalFS,
    SSHFS,
    REMOTE_RE,
    normalize_items,
    get_output,
    get_cmd_out,
    cmd_input,
    get_output_text,
    get_env_value,
    print_cmd,
    get_sudo_password,
    cmd_run_sudo,
    pexpect_cmd_with_args,
    get_user_pass_host_key,
    execute_cmd_input,
    exec_sudo_capture,
    exec_sudo,
    exec_expect,
    is_remote_file,
    is_remote_dir,
    is_local_file,
    is_local_dir,
    is_file,
    is_dir,
    is_exists,
    check_path_type,
    abstractEnv,
    eatInner,
    safe_split,
    line_contains,
    is_list,
    is_bool,
    get_slash,
    path_join,
    if_not_last_child_join,
    get_home_folder,
    simple_path_join,
    DEFAULT_FILE_NAME,
    DEFAULT_KEY,
    find_and_read_env_file,
    search_for_env_key,
    check_env_file,
    safe_env_load,
    split_eq,
    dotenv_load,
    AbstractEnv,
    get_env_path,
    read_from_file,
    write_to_file,
    get_logFile,
    if_none_default,
    if_none_change,
    get_initial_caller_dir,
    import_tag,
    from_tag,
    DEFAULT_ALLOWED_EXTS,
    DEFAULT_EXCLUDE_TYPES,
    DEFAULT_EXCLUDE_EXTS,
    DEFAULT_EXCLUDE_DIRS,
    DEFAULT_EXCLUDE_PATTERNS,
    AllowedPredicate,
    DEFAULT_EXCLUDE_FILE_PATTERNS,
    DEFAULT_ALLOWED_PATTERNS,
    DEFAULT_ALLOWED_DIRS,
    DEFAULT_ALLOWED_TYPES,
    CANONICAL_MAP,
    DEFAULT_ALLOWED_EXCLUDE_MAP,
    DEFAULT_CANONICAL_MAP,
    ScanConfig,
    SearchParams,
    AllParams,
    get_item_check_cmd,
    get_all_item_check_cmd,
    is_any,
    get_spec_kwargs,
    try_group,
    eatElse,
    clean_line,
    is_line_import,
    is_line_from_import,
    is_from_group_start,
    is_from_group_end,
    clean_imports,
    combine_lone_imports,
    merge_from_import_groups,
    clean_imports_pipeline,
    combine_params,
    get_safe_kwargs,
    create_canonical_map,
    get_safe_canonical_kwargs,
    get_dir_filter_kwargs,
    get_file_filter_kwargs,
    normalize_listlike,
    ensure_exts,
    ensure_patterns,
    ensure_directories,
    get_proper_type_str,
    get_allowed_predicate,
    get_globs,
    get_allowed_files,
    get_allowed_dirs,
    get_filtered_files,
    get_filtered_dirs,
    get_all_allowed_files,
    get_all_allowed_dirs,
    make_allowed_predicate,
    filter_allowed_items,
    derive_all_defaults,
    derive_file_defaults,
    define_defaults,
    get_file_filters,
    get_find_cmd,
    collect_globs,
    get_files_and_dirs,
    collect_filepaths,
    get_filename,
    find_files,
)
# ── search functionality delegated (lazily) to the standalone abstract_search ─
# abstract_search is the single source of truth for string search / filters /
# readers; file_utils keeps the historical public names and re-exports but no
# longer maintains its own copy. abstract_search is imported lazily (only when a
# search actually runs), matching this package's no-core-third-party policy —
# install it via the ``search`` extra: ``pip install abstract_utilities[search]``.
_ABSTRACT_SEARCH = None

def _search_mod():
    global _ABSTRACT_SEARCH
    if _ABSTRACT_SEARCH is None:
        from abstract_search import find_content as _fc
        _ABSTRACT_SEARCH = _fc
    return _ABSTRACT_SEARCH

# Kept for backward-compatible re-export; the live stop flag now lives in
# abstract_search and is toggled through the delegating functions below.
STOP_SEARCH = False

def request_find_console_stop():
    return _search_mod().request_find_console_stop()

def reset_find_console_stop():
    return _search_mod().reset_find_console_stop()

def get_contents(full_path=None, parse_lines=False, content=None):
    return _search_mod().get_contents(
        full_path=full_path, parse_lines=parse_lines, content=content
    )

def stringInContent(content, strings, total_strings=False, normalize=False, **kwargs):
    return _search_mod().stringInContent(
        content, strings, total_strings=total_strings, normalize=normalize, **kwargs
    )

def find_file(content, spec_line, strings, total_strings=False):
    return _search_mod().find_file(
        content, spec_line, strings, total_strings=total_strings
    )

def find_lines(content, strings, total_strings=False, normalize=True,
               any_per_line=True, **kwargs):
    return _search_mod().find_lines(
        content, strings, total_strings=total_strings, normalize=normalize,
        any_per_line=any_per_line, **kwargs
    )

def getPaths(files, strings):
    return _search_mod().getPaths(files, strings)

def findContent(
    *args,
    strings: list=[],
    total_strings=True,
    parse_lines=False,
    spec_line=False,
    get_lines=True,
    diffs=False,
    structured=False,
    regex=False,
    **kwargs
):
    # legacy ``diffs`` maps to abstract_search's ``structured`` (exact-match locations)
    return _search_mod().findContent(
        *args,
        strings=strings,
        total_strings=total_strings,
        parse_lines=parse_lines,
        spec_line=spec_line,
        get_lines=get_lines,
        structured=structured or diffs,
        regex=regex,
        **kwargs
    )
def return_function(start_dir=None,preferred_dir=None,basenames=None,functionName=None):
    if basenames:
        basenames = make_list(basenames,commaparse=False)
        abstract_file_finder = AbstractFileFinderImporter(start_dir=start_dir,preferred_dir=preferred_dir)
        paths = abstract_file_finder.find_paths(basenames)
        func = abstract_file_finder.import_function_from_path(paths[0], functionName)
        return func
def getLineNums(file_path):
    lines=[]
    if file_path and isinstance(file_path,dict):
        lines = file_path.get('lines')
        file_path = file_path.get('file_path')
    return file_path,lines
def get_line_content(obj):
    line,content=None,None
    if obj and isinstance(obj,dict):
        line=obj.get('line')
        content = obj.get('content')
    #print(f"line: {line}\ncontent: {content}")
    return line,content
def get_edit(file_path):
    if file_path and os.path.isfile(file_path):
        os.system(f"code {file_path}")
def editLines(file_paths):
    for file_path in file_paths:
        file_path,lines = getLineNums(file_path)
        for obj in lines:
            line,content = get_line_content(obj)
        get_edit(file_path)
def findContentAndEdit(*args,
    strings: list=[],
    total_strings=True,
    parse_lines=False,
    spec_line=False,
    get_lines=True,
    edit_lines=False,
    diffs=False,
    **kwargs
    ):
    file_paths = findContent(
        *args,
        strings=strings,
        total_strings=total_strings,
        parse_lines=parse_lines,
        spec_line=spec_line,
        get_lines=get_lines,
        diffs=diffs,
        **kwargs
        )
    if edit_lines:
        editLines(file_paths)
    return file_paths

