# coding: utf-8

"""
    Knowledge Search API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from tako.models.contents_delivery_mode import ContentsDeliveryMode
from tako.models.contents_format import ContentsFormat
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ContentsRequest(BaseModel):
    """
    Request body for POST /api/v1/contents.  The caller passes the result URL it wants downloadable content for, and the endpoint detects the right content from the URL itself. A Tako card URL resolves to the card's underlying data. Any other URL resolves to the page's extracted full text. `mode` controls delivery: `url` (the default) returns a presigned download link, and `inline` returns the content in the response. `content_format` selects the card serialization (csv, json_records, json_compact, or card_json); web URLs ignore it (always text).
    """ # noqa: E501
    url: StrictStr = Field(description="The result URL to fetch downloadable content for (a TakoCard.webpage_url or a WebResult.url). A Tako card URL yields a CSV of the card's data; any other URL yields the page's extracted text.")
    mode: Optional[ContentsDeliveryMode] = Field(default=None, description="Delivery mode. 'url' (the default) returns a presigned download link. 'inline' returns the content in the response body: CSV data up to the 2,000-row system ceiling (with total_rows and truncated reported), or web text.")
    content_format: Optional[ContentsFormat] = Field(default=None, description="Serialization for Tako card data: 'csv' (default), 'json_records', 'json_compact', or 'card_json' (a rich card-type-specific JSON object; not all card types support it). Ignored for web URLs (always text).")
    max_rows: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Optional cap on the rows returned for a Tako card CSV export. When omitted, it defaults to the free-row allowance (20 rows), billed at the baseline only. Raise it to export more rows, up to the 2,000-row system ceiling (Tako clamps larger values). Rows beyond the free allowance bill at the per-1,000-row rate. Billing counts the rows actually returned. Web URLs ignore this field. Do not use this field with content_format='card_json' (400): card_json always returns the complete payload.")
    max_chars: Optional[Annotated[int, Field(le=1000000, strict=True, ge=1)]] = Field(default=1000000, description="Character cap on extracted web page text. Ignored for Tako card URLs (they use max_rows). The default is the full page text, up to the 1000000-character ceiling. To truncate, pass a smaller value.")
    quote_only: Optional[StrictBool] = Field(default=False, description="When true, return only the price of the export (cost + export_pricing) without fetching content or charging. The response item's payload and url fields are null, and the request is free. `max_rows` shapes the quote and defaults to the 20-row free allowance, as a real export does. The request ignores `mode`, and it ignores `content_format` except for 'card_json': a card_json quote reports the exact price of the complete payload, so Tako builds the payload to count its rows. That build can fetch from the data provider, so a card_json quote is free but not instant, and it requires a funded account. The same export-safe gate applies, so an unexportable card still returns 403.")
    __properties: ClassVar[List[str]] = ["url", "mode", "content_format", "max_rows", "max_chars", "quote_only"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContentsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if max_rows (nullable) is None
        # and model_fields_set contains the field
        if self.max_rows is None and "max_rows" in self.model_fields_set:
            _dict['max_rows'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContentsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "mode": obj.get("mode"),
            "content_format": obj.get("content_format"),
            "max_rows": obj.get("max_rows"),
            "max_chars": obj.get("max_chars") if obj.get("max_chars") is not None else 1000000,
            "quote_only": obj.get("quote_only") if obj.get("quote_only") is not None else False
        })
        return _obj


