# coding: utf-8

"""
    Knowledge Search API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from tako.aio.models.agent_output_settings import AgentOutputSettings
from tako.aio.models.answer_agent_effort import AnswerAgentEffort
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AnswerAgentRunRequest(BaseModel):
    """
    Request body for POST /v1/agent/answer/runs.  Frozen contract: no output_schema, no structured outputs, and no inline data — ever. Cards are the only data-export path (via /v1/contents).
    """ # noqa: E501
    query: StrictStr = Field(description="Natural-language request for the answer agent.")
    thread_id: Optional[UUID] = Field(default=None, description="Existing thread to continue (follow-up). Omit to start a new thread.")
    effort: Optional[AnswerAgentEffort] = Field(default=None, description="Answer-agent effort. Only 'medium' is currently supported.")
    source_indexes: Optional[List[StrictStr]] = Field(default=None, description="Which sources the agent may use: 'data' (curated knowledge), 'web' (open-web search), or both. Defaults to ['data', 'web']. Tako accepts the legacy value 'tako' as a synonym for 'data'.")
    locale: Optional[StrictStr] = Field(default='en-US', description="BCP-47 locale. Drives the language of the agent's answer and the locale used when rendering card preview images. Defaults to en-US.")
    timezone: Optional[StrictStr] = Field(default=None, description="IANA timezone (for example, 'America/New_York'). The agent uses it to render dates and times in card preview images. It does not affect the returned data.")
    output_settings: Optional[AgentOutputSettings] = Field(default=None, description="Settings that control the response and rendering.")
    __properties: ClassVar[List[str]] = ["query", "thread_id", "effort", "source_indexes", "locale", "timezone", "output_settings"]

    @field_validator('source_indexes')
    def source_indexes_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['data', 'web']):
                raise ValueError("each list item must be one of ('data', 'web')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnswerAgentRunRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of output_settings
        if self.output_settings:
            _dict['output_settings'] = self.output_settings.to_dict()
        # set to None if thread_id (nullable) is None
        # and model_fields_set contains the field
        if self.thread_id is None and "thread_id" in self.model_fields_set:
            _dict['thread_id'] = None

        # set to None if timezone (nullable) is None
        # and model_fields_set contains the field
        if self.timezone is None and "timezone" in self.model_fields_set:
            _dict['timezone'] = None

        # set to None if output_settings (nullable) is None
        # and model_fields_set contains the field
        if self.output_settings is None and "output_settings" in self.model_fields_set:
            _dict['output_settings'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnswerAgentRunRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "thread_id": obj.get("thread_id"),
            "effort": obj.get("effort"),
            "source_indexes": obj.get("source_indexes"),
            "locale": obj.get("locale") if obj.get("locale") is not None else 'en-US',
            "timezone": obj.get("timezone"),
            "output_settings": AgentOutputSettings.from_dict(obj["output_settings"]) if obj.get("output_settings") is not None else None
        })
        return _obj


