# coding: utf-8

"""
    Managed Ray API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class EffectiveRoleBindings(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'role_id': 'str',
        'name': 'str',
        'role_bindings': 'list[EffectivePrincipalSummary]'
    }

    attribute_map = {
        'role_id': 'role_id',
        'name': 'name',
        'role_bindings': 'role_bindings'
    }

    def __init__(self, role_id=None, name=None, role_bindings=None, local_vars_configuration=None):  # noqa: E501
        """EffectiveRoleBindings - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._role_id = None
        self._name = None
        self._role_bindings = None
        self.discriminator = None

        self.role_id = role_id
        if name is not None:
            self.name = name
        if role_bindings is not None:
            self.role_bindings = role_bindings

    @property
    def role_id(self):
        """Gets the role_id of this EffectiveRoleBindings.  # noqa: E501


        :return: The role_id of this EffectiveRoleBindings.  # noqa: E501
        :rtype: str
        """
        return self._role_id

    @role_id.setter
    def role_id(self, role_id):
        """Sets the role_id of this EffectiveRoleBindings.


        :param role_id: The role_id of this EffectiveRoleBindings.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and role_id is None:  # noqa: E501
            raise ValueError("Invalid value for `role_id`, must not be `None`")  # noqa: E501

        self._role_id = role_id

    @property
    def name(self):
        """Gets the name of this EffectiveRoleBindings.  # noqa: E501

        The role's name.  # noqa: E501

        :return: The name of this EffectiveRoleBindings.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EffectiveRoleBindings.

        The role's name.  # noqa: E501

        :param name: The name of this EffectiveRoleBindings.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def role_bindings(self):
        """Gets the role_bindings of this EffectiveRoleBindings.  # noqa: E501


        :return: The role_bindings of this EffectiveRoleBindings.  # noqa: E501
        :rtype: list[EffectivePrincipalSummary]
        """
        return self._role_bindings

    @role_bindings.setter
    def role_bindings(self, role_bindings):
        """Sets the role_bindings of this EffectiveRoleBindings.


        :param role_bindings: The role_bindings of this EffectiveRoleBindings.  # noqa: E501
        :type: list[EffectivePrincipalSummary]
        """

        self._role_bindings = role_bindings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EffectiveRoleBindings):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EffectiveRoleBindings):
            return True

        return self.to_dict() != other.to_dict()
