# coding: utf-8

"""
    Managed Ray API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ImportWorkloadRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cr_namespace': 'str',
        'cr_name': 'str',
        'cr_uid': 'str',
        'project_id': 'str',
        'submitted_spec': 'object',
        'observed_state': 'str',
        'cloud_resource_id': 'str'
    }

    attribute_map = {
        'cr_namespace': 'cr_namespace',
        'cr_name': 'cr_name',
        'cr_uid': 'cr_uid',
        'project_id': 'project_id',
        'submitted_spec': 'submitted_spec',
        'observed_state': 'observed_state',
        'cloud_resource_id': 'cloud_resource_id'
    }

    def __init__(self, cr_namespace=None, cr_name=None, cr_uid=None, project_id=None, submitted_spec=None, observed_state=None, cloud_resource_id=None, local_vars_configuration=None):  # noqa: E501
        """ImportWorkloadRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._cr_namespace = None
        self._cr_name = None
        self._cr_uid = None
        self._project_id = None
        self._submitted_spec = None
        self._observed_state = None
        self._cloud_resource_id = None
        self.discriminator = None

        self.cr_namespace = cr_namespace
        self.cr_name = cr_name
        if cr_uid is not None:
            self.cr_uid = cr_uid
        if project_id is not None:
            self.project_id = project_id
        self.submitted_spec = submitted_spec
        if observed_state is not None:
            self.observed_state = observed_state
        self.cloud_resource_id = cloud_resource_id

    @property
    def cr_namespace(self):
        """Gets the cr_namespace of this ImportWorkloadRequest.  # noqa: E501

        Namespace of the CR.  # noqa: E501

        :return: The cr_namespace of this ImportWorkloadRequest.  # noqa: E501
        :rtype: str
        """
        return self._cr_namespace

    @cr_namespace.setter
    def cr_namespace(self, cr_namespace):
        """Sets the cr_namespace of this ImportWorkloadRequest.

        Namespace of the CR.  # noqa: E501

        :param cr_namespace: The cr_namespace of this ImportWorkloadRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and cr_namespace is None:  # noqa: E501
            raise ValueError("Invalid value for `cr_namespace`, must not be `None`")  # noqa: E501

        self._cr_namespace = cr_namespace

    @property
    def cr_name(self):
        """Gets the cr_name of this ImportWorkloadRequest.  # noqa: E501

        Name of the CR (used as the workload name).  # noqa: E501

        :return: The cr_name of this ImportWorkloadRequest.  # noqa: E501
        :rtype: str
        """
        return self._cr_name

    @cr_name.setter
    def cr_name(self, cr_name):
        """Sets the cr_name of this ImportWorkloadRequest.

        Name of the CR (used as the workload name).  # noqa: E501

        :param cr_name: The cr_name of this ImportWorkloadRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and cr_name is None:  # noqa: E501
            raise ValueError("Invalid value for `cr_name`, must not be `None`")  # noqa: E501

        self._cr_name = cr_name

    @property
    def cr_uid(self):
        """Gets the cr_uid of this ImportWorkloadRequest.  # noqa: E501

        K8s UID of the CR. Not available at mutating-admission time (the UID is assigned at persistence, after admission), so it is not the idempotency key; backfilled on first observation.  # noqa: E501

        :return: The cr_uid of this ImportWorkloadRequest.  # noqa: E501
        :rtype: str
        """
        return self._cr_uid

    @cr_uid.setter
    def cr_uid(self, cr_uid):
        """Sets the cr_uid of this ImportWorkloadRequest.

        K8s UID of the CR. Not available at mutating-admission time (the UID is assigned at persistence, after admission), so it is not the idempotency key; backfilled on first observation.  # noqa: E501

        :param cr_uid: The cr_uid of this ImportWorkloadRequest.  # noqa: E501
        :type: str
        """

        self._cr_uid = cr_uid

    @property
    def project_id(self):
        """Gets the project_id of this ImportWorkloadRequest.  # noqa: E501

        Project; defaults to the cloud's default project when omitted.  # noqa: E501

        :return: The project_id of this ImportWorkloadRequest.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this ImportWorkloadRequest.

        Project; defaults to the cloud's default project when omitted.  # noqa: E501

        :param project_id: The project_id of this ImportWorkloadRequest.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def submitted_spec(self):
        """Gets the submitted_spec of this ImportWorkloadRequest.  # noqa: E501

        Observed CR spec, stored in workload_specs and overwritten on re-import to reflect the current CR.  # noqa: E501

        :return: The submitted_spec of this ImportWorkloadRequest.  # noqa: E501
        :rtype: object
        """
        return self._submitted_spec

    @submitted_spec.setter
    def submitted_spec(self, submitted_spec):
        """Sets the submitted_spec of this ImportWorkloadRequest.

        Observed CR spec, stored in workload_specs and overwritten on re-import to reflect the current CR.  # noqa: E501

        :param submitted_spec: The submitted_spec of this ImportWorkloadRequest.  # noqa: E501
        :type: object
        """
        if self.local_vars_configuration.client_side_validation and submitted_spec is None:  # noqa: E501
            raise ValueError("Invalid value for `submitted_spec`, must not be `None`")  # noqa: E501

        self._submitted_spec = submitted_spec

    @property
    def observed_state(self):
        """Gets the observed_state of this ImportWorkloadRequest.  # noqa: E501

        Observed lifecycle (e.g. Running/Complete/Failed).  # noqa: E501

        :return: The observed_state of this ImportWorkloadRequest.  # noqa: E501
        :rtype: str
        """
        return self._observed_state

    @observed_state.setter
    def observed_state(self, observed_state):
        """Sets the observed_state of this ImportWorkloadRequest.

        Observed lifecycle (e.g. Running/Complete/Failed).  # noqa: E501

        :param observed_state: The observed_state of this ImportWorkloadRequest.  # noqa: E501
        :type: str
        """

        self._observed_state = observed_state

    @property
    def cloud_resource_id(self):
        """Gets the cloud_resource_id of this ImportWorkloadRequest.  # noqa: E501

        Verified cloud_resource the connector may act on.  # noqa: E501

        :return: The cloud_resource_id of this ImportWorkloadRequest.  # noqa: E501
        :rtype: str
        """
        return self._cloud_resource_id

    @cloud_resource_id.setter
    def cloud_resource_id(self, cloud_resource_id):
        """Sets the cloud_resource_id of this ImportWorkloadRequest.

        Verified cloud_resource the connector may act on.  # noqa: E501

        :param cloud_resource_id: The cloud_resource_id of this ImportWorkloadRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and cloud_resource_id is None:  # noqa: E501
            raise ValueError("Invalid value for `cloud_resource_id`, must not be `None`")  # noqa: E501

        self._cloud_resource_id = cloud_resource_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImportWorkloadRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImportWorkloadRequest):
            return True

        return self.to_dict() != other.to_dict()
