#
# Copyright (c) 2012-2025 Snowflake Computing Inc. All rights reserved.
#

_SPARKLE_SCHEMA = "snowflake.sparkle"


# CRC32_BINARY(col BINARY) -> BIGINT
crc32_binary = f"{_SPARKLE_SCHEMA}.CRC32_BINARY"

# CRC32_STRING(col VARCHAR) -> BIGINT
crc32_string = f"{_SPARKLE_SCHEMA}.CRC32_STRING"

# _SPARKLE_INTERNAL_XXHASH64_BYTES(value BINARY, seed BIGINT) -> BIGINT
xxhash64_bytes = f"{_SPARKLE_SCHEMA}._SPARKLE_INTERNAL_XXHASH64_BYTES"

# _SPARKLE_INTERNAL_XXHASH64_DOUBLE(value DOUBLE, seed BIGINT) -> BIGINT
xxhash64_double = f"{_SPARKLE_SCHEMA}._SPARKLE_INTERNAL_XXHASH64_DOUBLE"

# _SPARKLE_INTERNAL_XXHASH64_FLOAT(value FLOAT, seed BIGINT) -> BIGINT
xxhash64_float = f"{_SPARKLE_SCHEMA}._SPARKLE_INTERNAL_XXHASH64_FLOAT"

# _SPARKLE_INTERNAL_XXHASH64_INT(value BIGINT, seed BIGINT) -> BIGINT
xxhash64_int = f"{_SPARKLE_SCHEMA}._SPARKLE_INTERNAL_XXHASH64_INT"

# _SPARKLE_INTERNAL_XXHASH64_LONG(value BIGINT, seed BIGINT) -> BIGINT
xxhash64_long = f"{_SPARKLE_SCHEMA}._SPARKLE_INTERNAL_XXHASH64_LONG"

# _SPARKLE_INTERNAL_XXHASH64_STRING(value VARCHAR, seed BIGINT) -> BIGINT
xxhash64_string = f"{_SPARKLE_SCHEMA}._SPARKLE_INTERNAL_XXHASH64_STRING"
