"""Auto-generated stub for module: export."""
from typing import Any

# Functions
def export(model_path: Any.Any, export_format: str, simplify: bool, plate_config_file: Any.Any, save_dir: Any.Any, dynamic_batch: bool, skip_validation: bool, onnx_input_dtype: str, onnx_data_format: Any) -> None:
    """
    Export Keras models to other formats.
    """
    ...
def export_coreml(model: Any.Any, plate_config: Any, out_file: Any.Any, skip_validation: bool = False) -> None: ...
def export_onnx(model: Any.Any, plate_config: Any, out_file: Any.Any, simplify: bool, dynamic_batch: bool, skip_validation: bool = False, onnx_input_dtype: str = 'uint8', onnx_data_format: Any = 'channels_last') -> None: ...
def export_tflite(model: Any.Any, plate_config: Any, out_file: Any.Any, skip_validation: bool = False) -> None: ...
