[project]
name = "connector-py"
description = "An Abstract Tool to Perform Actions on Integrations."
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
keywords = ["integrations"]
authors = [
    { name = "teamlumos", email = "security@lumos.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "connector-sdk-types == 0.59.0",
    "gql[httpx]~=3.5.3",
    "httpx~=0.28.1",
    "msgpack~=1.1.2",
    "pydantic~=2.9.2",
    "urllib3~=2.6.2",
    "botocore~=1.40.61",
    "PyJWT~=2.10.1",
    "datadog~=0.49.1",
    "pip-system-certs~=5.2.0 ; platform_system == 'Windows'",
    "tomli~=2.4.1",
]
dynamic = ["version"]

[project.optional-dependencies]
fastapi = [
    "fastapi-slim~=0.115.2",
    "uvicorn~=0.38.0",
]
dev = [
    "pytest~=9.0.2",
    "pytest-asyncio~=1.3.0",
    "pytest-httpx~=0.36.0",
    "Flask~=3.1.2",
    "pyinstaller~=6.8.0",
    "pip-licenses~=5.5.0"
]
all = ["connector-py[dev,fastapi]"]

[project.urls]
Documentation = "https://developers.lumos.com/reference/the-lumos-connector-api"

[project.scripts]
connector = "connector.main:main"

[project.entry-points."pytest11"]
connector-sdk-fixtures = "connector.tests.pytest_plugin"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.poetry]
version = { attr = "connector.__about__.__version__" }

[tool.setuptools.dynamic]
version = { attr = "connector.__about__.__version__" }

[tool.setuptools.package-data]
connector = [
  "scaffold/templates/.*",
  "scaffold/templates/*",
  "spec/*",
]

[tool.setuptools.packages.find]
exclude = ["logs"]

[tool.coverage.run]
source_pkgs = ["connector", "tests"]
branch = true
parallel = true
omit = [
    "connector/__about__.py",
]

[tool.coverage.paths]
connector = ["connector", "*/python/connector"]
tests = ["tests"]

[tool.coverage.report]
exclude_lines = [
    "no cov",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

[tool.mypy]
exclude = [
    "scaffold/templates",
]
mypy_path = [
    "$MYPY_CONFIG_FILE_DIR/../../../../projects/libs/python/connector-sdk/",
    "$MYPY_CONFIG_FILE_DIR/../../../../projects/libs/python/connector-sdk-types/"
]

[[tool.mypy.overrides]]
module = [
    "msgpack",
    "PyInstaller",
    "PyInstaller.__main__",
]
ignore_missing_imports = true
