"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sentry_protos.billing.v1.date_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StartTrialRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORGANIZATION_ID_FIELD_NUMBER: builtins.int
    LINE_ITEM_UID_FIELD_NUMBER: builtins.int
    PACKAGE_UID_FIELD_NUMBER: builtins.int
    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    organization_id: builtins.int
    line_item_uid: builtins.str
    """product trials"""
    package_uid: builtins.str
    """subscription trials"""
    @property
    def start_date(self) -> sentry_protos.billing.v1.date_pb2.Date:
        """defaults to current date"""

    @property
    def end_date(self) -> sentry_protos.billing.v1.date_pb2.Date:
        """defaults to start_date plus 14 days"""

    def __init__(
        self,
        *,
        organization_id: builtins.int = ...,
        line_item_uid: builtins.str = ...,
        package_uid: builtins.str = ...,
        start_date: sentry_protos.billing.v1.date_pb2.Date | None = ...,
        end_date: sentry_protos.billing.v1.date_pb2.Date | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_end_date", b"_end_date", "_start_date", b"_start_date", "end_date", b"end_date", "line_item_uid", b"line_item_uid", "package_uid", b"package_uid", "scope", b"scope", "start_date", b"start_date"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_end_date", b"_end_date", "_start_date", b"_start_date", "end_date", b"end_date", "line_item_uid", b"line_item_uid", "organization_id", b"organization_id", "package_uid", b"package_uid", "scope", b"scope", "start_date", b"start_date"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_end_date", b"_end_date"]) -> typing.Literal["end_date"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_start_date", b"_start_date"]) -> typing.Literal["start_date"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["scope", b"scope"]) -> typing.Literal["line_item_uid", "package_uid"] | None: ...

global___StartTrialRequest = StartTrialRequest

@typing.final
class StartTrialResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___StartTrialResponse = StartTrialResponse
