"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sentry_protos.billing.v1.date_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _EffectiveUnitSource:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EffectiveUnitSourceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EffectiveUnitSource.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EFFECTIVE_UNIT_SOURCE_UNSPECIFIED: _EffectiveUnitSource.ValueType  # 0
    EFFECTIVE_UNIT_SOURCE_TRIAL: _EffectiveUnitSource.ValueType  # 1
    EFFECTIVE_UNIT_SOURCE_RECURRING_CREDIT: _EffectiveUnitSource.ValueType  # 2

class EffectiveUnitSource(_EffectiveUnitSource, metaclass=_EffectiveUnitSourceEnumTypeWrapper): ...

EFFECTIVE_UNIT_SOURCE_UNSPECIFIED: EffectiveUnitSource.ValueType  # 0
EFFECTIVE_UNIT_SOURCE_TRIAL: EffectiveUnitSource.ValueType  # 1
EFFECTIVE_UNIT_SOURCE_RECURRING_CREDIT: EffectiveUnitSource.ValueType  # 2
global___EffectiveUnitSource = EffectiveUnitSource

@typing.final
class EffectiveUnitGrant(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LINE_ITEM_UID_FIELD_NUMBER: builtins.int
    IS_UNLIMITED_FIELD_NUMBER: builtins.int
    UNITS_FIELD_NUMBER: builtins.int
    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    line_item_uid: builtins.str
    is_unlimited: builtins.bool
    units: builtins.int
    """this should be expressed line item's billable metric prior to unit conversion (ie milliseconds, bytes, etc.)"""
    source: global___EffectiveUnitSource.ValueType
    @property
    def start_date(self) -> sentry_protos.billing.v1.date_pb2.Date:
        """Grants only apply to days between [start_date, end_date] (inclusive)
        For units, this means Grants apply to usage that was accrued during the active period.
        For monetary, Grants are applied to invoices created during the active period.
        """

    @property
    def end_date(self) -> sentry_protos.billing.v1.date_pb2.Date: ...
    def __init__(
        self,
        *,
        line_item_uid: builtins.str = ...,
        is_unlimited: builtins.bool = ...,
        units: builtins.int = ...,
        start_date: sentry_protos.billing.v1.date_pb2.Date | None = ...,
        end_date: sentry_protos.billing.v1.date_pb2.Date | None = ...,
        source: global___EffectiveUnitSource.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["amount", b"amount", "end_date", b"end_date", "is_unlimited", b"is_unlimited", "start_date", b"start_date", "units", b"units"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["amount", b"amount", "end_date", b"end_date", "is_unlimited", b"is_unlimited", "line_item_uid", b"line_item_uid", "source", b"source", "start_date", b"start_date", "units", b"units"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["amount", b"amount"]) -> typing.Literal["is_unlimited", "units"] | None: ...

global___EffectiveUnitGrant = EffectiveUnitGrant

@typing.final
class GetUnitGrantsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_ID_FIELD_NUMBER: builtins.int
    contract_id: builtins.int
    def __init__(
        self,
        *,
        contract_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_id", b"contract_id"]) -> None: ...

global___GetUnitGrantsRequest = GetUnitGrantsRequest

@typing.final
class GetUnitGrantsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GRANTS_FIELD_NUMBER: builtins.int
    @property
    def grants(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EffectiveUnitGrant]: ...
    def __init__(
        self,
        *,
        grants: collections.abc.Iterable[global___EffectiveUnitGrant] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["grants", b"grants"]) -> None: ...

global___GetUnitGrantsResponse = GetUnitGrantsResponse
